# The numeric fixtures in fixtures/r/ are generated by scripts/regenerate_r_fixtures.R and replayed
# by the Python suite (python/tests/_r_parity.py). Replaying them in R checks that the installed
# survival still reproduces what was recorded, which flags drift before the fixtures are
# regenerated on a newer survival.

test_that("survfit() on lung reproduces the recorded Kaplan-Meier fixture", {
  skip_if_no_shared_cases()
  expected <- read_fixture("km_lung_overall")$overall
  fit <- survival::survfit(Surv(time, status) ~ 1, data = survival::lung)

  expect_equal(fit$time, r_numbers(expected$time), tolerance = 1e-9)
  expect_equal(fit$surv, r_numbers(expected$surv), tolerance = 1e-9)
  expect_equal(fit$cumhaz, r_numbers(expected$cumhaz), tolerance = 1e-9)
  expect_equal(unname(summary(fit)$table["median"]), expected$median)
})
