# Replays spec/conformance/surv/, generated by scripts/generate_surv_conformance.R. The Python suite replays the same cases
# (python/tests/test_surv_conformance.py). See spec/surv.md.

# Warnings that come from R's max() rather than from the contract, as in the Python suite.
R_ONLY_WARNINGS <- "^no non-missing arguments to max"

expected_warnings <- function(result) {
  warnings <- r_strings(result$warnings)
  warnings[!grepl(R_ONLY_WARNINGS, warnings)]
}

test_that("Surv() matches every recorded conformance case", {
  skip_if_no_shared_cases()
  cases <- read_conformance("surv", "surv")
  expect_gt(length(cases), 0)

  for (case in cases) {
    args <- lapply(case$args, decode_input)
    out <- capture(do.call(Surv, args))
    expected <- case$result
    label <- case$id

    expect_identical(out$ok, expected$ok, label = label)
    expect_identical(out$warnings, expected_warnings(expected), label = label)
    if (expected$ok) {
      expect_surv_matches(out$value, expected, label)
    } else {
      expect_identical(out$message, expected$message, label = label)
    }
  }
})
