# Replays the Kaplan-Meier fixtures in fixtures/r/, generated by scripts/regenerate_r_fixtures.R.
# The Python suite replays the same fixtures (python/tests/test_r_parity.py). The datasets come
# from the survival package, which is only needed for these tests.

TOL <- 1e-9

# Compare one curve with a fixture block written by km_one() in the generator.
expect_km_matches <- function(curve, expected, label) {
  expect_equal(curve$time, r_numbers(expected$time), tolerance = TOL, label = paste(label, "time"))
  expect_equal(curve$estimate, r_numbers(expected$surv), tolerance = TOL, label = paste(label, "surv"))
  expect_equal(curve$std_error, r_numbers(expected$se), tolerance = TOL, label = paste(label, "se"))
}

expect_limits_match <- function(fit, expected, suffix, label) {
  curve <- as.data.frame(fit)
  expect_equal(
    curve$conf_low,
    r_numbers(expected[[paste0("lower_", suffix)]]),
    tolerance = TOL,
    label = paste(label, "lower", suffix)
  )
  expect_equal(
    curve$conf_high,
    r_numbers(expected[[paste0("upper_", suffix)]]),
    tolerance = TOL,
    label = paste(label, "upper", suffix)
  )
}

test_that("the overall curve on lung matches the fixture", {
  skip_if_no_shared_cases()
  skip_if_not_installed("survival")
  expected <- read_fixture("km_lung_overall")$overall
  lung <- survival::lung

  fit <- kaplan_meier(Surv(time, status) ~ 1, data = lung)
  expect_km_matches(as.data.frame(fit), expected, "lung")
  expect_limits_match(fit, expected, "log", "lung")
  expect_limits_match(
    kaplan_meier(Surv(time, status) ~ 1, data = lung, conf_type = "plain"),
    expected,
    "plain",
    "lung"
  )
  expect_limits_match(
    kaplan_meier(Surv(time, status) ~ 1, data = lung, conf_type = "log-log"),
    expected,
    "loglog",
    "lung"
  )

  med <- median(fit)
  expect_equal(med$time, expected$median)
  expect_equal(med$conf_low, expected$median_lower)
  expect_equal(med$conf_high, expected$median_upper)
})

test_that("curves by sex on lung match the fixture", {
  skip_if_no_shared_cases()
  skip_if_not_installed("survival")
  expected <- read_fixture("km_lung_by_sex")
  fit <- kaplan_meier(Surv(time, status) ~ sex, data = survival::lung)

  expect_identical(fit$groups$sex, c(1, 2))
  curves <- as.data.frame(fit)
  med <- median(fit)
  for (sex in names(expected)) {
    rows <- curves[curves$sex == as.numeric(sex), ]
    expect_km_matches(rows, expected[[sex]], paste("sex", sex))
    expect_equal(rows$conf_low, r_numbers(expected[[sex]]$lower_log), tolerance = TOL)
    expect_equal(rows$conf_high, r_numbers(expected[[sex]]$upper_log), tolerance = TOL)
    expect_equal(med$time[med$sex == as.numeric(sex)], expected[[sex]]$median)
  }
})

test_that("the overall curve on veteran matches the fixture", {
  skip_if_no_shared_cases()
  skip_if_not_installed("survival")
  expected <- read_fixture("km_veteran_overall")$overall
  fit <- kaplan_meier(Surv(time, status) ~ 1, data = survival::veteran)
  expect_km_matches(as.data.frame(fit), expected, "veteran")
  expect_limits_match(fit, expected, "log", "veteran")
})

test_that("risk-set counts on lung match the fixture", {
  skip_if_no_shared_cases()
  skip_if_not_installed("survival")
  expected <- read_fixture("lung_km_overall")$overall
  curve <- as.data.frame(kaplan_meier(Surv(time, status) ~ 1, data = survival::lung))
  expect_equal(curve$time, r_numbers(expected$time))
  expect_equal(curve$n_risk, r_numbers(expected$n_risk))
  expect_equal(curve$n_event, r_numbers(expected$n_event))
  expect_equal(curve$n_censor, r_numbers(expected$n_censor))
})

test_that("delayed entry uses the start times in the risk set", {
  skip_if_no_shared_cases()
  fixture <- read_fixture("counting_truncation")
  trunc <- data.frame(
    start = r_numbers(fixture$data$start),
    stop = r_numbers(fixture$data$stop),
    event = r_numbers(fixture$data$event)
  )
  curve <- as.data.frame(kaplan_meier(Surv(start, stop, event) ~ 1, data = trunc))
  expected <- fixture$overall
  expect_equal(curve$time, r_numbers(expected$time))
  expect_equal(curve$n_risk, r_numbers(expected$n_risk))
  expect_equal(curve$n_event, r_numbers(expected$n_event))
  expect_equal(curve$n_censor, r_numbers(expected$n_censor))
})

# -- behaviour ------------------------------------------------------------------------------------

small <- data.frame(
  time = c(306, 455, 1010, 210, 883, 1022, 310, 361, 218, 166),
  status = c(2, 2, 1, 2, 2, 1, 2, 2, 2, 2),
  sex = c(1, 1, 1, 1, 1, 2, 2, 2, 2, 2),
  ecog = c(0, 1, 0, 1, 0, 1, 0, 1, 0, 1)
)

test_that("integer weights match replicated rows", {
  w <- c(2, 1, 3, 1, 1, 2, 1, 1, 2, 1)
  weighted <- kaplan_meier(Surv(time, status) ~ 1, data = small, weights = w)
  replicated <- kaplan_meier(Surv(time, status) ~ 1, data = small[rep(seq_along(w), w), ])
  expect_equal(as.data.frame(weighted), as.data.frame(replicated))
})

test_that("weights and subset are evaluated in data", {
  small$w <- 2
  by_name <- kaplan_meier(Surv(time, status) ~ 1, data = small, weights = w, subset = sex == 1)
  expect_identical(as.data.frame(by_name)$n_risk[1], 10)
})

test_that("rows with missing values are dropped and counted", {
  gappy <- small
  gappy$time[2] <- NA
  gappy$sex[3] <- NA
  fit <- kaplan_meier(Surv(time, status) ~ sex, data = gappy)
  expect_identical(fit$n_dropped, 2L)
  expect_identical(sum(vapply(fit$curves, function(curve) curve$n_risk[1], numeric(1))), 8)
})

test_that("several grouping variables give one curve per combination", {
  fit <- kaplan_meier(Surv(time, status) ~ sex + ecog, data = small)
  expect_identical(nrow(fit$groups), 4L)
  expect_named(as.data.frame(fit), c(
    "sex", "ecog", "time", "n_risk", "n_event", "n_censor",
    "estimate", "std_error", "conf_low", "conf_high"
  ))
  expect_named(median(fit), c("sex", "ecog", "time", "conf_low", "conf_high"))
})

test_that("quantile() returns one row per group and probability", {
  fit <- kaplan_meier(Surv(time, status) ~ sex, data = small)
  q <- quantile(fit, probs = c(0.25, 0.5))
  expect_identical(nrow(q), 4L)
  expect_identical(q$prob, c(0.25, 0.5, 0.25, 0.5))
  expect_error(quantile(fit, probs = 2), "between 0 and 1")
})

test_that("invalid input is rejected", {
  expect_error(kaplan_meier(time ~ 1, data = small), "must be a `Surv\\(\\)` response")
  expect_error(
    kaplan_meier(Surv(time, time + 1, type = "interval2") ~ 1, data = small),
    "right-censored or counting-process"
  )
  expect_error(kaplan_meier(Surv(time, status) ~ 1, data = small, conf_level = 1), "between 0 and 1")
  expect_error(kaplan_meier(Surv(time, status) ~ 1, data = small, conf_type = "logit"))
  expect_error(kaplan_meier(Surv(time, status) ~ 1, data = small, weights = -time), "non-negative")
})

test_that("a fit prints a summary per group", {
  expect_snapshot({
    kaplan_meier(Surv(time, status) ~ 1, data = small)
    kaplan_meier(Surv(time, status) ~ sex, data = small)
  })
})
