# Replays spec/conformance/surv/, generated by scripts/generate_surv_conformance.R. The Python
# suite replays the same cases (python/tests/test_surv_conformance.py). See spec/surv.md.

test_that("Surv() matches every recorded survival::Surv() case", {
  skip_if_no_shared_cases()
  cases <- read_conformance("surv", "surv")
  expect_gt(length(cases), 0)

  for (case in cases) {
    args <- lapply(case$args, decode_input)
    out <- capture(do.call(Surv, args))
    expected <- case$result
    label <- case$id

    expect_identical(out$ok, expected$ok, label = label)
    expect_identical(out$warnings, r_strings(expected$warnings), label = label)
    if (expected$ok) {
      expect_surv_matches(out$value, expected, label)
    } else {
      expect_identical(out$message, expected$message, label = label)
    }
  }
})
