{
  "hash": "d4a6b3318922ac3528452f65795461b9",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: Prediction performance\nguide-section: \"Evaluation\"\nbread-crumbs: false\n---\n\n\n\nA model that fits the data in front of it is not necessarily a model that predicts well. To judge a\nsurvival model as a predictor, or to compare competing models, you need metrics that account for\ncensoring. Greenwood provides three complementary ones: (1) the concordance index, (measures how\nwell a model ranks subjects by risk), (2) the Brier score (measures how accurate its probability\npredictions are), and (3) the time-dependent AUC (shows how discrimination changes over the\nfollow-up horizon). This guide page explains all three and shows how to compute them for a fitted\nmodel or for any external risk score.\n\nWe start from the `lung` outcomes and a Cox model fit to them. This is the model whose predictions\nwe will judge.\n\n::: {#e9f0532f .cell execution_count=2}\n``` {.python .cell-code}\nimport greenwood as gw\n\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\n\ny = gw.Surv.right(lung[\"time\"], event=(lung[\"status\"] == 2))\ny\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```\nSurv(type=right, n=228, events=165)\n```\n:::\n:::\n\n\nThe response `y` records 165 events among 228 subjects. We fit a Cox model to it, then set the model\naside: everything below needs only `y` and the risk scores and survival probabilities that `cox`\nproduces.\n\n::: {#88949ceb .cell execution_count=3}\n``` {.python .cell-code}\ncox = gw.CoxPH().fit(y, lung[[\"age\", \"sex\"]])\n```\n:::\n\n\n## Discrimination: the concordance index\n\nDiscrimination is the ability to rank subjects correctly: to give higher risk scores to subjects who\ngo on to have the event sooner. The concordance index, or C-statistic, measures exactly this. It is\nthe probability that, for a randomly chosen comparable pair of subjects, the one who failed first\nhad the higher risk score. A value of 0.5 is no better than a coin flip, and 1.0 is perfect\nordering.\n\nYou can compute it for any risk score, which makes it useful for evaluating a model on new data or\nfor comparing an external score. Here we use the Cox model's linear predictor. Asking for\n`type=\"lp\"` returns one number per subject, where a larger value means higher predicted risk.\n\n::: {#8a985434 .cell execution_count=4}\n``` {.python .cell-code}\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\n\ny = gw.Surv.right(lung[\"time\"], event=(lung[\"status\"] == 2))\ncox = gw.CoxPH().fit(y, lung[[\"age\", \"sex\"]])\n\nrisk = cox.predict(type=\"lp\")\nrisk[:8]\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```\narray([ 0.3995047 ,  0.2972327 ,  0.09268872,  0.10973405,  0.16087005,\n        0.3995047 , -0.21598581, -0.16484982])\n```\n:::\n:::\n\n\n::: {.callout-tip}\n## Linear predictors are centered\n\nThe linear predictor returned by `predict(type=\"lp\")` is always centered around the mean of the\ntraining covariates. This ensures consistent, numerically stable predictions across all variable\ntypes: continuous, categorical, and mixed. The centering is applied uniformly, so you always get\nmathematically sound risk scores, even in edge cases like categorical-only models with all positive\nassociations.\n:::\n\nThese are the scores the index will rank against the observed event order. Because higher risk\nshould correspond to earlier failure, we pass a score where larger means higher risk, such as this\nlinear predictor or its exponential.\n\n::: {#1ac42e2c .cell execution_count=5}\n``` {.python .cell-code}\ngw.concordance_index(y, risk)\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```\n0.6028530028979714\n```\n:::\n:::\n\n\n::: {.callout-note}\n## Discrimination is only part of the story\n\nA model can rank subjects well yet produce poorly calibrated probabilities, or vice versa. The\nconcordance index says nothing about whether predicted probabilities are numerically accurate. That\nis what the Brier score adds.\n:::\n\n## Censoring-corrected discrimination: the IPCW concordance index\n\nHarrell's C treats censored subjects by simply excluding incomparable pairs. When censoring is light\nand roughly uniform, this works well. But when censoring is heavy (more than 30-40% of subjects) or\ndiffers across risk groups, the resulting estimate can be biased because the excluded pairs are not\nmissing at random.\n\nThe IPCW concordance index of Uno et al. (2011) corrects for this by weighting each concordant pair\nby the inverse of the censoring probability at the event time. Subjects whose events occur at times\nwhen many others have already been censored receive higher weight, compensating for the information\nlost to censoring. The result is a consistent estimator of the true concordance probability.\n\n::: {#1346064e .cell execution_count=6}\n``` {.python .cell-code}\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\n\ny = gw.Surv.right(lung[\"time\"], event=(lung[\"status\"] == 2))\ncox = gw.CoxPH().fit(y, lung[[\"age\", \"sex\"]])\n\nrisk = cox.predict(type=\"lp\")\ngw.concordance_index_ipcw(y, risk)\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n```\nnp.float64(0.595890711822792)\n```\n:::\n:::\n\n\nIn the `lung` dataset censoring is moderate (~28%), so the IPCW and Harrell values are close. In\ndatasets with heavier censoring the two can diverge meaningfully. The IPCW version is the safer\ndefault for formal model comparisons.\n\nThe `tau` parameter restricts the evaluation to events before a truncation time. This avoids\ninstability from very small censoring probabilities in the tail, where few subjects remain under\nobservation. It also focuses discrimination on a clinically relevant horizon.\n\n::: {#c5aaf78a .cell execution_count=7}\n``` {.python .cell-code}\ngw.concordance_index_ipcw(y, risk, tau=365.0)\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```\nnp.float64(0.5990691290907791)\n```\n:::\n:::\n\n\n::: {.callout-tip}\n## Choosing tau\n\nWhen the censoring survival function drops close to zero in the tail, the IPCW weights become very\nlarge and the estimate becomes unstable. Setting `tau` to the end of the clinically relevant\nfollow-up window (for example, one year or five years) avoids this. The default is the largest\nobserved event time, which works well when censoring remains moderate throughout follow-up.\n:::\n\n## Accuracy: the Brier score\n\nThe Brier score is the mean squared error between predicted survival probabilities and actual\noutcomes, evaluated at a fixed time. Lower is better. Because outcomes are censored, the score uses\ninverse-probability-of-censoring weighting so that censored subjects contribute correctly rather\nthan being ignored or mishandled.\n\nTo compute it you supply predicted survival probabilities for each subject at each evaluation time.\nStart by asking the Cox model for survival curves at three fixed times.\n\n::: {#f94273d9 .cell execution_count=8}\n``` {.python .cell-code}\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\n\ny = gw.Surv.right(lung[\"time\"], event=(lung[\"status\"] == 2))\ncox = gw.CoxPH().fit(y, lung[[\"age\", \"sex\"]])\n\ntimes = [180, 365, 540]\nsurv = cox.predict(lung[[\"age\", \"sex\"]], type=\"survival\", times=times, format=\"polars\")\nsurv.shape\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```\n(3, 229)\n```\n:::\n:::\n\n\nThe returned DataFrame has a leading `time` column and one column per subject, so its shape is 3\nrows (the requested times) by 229 columns (228 subjects plus the time column). The Brier score wants\nthe transpose of this: an array with one row per subject and one column per time. We drop the `time`\ncolumn and transpose to get there.\n\n::: {#383c199c .cell execution_count=9}\n``` {.python .cell-code}\nprobs = surv.drop(\"time\").to_numpy().T\nprobs.shape\n```\n\n::: {.cell-output .cell-output-display execution_count=9}\n```\n(228, 3)\n```\n:::\n:::\n\n\nWith the probabilities in the expected `(n_subjects, n_times)` shape, we can score them.\n\n::: {#1314ad6b .cell execution_count=10}\n``` {.python .cell-code}\ngw.brier_score(y, probs, times)\n```\n\n::: {.cell-output .cell-output-display execution_count=10}\n```\narray([0.19160509, 0.23614214, 0.18644928])\n```\n:::\n:::\n\n\nThe result is one Brier score per time. As a rule of thumb, a useful model should beat the Brier\nscore of a model that ignores covariates, and a score approaching 0.25 at a time where about half\nthe subjects have had the event is close to uninformative.\n\nTo summarize accuracy across a range of times in a single number, integrate the Brier score over\ntime.\n\n::: {#143c7f1c .cell execution_count=11}\n``` {.python .cell-code}\ngw.integrated_brier_score(y, probs, times)\n```\n\n::: {.cell-output .cell-output-display execution_count=11}\n```\n0.21262046811957802\n```\n:::\n:::\n\n\n::: {.callout-tip}\n## Evaluate on data the model did not see\n\nComputing these metrics on the same data used to fit the model gives optimistic results. For an\nhonest assessment, evaluate on a held-out test set or use cross-validation, fitting on one part of\nthe data and scoring predictions on another.\n:::\n\n## Time-dependent discrimination: AUC over time\n\nThe concordance index summarises discrimination with a single number across all event times. But a\nmarker's ability to separate early failures from survivors often changes over follow-up: a biomarker\nmay identify six-month events well but lose its signal at five years. `time_dependent_auc()` gives\nyou a per-horizon view by computing the area under the ROC curve separately at each requested time.\n\nAt each time $t$, the estimator compares *cases* (subjects who had an event by $t$) against\n*controls* (subjects still at risk after $t$), and measures how well the marker separates the two\ngroups. Inverse-probability-of-censoring weights correct for the fact that not all subjects are\nobserved to the end of follow-up. The marker must be on a scale where larger means higher risk, so,\nthe Cox linear predictor is a natural choice.\n\n::: {#f0a8b315 .cell execution_count=12}\n``` {.python .cell-code}\nlp = cox.predict(type=\"lp\")\ngw.time_dependent_auc(y, lp, times=[180, 365, 540])\n```\n\n::: {.cell-output .cell-output-display execution_count=12}\n```\narray([0.64152627, 0.5943264 , 0.6023971 ])\n```\n:::\n:::\n\n\nEach value is the AUC at one horizon. Values above 0.5 mean the marker separates early failures from\nsurvivors better than chance at that time. Values close to 0.5 signal that the marker has lost\npredictive power at that horizon.\n\nTo reduce these to a single number for model comparison, `integrated_auc()` computes the\ntime-averaged AUC using the trapezoidal rule over the supplied time range.\n\n::: {#9347cebc .cell execution_count=13}\n``` {.python .cell-code}\ngw.integrated_auc(y, lp, times=[180, 365, 540])\n```\n\n::: {.cell-output .cell-output-display execution_count=13}\n```\n0.6084157733720682\n```\n:::\n:::\n\n\nThe integrated AUC plays the same role as the integrated Brier score: it collapses time-specific\ndiscrimination into one comparison-friendly number. Higher is better, and 0.5 is the random\nbaseline.\n\n## Cross-validation\n\nRather than splitting the data by hand, `cross_validate()` runs k-fold cross-validation for you: it\nfits a fresh copy of the model on each set of training folds and scores its predictions on the\nheld-out fold. Pass an unfitted model, the response, and the covariates.\n\n::: {#3723ec65 .cell execution_count=14}\n``` {.python .cell-code}\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\n\ny = gw.Surv.right(lung[\"time\"], event=(lung[\"status\"] == 2))\n\ngw.cross_validate(gw.CoxPH(), y, lung[[\"age\", \"sex\"]], k=5, metric=\"concordance\", seed=23)\n```\n\n::: {.cell-output .cell-output-display execution_count=14}\n```\n{'metric': 'concordance',\n 'k': 5,\n 'scores': [0.6617466174661747,\n  0.5448877805486284,\n  0.6838235294117647,\n  0.5580524344569289,\n  0.5926694329183956],\n 'mean': 0.6082359589603785,\n 'std': 0.06194870045682596}\n```\n:::\n:::\n\n\nThe result reports the score on each fold plus their mean and standard deviation. The\ncross-validated concordance is usually a little lower than the value computed on the training data,\nwhich is exactly the optimism we are trying to remove. Set `metric=\"brier\"` with a list of `times`\nto cross-validate the integrated Brier score instead. The same call works for `AFT` and\n`RoystonParmar` models.\n\n::: {#9eb862b3 .cell execution_count=15}\n``` {.python .cell-code}\ngw.cross_validate(\n    gw.CoxPH(), y, lung[[\"age\", \"sex\"]], k=5,\n    metric=\"brier\", times=[180, 365, 540], seed=23\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=15}\n```\n{'metric': 'brier',\n 'k': 5,\n 'scores': [0.21443779185001313,\n  0.20048397452015598,\n  0.21327986359004625,\n  0.23470395029714616,\n  0.22403878785186804],\n 'mean': 0.21738887362184595,\n 'std': 0.012800407222447734}\n```\n:::\n:::\n\n\n### Multi-metric mode\n\nWhen you want concordance, Brier, and AUC together, pass `metrics=` (plural) instead of `metric=`.\nThe model is fit once per fold and scored on every requested metric, so you get consistent fold\nassignments and avoid redundant refitting.\n\n::: {#9171a272 .cell execution_count=16}\n``` {.python .cell-code}\nresult_multi = gw.cross_validate(\n    gw.CoxPH(), y, lung[[\"age\", \"sex\"]], k=5,\n    metrics=[\"concordance\", \"brier\", \"auc\"],\n    times=[180, 365, 540], seed=23\n)\nresult_multi\n```\n\n::: {.cell-output .cell-output-display execution_count=16}\n```\n{'k': 5,\n 'results': {'concordance': {'scores': [0.6617466174661747,\n    0.5448877805486284,\n    0.6838235294117647,\n    0.5580524344569289,\n    0.5926694329183956],\n   'mean': 0.6082359589603785,\n   'std': 0.06194870045682596},\n  'brier': {'scores': [0.21443779185001313,\n    0.20048397452015598,\n    0.21327986359004625,\n    0.23470395029714616,\n    0.22403878785186804],\n   'mean': 0.21738887362184595,\n   'std': 0.012800407222447734},\n  'auc': {'scores': [0.7003890238319559,\n    0.5241297774787457,\n    0.7289478073383704,\n    0.5316521748637566,\n    0.47168767470244194],\n   'mean': 0.5913612916430542,\n   'std': 0.11535177220406084}}}\n```\n:::\n:::\n\n\nThe return value is a keyed dictionary. Each metric has its own `scores`, `mean`, and `std`:\n\n::: {#b8e3c6a6 .cell execution_count=17}\n``` {.python .cell-code}\nresult_multi[\"results\"][\"concordance\"][\"mean\"]\n```\n\n::: {.cell-output .cell-output-display execution_count=17}\n```\n0.6082359589603785\n```\n:::\n:::\n\n\n::: {#15f726bc .cell execution_count=18}\n``` {.python .cell-code}\nresult_multi[\"results\"][\"brier\"][\"mean\"]\n```\n\n::: {.cell-output .cell-output-display execution_count=18}\n```\n0.21738887362184595\n```\n:::\n:::\n\n\n### Stratified folds for imbalanced data\n\nBy default, `cross_validate()` uses stratified k-fold splitting. Rather than randomly assigning\nsubjects to folds, it groups subjects by event status first, then draws from each group\nproportionally. This ensures that each fold contains roughly the same fraction of events as the\noverall dataset.\n\nThis matters whenever events are rare. In a dataset where only 10% of subjects have the event, pure\nrandom splitting could easily put all events in one fold and none in another, leaving training sets\nwithout enough events to fit the model at all. Stratification prevents that. You can opt out with\n`stratified=False`, but there is rarely a good reason to.\n\n::: {.callout-warning}\n## Watch the event count\n\n`cross_validate()` warns when the total number of events is less than twice the number of folds. At\nthat point, some test folds will contain only one event, making per-fold scores unreliable:\n\n```\nUserWarning: Only 6 events found for 5-fold cross-validation\n(fewer than 2 × k = 10). Some folds may contain too few events\nfor reliable evaluation. Consider reducing k or collecting more\ndata with observed events.\n```\n\nIf you see this warning, either reduce `k=` to match the event count (e.g., `k=3` with 6 events) or\ntreat the cross-validated scores with caution.\n:::\n\n### Comparing models\n\nCross-validation is most useful as a comparison tool. Fit the same folds on two competing models,\nkeeping the same `seed`, and compare their mean scores directly. The model with higher mean\nconcordance (or lower mean Brier score) generalizes better to unseen subjects.\n\n::: {#46b5ef29 .cell execution_count=19}\n``` {.python .cell-code}\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\ny = gw.Surv.right(lung[\"time\"], event=(lung[\"status\"] == 2))\n\ncols_simple = lung[[\"age\", \"sex\"]]\ncols_full = lung[[\"age\", \"sex\", \"ph.ecog\"]]\n\nsimple_cv = gw.cross_validate(gw.CoxPH(), y, cols_simple, seed=1)\nfull_cv = gw.cross_validate(gw.CoxPH(), y, cols_full, seed=1)\n\nprint(f\"Simple model  C-index: {simple_cv['mean']:.3f} ± {simple_cv['std']:.3f}\")\nprint(f\"Full model    C-index: {full_cv['mean']:.3f} ± {full_cv['std']:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSimple model  C-index: 0.604 ± 0.077\nFull model    C-index: 0.639 ± 0.043\n```\n:::\n:::\n\n\nThe standard deviation across folds gives a rough sense of how stable the estimate is. Large\nfold-to-fold variation (relative to the difference between models) means the data do not contain\nenough information to reliably distinguish the two models on this metric alone.\n\n## Calibration\n\nDiscrimination and the Brier score both summarize a model in a single number. Calibration asks a\nmore detailed question: at a chosen time, do the predicted survival probabilities match what\nactually happens? `calibration()` groups subjects into bins by their predicted survival at a\nhorizon, then compares the mean prediction in each bin against the observed survival, a Kaplan-Meier\nestimate for that bin.\n\n::: {#a94d7b43 .cell execution_count=20}\n``` {.python .cell-code}\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\n\ny = gw.Surv.right(lung[\"time\"], event=(lung[\"status\"] == 2))\ncox = gw.CoxPH().fit(y, lung[[\"age\", \"sex\"]])\n\nsurv_at_year = cox.predict(\n    lung[[\"age\", \"sex\"]], type=\"survival\", times=[365.0], format=\"polars\"\n)\n\npredicted = surv_at_year.slice(0, 1).drop(\"time\").to_numpy().flatten()\n\ngw.calibration(y, predicted, 365.0, n_bins=5, format=\"polars\")\n```\n\n::: {.cell-output .cell-output-display execution_count=20}\n```{=html}\n<div id=\"gd-tbl-ea88de9b\" class=\"gd-tbl-preview\" style=\"padding-left: 0px; overflow-x: auto; overflow-y: hidden; width: 100%; max-width: 100%; margin-bottom: 1em;\">\n<style>\n@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,600;1,400&family=IBM+Plex+Sans:wght@400;600&display=swap');\n#gd-tbl-ea88de9b .gt_table {\n  display: table;\n  border-collapse: collapse;\n  table-layout: fixed;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 14px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n}\n#gd-tbl-ea88de9b .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-ea88de9b .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n#gd-tbl-ea88de9b .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n#gd-tbl-ea88de9b .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n#gd-tbl-ea88de9b .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-ea88de9b .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #F2F2F2;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #F2F2F2;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n#gd-tbl-ea88de9b .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n}\n#gd-tbl-ea88de9b .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #E9E9E9;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #E9E9E9;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #E9E9E9;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n#gd-tbl-ea88de9b .gt_left { text-align: left; }\n#gd-tbl-ea88de9b .gt_center { text-align: center; }\n#gd-tbl-ea88de9b .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n#gd-tbl-ea88de9b .gt_font_normal { font-weight: normal; }\n#gd-tbl-ea88de9b .gt_font_bold { font-weight: bold; }\n#gd-tbl-ea88de9b .gt_font_italic { font-style: italic; }\n#gd-tbl-ea88de9b .gt_striped { background-color: rgba(128,128,128,0.05); }\n#gd-tbl-ea88de9b .gt_from_md > :first-child { margin-top: 0; }\n#gd-tbl-ea88de9b .gt_from_md > :last-child { margin-bottom: 0; }\n/* Data cell font */\n#gd-tbl-ea88de9b .gt_table_body .gt_row {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  height: 14px;\n}\n/* Column label font */\n#gd-tbl-ea88de9b .gt_col_heading {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n}\n/* Row number styling */\n#gd-tbl-ea88de9b .gd-tbl-rownum {\n  color: gray;\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 10px;\n  border-right: 2px solid rgba(102, 153, 204, 0.5) !important;\n  text-align: right;\n  padding-right: 6px;\n  white-space: nowrap;\n}\n/* Head/tail divider */\n#gd-tbl-ea88de9b tr.gd-tbl-divider td,\n#gd-tbl-ea88de9b tr.gd-tbl-divider th {\n  border-bottom: 2px solid rgba(102, 153, 204, 0.5);\n}\n/* Missing values */\n#gd-tbl-ea88de9b .gd-tbl-missing {\n  color: #B22222 !important;\n  background-color: rgba(255, 193, 193, 0.35);\n}\n/* Column label sub-elements */\n#gd-tbl-ea88de9b .gd-tbl-colname {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-bottom: 0;\n  margin-bottom: 0;\n}\n#gd-tbl-ea88de9b .gd-tbl-dtype {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-top: 0;\n  margin-top: 0;\n  color: #666666;\n}\n/* Header badge styling */\n#gd-tbl-ea88de9b .gd-tbl-badge {\n  display: inline-block;\n  padding: 2px 10px;\n  font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, sans-serif;\n  font-size: 10px;\n  font-weight: bold;\n  text-transform: uppercase;\n  position: inherit;\n}\n#gd-tbl-ea88de9b .gd-tbl-badge-rows-label {\n  background-color: #eecbff;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: 5px;\n}\n#gd-tbl-ea88de9b .gd-tbl-badge-rows-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: -4px;\n  margin-right: 3px;\n}\n#gd-tbl-ea88de9b .gd-tbl-badge-cols-label {\n  background-color: #BDE7B4;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n}\n#gd-tbl-ea88de9b .gd-tbl-badge-cols-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n  margin-left: -4px;\n}\n/* Dark mode */\nbody.quarto-dark #gd-tbl-ea88de9b .gt_table,\nhtml.quarto-dark #gd-tbl-ea88de9b .gt_table,\n:root[data-bs-theme=\"dark\"] #gd-tbl-ea88de9b .gt_table {\n  background-color: #1a1a2e;\n  color: #e0e0e0;\n  border-top-color: #555;\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-ea88de9b .gt_heading,\nhtml.quarto-dark #gd-tbl-ea88de9b .gt_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-ea88de9b .gt_heading {\n  background-color: #1a1a2e;\n  border-bottom-color: #1a1a2e;\n}\nbody.quarto-dark #gd-tbl-ea88de9b .gt_title,\nhtml.quarto-dark #gd-tbl-ea88de9b .gt_title,\n:root[data-bs-theme=\"dark\"] #gd-tbl-ea88de9b .gt_title {\n  color: #e0e0e0;\n}\nbody.quarto-dark #gd-tbl-ea88de9b .gt_subtitle,\nhtml.quarto-dark #gd-tbl-ea88de9b .gt_subtitle,\n:root[data-bs-theme=\"dark\"] #gd-tbl-ea88de9b .gt_subtitle {\n  color: #b0b0b0;\n}\nbody.quarto-dark #gd-tbl-ea88de9b .gt_col_headings,\nhtml.quarto-dark #gd-tbl-ea88de9b .gt_col_headings,\n:root[data-bs-theme=\"dark\"] #gd-tbl-ea88de9b .gt_col_headings {\n  border-top-color: #444;\n  border-bottom-color: #444;\n}\nbody.quarto-dark #gd-tbl-ea88de9b .gt_col_heading,\nhtml.quarto-dark #gd-tbl-ea88de9b .gt_col_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-ea88de9b .gt_col_heading {\n  color: #b0b0b0;\n  background-color: #1a1a2e;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-ea88de9b .gt_table_body,\nhtml.quarto-dark #gd-tbl-ea88de9b .gt_table_body,\n:root[data-bs-theme=\"dark\"] #gd-tbl-ea88de9b .gt_table_body {\n  border-top-color: #444;\n}\nbody.quarto-dark #gd-tbl-ea88de9b .gt_table_body .gt_row,\nhtml.quarto-dark #gd-tbl-ea88de9b .gt_table_body .gt_row,\n:root[data-bs-theme=\"dark\"] #gd-tbl-ea88de9b .gt_table_body .gt_row {\n  color: #d0d0d0;\n  border-top-color: #4b4b4b;\n  border-bottom-color: #4b4b4b;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-ea88de9b .gd-tbl-rownum,\nhtml.quarto-dark #gd-tbl-ea88de9b .gd-tbl-rownum,\n:root[data-bs-theme=\"dark\"] #gd-tbl-ea88de9b .gd-tbl-rownum {\n  color: #888;\n  border-right-color: rgba(102, 153, 204, 0.4) !important;\n}\nbody.quarto-dark #gd-tbl-ea88de9b .gd-tbl-missing,\nhtml.quarto-dark #gd-tbl-ea88de9b .gd-tbl-missing,\n:root[data-bs-theme=\"dark\"] #gd-tbl-ea88de9b .gd-tbl-missing {\n  color: #ff6b6b !important;\n  background-color: rgba(60, 17, 24, 0.2);\n}\nbody.quarto-dark #gd-tbl-ea88de9b .gd-tbl-dtype,\nhtml.quarto-dark #gd-tbl-ea88de9b .gd-tbl-dtype,\n:root[data-bs-theme=\"dark\"] #gd-tbl-ea88de9b .gd-tbl-dtype {\n  color: #888;\n}\nbody.quarto-dark #gd-tbl-ea88de9b .gt_bottom_border,\nhtml.quarto-dark #gd-tbl-ea88de9b .gt_bottom_border,\n:root[data-bs-theme=\"dark\"] #gd-tbl-ea88de9b .gt_bottom_border {\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-ea88de9b .gd-tbl-badge-rows-label,\nhtml.quarto-dark #gd-tbl-ea88de9b .gd-tbl-badge-rows-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-ea88de9b .gd-tbl-badge-rows-label {\n  background-color: #3d2a4d;\n  border-color: #3d2a4d;\n  color: #e0c0ff;\n}\nbody.quarto-dark #gd-tbl-ea88de9b .gd-tbl-badge-rows-value,\nhtml.quarto-dark #gd-tbl-ea88de9b .gd-tbl-badge-rows-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-ea88de9b .gd-tbl-badge-rows-value {\n  border-color: #3d2a4d;\n  color: #d0b0e0;\n}\nbody.quarto-dark #gd-tbl-ea88de9b .gd-tbl-badge-cols-label,\nhtml.quarto-dark #gd-tbl-ea88de9b .gd-tbl-badge-cols-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-ea88de9b .gd-tbl-badge-cols-label {\n  background-color: #2a4d2a;\n  border-color: #2a4d2a;\n  color: #b0e0b0;\n}\nbody.quarto-dark #gd-tbl-ea88de9b .gd-tbl-badge-cols-value,\nhtml.quarto-dark #gd-tbl-ea88de9b .gd-tbl-badge-cols-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-ea88de9b .gd-tbl-badge-cols-value {\n  border-color: #2a4d2a;\n  color: #a0d0a0;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"true\" data-quarto-bootstrap=\"false\">\n<colgroup>\n<col style=\"width: 35px\"/>\n<col style=\"width: 50px\"/>\n<col style=\"width: 50px\"/>\n<col style=\"width: 117px\"/>\n<col style=\"width: 117px\"/>\n<col style=\"width: 125px\"/>\n<col style=\"width: 125px\"/>\n</colgroup>\n<thead>\n<tr class=\"gt_heading\"><td class=\"gt_heading gt_title gt_font_normal\" colspan=\"7\"><div style=\"padding-top: 0; padding-bottom: 7px;\"><span class=\"gd-tbl-badge\" style=\"background-color: #0075FF; color: #FFFFFF; border: 1px solid #0075FF; margin-right: 8px;\">Polars</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-label\">Rows</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-value\">5</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-label\">Columns</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-value\">6</span></div></td></tr>\n<tr class=\"gt_col_headings\">\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\"></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"bin\"><div><div class=\"gd-tbl-colname\">bin</div><div class=\"gd-tbl-dtype\"><em>i64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\"><div><div class=\"gd-tbl-colname\">n</div><div class=\"gd-tbl-dtype\"><em>i64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"predicted\"><div><div class=\"gd-tbl-colname\">predicted</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"observed\"><div><div class=\"gd-tbl-colname\">observed</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"observed_lower\"><div><div class=\"gd-tbl-colname\">observed_lower</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"observed_upper\"><div><div class=\"gd-tbl-colname\">observed_upper</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 50px;\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 50px;\">45</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.275643654127</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.226515151515</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 125px;\">0.125630250282</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 125px;\">0.40841368819</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 50px;\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 50px;\">44</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.325992610784</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.363081617086</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 125px;\">0.237804025086</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 125px;\">0.554356725535</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 50px;\">3</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 50px;\">45</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.388623683685</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.408115942029</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 125px;\">0.284454511367</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 125px;\">0.585536932909</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">3</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 50px;\">4</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 50px;\">45</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.485377847087</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.54000350566</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 125px;\">0.395496812687</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 125px;\">0.737310078795</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">4</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 50px;\">5</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 50px;\">49</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.568638173192</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.514285348805</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 125px;\">0.376278476604</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 125px;\">0.702908713734</td>\n</tr>\n</tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nEach row is a bin, from the lowest predicted survival to the highest. A well-calibrated model has\n`observed` close to `predicted` in every bin, with the observed values inside their confidence\nlimits. Systematic gaps, for example predictions consistently higher than observed, signal\nmiscalibration even when discrimination is good.\n\n::: {.callout-tip}\n## Assess calibration out of sample too\n\nLike the other metrics, calibration is optimistic on the training data. For a fair picture,\ncompute it on held-out predictions, for instance the test-fold predictions from a\ncross-validation split.\n:::\n\n## Next steps\n\nYou can now quantify how well a survival model discriminates and predicts.\n\n- [Cox model diagnostics](cox-diagnostics.qmd) covers the assumption checks and residuals\nthat complement these performance metrics.\n- [Parametric survival models](parametric-models.qmd) and\n[Cox regression](cox-regression.qmd) produce the predictions these metrics evaluate.\n- The [Quick start](quick-start.qmd) ties the whole workflow together.\n\n",
    "supporting": [
      "prediction-performance_files/figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}