{
  "hash": "01cb073658b7f09c3df63ef3ebf10d50",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: Prediction performance\nguide-section: \"Evaluation\"\nbread-crumbs: false\n---\n\n\n\nA model that fits the data in front of it is not necessarily a model that predicts well. To judge a\nsurvival model as a predictor, or to compare competing models, you need metrics that account for\ncensoring. Greenwood provides three complementary ones: (1) the concordance index, (measures how\nwell a model ranks subjects by risk), (2) the Brier score (measures how accurate its probability\npredictions are), and (3) the time-dependent AUC (shows how discrimination changes over the\nfollow-up horizon). This guide page explains all three and shows how to compute them for a fitted\nmodel or for any external risk score.\n\nWe start from the `lung` outcomes and a Cox model fit to them. This is the model whose predictions\nwe will judge.\n\n::: {#5ca89c75 .cell execution_count=2}\n``` {.python .cell-code}\nimport greenwood as gw\n\n# Load the lung dataset\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\n\n# Name the survival response columns, then bind them to the data to display a summary\ndeath = gw.Outcome.surv(time=\"time\", event=\"status\")\ndeath.bind(lung)\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```\nSurv(type=right, n=228, events=165)\n```\n:::\n:::\n\n\nThe response `death` names the follow-up time and event columns, and bound to `lung` it records 165\nevents among 228 subjects. We fit a Cox model with the same response, then set the model aside:\neverything below needs only `death`, the data, and the risk scores and survival probabilities that\n`cox` produces. Each metric reads the response columns from the frame passed as `data=`.\n\n::: {#b44c463d .cell execution_count=3}\n``` {.python .cell-code}\n# Fit a Cox model with age and sex as covariates\ncox = gw.CoxPH().fit(\"Surv(time, status) ~ age + sex\", data=lung)\n```\n:::\n\n\n## Discrimination: the concordance index\n\nDiscrimination is the ability to rank subjects correctly: to give higher risk scores to subjects who\ngo on to have the event sooner. The concordance index, or C-statistic, measures exactly this. It is\nthe probability that, for a randomly chosen comparable pair of subjects, the one who failed first\nhad the higher risk score. A value of 0.5 is no better than a coin flip, and 1.0 is perfect\nordering.\n\nYou can compute it for any risk score, which makes it useful for evaluating a model on new data or\nfor comparing an external score. Here we use the Cox model's linear predictor. Asking for\n`type=\"lp\"` returns one number per subject, where a larger value means higher predicted risk.\n\n::: {#70a753bc .cell execution_count=4}\n``` {.python .cell-code}\n# Rebuild the dataset, response, and Cox fit for this section\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\n\ndeath = gw.Outcome.surv(time=\"time\", event=\"status\")\ncox = gw.CoxPH().fit(\"Surv(time, status) ~ age + sex\", data=lung)\n\n# Extract the linear predictor (risk score) for each subject\nrisk = cox.predict(type=\"lp\")\nrisk[:8]\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```\narray([ 0.3995047 ,  0.2972327 ,  0.09268872,  0.10973405,  0.16087005,\n        0.3995047 , -0.21598581, -0.16484982])\n```\n:::\n:::\n\n\n::: {.callout-tip}\n## Linear predictors are centered\n\nThe linear predictor returned by `predict(type=\"lp\")` is always centered around the mean of the\ntraining covariates. This ensures consistent, numerically stable predictions across all variable\ntypes: continuous, categorical, and mixed. The centering is applied uniformly, so you always get\nmathematically sound risk scores, even in edge cases like categorical-only models with all positive\nassociations.\n:::\n\nThese are the scores the index will rank against the observed event order. Because higher risk\nshould correspond to earlier failure, we pass a score where larger means higher risk, such as this\nlinear predictor or its exponential.\n\n::: {#3ad01582 .cell execution_count=5}\n``` {.python .cell-code}\n# Compute Harrell's concordance index from the risk scores\ngw.concordance_index(death, risk=risk, data=lung)\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```\n0.6028530028979714\n```\n:::\n:::\n\n\n::: {.callout-note}\n## Discrimination is only part of the story\n\nA model can rank subjects well yet produce poorly calibrated probabilities, or vice versa. The\nconcordance index says nothing about whether predicted probabilities are numerically accurate. That\nis what the Brier score adds.\n:::\n\n## Censoring-corrected discrimination: the IPCW concordance index\n\nHarrell's C treats censored subjects by simply excluding incomparable pairs. When censoring is light\nand roughly uniform, this works well. But when censoring is heavy (more than 30-40% of subjects) or\ndiffers across risk groups, the resulting estimate can be biased because the excluded pairs are not\nmissing at random.\n\nThe IPCW concordance index of Uno et al. (2011) corrects for this by weighting each concordant pair\nby the inverse of the censoring probability at the event time. Subjects whose events occur at times\nwhen many others have already been censored receive higher weight, compensating for the information\nlost to censoring. The result is a consistent estimator of the true concordance probability.\n\n::: {#13a162a6 .cell execution_count=6}\n``` {.python .cell-code}\n# Rebuild the dataset, response, and Cox fit\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\n\ndeath = gw.Outcome.surv(time=\"time\", event=\"status\")\ncox = gw.CoxPH().fit(\"Surv(time, status) ~ age + sex\", data=lung)\n\n# IPCW concordance index corrected for censoring bias\nrisk = cox.predict(type=\"lp\")\ngw.concordance_index_ipcw(death, risk=risk, data=lung)\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n```\nnp.float64(0.595890711822792)\n```\n:::\n:::\n\n\nIn the `lung` dataset censoring is moderate (~28%), so the IPCW and Harrell values are close. In\ndatasets with heavier censoring the two can diverge meaningfully. The IPCW version is the safer\ndefault for formal model comparisons.\n\nThe `tau` parameter restricts the evaluation to events before a truncation time. This avoids\ninstability from very small censoring probabilities in the tail, where few subjects remain under\nobservation. It also focuses discrimination on a clinically relevant horizon.\n\n::: {#74b7bd6d .cell execution_count=7}\n``` {.python .cell-code}\n# Restrict evaluation to events before one year\ngw.concordance_index_ipcw(death, risk=risk, data=lung, tau=365.0)\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```\nnp.float64(0.5990691290907791)\n```\n:::\n:::\n\n\n::: {.callout-tip}\n## Choosing tau\n\nWhen the censoring survival function drops close to zero in the tail, the IPCW weights become very\nlarge and the estimate becomes unstable. Setting `tau` to the end of the clinically relevant\nfollow-up window (for example, one year or five years) avoids this. The default is the largest\nobserved event time, which works well when censoring remains moderate throughout follow-up.\n:::\n\n## Concordance confidence intervals\n\nA point estimate of the concordance is not enough for a formal comparison. You also need a standard\nerror and a confidence interval. `concordance_index_ci()` computes the IPCW concordance and derives\nthe standard error from the influence function decomposition, which avoids the cost of\nbootstrapping. The confidence interval is constructed on the logit scale (the default), which\nrespects the [0, 1] bounds and provides better coverage when the estimate is near either extreme.\n\n::: {#9e880828 .cell execution_count=8}\n``` {.python .cell-code}\n# Rebuild the dataset, response, and Cox fit\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\n\ndeath = gw.Outcome.surv(time=\"time\", event=\"status\")\ncox = gw.CoxPH().fit(\"Surv(time, status) ~ age + sex\", data=lung)\n\n# Concordance with standard error and confidence interval\nrisk = cox.predict(type=\"lp\")\ngw.concordance_index_ci(death, risk=risk, data=lung)\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```\nConcordanceResult(estimate=0.5959, se=0.0391, CI=[0.5176, 0.6696], conf_level=0.95)\n```\n:::\n:::\n\n\nThe result is a `ConcordanceResult` with the point estimate, standard error, and confidence limits.\nYou can convert it to a one-row DataFrame with `to_frame()`.\n\n::: {#45380bf6 .cell execution_count=9}\n``` {.python .cell-code}\n# Convert the result to a one-row DataFrame\ngw.concordance_index_ci(death, risk=risk, data=lung).to_frame()\n```\n\n::: {.cell-output .cell-output-display execution_count=9}\n```{=html}\n<div id=\"gd-tbl-4bb38817\" class=\"gd-tbl-preview\" style=\"padding-left: 0px; overflow-x: auto; overflow-y: hidden; width: 100%; max-width: 100%; margin-bottom: 1em;\">\n<style>\n@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,600;1,400&family=IBM+Plex+Sans:wght@400;600&display=swap');\n#gd-tbl-4bb38817 .gt_table {\n  display: table;\n  border-collapse: collapse;\n  table-layout: fixed;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 14px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n}\n#gd-tbl-4bb38817 .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-4bb38817 .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n#gd-tbl-4bb38817 .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n#gd-tbl-4bb38817 .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n#gd-tbl-4bb38817 .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-4bb38817 .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #F2F2F2;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #F2F2F2;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n#gd-tbl-4bb38817 .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n}\n#gd-tbl-4bb38817 .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #E9E9E9;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #E9E9E9;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #E9E9E9;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n#gd-tbl-4bb38817 .gt_left { text-align: left; }\n#gd-tbl-4bb38817 .gt_center { text-align: center; }\n#gd-tbl-4bb38817 .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n#gd-tbl-4bb38817 .gt_font_normal { font-weight: normal; }\n#gd-tbl-4bb38817 .gt_font_bold { font-weight: bold; }\n#gd-tbl-4bb38817 .gt_font_italic { font-style: italic; }\n#gd-tbl-4bb38817 .gt_striped { background-color: rgba(128,128,128,0.05); }\n#gd-tbl-4bb38817 .gt_from_md > :first-child { margin-top: 0; }\n#gd-tbl-4bb38817 .gt_from_md > :last-child { margin-bottom: 0; }\n/* Data cell font */\n#gd-tbl-4bb38817 .gt_table_body .gt_row {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  height: 14px;\n}\n/* Column label font */\n#gd-tbl-4bb38817 .gt_col_heading {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n}\n/* Row number styling */\n#gd-tbl-4bb38817 .gd-tbl-rownum {\n  color: gray;\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 10px;\n  border-right: 2px solid rgba(102, 153, 204, 0.5) !important;\n  text-align: right;\n  padding-right: 6px;\n  white-space: nowrap;\n}\n/* Head/tail divider */\n#gd-tbl-4bb38817 tr.gd-tbl-divider td,\n#gd-tbl-4bb38817 tr.gd-tbl-divider th {\n  border-bottom: 2px solid rgba(102, 153, 204, 0.5);\n}\n/* Missing values */\n#gd-tbl-4bb38817 .gd-tbl-missing {\n  color: #B22222 !important;\n  background-color: rgba(255, 193, 193, 0.35);\n}\n/* Column label sub-elements */\n#gd-tbl-4bb38817 .gd-tbl-colname {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-bottom: 0;\n  margin-bottom: 0;\n}\n#gd-tbl-4bb38817 .gd-tbl-dtype {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-top: 0;\n  margin-top: 0;\n  color: #666666;\n}\n/* Header badge styling */\n#gd-tbl-4bb38817 .gd-tbl-badge {\n  display: inline-block;\n  padding: 2px 10px;\n  font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, sans-serif;\n  font-size: 10px;\n  font-weight: bold;\n  text-transform: uppercase;\n  position: inherit;\n}\n#gd-tbl-4bb38817 .gd-tbl-badge-rows-label {\n  background-color: #eecbff;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: 5px;\n}\n#gd-tbl-4bb38817 .gd-tbl-badge-rows-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: -4px;\n  margin-right: 3px;\n}\n#gd-tbl-4bb38817 .gd-tbl-badge-cols-label {\n  background-color: #BDE7B4;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n}\n#gd-tbl-4bb38817 .gd-tbl-badge-cols-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n  margin-left: -4px;\n}\n/* Dark mode */\nbody.quarto-dark #gd-tbl-4bb38817 .gt_table,\nhtml.quarto-dark #gd-tbl-4bb38817 .gt_table,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4bb38817 .gt_table {\n  background-color: #1a1a2e;\n  color: #e0e0e0;\n  border-top-color: #555;\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-4bb38817 .gt_heading,\nhtml.quarto-dark #gd-tbl-4bb38817 .gt_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4bb38817 .gt_heading {\n  background-color: #1a1a2e;\n  border-bottom-color: #1a1a2e;\n}\nbody.quarto-dark #gd-tbl-4bb38817 .gt_title,\nhtml.quarto-dark #gd-tbl-4bb38817 .gt_title,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4bb38817 .gt_title {\n  color: #e0e0e0;\n}\nbody.quarto-dark #gd-tbl-4bb38817 .gt_subtitle,\nhtml.quarto-dark #gd-tbl-4bb38817 .gt_subtitle,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4bb38817 .gt_subtitle {\n  color: #b0b0b0;\n}\nbody.quarto-dark #gd-tbl-4bb38817 .gt_col_headings,\nhtml.quarto-dark #gd-tbl-4bb38817 .gt_col_headings,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4bb38817 .gt_col_headings {\n  border-top-color: #444;\n  border-bottom-color: #444;\n}\nbody.quarto-dark #gd-tbl-4bb38817 .gt_col_heading,\nhtml.quarto-dark #gd-tbl-4bb38817 .gt_col_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4bb38817 .gt_col_heading {\n  color: #b0b0b0;\n  background-color: #1a1a2e;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-4bb38817 .gt_table_body,\nhtml.quarto-dark #gd-tbl-4bb38817 .gt_table_body,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4bb38817 .gt_table_body {\n  border-top-color: #444;\n}\nbody.quarto-dark #gd-tbl-4bb38817 .gt_table_body .gt_row,\nhtml.quarto-dark #gd-tbl-4bb38817 .gt_table_body .gt_row,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4bb38817 .gt_table_body .gt_row {\n  color: #d0d0d0;\n  border-top-color: #4b4b4b;\n  border-bottom-color: #4b4b4b;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-4bb38817 .gd-tbl-rownum,\nhtml.quarto-dark #gd-tbl-4bb38817 .gd-tbl-rownum,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4bb38817 .gd-tbl-rownum {\n  color: #888;\n  border-right-color: rgba(102, 153, 204, 0.4) !important;\n}\nbody.quarto-dark #gd-tbl-4bb38817 .gd-tbl-missing,\nhtml.quarto-dark #gd-tbl-4bb38817 .gd-tbl-missing,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4bb38817 .gd-tbl-missing {\n  color: #ff6b6b !important;\n  background-color: rgba(60, 17, 24, 0.2);\n}\nbody.quarto-dark #gd-tbl-4bb38817 .gd-tbl-dtype,\nhtml.quarto-dark #gd-tbl-4bb38817 .gd-tbl-dtype,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4bb38817 .gd-tbl-dtype {\n  color: #888;\n}\nbody.quarto-dark #gd-tbl-4bb38817 .gt_bottom_border,\nhtml.quarto-dark #gd-tbl-4bb38817 .gt_bottom_border,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4bb38817 .gt_bottom_border {\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-4bb38817 .gd-tbl-badge-rows-label,\nhtml.quarto-dark #gd-tbl-4bb38817 .gd-tbl-badge-rows-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4bb38817 .gd-tbl-badge-rows-label {\n  background-color: #3d2a4d;\n  border-color: #3d2a4d;\n  color: #e0c0ff;\n}\nbody.quarto-dark #gd-tbl-4bb38817 .gd-tbl-badge-rows-value,\nhtml.quarto-dark #gd-tbl-4bb38817 .gd-tbl-badge-rows-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4bb38817 .gd-tbl-badge-rows-value {\n  border-color: #3d2a4d;\n  color: #d0b0e0;\n}\nbody.quarto-dark #gd-tbl-4bb38817 .gd-tbl-badge-cols-label,\nhtml.quarto-dark #gd-tbl-4bb38817 .gd-tbl-badge-cols-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4bb38817 .gd-tbl-badge-cols-label {\n  background-color: #2a4d2a;\n  border-color: #2a4d2a;\n  color: #b0e0b0;\n}\nbody.quarto-dark #gd-tbl-4bb38817 .gd-tbl-badge-cols-value,\nhtml.quarto-dark #gd-tbl-4bb38817 .gd-tbl-badge-cols-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4bb38817 .gd-tbl-badge-cols-value {\n  border-color: #2a4d2a;\n  color: #a0d0a0;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"true\" data-quarto-bootstrap=\"false\">\n<colgroup>\n<col style=\"width: 35px\"/>\n<col style=\"width: 117px\"/>\n<col style=\"width: 124px\"/>\n<col style=\"width: 117px\"/>\n<col style=\"width: 117px\"/>\n<col style=\"width: 50px\"/>\n</colgroup>\n<thead>\n<tr class=\"gt_heading\"><td class=\"gt_heading gt_title gt_font_normal\" colspan=\"6\"><div style=\"padding-top: 0; padding-bottom: 7px;\"><span class=\"gd-tbl-badge\" style=\"background-color: #0075FF; color: #FFFFFF; border: 1px solid #0075FF; margin-right: 8px;\">Polars</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-label\">Rows</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-value\">1</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-label\">Columns</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-value\">5</span></div></td></tr>\n<tr class=\"gt_col_headings\">\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\"></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><div><div class=\"gd-tbl-colname\">estimate</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"se\"><div><div class=\"gd-tbl-colname\">se</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf_low\"><div><div class=\"gd-tbl-colname\">conf_low</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf_high\"><div><div class=\"gd-tbl-colname\">conf_high</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\"><div><div class=\"gd-tbl-colname\">n</div><div class=\"gd-tbl-dtype\"><em>i64</em></div></div></th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.595890711823</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 124px;\">0.0390599327328</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.517606378803</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.669580691608</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 50px;\">228</td>\n</tr>\n</tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThe `transform` parameter controls the scale on which the CI is constructed. The default `\"logit\"`\nis recommended because it keeps the interval inside [0, 1] even when the estimate is close to the\nboundary. The `\"log\"` and `\"identity\"` options are available for comparison.\n\n::: {#1ebfcc5b .cell execution_count=10}\n``` {.python .cell-code}\n# Same concordance with an identity-scale confidence interval\ngw.concordance_index_ci(death, risk=risk, data=lung, transform=\"identity\")\n```\n\n::: {.cell-output .cell-output-display execution_count=10}\n```\nConcordanceResult(estimate=0.5959, se=0.0391, CI=[0.5193, 0.6724], conf_level=0.95)\n```\n:::\n:::\n\n\nFor competing-risks data, pass `cause=` and `tau=` to get the cause-specific concordance with its\nCI. This uses the incidence-weighted influence function, which accounts for both standard and\ncompeting-event pairs.\n\n::: {#2d44e73c .cell execution_count=11}\n``` {.python .cell-code}\nimport numpy as np\n\n# Load competing-risks data\nmgus2 = gw.load_dataset(\"mgus2\", backend=\"polars\")\n\n# The first observed endpoint (PCM at `ptime`, or death at `futime`) is the event\ncr = gw.Outcome.first_event(\n    endpoints={\"pcm\": (\"ptime\", \"pstat\"), \"death\": (\"futime\", \"death\")},\n)\n\n# Fit a Fine-Gray model for PCM and predict CIF at 240 months\nfg = gw.FineGray(cause=\"pcm\").fit(cr, covariates=[\"age\", \"sex\"], data=mgus2)\ncif_at_tau = fg.predict_cumulative_incidence(\n    mgus2, times=np.array([240.0]), format=\"pandas\"\n).drop(columns=\"time\").values.flatten()\n\n# Cause-specific concordance with confidence interval\ngw.concordance_index_ci(cr, risk=cif_at_tau, data=mgus2, cause=1, tau=240.0)\n```\n\n::: {.cell-output .cell-output-display execution_count=11}\n```\nConcordanceResult(estimate=0.5780, se=0.0278, CI=[0.5228, 0.6314], conf_level=0.95)\n```\n:::\n:::\n\n\n## Comparing two concordance indices\n\nWhen two models are fit on the same subjects, their concordance estimates are correlated. A naive\ncomparison that treats them as independent underestimates uncertainty and inflates the Type I error\nrate. The `concordance_index_compare()` function uses the paired influence-function delta method:\nit computes the difference in concordance indices and derives the standard error from the joint\ninfluence function, which properly accounts for the shared subjects.\n\n::: {#72760f09 .cell execution_count=12}\n``` {.python .cell-code}\n# Rebuild the dataset and response\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\n\ndeath = gw.Outcome.surv(time=\"time\", event=\"status\")\n\n# Fit two competing Cox models\ncox_full = gw.CoxPH().fit(\"Surv(time, status) ~ age + sex\", data=lung)\ncox_age = gw.CoxPH().fit(\"Surv(time, status) ~ age\", data=lung)\n\n# Extract linear predictors from each model\nlp_full = cox_full.predict(type=\"lp\")\nlp_age = cox_age.predict(type=\"lp\")\n\n# Paired comparison of concordance indices\ngw.concordance_index_compare(death, risk_a=lp_full, risk_b=lp_age, data=lung)\n```\n\n::: {.cell-output .cell-output-display execution_count=12}\n```\nConcordanceCompareResult(delta=0.0467, se=0.0355, CI=[-0.0228, 0.1162], z=1.318, p=0.1875)\n```\n:::\n:::\n\n\nThe result reports the difference (model A minus model B), its standard error, a confidence\ninterval, a z-statistic, and a two-sided p-value. A small p-value means the two models have\ndetectably different discrimination on this data. The result also has a `to_frame()` method for\ntabular output.\n\n::: {#1952a6aa .cell execution_count=13}\n``` {.python .cell-code}\n# Tabular output of the paired comparison\ngw.concordance_index_compare(death, risk_a=lp_full, risk_b=lp_age, data=lung).to_frame()\n```\n\n::: {.cell-output .cell-output-display execution_count=13}\n```{=html}\n<div id=\"gd-tbl-9d06f6bb\" class=\"gd-tbl-preview\" style=\"padding-left: 0px; overflow-x: auto; overflow-y: hidden; width: 100%; max-width: 100%; margin-bottom: 1em;\">\n<style>\n@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,600;1,400&family=IBM+Plex+Sans:wght@400;600&display=swap');\n#gd-tbl-9d06f6bb .gt_table {\n  display: table;\n  border-collapse: collapse;\n  table-layout: fixed;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 14px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n}\n#gd-tbl-9d06f6bb .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-9d06f6bb .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n#gd-tbl-9d06f6bb .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n#gd-tbl-9d06f6bb .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n#gd-tbl-9d06f6bb .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-9d06f6bb .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #F2F2F2;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #F2F2F2;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n#gd-tbl-9d06f6bb .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n}\n#gd-tbl-9d06f6bb .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #E9E9E9;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #E9E9E9;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #E9E9E9;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n#gd-tbl-9d06f6bb .gt_left { text-align: left; }\n#gd-tbl-9d06f6bb .gt_center { text-align: center; }\n#gd-tbl-9d06f6bb .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n#gd-tbl-9d06f6bb .gt_font_normal { font-weight: normal; }\n#gd-tbl-9d06f6bb .gt_font_bold { font-weight: bold; }\n#gd-tbl-9d06f6bb .gt_font_italic { font-style: italic; }\n#gd-tbl-9d06f6bb .gt_striped { background-color: rgba(128,128,128,0.05); }\n#gd-tbl-9d06f6bb .gt_from_md > :first-child { margin-top: 0; }\n#gd-tbl-9d06f6bb .gt_from_md > :last-child { margin-bottom: 0; }\n/* Data cell font */\n#gd-tbl-9d06f6bb .gt_table_body .gt_row {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  height: 14px;\n}\n/* Column label font */\n#gd-tbl-9d06f6bb .gt_col_heading {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n}\n/* Row number styling */\n#gd-tbl-9d06f6bb .gd-tbl-rownum {\n  color: gray;\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 10px;\n  border-right: 2px solid rgba(102, 153, 204, 0.5) !important;\n  text-align: right;\n  padding-right: 6px;\n  white-space: nowrap;\n}\n/* Head/tail divider */\n#gd-tbl-9d06f6bb tr.gd-tbl-divider td,\n#gd-tbl-9d06f6bb tr.gd-tbl-divider th {\n  border-bottom: 2px solid rgba(102, 153, 204, 0.5);\n}\n/* Missing values */\n#gd-tbl-9d06f6bb .gd-tbl-missing {\n  color: #B22222 !important;\n  background-color: rgba(255, 193, 193, 0.35);\n}\n/* Column label sub-elements */\n#gd-tbl-9d06f6bb .gd-tbl-colname {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-bottom: 0;\n  margin-bottom: 0;\n}\n#gd-tbl-9d06f6bb .gd-tbl-dtype {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-top: 0;\n  margin-top: 0;\n  color: #666666;\n}\n/* Header badge styling */\n#gd-tbl-9d06f6bb .gd-tbl-badge {\n  display: inline-block;\n  padding: 2px 10px;\n  font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, sans-serif;\n  font-size: 10px;\n  font-weight: bold;\n  text-transform: uppercase;\n  position: inherit;\n}\n#gd-tbl-9d06f6bb .gd-tbl-badge-rows-label {\n  background-color: #eecbff;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: 5px;\n}\n#gd-tbl-9d06f6bb .gd-tbl-badge-rows-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: -4px;\n  margin-right: 3px;\n}\n#gd-tbl-9d06f6bb .gd-tbl-badge-cols-label {\n  background-color: #BDE7B4;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n}\n#gd-tbl-9d06f6bb .gd-tbl-badge-cols-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n  margin-left: -4px;\n}\n/* Dark mode */\nbody.quarto-dark #gd-tbl-9d06f6bb .gt_table,\nhtml.quarto-dark #gd-tbl-9d06f6bb .gt_table,\n:root[data-bs-theme=\"dark\"] #gd-tbl-9d06f6bb .gt_table {\n  background-color: #1a1a2e;\n  color: #e0e0e0;\n  border-top-color: #555;\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-9d06f6bb .gt_heading,\nhtml.quarto-dark #gd-tbl-9d06f6bb .gt_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-9d06f6bb .gt_heading {\n  background-color: #1a1a2e;\n  border-bottom-color: #1a1a2e;\n}\nbody.quarto-dark #gd-tbl-9d06f6bb .gt_title,\nhtml.quarto-dark #gd-tbl-9d06f6bb .gt_title,\n:root[data-bs-theme=\"dark\"] #gd-tbl-9d06f6bb .gt_title {\n  color: #e0e0e0;\n}\nbody.quarto-dark #gd-tbl-9d06f6bb .gt_subtitle,\nhtml.quarto-dark #gd-tbl-9d06f6bb .gt_subtitle,\n:root[data-bs-theme=\"dark\"] #gd-tbl-9d06f6bb .gt_subtitle {\n  color: #b0b0b0;\n}\nbody.quarto-dark #gd-tbl-9d06f6bb .gt_col_headings,\nhtml.quarto-dark #gd-tbl-9d06f6bb .gt_col_headings,\n:root[data-bs-theme=\"dark\"] #gd-tbl-9d06f6bb .gt_col_headings {\n  border-top-color: #444;\n  border-bottom-color: #444;\n}\nbody.quarto-dark #gd-tbl-9d06f6bb .gt_col_heading,\nhtml.quarto-dark #gd-tbl-9d06f6bb .gt_col_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-9d06f6bb .gt_col_heading {\n  color: #b0b0b0;\n  background-color: #1a1a2e;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-9d06f6bb .gt_table_body,\nhtml.quarto-dark #gd-tbl-9d06f6bb .gt_table_body,\n:root[data-bs-theme=\"dark\"] #gd-tbl-9d06f6bb .gt_table_body {\n  border-top-color: #444;\n}\nbody.quarto-dark #gd-tbl-9d06f6bb .gt_table_body .gt_row,\nhtml.quarto-dark #gd-tbl-9d06f6bb .gt_table_body .gt_row,\n:root[data-bs-theme=\"dark\"] #gd-tbl-9d06f6bb .gt_table_body .gt_row {\n  color: #d0d0d0;\n  border-top-color: #4b4b4b;\n  border-bottom-color: #4b4b4b;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-9d06f6bb .gd-tbl-rownum,\nhtml.quarto-dark #gd-tbl-9d06f6bb .gd-tbl-rownum,\n:root[data-bs-theme=\"dark\"] #gd-tbl-9d06f6bb .gd-tbl-rownum {\n  color: #888;\n  border-right-color: rgba(102, 153, 204, 0.4) !important;\n}\nbody.quarto-dark #gd-tbl-9d06f6bb .gd-tbl-missing,\nhtml.quarto-dark #gd-tbl-9d06f6bb .gd-tbl-missing,\n:root[data-bs-theme=\"dark\"] #gd-tbl-9d06f6bb .gd-tbl-missing {\n  color: #ff6b6b !important;\n  background-color: rgba(60, 17, 24, 0.2);\n}\nbody.quarto-dark #gd-tbl-9d06f6bb .gd-tbl-dtype,\nhtml.quarto-dark #gd-tbl-9d06f6bb .gd-tbl-dtype,\n:root[data-bs-theme=\"dark\"] #gd-tbl-9d06f6bb .gd-tbl-dtype {\n  color: #888;\n}\nbody.quarto-dark #gd-tbl-9d06f6bb .gt_bottom_border,\nhtml.quarto-dark #gd-tbl-9d06f6bb .gt_bottom_border,\n:root[data-bs-theme=\"dark\"] #gd-tbl-9d06f6bb .gt_bottom_border {\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-9d06f6bb .gd-tbl-badge-rows-label,\nhtml.quarto-dark #gd-tbl-9d06f6bb .gd-tbl-badge-rows-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-9d06f6bb .gd-tbl-badge-rows-label {\n  background-color: #3d2a4d;\n  border-color: #3d2a4d;\n  color: #e0c0ff;\n}\nbody.quarto-dark #gd-tbl-9d06f6bb .gd-tbl-badge-rows-value,\nhtml.quarto-dark #gd-tbl-9d06f6bb .gd-tbl-badge-rows-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-9d06f6bb .gd-tbl-badge-rows-value {\n  border-color: #3d2a4d;\n  color: #d0b0e0;\n}\nbody.quarto-dark #gd-tbl-9d06f6bb .gd-tbl-badge-cols-label,\nhtml.quarto-dark #gd-tbl-9d06f6bb .gd-tbl-badge-cols-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-9d06f6bb .gd-tbl-badge-cols-label {\n  background-color: #2a4d2a;\n  border-color: #2a4d2a;\n  color: #b0e0b0;\n}\nbody.quarto-dark #gd-tbl-9d06f6bb .gd-tbl-badge-cols-value,\nhtml.quarto-dark #gd-tbl-9d06f6bb .gd-tbl-badge-cols-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-9d06f6bb .gd-tbl-badge-cols-value {\n  border-color: #2a4d2a;\n  color: #a0d0a0;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"true\" data-quarto-bootstrap=\"false\">\n<colgroup>\n<col style=\"width: 35px\"/>\n<col style=\"width: 124px\"/>\n<col style=\"width: 124px\"/>\n<col style=\"width: 131px\"/>\n<col style=\"width: 117px\"/>\n<col style=\"width: 110px\"/>\n<col style=\"width: 117px\"/>\n</colgroup>\n<thead>\n<tr class=\"gt_heading\"><td class=\"gt_heading gt_title gt_font_normal\" colspan=\"7\"><div style=\"padding-top: 0; padding-bottom: 7px;\"><span class=\"gd-tbl-badge\" style=\"background-color: #0075FF; color: #FFFFFF; border: 1px solid #0075FF; margin-right: 8px;\">Polars</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-label\">Rows</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-value\">1</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-label\">Columns</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-value\">6</span></div></td></tr>\n<tr class=\"gt_col_headings\">\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\"></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"delta\"><div><div class=\"gd-tbl-colname\">delta</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"se\"><div><div class=\"gd-tbl-colname\">se</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf_low\"><div><div class=\"gd-tbl-colname\">conf_low</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf_high\"><div><div class=\"gd-tbl-colname\">conf_high</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"z\"><div><div class=\"gd-tbl-colname\">z</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"pvalue\"><div><div class=\"gd-tbl-colname\">pvalue</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 124px;\">0.0467304912597</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 124px;\">0.0354554283048</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 131px;\">-0.0227608712742</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.116221853794</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 110px;\">1.31800667751</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.187501412585</td>\n</tr>\n</tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {.callout-tip}\n## When to use paired comparison vs. cross-validation\n\n`concordance_index_compare()` gives you a formal hypothesis test on a single dataset. Cross-\nvalidation with `cross_validate()` gives you an estimate of out-of-sample performance. They answer\ndifferent questions. Use the paired test when you want a p-value for the difference on the observed\ndata. Use cross-validation when you want to estimate how much better one model will perform on new\nsubjects.\n:::\n\n## The censoring distribution\n\nThe IPCW concordance index above works because it knows how likely each subject was to be censored.\nThat knowledge comes from a `CensoringDistribution`, which estimates the Kaplan-Meier curve of the\ncensoring process. Greenwood uses it internally for all IPCW metrics, but you can also create one\ndirectly when you need the censoring probabilities or IPC weights for a custom analysis.\n\n::: {#ea51ae99 .cell execution_count=14}\n``` {.python .cell-code}\n# Rebuild the dataset and response\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\ndeath = gw.Outcome.surv(time=\"time\", event=\"status\")\n\n# Estimate the censoring distribution from the response (it takes a bound `Surv`)\ncens = gw.CensoringDistribution(death.bind(lung))\ncens\n```\n\n::: {.cell-output .cell-output-display execution_count=14}\n```\nCensoringDistribution (n=228, censored=63)\n  60 unique censoring times, tail G = 0.0000\n```\n:::\n:::\n\n\nThe `survival()` method evaluates the censoring survival function G(t), which is the probability of\nnot being censored by time t, at any set of query times.\n\n::: {#0ce3e0a8 .cell execution_count=15}\n``` {.python .cell-code}\n# Evaluate the censoring survival function G(t) at three times\ncens.survival(times=[180, 365, 540])\n```\n\n::: {.cell-output .cell-output-display execution_count=15}\n```\narray([0.96644606, 0.69728182, 0.56736787])\n```\n:::\n:::\n\n\nThe values decrease over follow-up as more subjects are censored. At 180 days about 97% of subjects\nare still under observation, but by 540 days only 57% remain.\n\nThe `weights()` method returns the IPC weights that correct for censoring. Each uncensored subject\nreceives a weight of 1 / G(t-), where G(t-) is the censoring survival just before their event time.\nCensored subjects receive weight zero (they are excluded from the reweighted analysis). Subjects\nwhose events occur when censoring is heavy get larger weights because they represent more unobserved\nindividuals.\n\n::: {#ff8e4be5 .cell execution_count=16}\n``` {.python .cell-code}\n# IPC weights: 1/G(t-) for uncensored, 0 for censored\nw = cens.weights()\nw[:10]\n```\n\n::: {.cell-output .cell-output-display execution_count=16}\n```\narray([1.35885572, 1.59245456, 0.        , 1.09235351, 3.8210638 ,\n       0.        , 1.35885572, 1.41273529, 1.10044502, 1.01015385])\n```\n:::\n:::\n\n\nYou can restrict weights to a time horizon with `tau`. Subjects with events after `tau` receive zero\nweight, which avoids instability from very small censoring probabilities in the tail.\n\n::: {#90b61455 .cell execution_count=17}\n``` {.python .cell-code}\n# Restrict weights to events before one year\ncens.weights(tau=365.0)[:10]\n```\n\n::: {.cell-output .cell-output-display execution_count=17}\n```\narray([1.35885572, 0.        , 0.        , 1.09235351, 0.        ,\n       0.        , 1.35885572, 1.41273529, 1.10044502, 1.01015385])\n```\n:::\n:::\n\n\nThe full censoring curve is available as a DataFrame via `to_frame()`.\n\n::: {#8bfac60f .cell execution_count=18}\n``` {.python .cell-code}\n# Full censoring curve as a DataFrame\ncens.to_frame()\n```\n\n::: {.cell-output .cell-output-display execution_count=18}\n```{=html}\n<div id=\"gd-tbl-4b21349f\" class=\"gd-tbl-preview\" style=\"padding-left: 0px; overflow-x: auto; overflow-y: hidden; width: 100%; max-width: 100%; margin-bottom: 1em;\">\n<style>\n@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,600;1,400&family=IBM+Plex+Sans:wght@400;600&display=swap');\n#gd-tbl-4b21349f .gt_table {\n  display: table;\n  border-collapse: collapse;\n  table-layout: fixed;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 14px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n}\n#gd-tbl-4b21349f .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-4b21349f .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n#gd-tbl-4b21349f .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n#gd-tbl-4b21349f .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n#gd-tbl-4b21349f .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-4b21349f .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #F2F2F2;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #F2F2F2;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n#gd-tbl-4b21349f .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n}\n#gd-tbl-4b21349f .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #E9E9E9;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #E9E9E9;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #E9E9E9;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n#gd-tbl-4b21349f .gt_left { text-align: left; }\n#gd-tbl-4b21349f .gt_center { text-align: center; }\n#gd-tbl-4b21349f .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n#gd-tbl-4b21349f .gt_font_normal { font-weight: normal; }\n#gd-tbl-4b21349f .gt_font_bold { font-weight: bold; }\n#gd-tbl-4b21349f .gt_font_italic { font-style: italic; }\n#gd-tbl-4b21349f .gt_striped { background-color: rgba(128,128,128,0.05); }\n#gd-tbl-4b21349f .gt_from_md > :first-child { margin-top: 0; }\n#gd-tbl-4b21349f .gt_from_md > :last-child { margin-bottom: 0; }\n/* Data cell font */\n#gd-tbl-4b21349f .gt_table_body .gt_row {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  height: 14px;\n}\n/* Column label font */\n#gd-tbl-4b21349f .gt_col_heading {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n}\n/* Row number styling */\n#gd-tbl-4b21349f .gd-tbl-rownum {\n  color: gray;\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 10px;\n  border-right: 2px solid rgba(102, 153, 204, 0.5) !important;\n  text-align: right;\n  padding-right: 6px;\n  white-space: nowrap;\n}\n/* Head/tail divider */\n#gd-tbl-4b21349f tr.gd-tbl-divider td,\n#gd-tbl-4b21349f tr.gd-tbl-divider th {\n  border-bottom: 2px solid rgba(102, 153, 204, 0.5);\n}\n/* Missing values */\n#gd-tbl-4b21349f .gd-tbl-missing {\n  color: #B22222 !important;\n  background-color: rgba(255, 193, 193, 0.35);\n}\n/* Column label sub-elements */\n#gd-tbl-4b21349f .gd-tbl-colname {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-bottom: 0;\n  margin-bottom: 0;\n}\n#gd-tbl-4b21349f .gd-tbl-dtype {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-top: 0;\n  margin-top: 0;\n  color: #666666;\n}\n/* Header badge styling */\n#gd-tbl-4b21349f .gd-tbl-badge {\n  display: inline-block;\n  padding: 2px 10px;\n  font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, sans-serif;\n  font-size: 10px;\n  font-weight: bold;\n  text-transform: uppercase;\n  position: inherit;\n}\n#gd-tbl-4b21349f .gd-tbl-badge-rows-label {\n  background-color: #eecbff;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: 5px;\n}\n#gd-tbl-4b21349f .gd-tbl-badge-rows-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: -4px;\n  margin-right: 3px;\n}\n#gd-tbl-4b21349f .gd-tbl-badge-cols-label {\n  background-color: #BDE7B4;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n}\n#gd-tbl-4b21349f .gd-tbl-badge-cols-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n  margin-left: -4px;\n}\n/* Dark mode */\nbody.quarto-dark #gd-tbl-4b21349f .gt_table,\nhtml.quarto-dark #gd-tbl-4b21349f .gt_table,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4b21349f .gt_table {\n  background-color: #1a1a2e;\n  color: #e0e0e0;\n  border-top-color: #555;\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-4b21349f .gt_heading,\nhtml.quarto-dark #gd-tbl-4b21349f .gt_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4b21349f .gt_heading {\n  background-color: #1a1a2e;\n  border-bottom-color: #1a1a2e;\n}\nbody.quarto-dark #gd-tbl-4b21349f .gt_title,\nhtml.quarto-dark #gd-tbl-4b21349f .gt_title,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4b21349f .gt_title {\n  color: #e0e0e0;\n}\nbody.quarto-dark #gd-tbl-4b21349f .gt_subtitle,\nhtml.quarto-dark #gd-tbl-4b21349f .gt_subtitle,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4b21349f .gt_subtitle {\n  color: #b0b0b0;\n}\nbody.quarto-dark #gd-tbl-4b21349f .gt_col_headings,\nhtml.quarto-dark #gd-tbl-4b21349f .gt_col_headings,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4b21349f .gt_col_headings {\n  border-top-color: #444;\n  border-bottom-color: #444;\n}\nbody.quarto-dark #gd-tbl-4b21349f .gt_col_heading,\nhtml.quarto-dark #gd-tbl-4b21349f .gt_col_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4b21349f .gt_col_heading {\n  color: #b0b0b0;\n  background-color: #1a1a2e;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-4b21349f .gt_table_body,\nhtml.quarto-dark #gd-tbl-4b21349f .gt_table_body,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4b21349f .gt_table_body {\n  border-top-color: #444;\n}\nbody.quarto-dark #gd-tbl-4b21349f .gt_table_body .gt_row,\nhtml.quarto-dark #gd-tbl-4b21349f .gt_table_body .gt_row,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4b21349f .gt_table_body .gt_row {\n  color: #d0d0d0;\n  border-top-color: #4b4b4b;\n  border-bottom-color: #4b4b4b;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-4b21349f .gd-tbl-rownum,\nhtml.quarto-dark #gd-tbl-4b21349f .gd-tbl-rownum,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4b21349f .gd-tbl-rownum {\n  color: #888;\n  border-right-color: rgba(102, 153, 204, 0.4) !important;\n}\nbody.quarto-dark #gd-tbl-4b21349f .gd-tbl-missing,\nhtml.quarto-dark #gd-tbl-4b21349f .gd-tbl-missing,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4b21349f .gd-tbl-missing {\n  color: #ff6b6b !important;\n  background-color: rgba(60, 17, 24, 0.2);\n}\nbody.quarto-dark #gd-tbl-4b21349f .gd-tbl-dtype,\nhtml.quarto-dark #gd-tbl-4b21349f .gd-tbl-dtype,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4b21349f .gd-tbl-dtype {\n  color: #888;\n}\nbody.quarto-dark #gd-tbl-4b21349f .gt_bottom_border,\nhtml.quarto-dark #gd-tbl-4b21349f .gt_bottom_border,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4b21349f .gt_bottom_border {\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-4b21349f .gd-tbl-badge-rows-label,\nhtml.quarto-dark #gd-tbl-4b21349f .gd-tbl-badge-rows-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4b21349f .gd-tbl-badge-rows-label {\n  background-color: #3d2a4d;\n  border-color: #3d2a4d;\n  color: #e0c0ff;\n}\nbody.quarto-dark #gd-tbl-4b21349f .gd-tbl-badge-rows-value,\nhtml.quarto-dark #gd-tbl-4b21349f .gd-tbl-badge-rows-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4b21349f .gd-tbl-badge-rows-value {\n  border-color: #3d2a4d;\n  color: #d0b0e0;\n}\nbody.quarto-dark #gd-tbl-4b21349f .gd-tbl-badge-cols-label,\nhtml.quarto-dark #gd-tbl-4b21349f .gd-tbl-badge-cols-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4b21349f .gd-tbl-badge-cols-label {\n  background-color: #2a4d2a;\n  border-color: #2a4d2a;\n  color: #b0e0b0;\n}\nbody.quarto-dark #gd-tbl-4b21349f .gd-tbl-badge-cols-value,\nhtml.quarto-dark #gd-tbl-4b21349f .gd-tbl-badge-cols-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4b21349f .gd-tbl-badge-cols-value {\n  border-color: #2a4d2a;\n  color: #a0d0a0;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"true\" data-quarto-bootstrap=\"false\">\n<colgroup>\n<col style=\"width: 35px\"/>\n<col style=\"width: 195px\"/>\n<col style=\"width: 269px\"/>\n</colgroup>\n<thead>\n<tr class=\"gt_heading\"><td class=\"gt_heading gt_title gt_font_normal\" colspan=\"3\"><div style=\"padding-top: 0; padding-bottom: 7px;\"><span class=\"gd-tbl-badge\" style=\"background-color: #0075FF; color: #FFFFFF; border: 1px solid #0075FF; margin-right: 8px;\">Polars</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-label\">Rows</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-value\">60</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-label\">Columns</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-value\">2</span></div></td></tr>\n<tr class=\"gt_col_headings\">\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\"></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"time\"><div><div class=\"gd-tbl-colname\">time</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"survival\"><div><div class=\"gd-tbl-colname\">survival</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 195px;\">92</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 269px;\">0.995024875622</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 195px;\">105</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 269px;\">0.989948218093</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 195px;\">173</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 269px;\">0.984090536329</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">3</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 195px;\">174</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 269px;\">0.978232854565</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">4</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 195px;\">175</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 269px;\">0.972375172802</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">5</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 195px;\">177</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 269px;\">0.966446055894</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">6</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 195px;\">185</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 269px;\">0.96021092005</td>\n</tr>\n<tr class=\"gd-tbl-divider\">\n<td class=\"gt_row gt_right gd-tbl-rownum\">7</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 195px;\">188</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 269px;\">0.953935031683</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">57</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 195px;\">965</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 269px;\">0.174471482741</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">58</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 195px;\">1010</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 269px;\">0.0872357413706</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">59</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 195px;\">1022</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 269px;\">0</td>\n</tr>\n</tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## Accuracy: the Brier score\n\nThe Brier score is the mean squared error between predicted survival probabilities and actual\noutcomes, evaluated at a fixed time. Lower is better. Because outcomes are censored, the score uses\ninverse-probability-of-censoring weighting so that censored subjects contribute correctly rather\nthan being ignored or mishandled.\n\nTo compute it you supply predicted survival probabilities for each subject at each evaluation time.\nStart by asking the Cox model for survival curves at three fixed times.\n\n::: {#61c1274d .cell execution_count=19}\n``` {.python .cell-code}\n# Rebuild the dataset, response, and Cox fit\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\n\ndeath = gw.Outcome.surv(time=\"time\", event=\"status\")\ncox = gw.CoxPH().fit(\"Surv(time, status) ~ age + sex\", data=lung)\n\n# Predict survival probabilities at three fixed times\ntimes = [180, 365, 540]\nsurv = cox.predict(lung, type=\"survival\", times=times, format=\"polars\")\nsurv.shape\n```\n\n::: {.cell-output .cell-output-display execution_count=19}\n```\n(3, 229)\n```\n:::\n:::\n\n\nThe returned DataFrame has a leading `time` column and one column per subject, so its shape is 3\nrows (the requested times) by 229 columns (228 subjects plus the time column). The Brier score wants\nthe transpose of this: an array with one row per subject and one column per time. We drop the `time`\ncolumn and transpose to get there.\n\n::: {#6ab9f5e4 .cell execution_count=20}\n``` {.python .cell-code}\n# Transpose to (n_subjects, n_times) for the Brier score\nprobs = surv.drop(\"time\").to_numpy().T\nprobs.shape\n```\n\n::: {.cell-output .cell-output-display execution_count=20}\n```\n(228, 3)\n```\n:::\n:::\n\n\nWith the probabilities in the expected `(n_subjects, n_times)` shape, we can score them.\n\n::: {#96f8fdc0 .cell execution_count=21}\n``` {.python .cell-code}\n# IPCW Brier score at each evaluation time\ngw.brier_score(death, survival_prob=probs, times=times, data=lung)\n```\n\n::: {.cell-output .cell-output-display execution_count=21}\n```\narray([0.19160509, 0.23614214, 0.18644928])\n```\n:::\n:::\n\n\nThe result is one Brier score per time. As a rule of thumb, a useful model should beat the Brier\nscore of a model that ignores covariates, and a score approaching 0.25 at a time where about half\nthe subjects have had the event is close to uninformative.\n\nTo summarize accuracy across a range of times in a single number, integrate the Brier score over\ntime.\n\n::: {#3d83419d .cell execution_count=22}\n``` {.python .cell-code}\n# Integrated Brier score across the three time horizons\ngw.integrated_brier_score(death, survival_prob=probs, times=times, data=lung)\n```\n\n::: {.cell-output .cell-output-display execution_count=22}\n```\n0.21262046811957802\n```\n:::\n:::\n\n\n::: {.callout-tip}\n## Evaluate on data the model did not see\n\nComputing these metrics on the same data used to fit the model gives optimistic results. For an\nhonest assessment, evaluate on a held-out test set or use cross-validation, fitting on one part of\nthe data and scoring predictions on another.\n:::\n\n## Brier score for competing risks\n\nThe standard Brier score evaluates predicted survival probabilities. In a competing-risks setting,\nthe quantity of interest is instead the cumulative incidence function (CIF) for a specific cause.\n`brier_score_incidence()` extends the IPCW Brier score to this setting: it compares predicted CIF\nprobabilities against observed cause-specific outcomes.\n\nThe weighting scheme accounts for competing events. Subjects who experienced *any* event (including\na competing cause) before the evaluation time are weighted by the inverse censoring probability at\ntheir event time. Subjects still at risk contribute at the inverse censoring probability at the\nevaluation time. Subjects censored before the evaluation time receive zero weight.\n\nTo illustrate, we describe a competing-risks response for the `mgus2` dataset, where subjects may\nprogress to plasma cell malignancy (PCM) or die without progression. `Outcome.first_event()` names\nthe time and status columns of each endpoint.\n\n::: {#be8fad12 .cell execution_count=23}\n``` {.python .cell-code}\nimport numpy as np\n\n# Load competing-risks data\nmgus2 = gw.load_dataset(\"mgus2\", backend=\"polars\")\n\n# The first observed endpoint (PCM at `ptime`, or death at `futime`) is the event\ncr = gw.Outcome.first_event(\n    endpoints={\"pcm\": (\"ptime\", \"pstat\"), \"death\": (\"futime\", \"death\")},\n)\n\n# Bind the response to the data to display its summary\ncr.bind(mgus2)\n```\n\n::: {.cell-output .cell-output-display execution_count=23}\n```\nSurv(type=mright, n=1384, events=975, states=('pcm', 'death'))\n```\n:::\n:::\n\n\nAs a baseline, we use the marginal Aalen-Johansen CIF as a naive model that predicts the same CIF\nfor every subject.\n\n::: {#ed5ec1c7 .cell execution_count=24}\n``` {.python .cell-code}\n# Fit Aalen-Johansen and extract the marginal PCM incidence curve\naj = gw.AalenJohansen().fit(cr, data=mgus2)\ncif_df = aj.to_frame(format=\"polars\")\npcm_cif = cif_df.filter(cif_df[\"cause\"] == \"pcm\")\n\n# Interpolate the marginal CIF at the evaluation times\ntimes_cr = np.array([60, 120, 240])\nmarginal = np.array(\n    [float(np.interp(t, pcm_cif[\"time\"].to_numpy(), pcm_cif[\"estimate\"].to_numpy()))\n     for t in times_cr]\n)\n\n# Tile the marginal CIF across all subjects and compute the Brier score\nprobs_cr = np.tile(marginal, (mgus2.height, 1))\ngw.brier_score_incidence(cr, incidence_prob=probs_cr, times=times_cr, data=mgus2, cause=1)\n```\n\n::: {.cell-output .cell-output-display execution_count=24}\n```\narray([0.03293805, 0.05966165, 0.0898196 ])\n```\n:::\n:::\n\n\nThe `cause=` argument selects which event code to evaluate. Here `cause=1` corresponds to\nprogression (the first endpoint listed in `endpoints=`). To evaluate death predictions instead,\npass `cause=2`.\n\nAs with the survival Brier score, you can summarize accuracy over a range of times in a single\nnumber with the integrated version.\n\n::: {#3c05084a .cell execution_count=25}\n``` {.python .cell-code}\n# Evaluate the integrated Brier score on a finer grid\ntimes_fine = np.linspace(30, 360, 12)\nmarginal_fine = np.array(\n    [float(np.interp(t, pcm_cif[\"time\"].to_numpy(), pcm_cif[\"estimate\"].to_numpy()))\n     for t in times_fine]\n)\nprobs_fine = np.tile(marginal_fine, (mgus2.height, 1))\ngw.integrated_brier_score_incidence(\n    cr, incidence_prob=probs_fine, times=times_fine, data=mgus2, cause=1\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=25}\n```\n0.07514656777562731\n```\n:::\n:::\n\n\nA model that uses covariates to produce subject-specific CIF predictions should yield a lower\nintegrated Brier score than this marginal baseline.\n\n## Concordance for competing risks\n\nThe standard concordance index evaluates discrimination for a single event type. In a\ncompeting-risks setting, `concordance_index_incidence()` extends the IPCW concordance to\ncause-specific cumulative incidence predictions (Wolbers et al., 2014). It compares two types of\npairs: standard pairs (a subject who experienced the cause of interest vs. a subject still at risk)\nand competing-event pairs (a subject who experienced the cause vs. one who experienced a competing\nevent). Each pair type receives its own IPCW weight.\n\nUsing the same `mgus2` competing-risks data from above, we evaluate the concordance of the marginal\nAalen-Johansen CIF at 240 months. Because the marginal model predicts the same value for every\nsubject, its concordance is 0.5 (no discrimination).\n\n::: {#8359c5d8 .cell execution_count=26}\n``` {.python .cell-code}\n# Marginal CIF at tau=240 months: same prediction for everyone\ntau = 240.0\nmarginal_at_tau = float(\n    np.interp(tau, pcm_cif[\"time\"].to_numpy(), pcm_cif[\"estimate\"].to_numpy())\n)\npred_flat = np.full(mgus2.height, marginal_at_tau)\n\n# Concordance for the flat prediction (expected to be 0.5)\ngw.concordance_index_incidence(cr, incidence_prob=pred_flat, data=mgus2, cause=1, tau=tau)\n```\n\n::: {.cell-output .cell-output-display execution_count=26}\n```\nnp.float64(0.49999999999999994)\n```\n:::\n:::\n\n\nA model that produces subject-specific CIF predictions should achieve a concordance above 0.5.\n\n## Calibration for competing risks\n\nBeyond discrimination, a model's predicted CIF values should match the observed incidence on\naverage. `calibration_incidence()` checks marginal calibration by comparing the mean predicted CIF\nat each time against the nonparametric Aalen-Johansen reference. The result is the absolute\ncalibration error at each time point.\n\n::: {#3b6c58ad .cell execution_count=27}\n``` {.python .cell-code}\n# Calibration check: mean predicted CIF vs. AJ reference\ncal_err = gw.calibration_incidence(\n    cr, incidence_prob=probs_cr, times=times_cr, data=mgus2, cause=1\n)\ncal_err\n```\n\n::: {.cell-output .cell-output-display execution_count=27}\n```\narray([6.93889390e-18, 1.38777878e-17, 1.38777878e-17])\n```\n:::\n:::\n\n\nBecause the marginal model *is* the AJ reference, its calibration error is essentially zero. A\nsubject-specific model will typically show nonzero errors, especially in the tails.\n\n## Accuracy in time for competing risks\n\nWhen the model predicts CIFs for all competing causes, `accuracy_in_time()` evaluates whether the\nmodel correctly identifies the most likely outcome at each time horizon. At time $\\zeta$, each\nsubject's predicted outcome is the argmax of the predicted CIFs plus the implied survival\nprobability. The metric reports the proportion of uncensored subjects whose predicted class matches\nthe observed outcome.\n\n::: {#a0625ae8 .cell execution_count=28}\n``` {.python .cell-code}\n# Interpolate both CIFs at the evaluation times\ndeath_cif = cif_df.filter(cif_df[\"cause\"] == \"death\")\npcm_vals = np.array(\n    [float(np.interp(t, pcm_cif[\"time\"].to_numpy(), pcm_cif[\"estimate\"].to_numpy()))\n     for t in times_cr]\n)\ndeath_vals = np.array(\n    [float(np.interp(t, death_cif[\"time\"].to_numpy(), death_cif[\"estimate\"].to_numpy()))\n     for t in times_cr]\n)\n# Stack into (n_subjects, n_causes, n_times) and compute accuracy\nprobs_3d = np.stack(\n    [np.tile(pcm_vals, (mgus2.height, 1)), np.tile(death_vals, (mgus2.height, 1))], axis=1\n)\n\ngw.accuracy_in_time(cr, incidence_probs=probs_3d, times=times_cr, data=mgus2)\n```\n\n::: {.cell-output .cell-output-display execution_count=28}\n```\narray([0.63884786, 0.58021613, 0.83711747])\n```\n:::\n:::\n\n\nEarly times tend to show high accuracy because most subjects have survived and the model predicts\nsurvival. The metric becomes most informative at later times, when discriminating between competing\nevents matters.\n\n## Bundled competing-risks scoring\n\nWhen evaluating a competing-risks model you typically want concordance, per-time Brier scores, and\nthe integrated Brier score all at once. `score_cr()` computes them in a single call and returns a\ntidy summary table. The concordance row includes a confidence interval from the influence function.\nThe Brier rows report point estimates only.\n\n::: {#6d2b14b7 .cell execution_count=29}\n``` {.python .cell-code}\nimport numpy as np\n\n# Load data and build competing-risks response\nmgus2 = gw.load_dataset(\"mgus2\", backend=\"polars\")\n\n# The first observed endpoint (PCM at `ptime`, or death at `futime`) is the event\ncr = gw.Outcome.first_event(\n    endpoints={\"pcm\": (\"ptime\", \"pstat\"), \"death\": (\"futime\", \"death\")},\n)\n\n# Fit Fine-Gray for PCM and predict CIF at three horizons\nfg = gw.FineGray(cause=\"pcm\").fit(cr, covariates=[\"age\", \"sex\"], data=mgus2)\n\neval_times = np.array([120, 240, 360])\ncif_pred = fg.predict_cumulative_incidence(\n    mgus2, times=eval_times, format=\"pandas\"\n).drop(columns=\"time\").values.T\n\n# Bundle concordance, Brier, and integrated Brier into one summary\ngw.score_cr(cr, incidence_prob=cif_pred, data=mgus2, cause=1, times=eval_times)\n```\n\n::: {.cell-output .cell-output-display execution_count=29}\n```{=html}\n<div id=\"gd-tbl-e49eba35\" class=\"gd-tbl-preview\" style=\"padding-left: 0px; overflow-x: auto; overflow-y: hidden; width: 100%; max-width: 100%; margin-bottom: 1em;\">\n<style>\n@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,600;1,400&family=IBM+Plex+Sans:wght@400;600&display=swap');\n#gd-tbl-e49eba35 .gt_table {\n  display: table;\n  border-collapse: collapse;\n  table-layout: fixed;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 14px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n}\n#gd-tbl-e49eba35 .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-e49eba35 .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n#gd-tbl-e49eba35 .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n#gd-tbl-e49eba35 .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n#gd-tbl-e49eba35 .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-e49eba35 .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #F2F2F2;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #F2F2F2;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n#gd-tbl-e49eba35 .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n}\n#gd-tbl-e49eba35 .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #E9E9E9;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #E9E9E9;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #E9E9E9;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n#gd-tbl-e49eba35 .gt_left { text-align: left; }\n#gd-tbl-e49eba35 .gt_center { text-align: center; }\n#gd-tbl-e49eba35 .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n#gd-tbl-e49eba35 .gt_font_normal { font-weight: normal; }\n#gd-tbl-e49eba35 .gt_font_bold { font-weight: bold; }\n#gd-tbl-e49eba35 .gt_font_italic { font-style: italic; }\n#gd-tbl-e49eba35 .gt_striped { background-color: rgba(128,128,128,0.05); }\n#gd-tbl-e49eba35 .gt_from_md > :first-child { margin-top: 0; }\n#gd-tbl-e49eba35 .gt_from_md > :last-child { margin-bottom: 0; }\n/* Data cell font */\n#gd-tbl-e49eba35 .gt_table_body .gt_row {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  height: 14px;\n}\n/* Column label font */\n#gd-tbl-e49eba35 .gt_col_heading {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n}\n/* Row number styling */\n#gd-tbl-e49eba35 .gd-tbl-rownum {\n  color: gray;\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 10px;\n  border-right: 2px solid rgba(102, 153, 204, 0.5) !important;\n  text-align: right;\n  padding-right: 6px;\n  white-space: nowrap;\n}\n/* Head/tail divider */\n#gd-tbl-e49eba35 tr.gd-tbl-divider td,\n#gd-tbl-e49eba35 tr.gd-tbl-divider th {\n  border-bottom: 2px solid rgba(102, 153, 204, 0.5);\n}\n/* Missing values */\n#gd-tbl-e49eba35 .gd-tbl-missing {\n  color: #B22222 !important;\n  background-color: rgba(255, 193, 193, 0.35);\n}\n/* Column label sub-elements */\n#gd-tbl-e49eba35 .gd-tbl-colname {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-bottom: 0;\n  margin-bottom: 0;\n}\n#gd-tbl-e49eba35 .gd-tbl-dtype {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-top: 0;\n  margin-top: 0;\n  color: #666666;\n}\n/* Header badge styling */\n#gd-tbl-e49eba35 .gd-tbl-badge {\n  display: inline-block;\n  padding: 2px 10px;\n  font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, sans-serif;\n  font-size: 10px;\n  font-weight: bold;\n  text-transform: uppercase;\n  position: inherit;\n}\n#gd-tbl-e49eba35 .gd-tbl-badge-rows-label {\n  background-color: #eecbff;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: 5px;\n}\n#gd-tbl-e49eba35 .gd-tbl-badge-rows-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: -4px;\n  margin-right: 3px;\n}\n#gd-tbl-e49eba35 .gd-tbl-badge-cols-label {\n  background-color: #BDE7B4;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n}\n#gd-tbl-e49eba35 .gd-tbl-badge-cols-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n  margin-left: -4px;\n}\n/* Dark mode */\nbody.quarto-dark #gd-tbl-e49eba35 .gt_table,\nhtml.quarto-dark #gd-tbl-e49eba35 .gt_table,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e49eba35 .gt_table {\n  background-color: #1a1a2e;\n  color: #e0e0e0;\n  border-top-color: #555;\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-e49eba35 .gt_heading,\nhtml.quarto-dark #gd-tbl-e49eba35 .gt_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e49eba35 .gt_heading {\n  background-color: #1a1a2e;\n  border-bottom-color: #1a1a2e;\n}\nbody.quarto-dark #gd-tbl-e49eba35 .gt_title,\nhtml.quarto-dark #gd-tbl-e49eba35 .gt_title,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e49eba35 .gt_title {\n  color: #e0e0e0;\n}\nbody.quarto-dark #gd-tbl-e49eba35 .gt_subtitle,\nhtml.quarto-dark #gd-tbl-e49eba35 .gt_subtitle,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e49eba35 .gt_subtitle {\n  color: #b0b0b0;\n}\nbody.quarto-dark #gd-tbl-e49eba35 .gt_col_headings,\nhtml.quarto-dark #gd-tbl-e49eba35 .gt_col_headings,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e49eba35 .gt_col_headings {\n  border-top-color: #444;\n  border-bottom-color: #444;\n}\nbody.quarto-dark #gd-tbl-e49eba35 .gt_col_heading,\nhtml.quarto-dark #gd-tbl-e49eba35 .gt_col_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e49eba35 .gt_col_heading {\n  color: #b0b0b0;\n  background-color: #1a1a2e;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-e49eba35 .gt_table_body,\nhtml.quarto-dark #gd-tbl-e49eba35 .gt_table_body,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e49eba35 .gt_table_body {\n  border-top-color: #444;\n}\nbody.quarto-dark #gd-tbl-e49eba35 .gt_table_body .gt_row,\nhtml.quarto-dark #gd-tbl-e49eba35 .gt_table_body .gt_row,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e49eba35 .gt_table_body .gt_row {\n  color: #d0d0d0;\n  border-top-color: #4b4b4b;\n  border-bottom-color: #4b4b4b;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-e49eba35 .gd-tbl-rownum,\nhtml.quarto-dark #gd-tbl-e49eba35 .gd-tbl-rownum,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e49eba35 .gd-tbl-rownum {\n  color: #888;\n  border-right-color: rgba(102, 153, 204, 0.4) !important;\n}\nbody.quarto-dark #gd-tbl-e49eba35 .gd-tbl-missing,\nhtml.quarto-dark #gd-tbl-e49eba35 .gd-tbl-missing,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e49eba35 .gd-tbl-missing {\n  color: #ff6b6b !important;\n  background-color: rgba(60, 17, 24, 0.2);\n}\nbody.quarto-dark #gd-tbl-e49eba35 .gd-tbl-dtype,\nhtml.quarto-dark #gd-tbl-e49eba35 .gd-tbl-dtype,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e49eba35 .gd-tbl-dtype {\n  color: #888;\n}\nbody.quarto-dark #gd-tbl-e49eba35 .gt_bottom_border,\nhtml.quarto-dark #gd-tbl-e49eba35 .gt_bottom_border,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e49eba35 .gt_bottom_border {\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-e49eba35 .gd-tbl-badge-rows-label,\nhtml.quarto-dark #gd-tbl-e49eba35 .gd-tbl-badge-rows-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e49eba35 .gd-tbl-badge-rows-label {\n  background-color: #3d2a4d;\n  border-color: #3d2a4d;\n  color: #e0c0ff;\n}\nbody.quarto-dark #gd-tbl-e49eba35 .gd-tbl-badge-rows-value,\nhtml.quarto-dark #gd-tbl-e49eba35 .gd-tbl-badge-rows-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e49eba35 .gd-tbl-badge-rows-value {\n  border-color: #3d2a4d;\n  color: #d0b0e0;\n}\nbody.quarto-dark #gd-tbl-e49eba35 .gd-tbl-badge-cols-label,\nhtml.quarto-dark #gd-tbl-e49eba35 .gd-tbl-badge-cols-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e49eba35 .gd-tbl-badge-cols-label {\n  background-color: #2a4d2a;\n  border-color: #2a4d2a;\n  color: #b0e0b0;\n}\nbody.quarto-dark #gd-tbl-e49eba35 .gd-tbl-badge-cols-value,\nhtml.quarto-dark #gd-tbl-e49eba35 .gd-tbl-badge-cols-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e49eba35 .gd-tbl-badge-cols-value {\n  border-color: #2a4d2a;\n  color: #a0d0a0;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"true\" data-quarto-bootstrap=\"false\">\n<colgroup>\n<col style=\"width: 35px\"/>\n<col style=\"width: 131px\"/>\n<col style=\"width: 124px\"/>\n<col style=\"width: 124px\"/>\n<col style=\"width: 117px\"/>\n<col style=\"width: 110px\"/>\n</colgroup>\n<thead>\n<tr class=\"gt_heading\"><td class=\"gt_heading gt_title gt_font_normal\" colspan=\"6\"><div style=\"padding-top: 0; padding-bottom: 7px;\"><span class=\"gd-tbl-badge\" style=\"background-color: #0075FF; color: #FFFFFF; border: 1px solid #0075FF; margin-right: 8px;\">Polars</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-label\">Rows</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-value\">5</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-label\">Columns</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-value\">5</span></div></td></tr>\n<tr class=\"gt_col_headings\">\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\"></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"metric\"><div><div class=\"gd-tbl-colname\">metric</div><div class=\"gd-tbl-dtype\"><em>str</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><div><div class=\"gd-tbl-colname\">estimate</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"se\"><div><div class=\"gd-tbl-colname\">se</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf_low\"><div><div class=\"gd-tbl-colname\">conf_low</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf_high\"><div><div class=\"gd-tbl-colname\">conf_high</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">0</td>\n<td class=\"gt_row gt_left\" style=\"max-width: 131px;\">concordance</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 124px;\">0.664422241225</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 124px;\">0.0445690503462</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.572310071046</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 110px;\">0.74551736935</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">1</td>\n<td class=\"gt_row gt_left\" style=\"max-width: 131px;\">brier(120)</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 124px;\">0.0877376948292</td>\n<td class=\"gt_row gt_right gd-tbl-missing\" style=\"max-width: 124px;\">NaN</td>\n<td class=\"gt_row gt_right gd-tbl-missing\" style=\"max-width: 117px;\">NaN</td>\n<td class=\"gt_row gt_right gd-tbl-missing\" style=\"max-width: 110px;\">NaN</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">2</td>\n<td class=\"gt_row gt_left\" style=\"max-width: 131px;\">brier(240)</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 124px;\">0.147587386975</td>\n<td class=\"gt_row gt_right gd-tbl-missing\" style=\"max-width: 124px;\">NaN</td>\n<td class=\"gt_row gt_right gd-tbl-missing\" style=\"max-width: 117px;\">NaN</td>\n<td class=\"gt_row gt_right gd-tbl-missing\" style=\"max-width: 110px;\">NaN</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">3</td>\n<td class=\"gt_row gt_left\" style=\"max-width: 131px;\">brier(360)</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 124px;\">0.199861349421</td>\n<td class=\"gt_row gt_right gd-tbl-missing\" style=\"max-width: 124px;\">NaN</td>\n<td class=\"gt_row gt_right gd-tbl-missing\" style=\"max-width: 117px;\">NaN</td>\n<td class=\"gt_row gt_right gd-tbl-missing\" style=\"max-width: 110px;\">NaN</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">4</td>\n<td class=\"gt_row gt_left\" style=\"max-width: 131px;\">integrated_brier</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 124px;\">0.14569345455</td>\n<td class=\"gt_row gt_right gd-tbl-missing\" style=\"max-width: 124px;\">NaN</td>\n<td class=\"gt_row gt_right gd-tbl-missing\" style=\"max-width: 117px;\">NaN</td>\n<td class=\"gt_row gt_right gd-tbl-missing\" style=\"max-width: 110px;\">NaN</td>\n</tr>\n</tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThe `incidence_prob` argument expects a matrix with shape `(n_subjects, n_times)`, where each column\nholds the predicted CIF at the corresponding evaluation time. The `cause` argument selects the event\ncode and the `tau` parameter (defaulting to the last evaluation time) truncates the concordance\ncalculation.\n\nThis is the competing-risks counterpart of running `concordance_index_ci()`,\n`brier_score_incidence()`, and `integrated_brier_score_incidence()` separately. When you only need\none of those metrics, calling them individually is fine. The `score_cr()` function saves repetitive\nsetup when you want the full picture.\n\n## Time-dependent discrimination: AUC over time\n\nThe concordance index summarises discrimination with a single number across all event times. But a\nmarker's ability to separate early failures from survivors often changes over follow-up: a biomarker\nmay identify six-month events well but lose its signal at five years. `time_dependent_auc()` gives\nyou a per-horizon view by computing the area under the ROC curve separately at each requested time.\n\nAt each time $t$, the estimator compares *cases* (subjects who had an event by $t$) against\n*controls* (subjects still at risk after $t$), and measures how well the marker separates the two\ngroups. Inverse-probability-of-censoring weights correct for the fact that not all subjects are\nobserved to the end of follow-up. The marker must be on a scale where larger means higher risk, so,\nthe Cox linear predictor is a natural choice.\n\n::: {#911355b4 .cell execution_count=30}\n``` {.python .cell-code}\n# Time-dependent AUC at three horizons using the Cox linear predictor\nlp = cox.predict(type=\"lp\")\ngw.time_dependent_auc(death, marker=lp, times=[180, 365, 540], data=lung)\n```\n\n::: {.cell-output .cell-output-display execution_count=30}\n```\narray([0.64152627, 0.5943264 , 0.6023971 ])\n```\n:::\n:::\n\n\nEach value is the AUC at one horizon. Values above 0.5 mean the marker separates early failures from\nsurvivors better than chance at that time. Values close to 0.5 signal that the marker has lost\npredictive power at that horizon.\n\nTo reduce these to a single number for model comparison, `integrated_auc()` computes the\ntime-averaged AUC using the trapezoidal rule over the supplied time range.\n\n::: {#6a3cd07e .cell execution_count=31}\n``` {.python .cell-code}\n# Time-averaged AUC across the three horizons\ngw.integrated_auc(death, marker=lp, times=[180, 365, 540], data=lung)\n```\n\n::: {.cell-output .cell-output-display execution_count=31}\n```\n0.6084157733720682\n```\n:::\n:::\n\n\nThe integrated AUC plays the same role as the integrated Brier score: it collapses time-specific\ndiscrimination into one comparison-friendly number. Higher is better, and 0.5 is the random\nbaseline.\n\n## Cross-validation\n\nRather than splitting the data by hand, `cross_validate()` runs k-fold cross-validation for you: it\nfits a fresh copy of the model on each set of training folds and scores its predictions on the\nheld-out fold. Pass an unfitted model and a formula naming the response and the covariates.\n\n::: {#839b1ce9 .cell execution_count=32}\n``` {.python .cell-code}\n# Rebuild the dataset\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\n\n# Five-fold cross-validated concordance\ngw.cross_validate(\n    gw.CoxPH(), \"Surv(time, status) ~ age + sex\", data=lung, k=5, metric=\"concordance\", seed=23\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=32}\n```\n{'metric': 'concordance',\n 'k': 5,\n 'scores': [0.6617466174661747,\n  0.5448877805486284,\n  0.6838235294117647,\n  0.5580524344569289,\n  0.5926694329183956],\n 'mean': 0.6082359589603785,\n 'std': 0.06194870045682596}\n```\n:::\n:::\n\n\nThe result reports the score on each fold plus their mean and standard deviation. The\ncross-validated concordance is usually a little lower than the value computed on the training data,\nwhich is exactly the optimism we are trying to remove. Set `metric=\"brier\"` with a list of `times`\nto cross-validate the integrated Brier score instead. The same call works for `AFT` and\n`RoystonParmar` models.\n\n::: {#83e196c6 .cell execution_count=33}\n``` {.python .cell-code}\n# Cross-validated integrated Brier score at three time points\ngw.cross_validate(\n    gw.CoxPH(), \"Surv(time, status) ~ age + sex\", data=lung, k=5,\n    metric=\"brier\", times=[180, 365, 540], seed=23\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=33}\n```\n{'metric': 'brier',\n 'k': 5,\n 'scores': [0.21443779185001313,\n  0.20048397452015598,\n  0.21327986359004625,\n  0.23470395029714616,\n  0.22403878785186804],\n 'mean': 0.21738887362184595,\n 'std': 0.012800407222447734}\n```\n:::\n:::\n\n\n### Multi-metric mode\n\nWhen you want concordance, Brier, and AUC together, pass `metrics=` (plural) instead of `metric=`.\nThe model is fit once per fold and scored on every requested metric, so you get consistent fold\nassignments and avoid redundant refitting.\n\n::: {#bab0114a .cell execution_count=34}\n``` {.python .cell-code}\n# Multi-metric cross-validation: concordance, Brier, and AUC in one pass\nresult_multi = gw.cross_validate(\n    gw.CoxPH(), \"Surv(time, status) ~ age + sex\", data=lung, k=5,\n    metrics=[\"concordance\", \"brier\", \"auc\"],\n    times=[180, 365, 540], seed=23\n)\nresult_multi\n```\n\n::: {.cell-output .cell-output-display execution_count=34}\n```\n{'k': 5,\n 'results': {'concordance': {'scores': [0.6617466174661747,\n    0.5448877805486284,\n    0.6838235294117647,\n    0.5580524344569289,\n    0.5926694329183956],\n   'mean': 0.6082359589603785,\n   'std': 0.06194870045682596},\n  'brier': {'scores': [0.21443779185001313,\n    0.20048397452015598,\n    0.21327986359004625,\n    0.23470395029714616,\n    0.22403878785186804],\n   'mean': 0.21738887362184595,\n   'std': 0.012800407222447734},\n  'auc': {'scores': [0.7003890238319559,\n    0.5241297774787457,\n    0.7289478073383704,\n    0.5316521748637566,\n    0.47168767470244194],\n   'mean': 0.5913612916430542,\n   'std': 0.11535177220406084}}}\n```\n:::\n:::\n\n\nThe return value is a keyed dictionary. Each metric has its own `scores`, `mean`, and `std`:\n\n::: {#f51e6850 .cell execution_count=35}\n``` {.python .cell-code}\n# Mean cross-validated concordance\nresult_multi[\"results\"][\"concordance\"][\"mean\"]\n```\n\n::: {.cell-output .cell-output-display execution_count=35}\n```\n0.6082359589603785\n```\n:::\n:::\n\n\n::: {#7c543467 .cell execution_count=36}\n``` {.python .cell-code}\n# Mean cross-validated integrated Brier score\nresult_multi[\"results\"][\"brier\"][\"mean\"]\n```\n\n::: {.cell-output .cell-output-display execution_count=36}\n```\n0.21738887362184595\n```\n:::\n:::\n\n\n### Stratified folds for imbalanced data\n\nBy default, `cross_validate()` uses stratified k-fold splitting. Rather than randomly assigning\nsubjects to folds, it groups subjects by event status first, then draws from each group\nproportionally. This ensures that each fold contains roughly the same fraction of events as the\noverall dataset.\n\nThis matters whenever events are rare. In a dataset where only 10% of subjects have the event, pure\nrandom splitting could easily put all events in one fold and none in another, leaving training sets\nwithout enough events to fit the model at all. Stratification prevents that. You can opt out with\n`stratified=False`, but there is rarely a good reason to.\n\n::: {.callout-warning}\n## Watch the event count\n\n`cross_validate()` warns when the total number of events is less than twice the number of folds. At\nthat point, some test folds will contain only one event, making per-fold scores unreliable:\n\n```\nUserWarning: Only 6 events found for 5-fold cross-validation\n(fewer than 2 × k = 10). Some folds may contain too few events\nfor reliable evaluation. Consider reducing k or collecting more\ndata with observed events.\n```\n\nIf you see this warning, either reduce `k=` to match the event count (e.g., `k=3` with 6 events) or\ntreat the cross-validated scores with caution.\n:::\n\n### Comparing models\n\nCross-validation is most useful as a comparison tool. Fit the same folds on two competing models,\nkeeping the same `seed`, and compare their mean scores directly. The model with higher mean\nconcordance (or lower mean Brier score) generalizes better to unseen subjects.\n\n::: {#5a0701be .cell execution_count=37}\n``` {.python .cell-code}\n# Rebuild the dataset\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\n\n# Define two models: simple and full\nformula_simple = \"Surv(time, status) ~ age + sex\"\nformula_full = \"Surv(time, status) ~ age + sex + ph.ecog\"\n\n# Cross-validate both models with the same seed for matched folds\nsimple_cv = gw.cross_validate(gw.CoxPH(), formula_simple, data=lung, seed=1)\nfull_cv = gw.cross_validate(gw.CoxPH(), formula_full, data=lung, seed=1)\n\n# Compare mean concordance and fold-to-fold variability\nprint(f\"Simple model  C-index: {simple_cv['mean']:.3f} ± {simple_cv['std']:.3f}\")\nprint(f\"Full model    C-index: {full_cv['mean']:.3f} ± {full_cv['std']:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSimple model  C-index: 0.604 ± 0.077\nFull model    C-index: 0.639 ± 0.043\n```\n:::\n:::\n\n\nThe standard deviation across folds gives a rough sense of how stable the estimate is. Large\nfold-to-fold variation (relative to the difference between models) means the data do not contain\nenough information to reliably distinguish the two models on this metric alone.\n\n## Calibration\n\nDiscrimination and the Brier score both summarize a model in a single number. Calibration asks a\nmore detailed question: at a chosen time, do the predicted survival probabilities match what\nactually happens? The `calibration()` function groups subjects into bins by their predicted survival\nat a horizon, then compares the mean prediction in each bin against the observed survival, a\nKaplan-Meier estimate for that bin.\n\n::: {#357254a5 .cell execution_count=38}\n``` {.python .cell-code}\n# Rebuild the dataset, response, and Cox fit\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\n\ndeath = gw.Outcome.surv(time=\"time\", event=\"status\")\ncox = gw.CoxPH().fit(\"Surv(time, status) ~ age + sex\", data=lung)\n\n# Predict one-year survival for each subject\nsurv_at_year = cox.predict(\n    lung, type=\"survival\", times=[365.0], format=\"polars\"\n)\n\n# Extract predictions as a flat array and compute calibration by quintile\npredicted = surv_at_year.slice(0, 1).drop(\"time\").to_numpy().flatten()\n\ngw.calibration(death, predicted=predicted, time=365.0, data=lung, n_bins=5, format=\"polars\")\n```\n\n::: {.cell-output .cell-output-display execution_count=38}\n```{=html}\n<div id=\"gd-tbl-082c8a49\" class=\"gd-tbl-preview\" style=\"padding-left: 0px; overflow-x: auto; overflow-y: hidden; width: 100%; max-width: 100%; margin-bottom: 1em;\">\n<style>\n@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,600;1,400&family=IBM+Plex+Sans:wght@400;600&display=swap');\n#gd-tbl-082c8a49 .gt_table {\n  display: table;\n  border-collapse: collapse;\n  table-layout: fixed;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 14px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n}\n#gd-tbl-082c8a49 .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-082c8a49 .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n#gd-tbl-082c8a49 .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n#gd-tbl-082c8a49 .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n#gd-tbl-082c8a49 .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-082c8a49 .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #F2F2F2;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #F2F2F2;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n#gd-tbl-082c8a49 .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n}\n#gd-tbl-082c8a49 .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #E9E9E9;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #E9E9E9;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #E9E9E9;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n#gd-tbl-082c8a49 .gt_left { text-align: left; }\n#gd-tbl-082c8a49 .gt_center { text-align: center; }\n#gd-tbl-082c8a49 .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n#gd-tbl-082c8a49 .gt_font_normal { font-weight: normal; }\n#gd-tbl-082c8a49 .gt_font_bold { font-weight: bold; }\n#gd-tbl-082c8a49 .gt_font_italic { font-style: italic; }\n#gd-tbl-082c8a49 .gt_striped { background-color: rgba(128,128,128,0.05); }\n#gd-tbl-082c8a49 .gt_from_md > :first-child { margin-top: 0; }\n#gd-tbl-082c8a49 .gt_from_md > :last-child { margin-bottom: 0; }\n/* Data cell font */\n#gd-tbl-082c8a49 .gt_table_body .gt_row {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  height: 14px;\n}\n/* Column label font */\n#gd-tbl-082c8a49 .gt_col_heading {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n}\n/* Row number styling */\n#gd-tbl-082c8a49 .gd-tbl-rownum {\n  color: gray;\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 10px;\n  border-right: 2px solid rgba(102, 153, 204, 0.5) !important;\n  text-align: right;\n  padding-right: 6px;\n  white-space: nowrap;\n}\n/* Head/tail divider */\n#gd-tbl-082c8a49 tr.gd-tbl-divider td,\n#gd-tbl-082c8a49 tr.gd-tbl-divider th {\n  border-bottom: 2px solid rgba(102, 153, 204, 0.5);\n}\n/* Missing values */\n#gd-tbl-082c8a49 .gd-tbl-missing {\n  color: #B22222 !important;\n  background-color: rgba(255, 193, 193, 0.35);\n}\n/* Column label sub-elements */\n#gd-tbl-082c8a49 .gd-tbl-colname {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-bottom: 0;\n  margin-bottom: 0;\n}\n#gd-tbl-082c8a49 .gd-tbl-dtype {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-top: 0;\n  margin-top: 0;\n  color: #666666;\n}\n/* Header badge styling */\n#gd-tbl-082c8a49 .gd-tbl-badge {\n  display: inline-block;\n  padding: 2px 10px;\n  font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, sans-serif;\n  font-size: 10px;\n  font-weight: bold;\n  text-transform: uppercase;\n  position: inherit;\n}\n#gd-tbl-082c8a49 .gd-tbl-badge-rows-label {\n  background-color: #eecbff;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: 5px;\n}\n#gd-tbl-082c8a49 .gd-tbl-badge-rows-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: -4px;\n  margin-right: 3px;\n}\n#gd-tbl-082c8a49 .gd-tbl-badge-cols-label {\n  background-color: #BDE7B4;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n}\n#gd-tbl-082c8a49 .gd-tbl-badge-cols-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n  margin-left: -4px;\n}\n/* Dark mode */\nbody.quarto-dark #gd-tbl-082c8a49 .gt_table,\nhtml.quarto-dark #gd-tbl-082c8a49 .gt_table,\n:root[data-bs-theme=\"dark\"] #gd-tbl-082c8a49 .gt_table {\n  background-color: #1a1a2e;\n  color: #e0e0e0;\n  border-top-color: #555;\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-082c8a49 .gt_heading,\nhtml.quarto-dark #gd-tbl-082c8a49 .gt_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-082c8a49 .gt_heading {\n  background-color: #1a1a2e;\n  border-bottom-color: #1a1a2e;\n}\nbody.quarto-dark #gd-tbl-082c8a49 .gt_title,\nhtml.quarto-dark #gd-tbl-082c8a49 .gt_title,\n:root[data-bs-theme=\"dark\"] #gd-tbl-082c8a49 .gt_title {\n  color: #e0e0e0;\n}\nbody.quarto-dark #gd-tbl-082c8a49 .gt_subtitle,\nhtml.quarto-dark #gd-tbl-082c8a49 .gt_subtitle,\n:root[data-bs-theme=\"dark\"] #gd-tbl-082c8a49 .gt_subtitle {\n  color: #b0b0b0;\n}\nbody.quarto-dark #gd-tbl-082c8a49 .gt_col_headings,\nhtml.quarto-dark #gd-tbl-082c8a49 .gt_col_headings,\n:root[data-bs-theme=\"dark\"] #gd-tbl-082c8a49 .gt_col_headings {\n  border-top-color: #444;\n  border-bottom-color: #444;\n}\nbody.quarto-dark #gd-tbl-082c8a49 .gt_col_heading,\nhtml.quarto-dark #gd-tbl-082c8a49 .gt_col_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-082c8a49 .gt_col_heading {\n  color: #b0b0b0;\n  background-color: #1a1a2e;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-082c8a49 .gt_table_body,\nhtml.quarto-dark #gd-tbl-082c8a49 .gt_table_body,\n:root[data-bs-theme=\"dark\"] #gd-tbl-082c8a49 .gt_table_body {\n  border-top-color: #444;\n}\nbody.quarto-dark #gd-tbl-082c8a49 .gt_table_body .gt_row,\nhtml.quarto-dark #gd-tbl-082c8a49 .gt_table_body .gt_row,\n:root[data-bs-theme=\"dark\"] #gd-tbl-082c8a49 .gt_table_body .gt_row {\n  color: #d0d0d0;\n  border-top-color: #4b4b4b;\n  border-bottom-color: #4b4b4b;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-082c8a49 .gd-tbl-rownum,\nhtml.quarto-dark #gd-tbl-082c8a49 .gd-tbl-rownum,\n:root[data-bs-theme=\"dark\"] #gd-tbl-082c8a49 .gd-tbl-rownum {\n  color: #888;\n  border-right-color: rgba(102, 153, 204, 0.4) !important;\n}\nbody.quarto-dark #gd-tbl-082c8a49 .gd-tbl-missing,\nhtml.quarto-dark #gd-tbl-082c8a49 .gd-tbl-missing,\n:root[data-bs-theme=\"dark\"] #gd-tbl-082c8a49 .gd-tbl-missing {\n  color: #ff6b6b !important;\n  background-color: rgba(60, 17, 24, 0.2);\n}\nbody.quarto-dark #gd-tbl-082c8a49 .gd-tbl-dtype,\nhtml.quarto-dark #gd-tbl-082c8a49 .gd-tbl-dtype,\n:root[data-bs-theme=\"dark\"] #gd-tbl-082c8a49 .gd-tbl-dtype {\n  color: #888;\n}\nbody.quarto-dark #gd-tbl-082c8a49 .gt_bottom_border,\nhtml.quarto-dark #gd-tbl-082c8a49 .gt_bottom_border,\n:root[data-bs-theme=\"dark\"] #gd-tbl-082c8a49 .gt_bottom_border {\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-082c8a49 .gd-tbl-badge-rows-label,\nhtml.quarto-dark #gd-tbl-082c8a49 .gd-tbl-badge-rows-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-082c8a49 .gd-tbl-badge-rows-label {\n  background-color: #3d2a4d;\n  border-color: #3d2a4d;\n  color: #e0c0ff;\n}\nbody.quarto-dark #gd-tbl-082c8a49 .gd-tbl-badge-rows-value,\nhtml.quarto-dark #gd-tbl-082c8a49 .gd-tbl-badge-rows-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-082c8a49 .gd-tbl-badge-rows-value {\n  border-color: #3d2a4d;\n  color: #d0b0e0;\n}\nbody.quarto-dark #gd-tbl-082c8a49 .gd-tbl-badge-cols-label,\nhtml.quarto-dark #gd-tbl-082c8a49 .gd-tbl-badge-cols-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-082c8a49 .gd-tbl-badge-cols-label {\n  background-color: #2a4d2a;\n  border-color: #2a4d2a;\n  color: #b0e0b0;\n}\nbody.quarto-dark #gd-tbl-082c8a49 .gd-tbl-badge-cols-value,\nhtml.quarto-dark #gd-tbl-082c8a49 .gd-tbl-badge-cols-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-082c8a49 .gd-tbl-badge-cols-value {\n  border-color: #2a4d2a;\n  color: #a0d0a0;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"true\" data-quarto-bootstrap=\"false\">\n<colgroup>\n<col style=\"width: 35px\"/>\n<col style=\"width: 50px\"/>\n<col style=\"width: 50px\"/>\n<col style=\"width: 117px\"/>\n<col style=\"width: 117px\"/>\n<col style=\"width: 125px\"/>\n<col style=\"width: 125px\"/>\n</colgroup>\n<thead>\n<tr class=\"gt_heading\"><td class=\"gt_heading gt_title gt_font_normal\" colspan=\"7\"><div style=\"padding-top: 0; padding-bottom: 7px;\"><span class=\"gd-tbl-badge\" style=\"background-color: #0075FF; color: #FFFFFF; border: 1px solid #0075FF; margin-right: 8px;\">Polars</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-label\">Rows</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-value\">5</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-label\">Columns</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-value\">6</span></div></td></tr>\n<tr class=\"gt_col_headings\">\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\"></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"bin\"><div><div class=\"gd-tbl-colname\">bin</div><div class=\"gd-tbl-dtype\"><em>i64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\"><div><div class=\"gd-tbl-colname\">n</div><div class=\"gd-tbl-dtype\"><em>i64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"predicted\"><div><div class=\"gd-tbl-colname\">predicted</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"observed\"><div><div class=\"gd-tbl-colname\">observed</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"observed_lower\"><div><div class=\"gd-tbl-colname\">observed_lower</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"observed_upper\"><div><div class=\"gd-tbl-colname\">observed_upper</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 50px;\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 50px;\">45</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.275643654127</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.226515151515</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 125px;\">0.125630250282</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 125px;\">0.40841368819</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 50px;\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 50px;\">44</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.325992610784</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.363081617086</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 125px;\">0.237804025086</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 125px;\">0.554356725535</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 50px;\">3</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 50px;\">45</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.388623683685</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.408115942029</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 125px;\">0.284454511367</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 125px;\">0.585536932909</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">3</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 50px;\">4</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 50px;\">45</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.485377847087</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.54000350566</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 125px;\">0.395496812687</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 125px;\">0.737310078795</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">4</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 50px;\">5</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 50px;\">49</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.568638173192</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.514285348805</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 125px;\">0.376278476604</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 125px;\">0.702908713734</td>\n</tr>\n</tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nEach row is a bin, from the lowest predicted survival to the highest. A well-calibrated model has\n`observed` close to `predicted` in every bin, with the observed values inside their confidence\nlimits. Systematic gaps, for example predictions consistently higher than observed, signal\nmiscalibration even when discrimination is good.\n\n::: {.callout-tip}\n## Assess calibration out of sample too\n\nLike the other metrics, calibration is optimistic on the training data. For a fair picture, compute\nit on held-out predictions, for instance the test-fold predictions from a cross-validation split.\n:::\n\n## Next steps\n\nYou can now quantify how well a survival model discriminates and predicts.\n\n- [Cox model diagnostics](cox-diagnostics.qmd) covers the assumption checks and residuals\nthat complement these performance metrics.\n- [Parametric survival models](parametric-models.qmd) and\n[Cox regression](cox-regression.qmd) produce the predictions these metrics evaluate.\n- The [Quick start](quick-start.qmd) ties the whole workflow together.\n\n",
    "supporting": [
      "prediction-performance_files/figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}