{
  "hash": "91ed7fe0703cf7167efc8bcae8b5063f",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: Time-varying covariates\nguide-section: \"Regression\"\nbread-crumbs: false\n---\n\n\n\nA standard Cox model assumes each covariate is measured once and stays constant throughout\nfollow-up. In many studies that assumption is wrong. A patient's bilirubin rises over months,\na worker's cumulative exposure increases with each shift, a trial subject crosses over to the\nactive arm mid-study. Treating a changing value as fixed introduces bias in the estimated\nhazard ratio. Time-varying covariates (TVC) solve this by letting the covariate take a\ndifferent value in each interval of follow-up.\n\nThe counting-process form of the Cox model handles time-varying covariates naturally. Instead\nof one row per subject you create one row per *interval*: each row records when the subject\nentered the risk set (`tstart`), when they exited (`tstop`), the event indicator for that\ninterval, and the covariate values that were constant during it. The `split_episodes()`\nfunction builds this dataset from the raw repeated-measurement data, and `Surv.counting()`\nwraps it into the response object.\n\n## The data\n\nThe `pbcseq` dataset contains repeated lab measurements for subjects in the Mayo Clinic PBC\ntrial. It is a companion to the cross-sectional `pbc` dataset: while `pbc` gives each\nsubject a single row with final outcome, `pbcseq` records the values of bilirubin, albumin,\nprothrombin time, and several other markers at each clinical visit.\n\n::: {#50f80ee8 .cell execution_count=2}\n``` {.python .cell-code}\nimport greenwood as gw\n\n# Load both datasets as Polars DataFrames\npbc    = gw.load_dataset(\"pbc\",    backend=\"polars\")\npbcseq = gw.load_dataset(\"pbcseq\", backend=\"polars\")\n\npbcseq.select([\"id\", \"day\", \"bili\", \"albumin\", \"protime\"])\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div id=\"gd-tbl-d88d82c4\" class=\"gd-tbl-preview\" style=\"padding-left: 0px; overflow-x: auto; overflow-y: hidden; width: 100%; max-width: 100%; margin-bottom: 1em;\">\n<style>\n@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,600;1,400&family=IBM+Plex+Sans:wght@400;600&display=swap');\n#gd-tbl-d88d82c4 .gt_table {\n  display: table;\n  border-collapse: collapse;\n  table-layout: fixed;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 14px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n}\n#gd-tbl-d88d82c4 .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-d88d82c4 .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n#gd-tbl-d88d82c4 .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n#gd-tbl-d88d82c4 .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n#gd-tbl-d88d82c4 .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-d88d82c4 .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #F2F2F2;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #F2F2F2;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n#gd-tbl-d88d82c4 .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n}\n#gd-tbl-d88d82c4 .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #E9E9E9;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #E9E9E9;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #E9E9E9;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n#gd-tbl-d88d82c4 .gt_left { text-align: left; }\n#gd-tbl-d88d82c4 .gt_center { text-align: center; }\n#gd-tbl-d88d82c4 .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n#gd-tbl-d88d82c4 .gt_font_normal { font-weight: normal; }\n#gd-tbl-d88d82c4 .gt_font_bold { font-weight: bold; }\n#gd-tbl-d88d82c4 .gt_font_italic { font-style: italic; }\n#gd-tbl-d88d82c4 .gt_striped { background-color: rgba(128,128,128,0.05); }\n#gd-tbl-d88d82c4 .gt_from_md > :first-child { margin-top: 0; }\n#gd-tbl-d88d82c4 .gt_from_md > :last-child { margin-bottom: 0; }\n/* Data cell font */\n#gd-tbl-d88d82c4 .gt_table_body .gt_row {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  height: 14px;\n}\n/* Column label font */\n#gd-tbl-d88d82c4 .gt_col_heading {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n}\n/* Row number styling */\n#gd-tbl-d88d82c4 .gd-tbl-rownum {\n  color: gray;\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 10px;\n  border-right: 2px solid rgba(102, 153, 204, 0.5) !important;\n  text-align: right;\n  padding-right: 6px;\n  white-space: nowrap;\n}\n/* Head/tail divider */\n#gd-tbl-d88d82c4 tr.gd-tbl-divider td,\n#gd-tbl-d88d82c4 tr.gd-tbl-divider th {\n  border-bottom: 2px solid rgba(102, 153, 204, 0.5);\n}\n/* Missing values */\n#gd-tbl-d88d82c4 .gd-tbl-missing {\n  color: #B22222 !important;\n  background-color: rgba(255, 193, 193, 0.35);\n}\n/* Column label sub-elements */\n#gd-tbl-d88d82c4 .gd-tbl-colname {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-bottom: 0;\n  margin-bottom: 0;\n}\n#gd-tbl-d88d82c4 .gd-tbl-dtype {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-top: 0;\n  margin-top: 0;\n  color: #666666;\n}\n/* Header badge styling */\n#gd-tbl-d88d82c4 .gd-tbl-badge {\n  display: inline-block;\n  padding: 2px 10px;\n  font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, sans-serif;\n  font-size: 10px;\n  font-weight: bold;\n  text-transform: uppercase;\n  position: inherit;\n}\n#gd-tbl-d88d82c4 .gd-tbl-badge-rows-label {\n  background-color: #eecbff;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: 5px;\n}\n#gd-tbl-d88d82c4 .gd-tbl-badge-rows-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: -4px;\n  margin-right: 3px;\n}\n#gd-tbl-d88d82c4 .gd-tbl-badge-cols-label {\n  background-color: #BDE7B4;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n}\n#gd-tbl-d88d82c4 .gd-tbl-badge-cols-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n  margin-left: -4px;\n}\n/* Dark mode */\nbody.quarto-dark #gd-tbl-d88d82c4 .gt_table,\nhtml.quarto-dark #gd-tbl-d88d82c4 .gt_table,\n:root[data-bs-theme=\"dark\"] #gd-tbl-d88d82c4 .gt_table {\n  background-color: #1a1a2e;\n  color: #e0e0e0;\n  border-top-color: #555;\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-d88d82c4 .gt_heading,\nhtml.quarto-dark #gd-tbl-d88d82c4 .gt_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-d88d82c4 .gt_heading {\n  background-color: #1a1a2e;\n  border-bottom-color: #1a1a2e;\n}\nbody.quarto-dark #gd-tbl-d88d82c4 .gt_title,\nhtml.quarto-dark #gd-tbl-d88d82c4 .gt_title,\n:root[data-bs-theme=\"dark\"] #gd-tbl-d88d82c4 .gt_title {\n  color: #e0e0e0;\n}\nbody.quarto-dark #gd-tbl-d88d82c4 .gt_subtitle,\nhtml.quarto-dark #gd-tbl-d88d82c4 .gt_subtitle,\n:root[data-bs-theme=\"dark\"] #gd-tbl-d88d82c4 .gt_subtitle {\n  color: #b0b0b0;\n}\nbody.quarto-dark #gd-tbl-d88d82c4 .gt_col_headings,\nhtml.quarto-dark #gd-tbl-d88d82c4 .gt_col_headings,\n:root[data-bs-theme=\"dark\"] #gd-tbl-d88d82c4 .gt_col_headings {\n  border-top-color: #444;\n  border-bottom-color: #444;\n}\nbody.quarto-dark #gd-tbl-d88d82c4 .gt_col_heading,\nhtml.quarto-dark #gd-tbl-d88d82c4 .gt_col_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-d88d82c4 .gt_col_heading {\n  color: #b0b0b0;\n  background-color: #1a1a2e;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-d88d82c4 .gt_table_body,\nhtml.quarto-dark #gd-tbl-d88d82c4 .gt_table_body,\n:root[data-bs-theme=\"dark\"] #gd-tbl-d88d82c4 .gt_table_body {\n  border-top-color: #444;\n}\nbody.quarto-dark #gd-tbl-d88d82c4 .gt_table_body .gt_row,\nhtml.quarto-dark #gd-tbl-d88d82c4 .gt_table_body .gt_row,\n:root[data-bs-theme=\"dark\"] #gd-tbl-d88d82c4 .gt_table_body .gt_row {\n  color: #d0d0d0;\n  border-top-color: #4b4b4b;\n  border-bottom-color: #4b4b4b;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-d88d82c4 .gd-tbl-rownum,\nhtml.quarto-dark #gd-tbl-d88d82c4 .gd-tbl-rownum,\n:root[data-bs-theme=\"dark\"] #gd-tbl-d88d82c4 .gd-tbl-rownum {\n  color: #888;\n  border-right-color: rgba(102, 153, 204, 0.4) !important;\n}\nbody.quarto-dark #gd-tbl-d88d82c4 .gd-tbl-missing,\nhtml.quarto-dark #gd-tbl-d88d82c4 .gd-tbl-missing,\n:root[data-bs-theme=\"dark\"] #gd-tbl-d88d82c4 .gd-tbl-missing {\n  color: #ff6b6b !important;\n  background-color: rgba(60, 17, 24, 0.2);\n}\nbody.quarto-dark #gd-tbl-d88d82c4 .gd-tbl-dtype,\nhtml.quarto-dark #gd-tbl-d88d82c4 .gd-tbl-dtype,\n:root[data-bs-theme=\"dark\"] #gd-tbl-d88d82c4 .gd-tbl-dtype {\n  color: #888;\n}\nbody.quarto-dark #gd-tbl-d88d82c4 .gt_bottom_border,\nhtml.quarto-dark #gd-tbl-d88d82c4 .gt_bottom_border,\n:root[data-bs-theme=\"dark\"] #gd-tbl-d88d82c4 .gt_bottom_border {\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-d88d82c4 .gd-tbl-badge-rows-label,\nhtml.quarto-dark #gd-tbl-d88d82c4 .gd-tbl-badge-rows-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-d88d82c4 .gd-tbl-badge-rows-label {\n  background-color: #3d2a4d;\n  border-color: #3d2a4d;\n  color: #e0c0ff;\n}\nbody.quarto-dark #gd-tbl-d88d82c4 .gd-tbl-badge-rows-value,\nhtml.quarto-dark #gd-tbl-d88d82c4 .gd-tbl-badge-rows-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-d88d82c4 .gd-tbl-badge-rows-value {\n  border-color: #3d2a4d;\n  color: #d0b0e0;\n}\nbody.quarto-dark #gd-tbl-d88d82c4 .gd-tbl-badge-cols-label,\nhtml.quarto-dark #gd-tbl-d88d82c4 .gd-tbl-badge-cols-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-d88d82c4 .gd-tbl-badge-cols-label {\n  background-color: #2a4d2a;\n  border-color: #2a4d2a;\n  color: #b0e0b0;\n}\nbody.quarto-dark #gd-tbl-d88d82c4 .gd-tbl-badge-cols-value,\nhtml.quarto-dark #gd-tbl-d88d82c4 .gd-tbl-badge-cols-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-d88d82c4 .gd-tbl-badge-cols-value {\n  border-color: #2a4d2a;\n  color: #a0d0a0;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"true\" data-quarto-bootstrap=\"false\">\n<colgroup>\n<col style=\"width: 39px\"/>\n<col style=\"width: 83px\"/>\n<col style=\"width: 83px\"/>\n<col style=\"width: 83px\"/>\n<col style=\"width: 104px\"/>\n<col style=\"width: 104px\"/>\n</colgroup>\n<thead>\n<tr class=\"gt_heading\"><td class=\"gt_heading gt_title gt_font_normal\" colspan=\"6\"><div style=\"padding-top: 0; padding-bottom: 7px;\"><span class=\"gd-tbl-badge\" style=\"background-color: #0075FF; color: #FFFFFF; border: 1px solid #0075FF; margin-right: 8px;\">Polars</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-label\">Rows</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-value\">1,945</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-label\">Columns</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-value\">5</span></div></td></tr>\n<tr class=\"gt_col_headings\">\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\"></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"id\"><div><div class=\"gd-tbl-colname\">id</div><div class=\"gd-tbl-dtype\"><em>i64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"day\"><div><div class=\"gd-tbl-colname\">day</div><div class=\"gd-tbl-dtype\"><em>i64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"bili\"><div><div class=\"gd-tbl-colname\">bili</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"albumin\"><div><div class=\"gd-tbl-colname\">albumin</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"protime\"><div><div class=\"gd-tbl-colname\">protime</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 83px;\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 83px;\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 83px;\">14.5</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 104px;\">2.6</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 104px;\">12.2</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 83px;\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 83px;\">192</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 83px;\">21.3</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 104px;\">2.94</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 104px;\">11.2</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 83px;\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 83px;\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 83px;\">1.1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 104px;\">4.14</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 104px;\">10.6</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">3</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 83px;\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 83px;\">182</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 83px;\">0.8</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 104px;\">3.6</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 104px;\">11</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">4</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 83px;\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 83px;\">365</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 83px;\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 104px;\">3.55</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 104px;\">11.6</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">5</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 83px;\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 83px;\">768</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 83px;\">1.9</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 104px;\">3.92</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 104px;\">10.6</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">6</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 83px;\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 83px;\">1790</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 83px;\">2.6</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 104px;\">3.32</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 104px;\">11.3</td>\n</tr>\n<tr class=\"gd-tbl-divider\">\n<td class=\"gt_row gt_right gd-tbl-rownum\">7</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 83px;\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 83px;\">2151</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 83px;\">3.6</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 104px;\">2.92</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 104px;\">11.5</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">1942</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 83px;\">312</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 83px;\">390</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 83px;\">7.4</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 104px;\">3.56</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 104px;\">11.7</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">1943</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 83px;\">312</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 83px;\">775</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 83px;\">16.3</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 104px;\">3.34</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 104px;\">13</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">1944</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 83px;\">312</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 83px;\">1075</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 83px;\">23.4</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 104px;\">3.42</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 104px;\">13.4</td>\n</tr>\n</tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nEach subject appears once per visit. `day` is the time of that visit (in days from\nenrollment), and the other columns hold the lab values measured that day. `futime` and\n`status` record the final outcome and are the same for every row belonging to the same\nsubject.\n\n## Building the counting-process dataset\n\n`split_episodes()` takes the per-subject baseline table and the repeated-measurements\ntable and merges them into the counting-process long format. The `id` column links the two.\n`visit_time` names the column in `visits` that carries measurement times.\n\n::: {#b269bd69 .cell execution_count=3}\n``` {.python .cell-code}\nimport pandas as pd\n\n# Build a per-subject baseline: one row per subject with follow-up time and outcome.\n# pbcseq repeats futime/status for every visit, so drop_duplicates gives one row per id.\npbcseq_pd = gw.load_dataset(\"pbcseq\", backend=\"pandas\")\nbase = (\n    pbcseq_pd.drop_duplicates(\"id\")[[\"id\", \"futime\", \"status\"]]\n             .rename(columns={\"futime\": \"time\"})\n)\n\n# Split into counting-process intervals, carrying bilirubin, albumin, and protime forward.\nlong = gw.split_episodes(\n    base,\n    pbcseq_pd[[\"id\", \"day\", \"bili\", \"albumin\", \"protime\"]],\n    id=\"id\",\n    time=\"time\",\n    event=\"status\",\n    visit_time=\"day\",\n    format=\"pandas\",\n)\n\nlong\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```{=html}\n<div id=\"gd-tbl-aeb11ed0\" class=\"gd-tbl-preview\" style=\"padding-left: 0px; overflow-x: auto; overflow-y: hidden; width: 100%; max-width: 100%; margin-bottom: 1em;\">\n<style>\n@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,600;1,400&family=IBM+Plex+Sans:wght@400;600&display=swap');\n#gd-tbl-aeb11ed0 .gt_table {\n  display: table;\n  border-collapse: collapse;\n  table-layout: fixed;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 14px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n}\n#gd-tbl-aeb11ed0 .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-aeb11ed0 .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n#gd-tbl-aeb11ed0 .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n#gd-tbl-aeb11ed0 .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n#gd-tbl-aeb11ed0 .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-aeb11ed0 .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #F2F2F2;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #F2F2F2;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n#gd-tbl-aeb11ed0 .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n}\n#gd-tbl-aeb11ed0 .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #E9E9E9;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #E9E9E9;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #E9E9E9;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n#gd-tbl-aeb11ed0 .gt_left { text-align: left; }\n#gd-tbl-aeb11ed0 .gt_center { text-align: center; }\n#gd-tbl-aeb11ed0 .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n#gd-tbl-aeb11ed0 .gt_font_normal { font-weight: normal; }\n#gd-tbl-aeb11ed0 .gt_font_bold { font-weight: bold; }\n#gd-tbl-aeb11ed0 .gt_font_italic { font-style: italic; }\n#gd-tbl-aeb11ed0 .gt_striped { background-color: rgba(128,128,128,0.05); }\n#gd-tbl-aeb11ed0 .gt_from_md > :first-child { margin-top: 0; }\n#gd-tbl-aeb11ed0 .gt_from_md > :last-child { margin-bottom: 0; }\n/* Data cell font */\n#gd-tbl-aeb11ed0 .gt_table_body .gt_row {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  height: 14px;\n}\n/* Column label font */\n#gd-tbl-aeb11ed0 .gt_col_heading {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n}\n/* Row number styling */\n#gd-tbl-aeb11ed0 .gd-tbl-rownum {\n  color: gray;\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 10px;\n  border-right: 2px solid rgba(102, 153, 204, 0.5) !important;\n  text-align: right;\n  padding-right: 6px;\n  white-space: nowrap;\n}\n/* Head/tail divider */\n#gd-tbl-aeb11ed0 tr.gd-tbl-divider td,\n#gd-tbl-aeb11ed0 tr.gd-tbl-divider th {\n  border-bottom: 2px solid rgba(102, 153, 204, 0.5);\n}\n/* Missing values */\n#gd-tbl-aeb11ed0 .gd-tbl-missing {\n  color: #B22222 !important;\n  background-color: rgba(255, 193, 193, 0.35);\n}\n/* Column label sub-elements */\n#gd-tbl-aeb11ed0 .gd-tbl-colname {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-bottom: 0;\n  margin-bottom: 0;\n}\n#gd-tbl-aeb11ed0 .gd-tbl-dtype {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-top: 0;\n  margin-top: 0;\n  color: #666666;\n}\n/* Header badge styling */\n#gd-tbl-aeb11ed0 .gd-tbl-badge {\n  display: inline-block;\n  padding: 2px 10px;\n  font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, sans-serif;\n  font-size: 10px;\n  font-weight: bold;\n  text-transform: uppercase;\n  position: inherit;\n}\n#gd-tbl-aeb11ed0 .gd-tbl-badge-rows-label {\n  background-color: #eecbff;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: 5px;\n}\n#gd-tbl-aeb11ed0 .gd-tbl-badge-rows-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: -4px;\n  margin-right: 3px;\n}\n#gd-tbl-aeb11ed0 .gd-tbl-badge-cols-label {\n  background-color: #BDE7B4;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n}\n#gd-tbl-aeb11ed0 .gd-tbl-badge-cols-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n  margin-left: -4px;\n}\n/* Dark mode */\nbody.quarto-dark #gd-tbl-aeb11ed0 .gt_table,\nhtml.quarto-dark #gd-tbl-aeb11ed0 .gt_table,\n:root[data-bs-theme=\"dark\"] #gd-tbl-aeb11ed0 .gt_table {\n  background-color: #1a1a2e;\n  color: #e0e0e0;\n  border-top-color: #555;\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-aeb11ed0 .gt_heading,\nhtml.quarto-dark #gd-tbl-aeb11ed0 .gt_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-aeb11ed0 .gt_heading {\n  background-color: #1a1a2e;\n  border-bottom-color: #1a1a2e;\n}\nbody.quarto-dark #gd-tbl-aeb11ed0 .gt_title,\nhtml.quarto-dark #gd-tbl-aeb11ed0 .gt_title,\n:root[data-bs-theme=\"dark\"] #gd-tbl-aeb11ed0 .gt_title {\n  color: #e0e0e0;\n}\nbody.quarto-dark #gd-tbl-aeb11ed0 .gt_subtitle,\nhtml.quarto-dark #gd-tbl-aeb11ed0 .gt_subtitle,\n:root[data-bs-theme=\"dark\"] #gd-tbl-aeb11ed0 .gt_subtitle {\n  color: #b0b0b0;\n}\nbody.quarto-dark #gd-tbl-aeb11ed0 .gt_col_headings,\nhtml.quarto-dark #gd-tbl-aeb11ed0 .gt_col_headings,\n:root[data-bs-theme=\"dark\"] #gd-tbl-aeb11ed0 .gt_col_headings {\n  border-top-color: #444;\n  border-bottom-color: #444;\n}\nbody.quarto-dark #gd-tbl-aeb11ed0 .gt_col_heading,\nhtml.quarto-dark #gd-tbl-aeb11ed0 .gt_col_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-aeb11ed0 .gt_col_heading {\n  color: #b0b0b0;\n  background-color: #1a1a2e;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-aeb11ed0 .gt_table_body,\nhtml.quarto-dark #gd-tbl-aeb11ed0 .gt_table_body,\n:root[data-bs-theme=\"dark\"] #gd-tbl-aeb11ed0 .gt_table_body {\n  border-top-color: #444;\n}\nbody.quarto-dark #gd-tbl-aeb11ed0 .gt_table_body .gt_row,\nhtml.quarto-dark #gd-tbl-aeb11ed0 .gt_table_body .gt_row,\n:root[data-bs-theme=\"dark\"] #gd-tbl-aeb11ed0 .gt_table_body .gt_row {\n  color: #d0d0d0;\n  border-top-color: #4b4b4b;\n  border-bottom-color: #4b4b4b;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-aeb11ed0 .gd-tbl-rownum,\nhtml.quarto-dark #gd-tbl-aeb11ed0 .gd-tbl-rownum,\n:root[data-bs-theme=\"dark\"] #gd-tbl-aeb11ed0 .gd-tbl-rownum {\n  color: #888;\n  border-right-color: rgba(102, 153, 204, 0.4) !important;\n}\nbody.quarto-dark #gd-tbl-aeb11ed0 .gd-tbl-missing,\nhtml.quarto-dark #gd-tbl-aeb11ed0 .gd-tbl-missing,\n:root[data-bs-theme=\"dark\"] #gd-tbl-aeb11ed0 .gd-tbl-missing {\n  color: #ff6b6b !important;\n  background-color: rgba(60, 17, 24, 0.2);\n}\nbody.quarto-dark #gd-tbl-aeb11ed0 .gd-tbl-dtype,\nhtml.quarto-dark #gd-tbl-aeb11ed0 .gd-tbl-dtype,\n:root[data-bs-theme=\"dark\"] #gd-tbl-aeb11ed0 .gd-tbl-dtype {\n  color: #888;\n}\nbody.quarto-dark #gd-tbl-aeb11ed0 .gt_bottom_border,\nhtml.quarto-dark #gd-tbl-aeb11ed0 .gt_bottom_border,\n:root[data-bs-theme=\"dark\"] #gd-tbl-aeb11ed0 .gt_bottom_border {\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-aeb11ed0 .gd-tbl-badge-rows-label,\nhtml.quarto-dark #gd-tbl-aeb11ed0 .gd-tbl-badge-rows-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-aeb11ed0 .gd-tbl-badge-rows-label {\n  background-color: #3d2a4d;\n  border-color: #3d2a4d;\n  color: #e0c0ff;\n}\nbody.quarto-dark #gd-tbl-aeb11ed0 .gd-tbl-badge-rows-value,\nhtml.quarto-dark #gd-tbl-aeb11ed0 .gd-tbl-badge-rows-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-aeb11ed0 .gd-tbl-badge-rows-value {\n  border-color: #3d2a4d;\n  color: #d0b0e0;\n}\nbody.quarto-dark #gd-tbl-aeb11ed0 .gd-tbl-badge-cols-label,\nhtml.quarto-dark #gd-tbl-aeb11ed0 .gd-tbl-badge-cols-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-aeb11ed0 .gd-tbl-badge-cols-label {\n  background-color: #2a4d2a;\n  border-color: #2a4d2a;\n  color: #b0e0b0;\n}\nbody.quarto-dark #gd-tbl-aeb11ed0 .gd-tbl-badge-cols-value,\nhtml.quarto-dark #gd-tbl-aeb11ed0 .gd-tbl-badge-cols-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-aeb11ed0 .gd-tbl-badge-cols-value {\n  border-color: #2a4d2a;\n  color: #a0d0a0;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"true\" data-quarto-bootstrap=\"false\">\n<colgroup>\n<col style=\"width: 39px\"/>\n<col style=\"width: 55px\"/>\n<col style=\"width: 68px\"/>\n<col style=\"width: 60px\"/>\n<col style=\"width: 68px\"/>\n<col style=\"width: 55px\"/>\n<col style=\"width: 76px\"/>\n<col style=\"width: 76px\"/>\n</colgroup>\n<thead>\n<tr class=\"gt_heading\"><td class=\"gt_heading gt_title gt_font_normal\" colspan=\"8\"><div style=\"padding-top: 0; padding-bottom: 7px;\"><span class=\"gd-tbl-badge\" style=\"background-color: #150458; color: #FFFFFF; border: 1px solid #150458; margin-right: 8px;\">Pandas</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-label\">Rows</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-value\">1,945</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-label\">Columns</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-value\">7</span></div></td></tr>\n<tr class=\"gt_col_headings\">\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\"></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"id\"><div><div class=\"gd-tbl-colname\">id</div><div class=\"gd-tbl-dtype\"><em>i64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"tstart\"><div><div class=\"gd-tbl-colname\">tstart</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"tstop\"><div><div class=\"gd-tbl-colname\">tstop</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"status\"><div><div class=\"gd-tbl-colname\">status</div><div class=\"gd-tbl-dtype\"><em>i64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"bili\"><div><div class=\"gd-tbl-colname\">bili</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"albumin\"><div><div class=\"gd-tbl-colname\">albumin</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"protime\"><div><div class=\"gd-tbl-colname\">protime</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 55px;\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 68px;\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 60px;\">192</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 68px;\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 55px;\">14.5</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 76px;\">2.6</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 76px;\">12.2</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 55px;\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 68px;\">192</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 60px;\">400</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 68px;\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 55px;\">21.3</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 76px;\">2.94</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 76px;\">11.2</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 55px;\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 68px;\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 60px;\">182</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 68px;\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 55px;\">1.1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 76px;\">4.14</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 76px;\">10.6</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">3</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 55px;\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 68px;\">182</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 60px;\">365</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 68px;\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 55px;\">0.8</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 76px;\">3.6</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 76px;\">11</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">4</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 55px;\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 68px;\">365</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 60px;\">768</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 68px;\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 55px;\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 76px;\">3.55</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 76px;\">11.6</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">5</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 55px;\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 68px;\">768</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 60px;\">1790</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 68px;\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 55px;\">1.9</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 76px;\">3.92</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 76px;\">10.6</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">6</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 55px;\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 68px;\">1790</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 60px;\">2151</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 68px;\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 55px;\">2.6</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 76px;\">3.32</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 76px;\">11.3</td>\n</tr>\n<tr class=\"gd-tbl-divider\">\n<td class=\"gt_row gt_right gd-tbl-rownum\">7</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 55px;\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 68px;\">2151</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 60px;\">2515</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 68px;\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 55px;\">3.6</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 76px;\">2.92</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 76px;\">11.5</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">1942</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 55px;\">312</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 68px;\">390</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 60px;\">775</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 68px;\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 55px;\">7.4</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 76px;\">3.56</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 76px;\">11.7</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">1943</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 55px;\">312</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 68px;\">775</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 60px;\">1075</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 68px;\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 55px;\">16.3</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 76px;\">3.34</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 76px;\">13</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">1944</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 55px;\">312</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 68px;\">1075</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 60px;\">1457</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 68px;\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 55px;\">23.4</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 76px;\">3.42</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 76px;\">13.4</td>\n</tr>\n</tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nEach row is now one interval for one subject. Subject 1, for example, contributes two rows:\nthe first covers days 0–192 (bilirubin 14.5), and the second covers days 192–400 (bilirubin\n21.3). The event column is 0 for the first row and carries the original status code (2 =\ndeath) for the last.\n\n::: {#00a02924 .cell execution_count=4}\n``` {.python .cell-code}\n# Subject 1's intervals\nlong[long[\"id\"] == 1][[\"id\", \"tstart\", \"tstop\", \"status\", \"bili\", \"albumin\", \"protime\"]]\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```{=html}\n<div id=\"gd-tbl-a9f147ec\" class=\"gd-tbl-preview\" style=\"padding-left: 0px; overflow-x: auto; overflow-y: hidden; width: 100%; max-width: 100%; margin-bottom: 1em;\">\n<style>\n@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,600;1,400&family=IBM+Plex+Sans:wght@400;600&display=swap');\n#gd-tbl-a9f147ec .gt_table {\n  display: table;\n  border-collapse: collapse;\n  table-layout: fixed;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 14px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n}\n#gd-tbl-a9f147ec .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-a9f147ec .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n#gd-tbl-a9f147ec .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n#gd-tbl-a9f147ec .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n#gd-tbl-a9f147ec .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-a9f147ec .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #F2F2F2;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #F2F2F2;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n#gd-tbl-a9f147ec .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n}\n#gd-tbl-a9f147ec .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #E9E9E9;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #E9E9E9;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #E9E9E9;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n#gd-tbl-a9f147ec .gt_left { text-align: left; }\n#gd-tbl-a9f147ec .gt_center { text-align: center; }\n#gd-tbl-a9f147ec .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n#gd-tbl-a9f147ec .gt_font_normal { font-weight: normal; }\n#gd-tbl-a9f147ec .gt_font_bold { font-weight: bold; }\n#gd-tbl-a9f147ec .gt_font_italic { font-style: italic; }\n#gd-tbl-a9f147ec .gt_striped { background-color: rgba(128,128,128,0.05); }\n#gd-tbl-a9f147ec .gt_from_md > :first-child { margin-top: 0; }\n#gd-tbl-a9f147ec .gt_from_md > :last-child { margin-bottom: 0; }\n/* Data cell font */\n#gd-tbl-a9f147ec .gt_table_body .gt_row {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  height: 14px;\n}\n/* Column label font */\n#gd-tbl-a9f147ec .gt_col_heading {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n}\n/* Row number styling */\n#gd-tbl-a9f147ec .gd-tbl-rownum {\n  color: gray;\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 10px;\n  border-right: 2px solid rgba(102, 153, 204, 0.5) !important;\n  text-align: right;\n  padding-right: 6px;\n  white-space: nowrap;\n}\n/* Head/tail divider */\n#gd-tbl-a9f147ec tr.gd-tbl-divider td,\n#gd-tbl-a9f147ec tr.gd-tbl-divider th {\n  border-bottom: 2px solid rgba(102, 153, 204, 0.5);\n}\n/* Missing values */\n#gd-tbl-a9f147ec .gd-tbl-missing {\n  color: #B22222 !important;\n  background-color: rgba(255, 193, 193, 0.35);\n}\n/* Column label sub-elements */\n#gd-tbl-a9f147ec .gd-tbl-colname {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-bottom: 0;\n  margin-bottom: 0;\n}\n#gd-tbl-a9f147ec .gd-tbl-dtype {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-top: 0;\n  margin-top: 0;\n  color: #666666;\n}\n/* Header badge styling */\n#gd-tbl-a9f147ec .gd-tbl-badge {\n  display: inline-block;\n  padding: 2px 10px;\n  font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, sans-serif;\n  font-size: 10px;\n  font-weight: bold;\n  text-transform: uppercase;\n  position: inherit;\n}\n#gd-tbl-a9f147ec .gd-tbl-badge-rows-label {\n  background-color: #eecbff;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: 5px;\n}\n#gd-tbl-a9f147ec .gd-tbl-badge-rows-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: -4px;\n  margin-right: 3px;\n}\n#gd-tbl-a9f147ec .gd-tbl-badge-cols-label {\n  background-color: #BDE7B4;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n}\n#gd-tbl-a9f147ec .gd-tbl-badge-cols-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n  margin-left: -4px;\n}\n/* Dark mode */\nbody.quarto-dark #gd-tbl-a9f147ec .gt_table,\nhtml.quarto-dark #gd-tbl-a9f147ec .gt_table,\n:root[data-bs-theme=\"dark\"] #gd-tbl-a9f147ec .gt_table {\n  background-color: #1a1a2e;\n  color: #e0e0e0;\n  border-top-color: #555;\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-a9f147ec .gt_heading,\nhtml.quarto-dark #gd-tbl-a9f147ec .gt_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-a9f147ec .gt_heading {\n  background-color: #1a1a2e;\n  border-bottom-color: #1a1a2e;\n}\nbody.quarto-dark #gd-tbl-a9f147ec .gt_title,\nhtml.quarto-dark #gd-tbl-a9f147ec .gt_title,\n:root[data-bs-theme=\"dark\"] #gd-tbl-a9f147ec .gt_title {\n  color: #e0e0e0;\n}\nbody.quarto-dark #gd-tbl-a9f147ec .gt_subtitle,\nhtml.quarto-dark #gd-tbl-a9f147ec .gt_subtitle,\n:root[data-bs-theme=\"dark\"] #gd-tbl-a9f147ec .gt_subtitle {\n  color: #b0b0b0;\n}\nbody.quarto-dark #gd-tbl-a9f147ec .gt_col_headings,\nhtml.quarto-dark #gd-tbl-a9f147ec .gt_col_headings,\n:root[data-bs-theme=\"dark\"] #gd-tbl-a9f147ec .gt_col_headings {\n  border-top-color: #444;\n  border-bottom-color: #444;\n}\nbody.quarto-dark #gd-tbl-a9f147ec .gt_col_heading,\nhtml.quarto-dark #gd-tbl-a9f147ec .gt_col_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-a9f147ec .gt_col_heading {\n  color: #b0b0b0;\n  background-color: #1a1a2e;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-a9f147ec .gt_table_body,\nhtml.quarto-dark #gd-tbl-a9f147ec .gt_table_body,\n:root[data-bs-theme=\"dark\"] #gd-tbl-a9f147ec .gt_table_body {\n  border-top-color: #444;\n}\nbody.quarto-dark #gd-tbl-a9f147ec .gt_table_body .gt_row,\nhtml.quarto-dark #gd-tbl-a9f147ec .gt_table_body .gt_row,\n:root[data-bs-theme=\"dark\"] #gd-tbl-a9f147ec .gt_table_body .gt_row {\n  color: #d0d0d0;\n  border-top-color: #4b4b4b;\n  border-bottom-color: #4b4b4b;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-a9f147ec .gd-tbl-rownum,\nhtml.quarto-dark #gd-tbl-a9f147ec .gd-tbl-rownum,\n:root[data-bs-theme=\"dark\"] #gd-tbl-a9f147ec .gd-tbl-rownum {\n  color: #888;\n  border-right-color: rgba(102, 153, 204, 0.4) !important;\n}\nbody.quarto-dark #gd-tbl-a9f147ec .gd-tbl-missing,\nhtml.quarto-dark #gd-tbl-a9f147ec .gd-tbl-missing,\n:root[data-bs-theme=\"dark\"] #gd-tbl-a9f147ec .gd-tbl-missing {\n  color: #ff6b6b !important;\n  background-color: rgba(60, 17, 24, 0.2);\n}\nbody.quarto-dark #gd-tbl-a9f147ec .gd-tbl-dtype,\nhtml.quarto-dark #gd-tbl-a9f147ec .gd-tbl-dtype,\n:root[data-bs-theme=\"dark\"] #gd-tbl-a9f147ec .gd-tbl-dtype {\n  color: #888;\n}\nbody.quarto-dark #gd-tbl-a9f147ec .gt_bottom_border,\nhtml.quarto-dark #gd-tbl-a9f147ec .gt_bottom_border,\n:root[data-bs-theme=\"dark\"] #gd-tbl-a9f147ec .gt_bottom_border {\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-a9f147ec .gd-tbl-badge-rows-label,\nhtml.quarto-dark #gd-tbl-a9f147ec .gd-tbl-badge-rows-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-a9f147ec .gd-tbl-badge-rows-label {\n  background-color: #3d2a4d;\n  border-color: #3d2a4d;\n  color: #e0c0ff;\n}\nbody.quarto-dark #gd-tbl-a9f147ec .gd-tbl-badge-rows-value,\nhtml.quarto-dark #gd-tbl-a9f147ec .gd-tbl-badge-rows-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-a9f147ec .gd-tbl-badge-rows-value {\n  border-color: #3d2a4d;\n  color: #d0b0e0;\n}\nbody.quarto-dark #gd-tbl-a9f147ec .gd-tbl-badge-cols-label,\nhtml.quarto-dark #gd-tbl-a9f147ec .gd-tbl-badge-cols-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-a9f147ec .gd-tbl-badge-cols-label {\n  background-color: #2a4d2a;\n  border-color: #2a4d2a;\n  color: #b0e0b0;\n}\nbody.quarto-dark #gd-tbl-a9f147ec .gd-tbl-badge-cols-value,\nhtml.quarto-dark #gd-tbl-a9f147ec .gd-tbl-badge-cols-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-a9f147ec .gd-tbl-badge-cols-value {\n  border-color: #2a4d2a;\n  color: #a0d0a0;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"true\" data-quarto-bootstrap=\"false\">\n<colgroup>\n<col style=\"width: 35px\"/>\n<col style=\"width: 56px\"/>\n<col style=\"width: 69px\"/>\n<col style=\"width: 61px\"/>\n<col style=\"width: 69px\"/>\n<col style=\"width: 56px\"/>\n<col style=\"width: 77px\"/>\n<col style=\"width: 77px\"/>\n</colgroup>\n<thead>\n<tr class=\"gt_heading\"><td class=\"gt_heading gt_title gt_font_normal\" colspan=\"8\"><div style=\"padding-top: 0; padding-bottom: 7px;\"><span class=\"gd-tbl-badge\" style=\"background-color: #150458; color: #FFFFFF; border: 1px solid #150458; margin-right: 8px;\">Pandas</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-label\">Rows</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-value\">2</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-label\">Columns</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-value\">7</span></div></td></tr>\n<tr class=\"gt_col_headings\">\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\"></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"id\"><div><div class=\"gd-tbl-colname\">id</div><div class=\"gd-tbl-dtype\"><em>i64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"tstart\"><div><div class=\"gd-tbl-colname\">tstart</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"tstop\"><div><div class=\"gd-tbl-colname\">tstop</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"status\"><div><div class=\"gd-tbl-colname\">status</div><div class=\"gd-tbl-dtype\"><em>i64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"bili\"><div><div class=\"gd-tbl-colname\">bili</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"albumin\"><div><div class=\"gd-tbl-colname\">albumin</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"protime\"><div><div class=\"gd-tbl-colname\">protime</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 56px;\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 69px;\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 61px;\">192</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 69px;\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 56px;\">14.5</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 77px;\">2.6</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 77px;\">12.2</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 56px;\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 69px;\">192</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 61px;\">400</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 69px;\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 56px;\">21.3</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 77px;\">2.94</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 77px;\">11.2</td>\n</tr>\n</tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nBefore fitting we drop the small number of rows with missing covariate values and create a\nbinary event indicator.\n\n::: {#4253cda5 .cell execution_count=5}\n``` {.python .cell-code}\nlong_clean = long.dropna(subset=[\"bili\", \"albumin\", \"protime\"]).copy()\nlong_clean[\"event\"] = (long_clean[\"status\"] == 2).astype(int)\nprint(f\"{len(long_clean)} intervals, {long_clean['event'].sum()} events, \"\n      f\"{long_clean['id'].nunique()} subjects\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n1945 intervals, 140 events, 312 subjects\n```\n:::\n:::\n\n\n## Fitting the TVC Cox model\n\nThe counting-process `Surv` object wraps `tstart` and `tstop` alongside the event indicator.\nPass the resulting response and covariate columns to `CoxPH` exactly as with a\nright-censored model.\n\n::: {#2291a62e .cell execution_count=6}\n``` {.python .cell-code}\ny = gw.Surv.counting(long_clean[\"tstart\"], long_clean[\"tstop\"], long_clean[\"event\"])\ncox_tvc = gw.CoxPH().fit(y, long_clean[[\"bili\", \"albumin\", \"protime\"]])\ncox_tvc\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n/var/folders/s8/bj_jsx3d7jqd2btw7bwm6yx80000gp/T/ipykernel_11628/3376967461.py:2: UserWarning: Subjects in counting-process data have different start times, some much larger than 0. This may indicate that start/stop times are calendar time rather than subject-relative time. Each subject's timeline should begin at 0. If you have calendar dates, subtract each subject's entry date from their start/stop times before fitting.\n  cox_tvc = gw.CoxPH().fit(y, long_clean[[\"bili\", \"albumin\", \"protime\"]])\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=6}\n```\nCoxPH (Cox proportional hazards model, ties='efron')\n\n           coef  exp(coef)  se(coef)        z          p\nbili     0.1378      1.148   0.01044   13.203  8.467e-40\nalbumin  -2.016     0.1331    0.1649  -12.232  2.107e-34\nprotime  0.1962      1.217   0.03393    5.783  7.356e-09\n\nn = 1945, events = 140\nLikelihood ratio test = 440.4 on 3 df, p = 3.852e-95\n```\n:::\n:::\n\n\nFor comparison, fit the same model using only the baseline lab values from `pbc`.\n\n::: {#3458483f .cell execution_count=7}\n``` {.python .cell-code}\npbc_pd = gw.load_dataset(\"pbc\", backend=\"pandas\")\npbc_clean = pbc_pd.dropna(subset=[\"bili\", \"albumin\", \"protime\"]).copy()\npbc_clean[\"event\"] = (pbc_clean[\"status\"] == 2).astype(int)\n\ny_static = gw.Surv.right(pbc_clean[\"time\"], event=pbc_clean[\"event\"])\ncox_static = gw.CoxPH().fit(y_static, pbc_clean[[\"bili\", \"albumin\", \"protime\"]])\ncox_static\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```\nCoxPH (Cox proportional hazards model, ties='efron')\n\n           coef  exp(coef)  se(coef)       z          p\nbili     0.1202      1.128    0.0126   9.547  1.332e-21\nalbumin  -1.226     0.2933     0.198  -6.193  5.902e-10\nprotime  0.1864      1.205   0.04962   3.756  0.0001729\n\nn = 416, events = 160\nLikelihood ratio test = 146.5 on 3 df, p = 1.481e-31\n```\n:::\n:::\n\n\nThe TVC model gives notably larger hazard ratios for bilirubin (exp(0.14) ≈ 1.15 vs\nexp(0.09) ≈ 1.09 in the static model). Updating the covariate at each visit lets the model\nuse the most recent measurement, which better reflects the current disease severity and\nrecovers more of the true effect.\n\n## Predicting survival along a covariate trajectory\n\nFor a subject whose covariates change over time you cannot describe them with a single static\nvector. Instead, pass a trajectory DataFrame to `predict()`. Each row of the trajectory\ndefines a constant-covariate interval `(tstart, tstop]`. The covariate values in that\ninterval are used to accumulate hazard up to any requested time point.\n\nSubject 1 of the PBC study had two visits. Their trajectory therefore has two rows.\n\n::: {#b6a1a18d .cell execution_count=8}\n``` {.python .cell-code}\ntvc_path = pd.DataFrame({\n    \"tstart\":  [0.0,   192.0],\n    \"tstop\":   [192.0, 400.0],\n    \"bili\":    [14.5,  21.3],\n    \"albumin\": [2.60,  2.94],\n    \"protime\": [12.2,  11.2],\n})\ntvc_path\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```{=html}\n<div id=\"gd-tbl-bfda56f6\" class=\"gd-tbl-preview\" style=\"padding-left: 0px; overflow-x: auto; overflow-y: hidden; width: 100%; max-width: 100%; margin-bottom: 1em;\">\n<style>\n@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,600;1,400&family=IBM+Plex+Sans:wght@400;600&display=swap');\n#gd-tbl-bfda56f6 .gt_table {\n  display: table;\n  border-collapse: collapse;\n  table-layout: fixed;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 14px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n}\n#gd-tbl-bfda56f6 .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-bfda56f6 .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n#gd-tbl-bfda56f6 .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n#gd-tbl-bfda56f6 .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n#gd-tbl-bfda56f6 .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-bfda56f6 .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #F2F2F2;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #F2F2F2;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n#gd-tbl-bfda56f6 .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n}\n#gd-tbl-bfda56f6 .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #E9E9E9;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #E9E9E9;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #E9E9E9;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n#gd-tbl-bfda56f6 .gt_left { text-align: left; }\n#gd-tbl-bfda56f6 .gt_center { text-align: center; }\n#gd-tbl-bfda56f6 .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n#gd-tbl-bfda56f6 .gt_font_normal { font-weight: normal; }\n#gd-tbl-bfda56f6 .gt_font_bold { font-weight: bold; }\n#gd-tbl-bfda56f6 .gt_font_italic { font-style: italic; }\n#gd-tbl-bfda56f6 .gt_striped { background-color: rgba(128,128,128,0.05); }\n#gd-tbl-bfda56f6 .gt_from_md > :first-child { margin-top: 0; }\n#gd-tbl-bfda56f6 .gt_from_md > :last-child { margin-bottom: 0; }\n/* Data cell font */\n#gd-tbl-bfda56f6 .gt_table_body .gt_row {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  height: 14px;\n}\n/* Column label font */\n#gd-tbl-bfda56f6 .gt_col_heading {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n}\n/* Row number styling */\n#gd-tbl-bfda56f6 .gd-tbl-rownum {\n  color: gray;\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 10px;\n  border-right: 2px solid rgba(102, 153, 204, 0.5) !important;\n  text-align: right;\n  padding-right: 6px;\n  white-space: nowrap;\n}\n/* Head/tail divider */\n#gd-tbl-bfda56f6 tr.gd-tbl-divider td,\n#gd-tbl-bfda56f6 tr.gd-tbl-divider th {\n  border-bottom: 2px solid rgba(102, 153, 204, 0.5);\n}\n/* Missing values */\n#gd-tbl-bfda56f6 .gd-tbl-missing {\n  color: #B22222 !important;\n  background-color: rgba(255, 193, 193, 0.35);\n}\n/* Column label sub-elements */\n#gd-tbl-bfda56f6 .gd-tbl-colname {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-bottom: 0;\n  margin-bottom: 0;\n}\n#gd-tbl-bfda56f6 .gd-tbl-dtype {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-top: 0;\n  margin-top: 0;\n  color: #666666;\n}\n/* Header badge styling */\n#gd-tbl-bfda56f6 .gd-tbl-badge {\n  display: inline-block;\n  padding: 2px 10px;\n  font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, sans-serif;\n  font-size: 10px;\n  font-weight: bold;\n  text-transform: uppercase;\n  position: inherit;\n}\n#gd-tbl-bfda56f6 .gd-tbl-badge-rows-label {\n  background-color: #eecbff;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: 5px;\n}\n#gd-tbl-bfda56f6 .gd-tbl-badge-rows-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: -4px;\n  margin-right: 3px;\n}\n#gd-tbl-bfda56f6 .gd-tbl-badge-cols-label {\n  background-color: #BDE7B4;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n}\n#gd-tbl-bfda56f6 .gd-tbl-badge-cols-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n  margin-left: -4px;\n}\n/* Dark mode */\nbody.quarto-dark #gd-tbl-bfda56f6 .gt_table,\nhtml.quarto-dark #gd-tbl-bfda56f6 .gt_table,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bfda56f6 .gt_table {\n  background-color: #1a1a2e;\n  color: #e0e0e0;\n  border-top-color: #555;\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-bfda56f6 .gt_heading,\nhtml.quarto-dark #gd-tbl-bfda56f6 .gt_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bfda56f6 .gt_heading {\n  background-color: #1a1a2e;\n  border-bottom-color: #1a1a2e;\n}\nbody.quarto-dark #gd-tbl-bfda56f6 .gt_title,\nhtml.quarto-dark #gd-tbl-bfda56f6 .gt_title,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bfda56f6 .gt_title {\n  color: #e0e0e0;\n}\nbody.quarto-dark #gd-tbl-bfda56f6 .gt_subtitle,\nhtml.quarto-dark #gd-tbl-bfda56f6 .gt_subtitle,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bfda56f6 .gt_subtitle {\n  color: #b0b0b0;\n}\nbody.quarto-dark #gd-tbl-bfda56f6 .gt_col_headings,\nhtml.quarto-dark #gd-tbl-bfda56f6 .gt_col_headings,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bfda56f6 .gt_col_headings {\n  border-top-color: #444;\n  border-bottom-color: #444;\n}\nbody.quarto-dark #gd-tbl-bfda56f6 .gt_col_heading,\nhtml.quarto-dark #gd-tbl-bfda56f6 .gt_col_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bfda56f6 .gt_col_heading {\n  color: #b0b0b0;\n  background-color: #1a1a2e;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-bfda56f6 .gt_table_body,\nhtml.quarto-dark #gd-tbl-bfda56f6 .gt_table_body,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bfda56f6 .gt_table_body {\n  border-top-color: #444;\n}\nbody.quarto-dark #gd-tbl-bfda56f6 .gt_table_body .gt_row,\nhtml.quarto-dark #gd-tbl-bfda56f6 .gt_table_body .gt_row,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bfda56f6 .gt_table_body .gt_row {\n  color: #d0d0d0;\n  border-top-color: #4b4b4b;\n  border-bottom-color: #4b4b4b;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-bfda56f6 .gd-tbl-rownum,\nhtml.quarto-dark #gd-tbl-bfda56f6 .gd-tbl-rownum,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bfda56f6 .gd-tbl-rownum {\n  color: #888;\n  border-right-color: rgba(102, 153, 204, 0.4) !important;\n}\nbody.quarto-dark #gd-tbl-bfda56f6 .gd-tbl-missing,\nhtml.quarto-dark #gd-tbl-bfda56f6 .gd-tbl-missing,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bfda56f6 .gd-tbl-missing {\n  color: #ff6b6b !important;\n  background-color: rgba(60, 17, 24, 0.2);\n}\nbody.quarto-dark #gd-tbl-bfda56f6 .gd-tbl-dtype,\nhtml.quarto-dark #gd-tbl-bfda56f6 .gd-tbl-dtype,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bfda56f6 .gd-tbl-dtype {\n  color: #888;\n}\nbody.quarto-dark #gd-tbl-bfda56f6 .gt_bottom_border,\nhtml.quarto-dark #gd-tbl-bfda56f6 .gt_bottom_border,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bfda56f6 .gt_bottom_border {\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-bfda56f6 .gd-tbl-badge-rows-label,\nhtml.quarto-dark #gd-tbl-bfda56f6 .gd-tbl-badge-rows-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bfda56f6 .gd-tbl-badge-rows-label {\n  background-color: #3d2a4d;\n  border-color: #3d2a4d;\n  color: #e0c0ff;\n}\nbody.quarto-dark #gd-tbl-bfda56f6 .gd-tbl-badge-rows-value,\nhtml.quarto-dark #gd-tbl-bfda56f6 .gd-tbl-badge-rows-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bfda56f6 .gd-tbl-badge-rows-value {\n  border-color: #3d2a4d;\n  color: #d0b0e0;\n}\nbody.quarto-dark #gd-tbl-bfda56f6 .gd-tbl-badge-cols-label,\nhtml.quarto-dark #gd-tbl-bfda56f6 .gd-tbl-badge-cols-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bfda56f6 .gd-tbl-badge-cols-label {\n  background-color: #2a4d2a;\n  border-color: #2a4d2a;\n  color: #b0e0b0;\n}\nbody.quarto-dark #gd-tbl-bfda56f6 .gd-tbl-badge-cols-value,\nhtml.quarto-dark #gd-tbl-bfda56f6 .gd-tbl-badge-cols-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bfda56f6 .gd-tbl-badge-cols-value {\n  border-color: #2a4d2a;\n  color: #a0d0a0;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"true\" data-quarto-bootstrap=\"false\">\n<colgroup>\n<col style=\"width: 35px\"/>\n<col style=\"width: 94px\"/>\n<col style=\"width: 86px\"/>\n<col style=\"width: 81px\"/>\n<col style=\"width: 102px\"/>\n<col style=\"width: 102px\"/>\n</colgroup>\n<thead>\n<tr class=\"gt_heading\"><td class=\"gt_heading gt_title gt_font_normal\" colspan=\"6\"><div style=\"padding-top: 0; padding-bottom: 7px;\"><span class=\"gd-tbl-badge\" style=\"background-color: #150458; color: #FFFFFF; border: 1px solid #150458; margin-right: 8px;\">Pandas</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-label\">Rows</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-value\">2</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-label\">Columns</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-value\">5</span></div></td></tr>\n<tr class=\"gt_col_headings\">\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\"></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"tstart\"><div><div class=\"gd-tbl-colname\">tstart</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"tstop\"><div><div class=\"gd-tbl-colname\">tstop</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"bili\"><div><div class=\"gd-tbl-colname\">bili</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"albumin\"><div><div class=\"gd-tbl-colname\">albumin</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"protime\"><div><div class=\"gd-tbl-colname\">protime</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 94px;\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 86px;\">192</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 81px;\">14.5</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 102px;\">2.6</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 102px;\">12.2</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 94px;\">192</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 86px;\">400</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 81px;\">21.3</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 102px;\">2.94</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 102px;\">11.2</td>\n</tr>\n</tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#9e3a80ad .cell execution_count=9}\n``` {.python .cell-code}\n# Predict survival at selected time points along the trajectory\nsurv_tvc = cox_tvc.predict(\n    trajectory=tvc_path,\n    times=[0, 50, 100, 192, 300, 400],\n    format=\"pandas\",\n)\nsurv_tvc\n```\n\n::: {.cell-output .cell-output-display execution_count=9}\n```{=html}\n<div id=\"gd-tbl-affa6e1e\" class=\"gd-tbl-preview\" style=\"padding-left: 0px; overflow-x: auto; overflow-y: hidden; width: 100%; max-width: 100%; margin-bottom: 1em;\">\n<style>\n@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,600;1,400&family=IBM+Plex+Sans:wght@400;600&display=swap');\n#gd-tbl-affa6e1e .gt_table {\n  display: table;\n  border-collapse: collapse;\n  table-layout: fixed;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 14px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n}\n#gd-tbl-affa6e1e .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-affa6e1e .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n#gd-tbl-affa6e1e .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n#gd-tbl-affa6e1e .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n#gd-tbl-affa6e1e .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-affa6e1e .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #F2F2F2;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #F2F2F2;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n#gd-tbl-affa6e1e .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n}\n#gd-tbl-affa6e1e .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #E9E9E9;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #E9E9E9;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #E9E9E9;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n#gd-tbl-affa6e1e .gt_left { text-align: left; }\n#gd-tbl-affa6e1e .gt_center { text-align: center; }\n#gd-tbl-affa6e1e .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n#gd-tbl-affa6e1e .gt_font_normal { font-weight: normal; }\n#gd-tbl-affa6e1e .gt_font_bold { font-weight: bold; }\n#gd-tbl-affa6e1e .gt_font_italic { font-style: italic; }\n#gd-tbl-affa6e1e .gt_striped { background-color: rgba(128,128,128,0.05); }\n#gd-tbl-affa6e1e .gt_from_md > :first-child { margin-top: 0; }\n#gd-tbl-affa6e1e .gt_from_md > :last-child { margin-bottom: 0; }\n/* Data cell font */\n#gd-tbl-affa6e1e .gt_table_body .gt_row {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  height: 14px;\n}\n/* Column label font */\n#gd-tbl-affa6e1e .gt_col_heading {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n}\n/* Row number styling */\n#gd-tbl-affa6e1e .gd-tbl-rownum {\n  color: gray;\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 10px;\n  border-right: 2px solid rgba(102, 153, 204, 0.5) !important;\n  text-align: right;\n  padding-right: 6px;\n  white-space: nowrap;\n}\n/* Head/tail divider */\n#gd-tbl-affa6e1e tr.gd-tbl-divider td,\n#gd-tbl-affa6e1e tr.gd-tbl-divider th {\n  border-bottom: 2px solid rgba(102, 153, 204, 0.5);\n}\n/* Missing values */\n#gd-tbl-affa6e1e .gd-tbl-missing {\n  color: #B22222 !important;\n  background-color: rgba(255, 193, 193, 0.35);\n}\n/* Column label sub-elements */\n#gd-tbl-affa6e1e .gd-tbl-colname {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-bottom: 0;\n  margin-bottom: 0;\n}\n#gd-tbl-affa6e1e .gd-tbl-dtype {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-top: 0;\n  margin-top: 0;\n  color: #666666;\n}\n/* Header badge styling */\n#gd-tbl-affa6e1e .gd-tbl-badge {\n  display: inline-block;\n  padding: 2px 10px;\n  font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, sans-serif;\n  font-size: 10px;\n  font-weight: bold;\n  text-transform: uppercase;\n  position: inherit;\n}\n#gd-tbl-affa6e1e .gd-tbl-badge-rows-label {\n  background-color: #eecbff;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: 5px;\n}\n#gd-tbl-affa6e1e .gd-tbl-badge-rows-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: -4px;\n  margin-right: 3px;\n}\n#gd-tbl-affa6e1e .gd-tbl-badge-cols-label {\n  background-color: #BDE7B4;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n}\n#gd-tbl-affa6e1e .gd-tbl-badge-cols-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n  margin-left: -4px;\n}\n/* Dark mode */\nbody.quarto-dark #gd-tbl-affa6e1e .gt_table,\nhtml.quarto-dark #gd-tbl-affa6e1e .gt_table,\n:root[data-bs-theme=\"dark\"] #gd-tbl-affa6e1e .gt_table {\n  background-color: #1a1a2e;\n  color: #e0e0e0;\n  border-top-color: #555;\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-affa6e1e .gt_heading,\nhtml.quarto-dark #gd-tbl-affa6e1e .gt_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-affa6e1e .gt_heading {\n  background-color: #1a1a2e;\n  border-bottom-color: #1a1a2e;\n}\nbody.quarto-dark #gd-tbl-affa6e1e .gt_title,\nhtml.quarto-dark #gd-tbl-affa6e1e .gt_title,\n:root[data-bs-theme=\"dark\"] #gd-tbl-affa6e1e .gt_title {\n  color: #e0e0e0;\n}\nbody.quarto-dark #gd-tbl-affa6e1e .gt_subtitle,\nhtml.quarto-dark #gd-tbl-affa6e1e .gt_subtitle,\n:root[data-bs-theme=\"dark\"] #gd-tbl-affa6e1e .gt_subtitle {\n  color: #b0b0b0;\n}\nbody.quarto-dark #gd-tbl-affa6e1e .gt_col_headings,\nhtml.quarto-dark #gd-tbl-affa6e1e .gt_col_headings,\n:root[data-bs-theme=\"dark\"] #gd-tbl-affa6e1e .gt_col_headings {\n  border-top-color: #444;\n  border-bottom-color: #444;\n}\nbody.quarto-dark #gd-tbl-affa6e1e .gt_col_heading,\nhtml.quarto-dark #gd-tbl-affa6e1e .gt_col_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-affa6e1e .gt_col_heading {\n  color: #b0b0b0;\n  background-color: #1a1a2e;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-affa6e1e .gt_table_body,\nhtml.quarto-dark #gd-tbl-affa6e1e .gt_table_body,\n:root[data-bs-theme=\"dark\"] #gd-tbl-affa6e1e .gt_table_body {\n  border-top-color: #444;\n}\nbody.quarto-dark #gd-tbl-affa6e1e .gt_table_body .gt_row,\nhtml.quarto-dark #gd-tbl-affa6e1e .gt_table_body .gt_row,\n:root[data-bs-theme=\"dark\"] #gd-tbl-affa6e1e .gt_table_body .gt_row {\n  color: #d0d0d0;\n  border-top-color: #4b4b4b;\n  border-bottom-color: #4b4b4b;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-affa6e1e .gd-tbl-rownum,\nhtml.quarto-dark #gd-tbl-affa6e1e .gd-tbl-rownum,\n:root[data-bs-theme=\"dark\"] #gd-tbl-affa6e1e .gd-tbl-rownum {\n  color: #888;\n  border-right-color: rgba(102, 153, 204, 0.4) !important;\n}\nbody.quarto-dark #gd-tbl-affa6e1e .gd-tbl-missing,\nhtml.quarto-dark #gd-tbl-affa6e1e .gd-tbl-missing,\n:root[data-bs-theme=\"dark\"] #gd-tbl-affa6e1e .gd-tbl-missing {\n  color: #ff6b6b !important;\n  background-color: rgba(60, 17, 24, 0.2);\n}\nbody.quarto-dark #gd-tbl-affa6e1e .gd-tbl-dtype,\nhtml.quarto-dark #gd-tbl-affa6e1e .gd-tbl-dtype,\n:root[data-bs-theme=\"dark\"] #gd-tbl-affa6e1e .gd-tbl-dtype {\n  color: #888;\n}\nbody.quarto-dark #gd-tbl-affa6e1e .gt_bottom_border,\nhtml.quarto-dark #gd-tbl-affa6e1e .gt_bottom_border,\n:root[data-bs-theme=\"dark\"] #gd-tbl-affa6e1e .gt_bottom_border {\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-affa6e1e .gd-tbl-badge-rows-label,\nhtml.quarto-dark #gd-tbl-affa6e1e .gd-tbl-badge-rows-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-affa6e1e .gd-tbl-badge-rows-label {\n  background-color: #3d2a4d;\n  border-color: #3d2a4d;\n  color: #e0c0ff;\n}\nbody.quarto-dark #gd-tbl-affa6e1e .gd-tbl-badge-rows-value,\nhtml.quarto-dark #gd-tbl-affa6e1e .gd-tbl-badge-rows-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-affa6e1e .gd-tbl-badge-rows-value {\n  border-color: #3d2a4d;\n  color: #d0b0e0;\n}\nbody.quarto-dark #gd-tbl-affa6e1e .gd-tbl-badge-cols-label,\nhtml.quarto-dark #gd-tbl-affa6e1e .gd-tbl-badge-cols-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-affa6e1e .gd-tbl-badge-cols-label {\n  background-color: #2a4d2a;\n  border-color: #2a4d2a;\n  color: #b0e0b0;\n}\nbody.quarto-dark #gd-tbl-affa6e1e .gd-tbl-badge-cols-value,\nhtml.quarto-dark #gd-tbl-affa6e1e .gd-tbl-badge-cols-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-affa6e1e .gd-tbl-badge-cols-value {\n  border-color: #2a4d2a;\n  color: #a0d0a0;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"true\" data-quarto-bootstrap=\"false\">\n<colgroup>\n<col style=\"width: 35px\"/>\n<col style=\"width: 199px\"/>\n<col style=\"width: 266px\"/>\n</colgroup>\n<thead>\n<tr class=\"gt_heading\"><td class=\"gt_heading gt_title gt_font_normal\" colspan=\"3\"><div style=\"padding-top: 0; padding-bottom: 7px;\"><span class=\"gd-tbl-badge\" style=\"background-color: #150458; color: #FFFFFF; border: 1px solid #150458; margin-right: 8px;\">Pandas</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-label\">Rows</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-value\">6</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-label\">Columns</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-value\">2</span></div></td></tr>\n<tr class=\"gt_col_headings\">\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\"></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"time\"><div><div class=\"gd-tbl-colname\">time</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"subject_1\"><div><div class=\"gd-tbl-colname\">subject_1</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 199px;\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 266px;\">1</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 199px;\">50</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 266px;\">0.966310651788</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 199px;\">100</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 266px;\">0.851568181027</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">3</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 199px;\">192</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 266px;\">0.667410151188</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">4</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 199px;\">300</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 266px;\">0.56241112508</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">5</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 199px;\">400</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 266px;\">0.395677691279</td>\n</tr>\n</tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nNotice the kink near day 192: bilirubin rises from 14.5 to 21.3 at the second visit, which\nsteepens the hazard and causes survival to drop more quickly after that point. A static model\nusing only the baseline value of 14.5 would miss this deterioration entirely.\n\nTo see how different the trajectories are, compare the TVC prediction to a static prediction\nthat fixes bilirubin at 14.5 for the entire follow-up:\n\n::: {#4b7d44b3 .cell execution_count=10}\n``` {.python .cell-code}\n# Static prediction: fix covariates at their baseline (day-0) values\nstatic_path = pd.DataFrame({\n    \"bili\": [14.5], \"albumin\": [2.60], \"protime\": [12.2]\n})\n\nsurv_static = cox_tvc.predict(\n    static_path,\n    type=\"survival\",\n    times=[0, 50, 100, 192, 300, 400],\n    format=\"pandas\",\n)\n\n# Side-by-side comparison\nimport polars as pl\n\ncomparison = pl.from_pandas(surv_tvc).rename({\"subject_1\": \"tvc\"}).with_columns(\n    pl.from_pandas(surv_static)[\"subject_1\"].alias(\"static (baseline bili only)\")\n)\ncomparison\n```\n\n::: {.cell-output .cell-output-display execution_count=10}\n```{=html}\n<div id=\"gd-tbl-4ea07e61\" class=\"gd-tbl-preview\" style=\"padding-left: 0px; overflow-x: auto; overflow-y: hidden; width: 100%; max-width: 100%; margin-bottom: 1em;\">\n<style>\n@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,600;1,400&family=IBM+Plex+Sans:wght@400;600&display=swap');\n#gd-tbl-4ea07e61 .gt_table {\n  display: table;\n  border-collapse: collapse;\n  table-layout: fixed;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 14px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n}\n#gd-tbl-4ea07e61 .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-4ea07e61 .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n#gd-tbl-4ea07e61 .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n#gd-tbl-4ea07e61 .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n#gd-tbl-4ea07e61 .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-4ea07e61 .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #F2F2F2;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #F2F2F2;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n#gd-tbl-4ea07e61 .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n}\n#gd-tbl-4ea07e61 .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #E9E9E9;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #E9E9E9;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #E9E9E9;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n#gd-tbl-4ea07e61 .gt_left { text-align: left; }\n#gd-tbl-4ea07e61 .gt_center { text-align: center; }\n#gd-tbl-4ea07e61 .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n#gd-tbl-4ea07e61 .gt_font_normal { font-weight: normal; }\n#gd-tbl-4ea07e61 .gt_font_bold { font-weight: bold; }\n#gd-tbl-4ea07e61 .gt_font_italic { font-style: italic; }\n#gd-tbl-4ea07e61 .gt_striped { background-color: rgba(128,128,128,0.05); }\n#gd-tbl-4ea07e61 .gt_from_md > :first-child { margin-top: 0; }\n#gd-tbl-4ea07e61 .gt_from_md > :last-child { margin-bottom: 0; }\n/* Data cell font */\n#gd-tbl-4ea07e61 .gt_table_body .gt_row {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  height: 14px;\n}\n/* Column label font */\n#gd-tbl-4ea07e61 .gt_col_heading {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n}\n/* Row number styling */\n#gd-tbl-4ea07e61 .gd-tbl-rownum {\n  color: gray;\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 10px;\n  border-right: 2px solid rgba(102, 153, 204, 0.5) !important;\n  text-align: right;\n  padding-right: 6px;\n  white-space: nowrap;\n}\n/* Head/tail divider */\n#gd-tbl-4ea07e61 tr.gd-tbl-divider td,\n#gd-tbl-4ea07e61 tr.gd-tbl-divider th {\n  border-bottom: 2px solid rgba(102, 153, 204, 0.5);\n}\n/* Missing values */\n#gd-tbl-4ea07e61 .gd-tbl-missing {\n  color: #B22222 !important;\n  background-color: rgba(255, 193, 193, 0.35);\n}\n/* Column label sub-elements */\n#gd-tbl-4ea07e61 .gd-tbl-colname {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-bottom: 0;\n  margin-bottom: 0;\n}\n#gd-tbl-4ea07e61 .gd-tbl-dtype {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-top: 0;\n  margin-top: 0;\n  color: #666666;\n}\n/* Header badge styling */\n#gd-tbl-4ea07e61 .gd-tbl-badge {\n  display: inline-block;\n  padding: 2px 10px;\n  font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, sans-serif;\n  font-size: 10px;\n  font-weight: bold;\n  text-transform: uppercase;\n  position: inherit;\n}\n#gd-tbl-4ea07e61 .gd-tbl-badge-rows-label {\n  background-color: #eecbff;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: 5px;\n}\n#gd-tbl-4ea07e61 .gd-tbl-badge-rows-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: -4px;\n  margin-right: 3px;\n}\n#gd-tbl-4ea07e61 .gd-tbl-badge-cols-label {\n  background-color: #BDE7B4;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n}\n#gd-tbl-4ea07e61 .gd-tbl-badge-cols-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n  margin-left: -4px;\n}\n/* Dark mode */\nbody.quarto-dark #gd-tbl-4ea07e61 .gt_table,\nhtml.quarto-dark #gd-tbl-4ea07e61 .gt_table,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4ea07e61 .gt_table {\n  background-color: #1a1a2e;\n  color: #e0e0e0;\n  border-top-color: #555;\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-4ea07e61 .gt_heading,\nhtml.quarto-dark #gd-tbl-4ea07e61 .gt_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4ea07e61 .gt_heading {\n  background-color: #1a1a2e;\n  border-bottom-color: #1a1a2e;\n}\nbody.quarto-dark #gd-tbl-4ea07e61 .gt_title,\nhtml.quarto-dark #gd-tbl-4ea07e61 .gt_title,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4ea07e61 .gt_title {\n  color: #e0e0e0;\n}\nbody.quarto-dark #gd-tbl-4ea07e61 .gt_subtitle,\nhtml.quarto-dark #gd-tbl-4ea07e61 .gt_subtitle,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4ea07e61 .gt_subtitle {\n  color: #b0b0b0;\n}\nbody.quarto-dark #gd-tbl-4ea07e61 .gt_col_headings,\nhtml.quarto-dark #gd-tbl-4ea07e61 .gt_col_headings,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4ea07e61 .gt_col_headings {\n  border-top-color: #444;\n  border-bottom-color: #444;\n}\nbody.quarto-dark #gd-tbl-4ea07e61 .gt_col_heading,\nhtml.quarto-dark #gd-tbl-4ea07e61 .gt_col_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4ea07e61 .gt_col_heading {\n  color: #b0b0b0;\n  background-color: #1a1a2e;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-4ea07e61 .gt_table_body,\nhtml.quarto-dark #gd-tbl-4ea07e61 .gt_table_body,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4ea07e61 .gt_table_body {\n  border-top-color: #444;\n}\nbody.quarto-dark #gd-tbl-4ea07e61 .gt_table_body .gt_row,\nhtml.quarto-dark #gd-tbl-4ea07e61 .gt_table_body .gt_row,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4ea07e61 .gt_table_body .gt_row {\n  color: #d0d0d0;\n  border-top-color: #4b4b4b;\n  border-bottom-color: #4b4b4b;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-4ea07e61 .gd-tbl-rownum,\nhtml.quarto-dark #gd-tbl-4ea07e61 .gd-tbl-rownum,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4ea07e61 .gd-tbl-rownum {\n  color: #888;\n  border-right-color: rgba(102, 153, 204, 0.4) !important;\n}\nbody.quarto-dark #gd-tbl-4ea07e61 .gd-tbl-missing,\nhtml.quarto-dark #gd-tbl-4ea07e61 .gd-tbl-missing,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4ea07e61 .gd-tbl-missing {\n  color: #ff6b6b !important;\n  background-color: rgba(60, 17, 24, 0.2);\n}\nbody.quarto-dark #gd-tbl-4ea07e61 .gd-tbl-dtype,\nhtml.quarto-dark #gd-tbl-4ea07e61 .gd-tbl-dtype,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4ea07e61 .gd-tbl-dtype {\n  color: #888;\n}\nbody.quarto-dark #gd-tbl-4ea07e61 .gt_bottom_border,\nhtml.quarto-dark #gd-tbl-4ea07e61 .gt_bottom_border,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4ea07e61 .gt_bottom_border {\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-4ea07e61 .gd-tbl-badge-rows-label,\nhtml.quarto-dark #gd-tbl-4ea07e61 .gd-tbl-badge-rows-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4ea07e61 .gd-tbl-badge-rows-label {\n  background-color: #3d2a4d;\n  border-color: #3d2a4d;\n  color: #e0c0ff;\n}\nbody.quarto-dark #gd-tbl-4ea07e61 .gd-tbl-badge-rows-value,\nhtml.quarto-dark #gd-tbl-4ea07e61 .gd-tbl-badge-rows-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4ea07e61 .gd-tbl-badge-rows-value {\n  border-color: #3d2a4d;\n  color: #d0b0e0;\n}\nbody.quarto-dark #gd-tbl-4ea07e61 .gd-tbl-badge-cols-label,\nhtml.quarto-dark #gd-tbl-4ea07e61 .gd-tbl-badge-cols-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4ea07e61 .gd-tbl-badge-cols-label {\n  background-color: #2a4d2a;\n  border-color: #2a4d2a;\n  color: #b0e0b0;\n}\nbody.quarto-dark #gd-tbl-4ea07e61 .gd-tbl-badge-cols-value,\nhtml.quarto-dark #gd-tbl-4ea07e61 .gd-tbl-badge-cols-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-4ea07e61 .gd-tbl-badge-cols-value {\n  border-color: #2a4d2a;\n  color: #a0d0a0;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"true\" data-quarto-bootstrap=\"false\">\n<colgroup>\n<col style=\"width: 35px\"/>\n<col style=\"width: 73px\"/>\n<col style=\"width: 140px\"/>\n<col style=\"width: 250px\"/>\n</colgroup>\n<thead>\n<tr class=\"gt_heading\"><td class=\"gt_heading gt_title gt_font_normal\" colspan=\"4\"><div style=\"padding-top: 0; padding-bottom: 7px;\"><span class=\"gd-tbl-badge\" style=\"background-color: #0075FF; color: #FFFFFF; border: 1px solid #0075FF; margin-right: 8px;\">Polars</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-label\">Rows</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-value\">6</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-label\">Columns</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-value\">3</span></div></td></tr>\n<tr class=\"gt_col_headings\">\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\"></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"time\"><div><div class=\"gd-tbl-colname\">time</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"tvc\"><div><div class=\"gd-tbl-colname\">tvc</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"static (baseline bili only)\"><div><div class=\"gd-tbl-colname\">static (baseline bili only)</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 73px;\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 140px;\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 250px;\">1</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 73px;\">50</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 140px;\">0.966310651788</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 250px;\">0.966310651788</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 73px;\">100</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 140px;\">0.851568181027</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 250px;\">0.851568181027</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">3</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 73px;\">192</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 140px;\">0.667410151188</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 250px;\">0.667410151188</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">4</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 73px;\">300</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 140px;\">0.56241112508</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 250px;\">0.567617113732</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">5</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 73px;\">400</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 140px;\">0.395677691279</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 250px;\">0.406971009427</td>\n</tr>\n</tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nAt day 400 (the subject's actual exit time) the TVC prediction gives a survival probability\nroughly 10 percentage points lower than the static prediction, reflecting the bilirubin rise\ncaptured during follow-up.\n\n## Visualizing the survival trajectory\n\nBuild predictions at a finer time resolution and melt them into a tidy long frame, then\npass it to Altair to draw overlapping survival curves.\n\n::: {#ce4d620c .cell execution_count=11}\n``` {.python .cell-code}\nimport altair as alt\nimport polars as pl\n\ntimes = list(range(0, 421, 5))\n\nsurv_tvc_fine = cox_tvc.predict(\n    trajectory=tvc_path, times=times, format=\"polars\"\n)\nsurv_static_fine = cox_tvc.predict(\n    static_path, type=\"survival\", times=times, format=\"polars\"\n)\n\n# Combine into a tidy long frame for Altair\nplot_data = (\n    surv_tvc_fine.rename({\"subject_1\": \"TVC (updating bilirubin)\"})\n    .join(\n        surv_static_fine.rename({\"subject_1\": \"Static (baseline bilirubin)\"}),\n        on=\"time\",\n    )\n    .unpivot(index=\"time\", variable_name=\"model\", value_name=\"survival\")\n)\n\nalt.Chart(plot_data).mark_line().encode(\n    x=alt.X(\"time:Q\", title=\"Time (days)\"),\n    y=alt.Y(\"survival:Q\", title=\"Survival probability\", scale=alt.Scale(domain=[0, 1])),\n    color=alt.Color(\"model:N\", title=\"Model\"),\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=11}\n```{=html}\n\n<style>\n  #altair-viz-4fb628fd315041de87ed0470aeda15fa.vega-embed {\n    width: 100%;\n    display: flex;\n  }\n\n  #altair-viz-4fb628fd315041de87ed0470aeda15fa.vega-embed details,\n  #altair-viz-4fb628fd315041de87ed0470aeda15fa.vega-embed details summary {\n    position: relative;\n  }\n</style>\n<div id=\"altair-viz-4fb628fd315041de87ed0470aeda15fa\"></div>\n<script type=\"text/javascript\">\n  var VEGA_DEBUG = (typeof VEGA_DEBUG == \"undefined\") ? {} : VEGA_DEBUG;\n  (function(spec, embedOpt){\n    let outputDiv = document.currentScript.previousElementSibling;\n    if (outputDiv.id !== \"altair-viz-4fb628fd315041de87ed0470aeda15fa\") {\n      outputDiv = document.getElementById(\"altair-viz-4fb628fd315041de87ed0470aeda15fa\");\n    }\n\n    const paths = {\n      \"vega\": \"https://cdn.jsdelivr.net/npm/vega@6?noext\",\n      \"vega-lib\": \"https://cdn.jsdelivr.net/npm/vega-lib?noext\",\n      \"vega-lite\": \"https://cdn.jsdelivr.net/npm/vega-lite@6.4.1?noext\",\n      \"vega-embed\": \"https://cdn.jsdelivr.net/npm/vega-embed@7?noext\",\n    };\n\n    function maybeLoadScript(lib, version) {\n      var key = `${lib.replace(\"-\", \"\")}_version`;\n      return (VEGA_DEBUG[key] == version) ?\n        Promise.resolve(paths[lib]) :\n        new Promise(function(resolve, reject) {\n          var s = document.createElement('script');\n          document.getElementsByTagName(\"head\")[0].appendChild(s);\n          s.async = true;\n          s.onload = () => {\n            VEGA_DEBUG[key] = version;\n            return resolve(paths[lib]);\n          };\n          s.onerror = () => reject(`Error loading script: ${paths[lib]}`);\n          s.src = paths[lib];\n        });\n    }\n\n    function showError(err) {\n      outputDiv.innerHTML = `<div class=\"error\" style=\"color:red;\">${err}</div>`;\n      throw err;\n    }\n\n    function displayChart(vegaEmbed) {\n      vegaEmbed(outputDiv, spec, embedOpt)\n        .catch(err => showError(`Javascript Error: ${err.message}<br>This usually means there's a typo in your chart specification. See the javascript console for the full traceback.`));\n    }\n\n    if(typeof define === \"function\" && define.amd) {\n      requirejs.config({paths});\n      let deps = [\"vega-embed\"];\n      require(deps, displayChart, err => showError(`Error loading script: ${err.message}`));\n    } else {\n      maybeLoadScript(\"vega\", \"6\")\n        .then(() => maybeLoadScript(\"vega-lite\", \"6.4.1\"))\n        .then(() => maybeLoadScript(\"vega-embed\", \"7\"))\n        .catch(showError)\n        .then(() => displayChart(vegaEmbed));\n    }\n  })({\"config\": {\"view\": {\"continuousWidth\": 300, \"continuousHeight\": 300}}, \"data\": {\"name\": \"data-388a24cc40902b81316bbd9ba400abf5\"}, \"mark\": {\"type\": \"line\"}, \"encoding\": {\"color\": {\"field\": \"model\", \"title\": \"Model\", \"type\": \"nominal\"}, \"x\": {\"field\": \"time\", \"title\": \"Time (days)\", \"type\": \"quantitative\"}, \"y\": {\"field\": \"survival\", \"scale\": {\"domain\": [0, 1]}, \"title\": \"Survival probability\", \"type\": \"quantitative\"}}, \"$schema\": \"https://vega.github.io/schema/vega-lite/v6.4.1.json\", \"datasets\": {\"data-388a24cc40902b81316bbd9ba400abf5\": [{\"time\": 0.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 1.0}, {\"time\": 5.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 1.0}, {\"time\": 10.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 1.0}, {\"time\": 15.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 1.0}, {\"time\": 20.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 1.0}, {\"time\": 25.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 1.0}, {\"time\": 30.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 1.0}, {\"time\": 35.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 1.0}, {\"time\": 40.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 1.0}, {\"time\": 45.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.9663106517875668}, {\"time\": 50.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.9663106517875668}, {\"time\": 55.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.927125087275458}, {\"time\": 60.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.927125087275458}, {\"time\": 65.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.927125087275458}, {\"time\": 70.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.927125087275458}, {\"time\": 75.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.8887413048269812}, {\"time\": 80.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.8515681810273269}, {\"time\": 85.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.8515681810273269}, {\"time\": 90.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.8515681810273269}, {\"time\": 95.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.8515681810273269}, {\"time\": 100.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.8515681810273269}, {\"time\": 105.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.8515681810273269}, {\"time\": 110.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.8150080036869577}, {\"time\": 115.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.8150080036869577}, {\"time\": 120.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.8150080036869577}, {\"time\": 125.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.8150080036869577}, {\"time\": 130.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.8150080036869577}, {\"time\": 135.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.7799927586836953}, {\"time\": 140.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.7112489247299745}, {\"time\": 145.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.7112489247299745}, {\"time\": 150.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.7112489247299745}, {\"time\": 155.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.7112489247299745}, {\"time\": 160.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.7112489247299745}, {\"time\": 165.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.7112489247299745}, {\"time\": 170.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.7112489247299745}, {\"time\": 175.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.7112489247299745}, {\"time\": 180.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.6923516981107397}, {\"time\": 185.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.6923516981107397}, {\"time\": 190.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.679581839787313}, {\"time\": 195.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.6674101511882433}, {\"time\": 200.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.6545955801126134}, {\"time\": 205.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.6545955801126134}, {\"time\": 210.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.6419714984207524}, {\"time\": 215.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.6419714984207524}, {\"time\": 220.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.6251426112072745}, {\"time\": 225.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.6080883521490454}, {\"time\": 230.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.6080883521490454}, {\"time\": 235.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.6080883521490454}, {\"time\": 240.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.6080883521490454}, {\"time\": 245.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.6080883521490454}, {\"time\": 250.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.6080883521490454}, {\"time\": 255.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.6080883521490454}, {\"time\": 260.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.6080883521490454}, {\"time\": 265.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.5907594714291882}, {\"time\": 270.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.5907594714291882}, {\"time\": 275.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.5907594714291882}, {\"time\": 280.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.5624111250802416}, {\"time\": 285.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.5624111250802416}, {\"time\": 290.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.5624111250802416}, {\"time\": 295.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.5624111250802416}, {\"time\": 300.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.5624111250802416}, {\"time\": 305.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.5432949177497564}, {\"time\": 310.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.5432949177497564}, {\"time\": 315.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.5432949177497564}, {\"time\": 320.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.5432949177497564}, {\"time\": 325.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.5248383872378771}, {\"time\": 330.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.4948560423738053}, {\"time\": 335.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.4649886837922926}, {\"time\": 340.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.4649886837922926}, {\"time\": 345.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.4649886837922926}, {\"time\": 350.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.4368880952958012}, {\"time\": 355.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.4368880952958012}, {\"time\": 360.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.4368880952958012}, {\"time\": 365.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.4368880952958012}, {\"time\": 370.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.4368880952958012}, {\"time\": 375.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.4368880952958012}, {\"time\": 380.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.4368880952958012}, {\"time\": 385.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.4368880952958012}, {\"time\": 390.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.4156507303793309}, {\"time\": 395.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.4156507303793309}, {\"time\": 400.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.39567769127880104}, {\"time\": 405.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.39567769127880104}, {\"time\": 410.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.39567769127880104}, {\"time\": 415.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.39567769127880104}, {\"time\": 420.0, \"model\": \"TVC (updating bilirubin)\", \"survival\": 0.39567769127880104}, {\"time\": 0.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 1.0}, {\"time\": 5.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 1.0}, {\"time\": 10.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 1.0}, {\"time\": 15.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 1.0}, {\"time\": 20.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 1.0}, {\"time\": 25.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 1.0}, {\"time\": 30.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 1.0}, {\"time\": 35.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 1.0}, {\"time\": 40.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 1.0}, {\"time\": 45.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.9663106517875668}, {\"time\": 50.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.9663106517875668}, {\"time\": 55.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.927125087275458}, {\"time\": 60.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.927125087275458}, {\"time\": 65.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.927125087275458}, {\"time\": 70.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.927125087275458}, {\"time\": 75.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.8887413048269812}, {\"time\": 80.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.8515681810273269}, {\"time\": 85.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.8515681810273269}, {\"time\": 90.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.8515681810273269}, {\"time\": 95.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.8515681810273269}, {\"time\": 100.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.8515681810273269}, {\"time\": 105.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.8515681810273269}, {\"time\": 110.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.8150080036869577}, {\"time\": 115.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.8150080036869577}, {\"time\": 120.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.8150080036869577}, {\"time\": 125.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.8150080036869577}, {\"time\": 130.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.8150080036869577}, {\"time\": 135.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.7799927586836953}, {\"time\": 140.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.7112489247299745}, {\"time\": 145.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.7112489247299745}, {\"time\": 150.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.7112489247299745}, {\"time\": 155.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.7112489247299745}, {\"time\": 160.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.7112489247299745}, {\"time\": 165.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.7112489247299745}, {\"time\": 170.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.7112489247299745}, {\"time\": 175.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.7112489247299745}, {\"time\": 180.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.6923516981107397}, {\"time\": 185.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.6923516981107397}, {\"time\": 190.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.679581839787313}, {\"time\": 195.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.6674101511882433}, {\"time\": 200.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.6552790654081704}, {\"time\": 205.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.6552790654081704}, {\"time\": 210.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.6433158030861104}, {\"time\": 215.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.6433158030861104}, {\"time\": 220.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.6273480894035429}, {\"time\": 225.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.611142908277818}, {\"time\": 230.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.611142908277818}, {\"time\": 235.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.611142908277818}, {\"time\": 240.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.611142908277818}, {\"time\": 245.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.611142908277818}, {\"time\": 250.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.611142908277818}, {\"time\": 255.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.611142908277818}, {\"time\": 260.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.611142908277818}, {\"time\": 265.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.5946516931697501}, {\"time\": 270.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.5946516931697501}, {\"time\": 275.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.5946516931697501}, {\"time\": 280.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.5676171137316857}, {\"time\": 285.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.5676171137316857}, {\"time\": 290.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.5676171137316857}, {\"time\": 295.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.5676171137316857}, {\"time\": 300.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.5676171137316857}, {\"time\": 305.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.5493455822407501}, {\"time\": 310.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.5493455822407501}, {\"time\": 315.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.5493455822407501}, {\"time\": 320.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.5493455822407501}, {\"time\": 325.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.5316717193768267}, {\"time\": 330.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.5028888372946708}, {\"time\": 335.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.47412280531171064}, {\"time\": 340.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.47412280531171064}, {\"time\": 345.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.47412280531171064}, {\"time\": 350.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.4469674904625814}, {\"time\": 355.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.4469674904625814}, {\"time\": 360.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.4469674904625814}, {\"time\": 365.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.4469674904625814}, {\"time\": 370.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.4469674904625814}, {\"time\": 375.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.4469674904625814}, {\"time\": 380.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.4469674904625814}, {\"time\": 385.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.4469674904625814}, {\"time\": 390.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.4263823506805876}, {\"time\": 395.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.4263823506805876}, {\"time\": 400.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.4069710094267881}, {\"time\": 405.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.4069710094267881}, {\"time\": 410.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.4069710094267881}, {\"time\": 415.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.4069710094267881}, {\"time\": 420.0, \"model\": \"Static (baseline bilirubin)\", \"survival\": 0.4069710094267881}]}}, {\"mode\": \"vega-lite\"});\n</script>\n```\n:::\n:::\n\n\nThe TVC curve (updating bilirubin at day 192) separates noticeably from the static curve\nafter the second visit. Both start from the same point because the baseline covariate values\nare identical. The divergence begins exactly where the trajectory changes.\n\n## Summary\n\n| Step | Code |\n|---|---|\n| Load repeated-measurement data | `gw.load_dataset(\"pbcseq\")` |\n| Build counting-process dataset | `gw.split_episodes(base, visits, id=, time=, event=, visit_time=)` |\n| Wrap the response | `gw.Surv.counting(tstart, tstop, event)` |\n| Fit the TVC Cox model | `gw.CoxPH().fit(y, covariates)` |\n| Predict along a trajectory | `cox.predict(trajectory=path, times=...)` |\n\nTime-varying covariates require more data preparation than a static model, but the tradeoff\nis hazard ratios that reflect the covariate at the time of each event rather than a single\nsnapshot.\n\n",
    "supporting": [
      "time-varying-covariates_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}