{
  "hash": "7c139501dc29eac6587d0bb9d6e26438",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: Quick start\nguide-section: \"Getting started\"\nbread-crumbs: false\n---\n\n\n\nThis is a short tour that goes from raw data to a survival curve, a plot, and a fitted model.\nEach step is only a few lines. The rest of the guide explains every piece in depth, and links\nare collected at the end.\n\n## Represent the data\n\nSurvival data pairs a follow-up time with an indicator of whether the event was actually\nobserved or the subject was censored (still event-free when we last saw them). Greenwood keeps\nthe two together in a `Surv` object. We use the bundled `lung` dataset, the survival times of\npatients with advanced lung cancer.\n\n::: {#c9e3f0e9 .cell execution_count=2}\n``` {.python .cell-code}\n# Import the Greenwood library\nimport greenwood as gw\n\n# Load the bundled lung cancer dataset as a Polars DataFrame\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\n\n# Build a right-censored response; status == 2 marks a death\ny = gw.Surv.right(lung[\"time\"], event=(lung[\"status\"] == 2))\ny\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```\nSurv(type=right, n=228, events=165)\n```\n:::\n:::\n\n\nThe summary reports 228 patients, of whom 165 died during the study; the rest were censored.\nOne detail to note: this dataset codes `status` as 1 for censored and 2 for dead, so we turn\nit into a plain event indicator with `status == 2`.\n\n## Estimate the survival curve\n\nThe Kaplan-Meier estimator turns those times into a survival curve, the probability of\nsurviving past each point in time. Printing the fitted estimator reports the median survival.\n\n::: {#d9663413 .cell execution_count=3}\n``` {.python .cell-code}\n# Load data and build the right-censored response\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\ny = gw.Surv.right(lung[\"time\"], event=(lung[\"status\"] == 2))\n\n# Fit the Kaplan-Meier estimator\nkm = gw.KaplanMeier().fit(y)\n\n# Print a summary: median survival with its confidence interval\nkm\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```\nKaplanMeier (Kaplan-Meier survival estimate)\n\n    n  events  median  0.95LCL  0.95UCL\n  228     165     310      285      363\n```\n:::\n:::\n\n\nThe median is 310 days: half of the patients are still alive at 310 days. The two columns\nafter it give a 95 percent confidence interval for that median, 285 to 363 days.\n\n## Plot the curve\n\n`plot_survival()` draws the curve as an interactive chart, with a shaded confidence band and a\nnotch wherever a patient was censored.\n\n::: {#8529f3e9 .cell execution_count=4}\n``` {.python .cell-code}\n# Load data and build the right-censored response\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\ny = gw.Surv.right(lung[\"time\"], event=(lung[\"status\"] == 2))\n\n# Fit the Kaplan-Meier estimator\nkm = gw.KaplanMeier().fit(y)\n\n# Draw an interactive survival curve with confidence band and censoring marks\ngw.plot_survival(km)\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```{=html}\n\n<style>\n  #altair-viz-c9e3ebb7ce7d493f909ff6dd0edc345d.vega-embed {\n    width: 100%;\n    display: flex;\n  }\n\n  #altair-viz-c9e3ebb7ce7d493f909ff6dd0edc345d.vega-embed details,\n  #altair-viz-c9e3ebb7ce7d493f909ff6dd0edc345d.vega-embed details summary {\n    position: relative;\n  }\n</style>\n<div id=\"altair-viz-c9e3ebb7ce7d493f909ff6dd0edc345d\"></div>\n<script type=\"text/javascript\">\n  var VEGA_DEBUG = (typeof VEGA_DEBUG == \"undefined\") ? {} : VEGA_DEBUG;\n  (function(spec, embedOpt){\n    let outputDiv = document.currentScript.previousElementSibling;\n    if (outputDiv.id !== \"altair-viz-c9e3ebb7ce7d493f909ff6dd0edc345d\") {\n      outputDiv = document.getElementById(\"altair-viz-c9e3ebb7ce7d493f909ff6dd0edc345d\");\n    }\n\n    const paths = {\n      \"vega\": \"https://cdn.jsdelivr.net/npm/vega@6?noext\",\n      \"vega-lib\": \"https://cdn.jsdelivr.net/npm/vega-lib?noext\",\n      \"vega-lite\": \"https://cdn.jsdelivr.net/npm/vega-lite@6.4.1?noext\",\n      \"vega-embed\": \"https://cdn.jsdelivr.net/npm/vega-embed@7?noext\",\n    };\n\n    function maybeLoadScript(lib, version) {\n      var key = `${lib.replace(\"-\", \"\")}_version`;\n      return (VEGA_DEBUG[key] == version) ?\n        Promise.resolve(paths[lib]) :\n        new Promise(function(resolve, reject) {\n          var s = document.createElement('script');\n          document.getElementsByTagName(\"head\")[0].appendChild(s);\n          s.async = true;\n          s.onload = () => {\n            VEGA_DEBUG[key] = version;\n            return resolve(paths[lib]);\n          };\n          s.onerror = () => reject(`Error loading script: ${paths[lib]}`);\n          s.src = paths[lib];\n        });\n    }\n\n    function showError(err) {\n      outputDiv.innerHTML = `<div class=\"error\" style=\"color:red;\">${err}</div>`;\n      throw err;\n    }\n\n    function displayChart(vegaEmbed) {\n      vegaEmbed(outputDiv, spec, embedOpt)\n        .catch(err => showError(`Javascript Error: ${err.message}<br>This usually means there's a typo in your chart specification. See the javascript console for the full traceback.`));\n    }\n\n    if(typeof define === \"function\" && define.amd) {\n      requirejs.config({paths});\n      let deps = [\"vega-embed\"];\n      require(deps, displayChart, err => showError(`Error loading script: ${err.message}`));\n    } else {\n      maybeLoadScript(\"vega\", \"6\")\n        .then(() => maybeLoadScript(\"vega-lite\", \"6.4.1\"))\n        .then(() => maybeLoadScript(\"vega-embed\", \"7\"))\n        .catch(showError)\n        .then(() => displayChart(vegaEmbed));\n    }\n  })({\"config\": {\"view\": {\"continuousWidth\": 300, \"continuousHeight\": 300}}, \"layer\": [{\"data\": {\"name\": \"data-eeb6c9ddc39bfcba9b1267e4de601f05\"}, \"mark\": {\"type\": \"area\", \"interpolate\": \"step-after\", \"opacity\": 0.18}, \"encoding\": {\"fill\": {\"value\": \"#20558A\"}, \"x\": {\"field\": \"time\", \"scale\": {\"domain\": [0.0, 1022.0], \"nice\": false, \"padding\": 16}, \"title\": \"Time\", \"type\": \"quantitative\"}, \"y\": {\"field\": \"conf_low\", \"scale\": {\"domain\": [0.0, 1.0]}, \"title\": \"Survival probability\", \"type\": \"quantitative\"}, \"y2\": {\"field\": \"conf_high\"}}, \"name\": \"view_2bc62d94c12061e0_0\", \"transform\": [{\"filter\": \"isValid(datum.conf_low) && isValid(datum.conf_high)\"}]}, {\"data\": {\"name\": \"data-eeb6c9ddc39bfcba9b1267e4de601f05\"}, \"mark\": {\"type\": \"line\", \"interpolate\": \"step-after\"}, \"encoding\": {\"color\": {\"value\": \"#20558A\"}, \"tooltip\": [{\"field\": \"strata\", \"title\": \"Group\", \"type\": \"nominal\"}, {\"field\": \"time\", \"title\": \"Time\", \"type\": \"quantitative\"}, {\"field\": \"estimate\", \"format\": \".3f\", \"title\": \"Survival probability\", \"type\": \"quantitative\"}], \"x\": {\"field\": \"time\", \"scale\": {\"domain\": [0.0, 1022.0], \"nice\": false, \"padding\": 16}, \"title\": \"Time\", \"type\": \"quantitative\"}, \"y\": {\"field\": \"estimate\", \"scale\": {\"domain\": [0.0, 1.0]}, \"title\": \"Survival probability\", \"type\": \"quantitative\"}}}, {\"data\": {\"name\": \"data-911618b04b6a5ab2aed534e81520f90f\"}, \"mark\": {\"type\": \"point\", \"opacity\": 0.9, \"shape\": \"M 0,0 L 1,-1\", \"size\": 140, \"strokeWidth\": 2}, \"encoding\": {\"stroke\": {\"value\": \"#133455\"}, \"x\": {\"field\": \"time\", \"scale\": {\"domain\": [0.0, 1022.0], \"nice\": false, \"padding\": 16}, \"title\": \"Time\", \"type\": \"quantitative\"}, \"y\": {\"field\": \"estimate\", \"scale\": {\"domain\": [0.0, 1.0]}, \"type\": \"quantitative\"}}}], \"height\": 300, \"params\": [{\"name\": \"param_1e9efca18e7a2868\", \"select\": {\"type\": \"interval\", \"encodings\": [\"x\", \"y\"]}, \"bind\": \"scales\", \"views\": [\"view_2bc62d94c12061e0_0\"]}], \"width\": 500, \"$schema\": \"https://vega.github.io/schema/vega-lite/v6.4.1.json\", \"datasets\": {\"data-eeb6c9ddc39bfcba9b1267e4de601f05\": [{\"time\": 0.0, \"estimate\": 1.0, \"conf_low\": 1.0, \"conf_high\": 1.0, \"strata\": \"Overall\"}, {\"time\": 5.0, \"estimate\": 0.9956140350877193, \"conf_low\": 0.9870734167405144, \"conf_high\": 1.0, \"strata\": \"Overall\"}, {\"time\": 11.0, \"estimate\": 0.9824561403508771, \"conf_low\": 0.9655618970753633, \"conf_high\": 0.9996459788199427, \"strata\": \"Overall\"}, {\"time\": 12.0, \"estimate\": 0.9780701754385964, \"conf_low\": 0.9592436769100913, \"conf_high\": 0.9972661703269687, \"strata\": \"Overall\"}, {\"time\": 13.0, \"estimate\": 0.969298245614035, \"conf_low\": 0.9471630031311905, \"conf_high\": 0.9919507897209447, \"strata\": \"Overall\"}, {\"time\": 15.0, \"estimate\": 0.9649122807017543, \"conf_low\": 0.9413217146007165, \"conf_high\": 0.9890940525514066, \"strata\": \"Overall\"}, {\"time\": 26.0, \"estimate\": 0.9605263157894736, \"conf_low\": 0.9355810726270364, \"conf_high\": 0.9861366698382242, \"strata\": \"Overall\"}, {\"time\": 30.0, \"estimate\": 0.956140350877193, \"conf_low\": 0.9299252668892968, \"conf_high\": 0.9830944519162026, \"strata\": \"Overall\"}, {\"time\": 31.0, \"estimate\": 0.9517543859649122, \"conf_low\": 0.9243423391699586, \"conf_high\": 0.979979357017088, \"strata\": \"Overall\"}, {\"time\": 53.0, \"estimate\": 0.9429824561403509, \"conf_low\": 0.9133597795943135, \"conf_high\": 0.9735658745379082, \"strata\": \"Overall\"}, {\"time\": 54.0, \"estimate\": 0.9385964912280702, \"conf_low\": 0.9079467094428936, \"conf_high\": 0.9702809252827124, \"strata\": \"Overall\"}, {\"time\": 59.0, \"estimate\": 0.9342105263157896, \"conf_low\": 0.9025787990057463, \"conf_high\": 0.9669508174140795, \"strata\": \"Overall\"}, {\"time\": 60.0, \"estimate\": 0.9254385964912282, \"conf_low\": 0.8919624428310943, \"conf_high\": 0.9601711403423212, \"strata\": \"Overall\"}, {\"time\": 61.0, \"estimate\": 0.9210526315789475, \"conf_low\": 0.8867074506937555, \"conf_high\": 0.9567281175710985, \"strata\": \"Overall\"}, {\"time\": 62.0, \"estimate\": 0.9166666666666667, \"conf_low\": 0.8814842999075683, \"conf_high\": 0.9532532546137109, \"strata\": \"Overall\"}, {\"time\": 65.0, \"estimate\": 0.9078947368421053, \"conf_low\": 0.8711247066201795, \"conf_high\": 0.9462168239764874, \"strata\": \"Overall\"}, {\"time\": 71.0, \"estimate\": 0.9035087719298246, \"conf_low\": 0.8659845059869967, \"conf_high\": 0.942659014463242, \"strata\": \"Overall\"}, {\"time\": 79.0, \"estimate\": 0.8991228070175439, \"conf_low\": 0.8608685484842603, \"conf_high\": 0.9390769630537714, \"strata\": \"Overall\"}, {\"time\": 81.0, \"estimate\": 0.8903508771929824, \"conf_low\": 0.8507039066100122, \"conf_high\": 0.9318455908792738, \"strata\": \"Overall\"}, {\"time\": 88.0, \"estimate\": 0.881578947368421, \"conf_low\": 0.8406211828565319, \"conf_high\": 0.9245323057435423, \"strata\": \"Overall\"}, {\"time\": 92.0, \"estimate\": 0.8771929824561403, \"conf_low\": 0.8356080266650665, \"conf_high\": 0.9208474594736283, \"strata\": \"Overall\"}, {\"time\": 93.0, \"estimate\": 0.8727849775191747, \"conf_low\": 0.8305833667271931, \"conf_high\": 0.9171308353846989, \"strata\": \"Overall\"}, {\"time\": 95.0, \"estimate\": 0.8639689676452437, \"conf_low\": 0.8205848920812576, \"conf_high\": 0.9096467461895124, \"strata\": \"Overall\"}, {\"time\": 105.0, \"estimate\": 0.8595609627082782, \"conf_low\": 0.8156096611974173, \"conf_high\": 0.9058806973022668, \"strata\": \"Overall\"}, {\"time\": 107.0, \"estimate\": 0.8506995094844816, \"conf_low\": 0.8056453359016675, \"conf_high\": 0.8982732515011631, \"strata\": \"Overall\"}, {\"time\": 110.0, \"estimate\": 0.8462687828725832, \"conf_low\": 0.8006849239055446, \"conf_high\": 0.8944477802471136, \"strata\": \"Overall\"}, {\"time\": 116.0, \"estimate\": 0.841838056260685, \"conf_low\": 0.7957383140762697, \"conf_high\": 0.890608508390664, \"strata\": \"Overall\"}, {\"time\": 118.0, \"estimate\": 0.8374073296487866, \"conf_low\": 0.7908050285896574, \"conf_high\": 0.8867559137808484, \"strata\": \"Overall\"}, {\"time\": 122.0, \"estimate\": 0.8329766030368883, \"conf_low\": 0.7858846221620303, \"conf_high\": 0.8828904417267229, \"strata\": \"Overall\"}, {\"time\": 131.0, \"estimate\": 0.8285458764249899, \"conf_low\": 0.7809766790650883, \"conf_high\": 0.8790125079825094, \"strata\": \"Overall\"}, {\"time\": 132.0, \"estimate\": 0.8196844232011932, \"conf_low\": 0.7711966521914116, \"conf_high\": 0.8712207862021566, \"strata\": \"Overall\"}, {\"time\": 135.0, \"estimate\": 0.8152536965892949, \"conf_low\": 0.7663238624353615, \"conf_high\": 0.8673077042000262, \"strata\": \"Overall\"}, {\"time\": 142.0, \"estimate\": 0.8108229699773966, \"conf_low\": 0.7614621201100752, \"conf_high\": 0.863383576517147, \"strata\": \"Overall\"}, {\"time\": 144.0, \"estimate\": 0.8063922433654982, \"conf_low\": 0.7566111230778938, \"conf_high\": 0.8594487053200448, \"strata\": \"Overall\"}, {\"time\": 145.0, \"estimate\": 0.7975307901417016, \"conf_low\": 0.7469402423914963, \"conf_high\": 0.8515478550031972, \"strata\": \"Overall\"}, {\"time\": 147.0, \"estimate\": 0.7931000635298032, \"conf_low\": 0.7421198366145, \"conf_high\": 0.8475823980672288, \"strata\": \"Overall\"}, {\"time\": 153.0, \"estimate\": 0.7886693369179049, \"conf_low\": 0.7373091295792805, \"conf_high\": 0.8436072442903965, \"strata\": \"Overall\"}, {\"time\": 156.0, \"estimate\": 0.7798078836941081, \"conf_low\": 0.7277159159467494, \"conf_high\": 0.835628742131265, \"strata\": \"Overall\"}, {\"time\": 163.0, \"estimate\": 0.7665157038584131, \"conf_low\": 0.7133935340522802, \"conf_high\": 0.8235935654254201, \"strata\": \"Overall\"}, {\"time\": 166.0, \"estimate\": 0.7576542506346163, \"conf_low\": 0.7038880896377023, \"conf_high\": 0.8155273145766193, \"strata\": \"Overall\"}, {\"time\": 167.0, \"estimate\": 0.7532235240227181, \"conf_low\": 0.6991477110928094, \"conf_high\": 0.8114818487418163, \"strata\": \"Overall\"}, {\"time\": 170.0, \"estimate\": 0.7487927974108197, \"conf_low\": 0.6944153581040137, \"conf_high\": 0.8074283595702635, \"strata\": \"Overall\"}, {\"time\": 173.0, \"estimate\": 0.7487927974108197, \"conf_low\": 0.6944153581040137, \"conf_high\": 0.8074283595702635, \"strata\": \"Overall\"}, {\"time\": 174.0, \"estimate\": 0.7487927974108197, \"conf_low\": 0.6944153581040137, \"conf_high\": 0.8074283595702635, \"strata\": \"Overall\"}, {\"time\": 175.0, \"estimate\": 0.7443090082047669, \"conf_low\": 0.6896269426384075, \"conf_high\": 0.8033269372789582, \"strata\": \"Overall\"}, {\"time\": 176.0, \"estimate\": 0.7397980445186774, \"conf_low\": 0.6848139057644401, \"conf_high\": 0.799196894319371, \"strata\": \"Overall\"}, {\"time\": 177.0, \"estimate\": 0.7352870808325879, \"conf_low\": 0.6800090367596316, \"conf_high\": 0.795058686007456, \"strata\": \"Overall\"}, {\"time\": 179.0, \"estimate\": 0.7262094625507041, \"conf_low\": 0.6703565535202383, \"conf_high\": 0.7867159360623163, \"strata\": \"Overall\"}, {\"time\": 180.0, \"estimate\": 0.7216706534097622, \"conf_low\": 0.6655423071305966, \"conf_high\": 0.7825325699252311, \"strata\": \"Overall\"}, {\"time\": 181.0, \"estimate\": 0.7125930351278784, \"conf_low\": 0.6559371648215316, \"conf_high\": 0.7741424955710837, \"strata\": \"Overall\"}, {\"time\": 182.0, \"estimate\": 0.7080542259869366, \"conf_low\": 0.6511460301448388, \"conf_high\": 0.7699360262189469, \"strata\": \"Overall\"}, {\"time\": 183.0, \"estimate\": 0.7035154168459947, \"conf_low\": 0.646362369485984, \"conf_high\": 0.7657220857915772, \"strata\": \"Overall\"}, {\"time\": 185.0, \"estimate\": 0.7035154168459947, \"conf_low\": 0.646362369485984, \"conf_high\": 0.7657220857915772, \"strata\": \"Overall\"}, {\"time\": 186.0, \"estimate\": 0.6989471349184234, \"conf_low\": 0.6415511474681548, \"conf_high\": 0.7614780198564327, \"strata\": \"Overall\"}, {\"time\": 188.0, \"estimate\": 0.6989471349184234, \"conf_low\": 0.6415511474681548, \"conf_high\": 0.7614780198564327, \"strata\": \"Overall\"}, {\"time\": 189.0, \"estimate\": 0.6943487985044865, \"conf_low\": 0.6367117813051317, \"conf_high\": 0.7572032874849182, \"strata\": \"Overall\"}, {\"time\": 191.0, \"estimate\": 0.6943487985044865, \"conf_low\": 0.6367117813051317, \"conf_high\": 0.7572032874849182, \"strata\": \"Overall\"}, {\"time\": 192.0, \"estimate\": 0.6943487985044865, \"conf_low\": 0.6367117813051317, \"conf_high\": 0.7572032874849182, \"strata\": \"Overall\"}, {\"time\": 194.0, \"estimate\": 0.6896887394541208, \"conf_low\": 0.6318068386265677, \"conf_high\": 0.7528733914369062, \"strata\": \"Overall\"}, {\"time\": 196.0, \"estimate\": 0.6896887394541208, \"conf_low\": 0.6318068386265677, \"conf_high\": 0.7528733914369062, \"strata\": \"Overall\"}, {\"time\": 197.0, \"estimate\": 0.6849969793217798, \"conf_low\": 0.6268721795556097, \"conf_high\": 0.7485112228342851, \"strata\": \"Overall\"}, {\"time\": 199.0, \"estimate\": 0.680272862223009, \"conf_low\": 0.621907150261977, \"conf_high\": 0.7441161705282591, \"strata\": \"Overall\"}, {\"time\": 201.0, \"estimate\": 0.6708246280254673, \"conf_low\": 0.6120011509890962, \"conf_high\": 0.7353020183674851, \"strata\": \"Overall\"}, {\"time\": 202.0, \"estimate\": 0.6661005109266964, \"conf_low\": 0.6070599689817395, \"conf_high\": 0.7308831307078861, \"strata\": \"Overall\"}, {\"time\": 203.0, \"estimate\": 0.6661005109266964, \"conf_low\": 0.6070599689817395, \"conf_high\": 0.7308831307078861, \"strata\": \"Overall\"}, {\"time\": 207.0, \"estimate\": 0.6613084209200296, \"conf_low\": 0.6020464948312768, \"conf_high\": 0.7264037434555686, \"strata\": \"Overall\"}, {\"time\": 208.0, \"estimate\": 0.6565163309133627, \"conf_low\": 0.5970411161533598, \"conf_high\": 0.7219162652195482, \"strata\": \"Overall\"}, {\"time\": 210.0, \"estimate\": 0.6517242409066958, \"conf_low\": 0.5920437326965584, \"conf_high\": 0.7174207963503673, \"strata\": \"Overall\"}, {\"time\": 211.0, \"estimate\": 0.6517242409066958, \"conf_low\": 0.5920437326965584, \"conf_high\": 0.7174207963503673, \"strata\": \"Overall\"}, {\"time\": 212.0, \"estimate\": 0.6468966539370166, \"conf_low\": 0.5870126010017613, \"conf_high\": 0.7128897747011952, \"strata\": \"Overall\"}, {\"time\": 218.0, \"estimate\": 0.6420690669673373, \"conf_low\": 0.5819895091101716, \"conf_high\": 0.7083507181884048, \"strata\": \"Overall\"}, {\"time\": 221.0, \"estimate\": 0.6420690669673373, \"conf_low\": 0.5819895091101716, \"conf_high\": 0.7083507181884048, \"strata\": \"Overall\"}, {\"time\": 222.0, \"estimate\": 0.6372049073691, \"conf_low\": 0.576931552453249, \"conf_high\": 0.703775157119987, \"strata\": \"Overall\"}, {\"time\": 223.0, \"estimate\": 0.6323033311585684, \"conf_low\": 0.5718379060086298, \"conf_high\": 0.6991622947573338, \"strata\": \"Overall\"}, {\"time\": 224.0, \"estimate\": 0.6323033311585684, \"conf_low\": 0.5718379060086298, \"conf_high\": 0.6991622947573338, \"strata\": \"Overall\"}, {\"time\": 225.0, \"estimate\": 0.6323033311585684, \"conf_low\": 0.5718379060086298, \"conf_high\": 0.6991622947573338, \"strata\": \"Overall\"}, {\"time\": 226.0, \"estimate\": 0.627285050752548, \"conf_low\": 0.5666157347189655, \"conf_high\": 0.6944504199001662, \"strata\": \"Overall\"}, {\"time\": 229.0, \"estimate\": 0.6222667703465277, \"conf_low\": 0.5614025265382911, \"conf_high\": 0.6897295882602119, \"strata\": \"Overall\"}, {\"time\": 230.0, \"estimate\": 0.6172484899405073, \"conf_low\": 0.5561981787765656, \"conf_high\": 0.6849999026819702, \"strata\": \"Overall\"}, {\"time\": 235.0, \"estimate\": 0.6172484899405073, \"conf_low\": 0.5561981787765656, \"conf_high\": 0.6849999026819702, \"strata\": \"Overall\"}, {\"time\": 237.0, \"estimate\": 0.6172484899405073, \"conf_low\": 0.5561981787765656, \"conf_high\": 0.6849999026819702, \"strata\": \"Overall\"}, {\"time\": 239.0, \"estimate\": 0.6070460355613254, \"conf_low\": 0.5456221661266805, \"conf_high\": 0.6753847482163395, \"strata\": \"Overall\"}, {\"time\": 240.0, \"estimate\": 0.6070460355613254, \"conf_low\": 0.5456221661266805, \"conf_high\": 0.6753847482163395, \"strata\": \"Overall\"}, {\"time\": 243.0, \"estimate\": 0.6070460355613254, \"conf_low\": 0.5456221661266805, \"conf_high\": 0.6753847482163395, \"strata\": \"Overall\"}, {\"time\": 245.0, \"estimate\": 0.6018576079069551, \"conf_low\": 0.5402459575191968, \"conf_high\": 0.6704956791511221, \"strata\": \"Overall\"}, {\"time\": 246.0, \"estimate\": 0.5966691802525848, \"conf_low\": 0.5348794322420498, \"conf_high\": 0.6655969349410016, \"strata\": \"Overall\"}, {\"time\": 252.0, \"estimate\": 0.5966691802525848, \"conf_low\": 0.5348794322420498, \"conf_high\": 0.6655969349410016, \"strata\": \"Overall\"}, {\"time\": 259.0, \"estimate\": 0.5966691802525848, \"conf_low\": 0.5348794322420498, \"conf_high\": 0.6655969349410016, \"strata\": \"Overall\"}, {\"time\": 266.0, \"estimate\": 0.5966691802525848, \"conf_low\": 0.5348794322420498, \"conf_high\": 0.6655969349410016, \"strata\": \"Overall\"}, {\"time\": 267.0, \"estimate\": 0.5913417768574724, \"conf_low\": 0.5293598558707568, \"conf_high\": 0.660581064428747, \"strata\": \"Overall\"}, {\"time\": 268.0, \"estimate\": 0.58601437346236, \"conf_low\": 0.5238508058197414, \"conf_high\": 0.6555546771892371, \"strata\": \"Overall\"}, {\"time\": 269.0, \"estimate\": 0.5806869700672477, \"conf_low\": 0.5183521669269323, \"conf_high\": 0.6505178886488815, \"strata\": \"Overall\"}, {\"time\": 270.0, \"estimate\": 0.5753102388629213, \"conf_low\": 0.5128062610268418, \"conf_high\": 0.6454325855494714, \"strata\": \"Overall\"}, {\"time\": 272.0, \"estimate\": 0.5753102388629213, \"conf_low\": 0.5128062610268418, \"conf_high\": 0.6454325855494714, \"strata\": \"Overall\"}, {\"time\": 276.0, \"estimate\": 0.5753102388629213, \"conf_low\": 0.5128062610268418, \"conf_high\": 0.6454325855494714, \"strata\": \"Overall\"}, {\"time\": 279.0, \"estimate\": 0.5753102388629213, \"conf_low\": 0.5128062610268418, \"conf_high\": 0.6454325855494714, \"strata\": \"Overall\"}, {\"time\": 283.0, \"estimate\": 0.5697784096430856, \"conf_low\": 0.5070895412825123, \"conf_high\": 0.6402171799369347, \"strata\": \"Overall\"}, {\"time\": 284.0, \"estimate\": 0.5642465804232498, \"conf_low\": 0.5013845415296376, \"conf_high\": 0.6349900668018728, \"strata\": \"Overall\"}, {\"time\": 285.0, \"estimate\": 0.5530733808109082, \"conf_low\": 0.4898816007674681, \"conf_high\": 0.6244165204049061, \"strata\": \"Overall\"}, {\"time\": 286.0, \"estimate\": 0.5474867810047375, \"conf_low\": 0.48414791008167085, \"conf_high\": 0.6191119885746609, \"strata\": \"Overall\"}, {\"time\": 288.0, \"estimate\": 0.5419001811985666, \"conf_low\": 0.4784259204720096, \"conf_high\": 0.6137957702904597, \"strata\": \"Overall\"}, {\"time\": 291.0, \"estimate\": 0.5363135813923958, \"conf_low\": 0.47271552726867255, \"conf_high\": 0.6084679706796671, \"strata\": \"Overall\"}, {\"time\": 292.0, \"estimate\": 0.5363135813923958, \"conf_low\": 0.47271552726867255, \"conf_high\": 0.6084679706796671, \"strata\": \"Overall\"}, {\"time\": 293.0, \"estimate\": 0.5306081177605618, \"conf_low\": 0.46687879965773993, \"conf_high\": 0.6030365371908117, \"strata\": \"Overall\"}, {\"time\": 296.0, \"estimate\": 0.5306081177605618, \"conf_low\": 0.46687879965773993, \"conf_high\": 0.6030365371908117, \"strata\": \"Overall\"}, {\"time\": 300.0, \"estimate\": 0.5306081177605618, \"conf_low\": 0.46687879965773993, \"conf_high\": 0.6030365371908117, \"strata\": \"Overall\"}, {\"time\": 301.0, \"estimate\": 0.5247772593236326, \"conf_low\": 0.46090868586544903, \"conf_high\": 0.5974961643131561, \"strata\": \"Overall\"}, {\"time\": 303.0, \"estimate\": 0.5188808856233671, \"conf_low\": 0.45487570019223056, \"conf_high\": 0.5918921880230358, \"strata\": \"Overall\"}, {\"time\": 305.0, \"estimate\": 0.5129167375127537, \"conf_low\": 0.44877768777750937, \"conf_high\": 0.5862225034484247, \"strata\": \"Overall\"}, {\"time\": 306.0, \"estimate\": 0.5069525894021403, \"conf_low\": 0.4426940689545054, \"conf_high\": 0.5805384483882624, \"strata\": \"Overall\"}, {\"time\": 310.0, \"estimate\": 0.49502429318091346, \"conf_low\": 0.4305695247299717, \"conf_high\": 0.5691277175107633, \"strata\": \"Overall\"}, {\"time\": 315.0, \"estimate\": 0.49502429318091346, \"conf_low\": 0.4305695247299717, \"conf_high\": 0.5691277175107633, \"strata\": \"Overall\"}, {\"time\": 320.0, \"estimate\": 0.48898741155675596, \"conf_low\": 0.42444434682043236, \"conf_high\": 0.5633452075688378, \"strata\": \"Overall\"}, {\"time\": 329.0, \"estimate\": 0.48295052993259846, \"conf_low\": 0.418333809280918, \"conf_high\": 0.5575480852554099, \"strata\": \"Overall\"}, {\"time\": 332.0, \"estimate\": 0.48295052993259846, \"conf_low\": 0.418333809280918, \"conf_high\": 0.5575480852554099, \"strata\": \"Overall\"}, {\"time\": 337.0, \"estimate\": 0.4768372320853504, \"conf_low\": 0.4121497260807857, \"conf_high\": 0.5516775373478003, \"strata\": \"Overall\"}, {\"time\": 340.0, \"estimate\": 0.4707239342381023, \"conf_low\": 0.405980833281674, \"conf_high\": 0.5457918307952778, \"strata\": \"Overall\"}, {\"time\": 345.0, \"estimate\": 0.46461063639085426, \"conf_low\": 0.39982703935768055, \"conf_high\": 0.5398910583793861, \"strata\": \"Overall\"}, {\"time\": 348.0, \"estimate\": 0.45849733854360614, \"conf_low\": 0.3936882632441165, \"conf_high\": 0.5339753024875369, \"strata\": \"Overall\"}, {\"time\": 350.0, \"estimate\": 0.45238404069635807, \"conf_low\": 0.38756443407038993, \"conf_high\": 0.5280446353846678, \"strata\": \"Overall\"}, {\"time\": 351.0, \"estimate\": 0.44627074284911, \"conf_low\": 0.38145549092912984, \"conf_high\": 0.5220991194490309, \"strata\": \"Overall\"}, {\"time\": 353.0, \"estimate\": 0.4340441471546138, \"conf_low\": 0.36928206778506917, \"conf_high\": 0.5101637423369986, \"strata\": \"Overall\"}, {\"time\": 356.0, \"estimate\": 0.4340441471546138, \"conf_low\": 0.36928206778506917, \"conf_high\": 0.5101637423369986, \"strata\": \"Overall\"}, {\"time\": 361.0, \"estimate\": 0.4278435164809765, \"conf_low\": 0.36311858389390567, \"conf_high\": 0.5041054980768772, \"strata\": \"Overall\"}, {\"time\": 363.0, \"estimate\": 0.4154422551337018, \"conf_low\": 0.35083835938802554, \"conf_high\": 0.4919424080412187, \"strata\": \"Overall\"}, {\"time\": 364.0, \"estimate\": 0.40924162446006446, \"conf_low\": 0.3447215817958266, \"conf_high\": 0.485837603547281, \"strata\": \"Overall\"}, {\"time\": 371.0, \"estimate\": 0.39664957447667787, \"conf_low\": 0.33232097603344973, \"conf_high\": 0.4734304972572465, \"strata\": \"Overall\"}, {\"time\": 376.0, \"estimate\": 0.39664957447667787, \"conf_low\": 0.33232097603344973, \"conf_high\": 0.4734304972572465, \"strata\": \"Overall\"}, {\"time\": 382.0, \"estimate\": 0.39664957447667787, \"conf_low\": 0.33232097603344973, \"conf_high\": 0.4734304972572465, \"strata\": \"Overall\"}, {\"time\": 384.0, \"estimate\": 0.39664957447667787, \"conf_low\": 0.33232097603344973, \"conf_high\": 0.4734304972572465, \"strata\": \"Overall\"}, {\"time\": 387.0, \"estimate\": 0.39003874823539986, \"conf_low\": 0.3257903393686721, \"conf_high\": 0.46695744698827135, \"strata\": \"Overall\"}, {\"time\": 390.0, \"estimate\": 0.3834279219941219, \"conf_low\": 0.3192797757213255, \"conf_high\": 0.4604644031479467, \"strata\": \"Overall\"}, {\"time\": 394.0, \"estimate\": 0.37681709575284394, \"conf_low\": 0.3127892793240402, \"conf_high\": 0.4539513756943998, \"strata\": \"Overall\"}, {\"time\": 404.0, \"estimate\": 0.37681709575284394, \"conf_low\": 0.3127892793240402, \"conf_high\": 0.4539513756943998, \"strata\": \"Overall\"}, {\"time\": 413.0, \"estimate\": 0.37681709575284394, \"conf_low\": 0.3127892793240402, \"conf_high\": 0.4539513756943998, \"strata\": \"Overall\"}, {\"time\": 426.0, \"estimate\": 0.36996587583006496, \"conf_low\": 0.3060473241272323, \"conf_high\": 0.44723393569618153, \"strata\": \"Overall\"}, {\"time\": 428.0, \"estimate\": 0.363114655907286, \"conf_low\": 0.29932852183718145, \"conf_high\": 0.4404934502245236, \"strata\": \"Overall\"}, {\"time\": 429.0, \"estimate\": 0.356263435984507, \"conf_low\": 0.292632885589053, \"conf_high\": 0.4337299123575842, \"strata\": \"Overall\"}, {\"time\": 433.0, \"estimate\": 0.349412216061728, \"conf_low\": 0.28596045145373156, \"conf_high\": 0.42694329272634296, \"strata\": \"Overall\"}, {\"time\": 442.0, \"estimate\": 0.342560996138949, \"conf_low\": 0.2793112786196021, \"conf_high\": 0.42013353938179837, \"strata\": \"Overall\"}, {\"time\": 444.0, \"estimate\": 0.33570977621617004, \"conf_low\": 0.2726854496904852, \"conf_high\": 0.41330057755202426, \"strata\": \"Overall\"}, {\"time\": 450.0, \"estimate\": 0.3287158225449998, \"conf_low\": 0.2659239701799572, \"conf_high\": 0.4063345320781461, \"strata\": \"Overall\"}, {\"time\": 455.0, \"estimate\": 0.3217218688738296, \"conf_low\": 0.2591880725114311, \"conf_high\": 0.39934307126383933, \"strata\": \"Overall\"}, {\"time\": 457.0, \"estimate\": 0.31472791520265936, \"conf_low\": 0.2524779008943496, \"conf_high\": 0.39232606203131315, \"strata\": \"Overall\"}, {\"time\": 458.0, \"estimate\": 0.31472791520265936, \"conf_low\": 0.2524779008943496, \"conf_high\": 0.39232606203131315, \"strata\": \"Overall\"}, {\"time\": 460.0, \"estimate\": 0.30757500803896254, \"conf_low\": 0.24561737689978488, \"conf_high\": 0.38516161504634455, \"strata\": \"Overall\"}, {\"time\": 473.0, \"estimate\": 0.3004221008752657, \"conf_low\": 0.23878538000538113, \"conf_high\": 0.3779688634717688, \"strata\": \"Overall\"}, {\"time\": 477.0, \"estimate\": 0.2932691937115689, \"conf_low\": 0.23198213826241193, \"conf_high\": 0.3707475955883514, \"strata\": \"Overall\"}, {\"time\": 511.0, \"estimate\": 0.2932691937115689, \"conf_low\": 0.23198213826241193, \"conf_high\": 0.3707475955883514, \"strata\": \"Overall\"}, {\"time\": 519.0, \"estimate\": 0.28574947079588764, \"conf_low\": 0.22480202617797093, \"conf_high\": 0.3632207478214058, \"strata\": \"Overall\"}, {\"time\": 520.0, \"estimate\": 0.2782297478802064, \"conf_low\": 0.2176576395510476, \"conf_high\": 0.3556585138254598, \"strata\": \"Overall\"}, {\"time\": 524.0, \"estimate\": 0.26319030204884386, \"conf_low\": 0.20347744499647386, \"conf_high\": 0.34042660155164645, \"strata\": \"Overall\"}, {\"time\": 529.0, \"estimate\": 0.26319030204884386, \"conf_low\": 0.20347744499647386, \"conf_high\": 0.34042660155164645, \"strata\": \"Overall\"}, {\"time\": 533.0, \"estimate\": 0.25544941081211314, \"conf_low\": 0.19619976940765507, \"conf_high\": 0.33259163189266083, \"strata\": \"Overall\"}, {\"time\": 543.0, \"estimate\": 0.25544941081211314, \"conf_low\": 0.19619976940765507, \"conf_high\": 0.33259163189266083, \"strata\": \"Overall\"}, {\"time\": 550.0, \"estimate\": 0.24746661672423462, \"conf_low\": 0.18869779010996507, \"conf_high\": 0.32453865176296615, \"strata\": \"Overall\"}, {\"time\": 551.0, \"estimate\": 0.24746661672423462, \"conf_low\": 0.18869779010996507, \"conf_high\": 0.32453865176296615, \"strata\": \"Overall\"}, {\"time\": 558.0, \"estimate\": 0.23921772950009346, \"conf_low\": 0.18095007695058357, \"conf_high\": 0.31624812252944073, \"strata\": \"Overall\"}, {\"time\": 559.0, \"estimate\": 0.23921772950009346, \"conf_low\": 0.18095007695058357, \"conf_high\": 0.31624812252944073, \"strata\": \"Overall\"}, {\"time\": 567.0, \"estimate\": 0.2306742391608044, \"conf_low\": 0.17293157128720876, \"conf_high\": 0.3076974563773701, \"strata\": \"Overall\"}, {\"time\": 574.0, \"estimate\": 0.22213074882151537, \"conf_low\": 0.164977741428185, \"conf_high\": 0.2990831923437733, \"strata\": \"Overall\"}, {\"time\": 583.0, \"estimate\": 0.21358725848222632, \"conf_low\": 0.15708958830312122, \"conf_high\": 0.29040445951087224, \"strata\": \"Overall\"}, {\"time\": 588.0, \"estimate\": 0.21358725848222632, \"conf_low\": 0.15708958830312122, \"conf_high\": 0.29040445951087224, \"strata\": \"Overall\"}, {\"time\": 613.0, \"estimate\": 0.20468778937880022, \"conf_low\": 0.14887877166751182, \"conf_high\": 0.2814174959365468, \"strata\": \"Overall\"}, {\"time\": 624.0, \"estimate\": 0.19578832027537413, \"conf_low\": 0.1407481800177885, \"conf_high\": 0.27235212811567255, \"strata\": \"Overall\"}, {\"time\": 641.0, \"estimate\": 0.18688885117194803, \"conf_low\": 0.13269961141317071, \"conf_high\": 0.2632068196765188, \"strata\": \"Overall\"}, {\"time\": 643.0, \"estimate\": 0.17798938206852194, \"conf_low\": 0.12473523956277675, \"conf_high\": 0.253979711268284, \"strata\": \"Overall\"}, {\"time\": 654.0, \"estimate\": 0.16908991296509585, \"conf_low\": 0.11685765966835891, \"conf_high\": 0.2446685886717725, \"strata\": \"Overall\"}, {\"time\": 655.0, \"estimate\": 0.16019044386166975, \"conf_low\": 0.10906994654918499, \"conf_high\": 0.2352708433117914, \"strata\": \"Overall\"}, {\"time\": 687.0, \"estimate\": 0.15129097475824366, \"conf_low\": 0.10137572838913213, \"conf_high\": 0.22578342377417931, \"strata\": \"Overall\"}, {\"time\": 689.0, \"estimate\": 0.14239150565481756, \"conf_low\": 0.09377928072077965, \"conf_high\": 0.21620277663478948, \"strata\": \"Overall\"}, {\"time\": 705.0, \"estimate\": 0.13349203655139147, \"conf_low\": 0.08628564710495039, \"conf_high\": 0.20652477463561444, \"strata\": \"Overall\"}, {\"time\": 707.0, \"estimate\": 0.12459256744796537, \"conf_low\": 0.0789007956900189, \"conf_high\": 0.19674463010820473, \"strata\": \"Overall\"}, {\"time\": 728.0, \"estimate\": 0.11569309834453928, \"conf_low\": 0.07163182496179636, \"conf_high\": 0.18685679181980702, \"strata\": \"Overall\"}, {\"time\": 731.0, \"estimate\": 0.10679362924111319, \"conf_low\": 0.06448723840578244, \"conf_high\": 0.1768548247441418, \"strata\": \"Overall\"}, {\"time\": 735.0, \"estimate\": 0.09789416013768708, \"conf_low\": 0.057477318057101406, \"conf_high\": 0.1667312761451836, \"strata\": \"Overall\"}, {\"time\": 740.0, \"estimate\": 0.09789416013768708, \"conf_low\": 0.057477318057101406, \"conf_high\": 0.1667312761451836, \"strata\": \"Overall\"}, {\"time\": 765.0, \"estimate\": 0.08810474412391837, \"conf_low\": 0.04976720259305024, \"conf_high\": 0.15597513086309414, \"strata\": \"Overall\"}, {\"time\": 791.0, \"estimate\": 0.07831532811014966, \"conf_low\": 0.04229358458915801, \"conf_high\": 0.14501704399330273, \"strata\": \"Overall\"}, {\"time\": 806.0, \"estimate\": 0.07831532811014966, \"conf_low\": 0.04229358458915801, \"conf_high\": 0.14501704399330273, \"strata\": \"Overall\"}, {\"time\": 814.0, \"estimate\": 0.067127424094414, \"conf_low\": 0.033793219329547194, \"conf_high\": 0.13334305387150253, \"strata\": \"Overall\"}, {\"time\": 821.0, \"estimate\": 0.067127424094414, \"conf_low\": 0.033793219329547194, \"conf_high\": 0.13334305387150253, \"strata\": \"Overall\"}, {\"time\": 840.0, \"estimate\": 0.067127424094414, \"conf_low\": 0.033793219329547194, \"conf_high\": 0.13334305387150253, \"strata\": \"Overall\"}, {\"time\": 883.0, \"estimate\": 0.0503455680708105, \"conf_low\": 0.02068546019897997, \"conf_high\": 0.12253419551659778, \"strata\": \"Overall\"}, {\"time\": 965.0, \"estimate\": 0.0503455680708105, \"conf_low\": 0.02068546019897997, \"conf_high\": 0.12253419551659778, \"strata\": \"Overall\"}, {\"time\": 1010.0, \"estimate\": 0.0503455680708105, \"conf_low\": 0.02068546019897997, \"conf_high\": 0.12253419551659778, \"strata\": \"Overall\"}, {\"time\": 1022.0, \"estimate\": 0.0503455680708105, \"conf_low\": 0.02068546019897997, \"conf_high\": 0.12253419551659778, \"strata\": \"Overall\"}], \"data-911618b04b6a5ab2aed534e81520f90f\": [{\"time\": 92.0, \"estimate\": 0.8771929824561403, \"strata\": \"Overall\"}, {\"time\": 105.0, \"estimate\": 0.8595609627082782, \"strata\": \"Overall\"}, {\"time\": 173.0, \"estimate\": 0.7487927974108197, \"strata\": \"Overall\"}, {\"time\": 174.0, \"estimate\": 0.7487927974108197, \"strata\": \"Overall\"}, {\"time\": 175.0, \"estimate\": 0.7443090082047669, \"strata\": \"Overall\"}, {\"time\": 177.0, \"estimate\": 0.7352870808325879, \"strata\": \"Overall\"}, {\"time\": 185.0, \"estimate\": 0.7035154168459947, \"strata\": \"Overall\"}, {\"time\": 188.0, \"estimate\": 0.6989471349184234, \"strata\": \"Overall\"}, {\"time\": 191.0, \"estimate\": 0.6943487985044865, \"strata\": \"Overall\"}, {\"time\": 192.0, \"estimate\": 0.6943487985044865, \"strata\": \"Overall\"}, {\"time\": 196.0, \"estimate\": 0.6896887394541208, \"strata\": \"Overall\"}, {\"time\": 197.0, \"estimate\": 0.6849969793217798, \"strata\": \"Overall\"}, {\"time\": 202.0, \"estimate\": 0.6661005109266964, \"strata\": \"Overall\"}, {\"time\": 203.0, \"estimate\": 0.6661005109266964, \"strata\": \"Overall\"}, {\"time\": 211.0, \"estimate\": 0.6517242409066958, \"strata\": \"Overall\"}, {\"time\": 221.0, \"estimate\": 0.6420690669673373, \"strata\": \"Overall\"}, {\"time\": 222.0, \"estimate\": 0.6372049073691, \"strata\": \"Overall\"}, {\"time\": 224.0, \"estimate\": 0.6323033311585684, \"strata\": \"Overall\"}, {\"time\": 225.0, \"estimate\": 0.6323033311585684, \"strata\": \"Overall\"}, {\"time\": 235.0, \"estimate\": 0.6172484899405073, \"strata\": \"Overall\"}, {\"time\": 237.0, \"estimate\": 0.6172484899405073, \"strata\": \"Overall\"}, {\"time\": 240.0, \"estimate\": 0.6070460355613254, \"strata\": \"Overall\"}, {\"time\": 243.0, \"estimate\": 0.6070460355613254, \"strata\": \"Overall\"}, {\"time\": 252.0, \"estimate\": 0.5966691802525848, \"strata\": \"Overall\"}, {\"time\": 259.0, \"estimate\": 0.5966691802525848, \"strata\": \"Overall\"}, {\"time\": 266.0, \"estimate\": 0.5966691802525848, \"strata\": \"Overall\"}, {\"time\": 269.0, \"estimate\": 0.5806869700672477, \"strata\": \"Overall\"}, {\"time\": 272.0, \"estimate\": 0.5753102388629213, \"strata\": \"Overall\"}, {\"time\": 276.0, \"estimate\": 0.5753102388629213, \"strata\": \"Overall\"}, {\"time\": 279.0, \"estimate\": 0.5753102388629213, \"strata\": \"Overall\"}, {\"time\": 284.0, \"estimate\": 0.5642465804232498, \"strata\": \"Overall\"}, {\"time\": 292.0, \"estimate\": 0.5363135813923958, \"strata\": \"Overall\"}, {\"time\": 296.0, \"estimate\": 0.5306081177605618, \"strata\": \"Overall\"}, {\"time\": 300.0, \"estimate\": 0.5306081177605618, \"strata\": \"Overall\"}, {\"time\": 301.0, \"estimate\": 0.5247772593236326, \"strata\": \"Overall\"}, {\"time\": 303.0, \"estimate\": 0.5188808856233671, \"strata\": \"Overall\"}, {\"time\": 315.0, \"estimate\": 0.49502429318091346, \"strata\": \"Overall\"}, {\"time\": 332.0, \"estimate\": 0.48295052993259846, \"strata\": \"Overall\"}, {\"time\": 356.0, \"estimate\": 0.4340441471546138, \"strata\": \"Overall\"}, {\"time\": 364.0, \"estimate\": 0.40924162446006446, \"strata\": \"Overall\"}, {\"time\": 376.0, \"estimate\": 0.39664957447667787, \"strata\": \"Overall\"}, {\"time\": 382.0, \"estimate\": 0.39664957447667787, \"strata\": \"Overall\"}, {\"time\": 384.0, \"estimate\": 0.39664957447667787, \"strata\": \"Overall\"}, {\"time\": 404.0, \"estimate\": 0.37681709575284394, \"strata\": \"Overall\"}, {\"time\": 413.0, \"estimate\": 0.37681709575284394, \"strata\": \"Overall\"}, {\"time\": 444.0, \"estimate\": 0.33570977621617004, \"strata\": \"Overall\"}, {\"time\": 458.0, \"estimate\": 0.31472791520265936, \"strata\": \"Overall\"}, {\"time\": 511.0, \"estimate\": 0.2932691937115689, \"strata\": \"Overall\"}, {\"time\": 529.0, \"estimate\": 0.26319030204884386, \"strata\": \"Overall\"}, {\"time\": 543.0, \"estimate\": 0.25544941081211314, \"strata\": \"Overall\"}, {\"time\": 551.0, \"estimate\": 0.24746661672423462, \"strata\": \"Overall\"}, {\"time\": 559.0, \"estimate\": 0.23921772950009346, \"strata\": \"Overall\"}, {\"time\": 588.0, \"estimate\": 0.21358725848222632, \"strata\": \"Overall\"}, {\"time\": 740.0, \"estimate\": 0.09789416013768708, \"strata\": \"Overall\"}, {\"time\": 806.0, \"estimate\": 0.07831532811014966, \"strata\": \"Overall\"}, {\"time\": 821.0, \"estimate\": 0.067127424094414, \"strata\": \"Overall\"}, {\"time\": 840.0, \"estimate\": 0.067127424094414, \"strata\": \"Overall\"}, {\"time\": 965.0, \"estimate\": 0.0503455680708105, \"strata\": \"Overall\"}, {\"time\": 1010.0, \"estimate\": 0.0503455680708105, \"strata\": \"Overall\"}, {\"time\": 1022.0, \"estimate\": 0.0503455680708105, \"strata\": \"Overall\"}]}}, {\"mode\": \"vega-lite\"});\n</script>\n```\n:::\n:::\n\n\nThe curve starts at 1.0 and steps down at each death. It does not reach 0 because some\npatients were still alive at the end of follow-up, so their survival time is only known to be\nat least that long.\n\n## Model a covariate effect\n\nTo ask how a characteristic changes the risk of death, fit a Cox proportional hazards model.\nHere we include `age` and `sex`. Printing the model shows a coefficient table.\n\n::: {#9c610381 .cell execution_count=5}\n``` {.python .cell-code}\n# Load data and build the right-censored response\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\ny = gw.Surv.right(lung[\"time\"], event=(lung[\"status\"] == 2))\n\n# Fit a Cox proportional hazards model with age and sex as covariates\ncox = gw.CoxPH().fit(y, lung[[\"age\", \"sex\"]])\n\n# Print the coefficient table and global test statistics\ncox\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```\nCoxPH (Cox proportional hazards model, ties='efron')\n\n        coef  exp(coef)  se(coef)       z         p\nage  0.01705      1.017  0.009223   1.848   0.06459\nsex  -0.5132     0.5986    0.1675  -3.065  0.002178\n\nn = 228, events = 165\nLikelihood ratio test = 14.12 on 2 df, p = 0.0008574\n```\n:::\n:::\n\n\nThe `exp(coef)` column holds hazard ratios. For `sex` (coded `1` for male, `2` for female) the\nhazard ratio is about 0.60, which means women had roughly 40 percent lower risk of death than\nmen over the study, holding age fixed. A ratio below 1 is lower risk, above 1 is higher risk.\n\n## Shared frailty for clustered survival data\n\nIf subjects are clustered (for example by center, family, or recurrent-event unit), you can make use\nof the shared gamma frailty Cox model.\n\n::: {#dd4ff939 .cell execution_count=6}\n``` {.python .cell-code}\n# Shared frailty Cox model (clustered by institution)\ncox_frailty = gw.CoxPH(ties=\"breslow\").fit(\n    y,\n    lung[[\"age\", \"sex\"]],\n    frailty=\"gamma\",\n    frailty_cluster=lung[\"inst\"],\n)\n\n# Frailty variance inference (tests theta = 0)\ncox_frailty.frailty_test()\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n```\n{'theta': 1.3779723598335543e-08,\n 'lr_statistic': 0.00043770764023065567,\n 'df': 1.0,\n 'p_value': 0.49165415243657906}\n```\n:::\n:::\n\n\nSee [Cox regression](cox-regression.qmd) for full guidance and interpretation.\n\n## Next steps\n\nThat is the core loop: represent the data, estimate a curve, visualize it, and model an\neffect. Each part of the guide takes one of these steps further.\n\n- [Survival data and the Surv object](survival-data.qmd) and\n[Data sources and formats](data-sources.qmd) cover the input side in full.\n- [Estimating survival with Kaplan-Meier](kaplan-meier.qmd),\n[Comparing groups](comparing-groups.qmd), and\n[Visualizing survival](visualization.qmd) cover description and comparison.\n- [Cox regression](cox-regression.qmd) and\n[Parametric survival models](parametric-models.qmd) cover modeling, and\n[Prediction performance](prediction-performance.qmd) covers evaluation.\n\n",
    "supporting": [
      "quick-start_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}