{
  "hash": "6889b84a6f84eefc135fe90016be48de",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: Cox model diagnostics\nguide-section: \"Regression\"\nbread-crumbs: false\n---\n\n\n\nFitting a Cox model is only half the work. Before you trust its hazard ratios, you should\ncheck that its central assumption holds, look at residuals for influential or poorly fit\nobservations, and understand what the model predicts. This page covers the proportional\nhazards test, residuals, baseline hazard and survival prediction, stratification, robust\nstandard errors, and the concordance index. Together these turn a fitted model into a\ndefensible one.\n\nWe begin with the `lung` outcomes. The response `y` is a `Surv` object pairing each follow-up\ntime with an event indicator, and it is the target every model on this page is fit against.\n\n::: {#556148a0 .cell execution_count=2}\n``` {.python .cell-code}\nimport greenwood as gw\n\n# Load the bundled lung dataset as a Polars DataFrame\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\n\n# Build a right-censored response; status == 2 marks a death\ny = gw.Surv.right(lung[\"time\"], event=(lung[\"status\"] == 2))\n\n# Display the response summary\ny\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```\nSurv(type=right, n=228, events=165)\n```\n:::\n:::\n\n\nThe printed response records 165 events among 228 subjects, with a `+` marking each censored\nobservation. We fit a Cox model to it using `age` and `sex` as covariates. This is the model\nwe diagnose throughout the page, so we fit it once here and reuse it below.\n\n::: {#514763e4 .cell execution_count=3}\n``` {.python .cell-code}\n# Fit the model we will diagnose throughout this page\ncox = gw.CoxPH().fit(y, lung[[\"age\", \"sex\"]])\n```\n:::\n\n\nWith the response and model in hand, the sections below work through each diagnostic in turn.\n\n## Checking the proportional hazards assumption\n\nThe Cox model assumes each covariate's effect on the hazard is constant over time. When this\nfails, for example if a treatment helps early but not late, the reported hazard ratio is a\nmisleading average. The Grambsch-Therneau test checks the assumption by looking for a trend\nin the scaled Schoenfeld residuals against time. A small p-value is evidence that the\nassumption is violated for that covariate.\n\nCalling `cox_zph()` returns a `ZPHResult`, an object that bundles the test statistics\ntogether. Displaying it directly gives a compact summary of the test.\n\n::: {#68790f05 .cell execution_count=4}\n``` {.python .cell-code}\n# Load data and build the response\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\ny = gw.Surv.right(lung[\"time\"], event=(lung[\"status\"] == 2))\n\n# Fit a Cox model with age and sex as covariates\ncox = gw.CoxPH().fit(y, lung[[\"age\", \"sex\"]])\n\n# Run the Grambsch-Therneau proportional hazards test\nzph = cox.cox_zph()\n\n# Print per-covariate test statistics and p-values\nzph\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```\nZPHResult(transform='identity', age: p=0.7065, sex: p=0.0992, GLOBAL p=0.2425)\n```\n:::\n:::\n\n\nFor the full per-covariate breakdown, call `to_frame()` on that result. This is the table\nyou will read most often.\n\n::: {#78249428 .cell execution_count=5}\n``` {.python .cell-code}\n# Export the ZPH test table as a tidy DataFrame (one row per term plus GLOBAL)\nzph.to_frame(format=\"polars\")\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```{=html}\n<div id=\"gd-tbl-45f3f1a1\" class=\"gd-tbl-preview\" style=\"padding-left: 0px; overflow-x: auto; overflow-y: hidden; width: 100%; max-width: 100%; margin-bottom: 1em;\">\n<style>\n@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,600;1,400&family=IBM+Plex+Sans:wght@400;600&display=swap');\n#gd-tbl-45f3f1a1 .gt_table {\n  display: table;\n  border-collapse: collapse;\n  table-layout: fixed;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 14px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n}\n#gd-tbl-45f3f1a1 .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-45f3f1a1 .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n#gd-tbl-45f3f1a1 .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n#gd-tbl-45f3f1a1 .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n#gd-tbl-45f3f1a1 .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-45f3f1a1 .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #F2F2F2;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #F2F2F2;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n#gd-tbl-45f3f1a1 .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n}\n#gd-tbl-45f3f1a1 .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #E9E9E9;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #E9E9E9;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #E9E9E9;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n#gd-tbl-45f3f1a1 .gt_left { text-align: left; }\n#gd-tbl-45f3f1a1 .gt_center { text-align: center; }\n#gd-tbl-45f3f1a1 .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n#gd-tbl-45f3f1a1 .gt_font_normal { font-weight: normal; }\n#gd-tbl-45f3f1a1 .gt_font_bold { font-weight: bold; }\n#gd-tbl-45f3f1a1 .gt_font_italic { font-style: italic; }\n#gd-tbl-45f3f1a1 .gt_striped { background-color: rgba(128,128,128,0.05); }\n#gd-tbl-45f3f1a1 .gt_from_md > :first-child { margin-top: 0; }\n#gd-tbl-45f3f1a1 .gt_from_md > :last-child { margin-bottom: 0; }\n/* Data cell font */\n#gd-tbl-45f3f1a1 .gt_table_body .gt_row {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  height: 14px;\n}\n/* Column label font */\n#gd-tbl-45f3f1a1 .gt_col_heading {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n}\n/* Row number styling */\n#gd-tbl-45f3f1a1 .gd-tbl-rownum {\n  color: gray;\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 10px;\n  border-right: 2px solid rgba(102, 153, 204, 0.5) !important;\n  text-align: right;\n  padding-right: 6px;\n  white-space: nowrap;\n}\n/* Head/tail divider */\n#gd-tbl-45f3f1a1 tr.gd-tbl-divider td,\n#gd-tbl-45f3f1a1 tr.gd-tbl-divider th {\n  border-bottom: 2px solid rgba(102, 153, 204, 0.5);\n}\n/* Missing values */\n#gd-tbl-45f3f1a1 .gd-tbl-missing {\n  color: #B22222 !important;\n  background-color: rgba(255, 193, 193, 0.35);\n}\n/* Column label sub-elements */\n#gd-tbl-45f3f1a1 .gd-tbl-colname {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-bottom: 0;\n  margin-bottom: 0;\n}\n#gd-tbl-45f3f1a1 .gd-tbl-dtype {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-top: 0;\n  margin-top: 0;\n  color: #666666;\n}\n/* Header badge styling */\n#gd-tbl-45f3f1a1 .gd-tbl-badge {\n  display: inline-block;\n  padding: 2px 10px;\n  font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, sans-serif;\n  font-size: 10px;\n  font-weight: bold;\n  text-transform: uppercase;\n  position: inherit;\n}\n#gd-tbl-45f3f1a1 .gd-tbl-badge-rows-label {\n  background-color: #eecbff;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: 5px;\n}\n#gd-tbl-45f3f1a1 .gd-tbl-badge-rows-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: -4px;\n  margin-right: 3px;\n}\n#gd-tbl-45f3f1a1 .gd-tbl-badge-cols-label {\n  background-color: #BDE7B4;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n}\n#gd-tbl-45f3f1a1 .gd-tbl-badge-cols-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n  margin-left: -4px;\n}\n/* Dark mode */\nbody.quarto-dark #gd-tbl-45f3f1a1 .gt_table,\nhtml.quarto-dark #gd-tbl-45f3f1a1 .gt_table,\n:root[data-bs-theme=\"dark\"] #gd-tbl-45f3f1a1 .gt_table {\n  background-color: #1a1a2e;\n  color: #e0e0e0;\n  border-top-color: #555;\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-45f3f1a1 .gt_heading,\nhtml.quarto-dark #gd-tbl-45f3f1a1 .gt_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-45f3f1a1 .gt_heading {\n  background-color: #1a1a2e;\n  border-bottom-color: #1a1a2e;\n}\nbody.quarto-dark #gd-tbl-45f3f1a1 .gt_title,\nhtml.quarto-dark #gd-tbl-45f3f1a1 .gt_title,\n:root[data-bs-theme=\"dark\"] #gd-tbl-45f3f1a1 .gt_title {\n  color: #e0e0e0;\n}\nbody.quarto-dark #gd-tbl-45f3f1a1 .gt_subtitle,\nhtml.quarto-dark #gd-tbl-45f3f1a1 .gt_subtitle,\n:root[data-bs-theme=\"dark\"] #gd-tbl-45f3f1a1 .gt_subtitle {\n  color: #b0b0b0;\n}\nbody.quarto-dark #gd-tbl-45f3f1a1 .gt_col_headings,\nhtml.quarto-dark #gd-tbl-45f3f1a1 .gt_col_headings,\n:root[data-bs-theme=\"dark\"] #gd-tbl-45f3f1a1 .gt_col_headings {\n  border-top-color: #444;\n  border-bottom-color: #444;\n}\nbody.quarto-dark #gd-tbl-45f3f1a1 .gt_col_heading,\nhtml.quarto-dark #gd-tbl-45f3f1a1 .gt_col_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-45f3f1a1 .gt_col_heading {\n  color: #b0b0b0;\n  background-color: #1a1a2e;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-45f3f1a1 .gt_table_body,\nhtml.quarto-dark #gd-tbl-45f3f1a1 .gt_table_body,\n:root[data-bs-theme=\"dark\"] #gd-tbl-45f3f1a1 .gt_table_body {\n  border-top-color: #444;\n}\nbody.quarto-dark #gd-tbl-45f3f1a1 .gt_table_body .gt_row,\nhtml.quarto-dark #gd-tbl-45f3f1a1 .gt_table_body .gt_row,\n:root[data-bs-theme=\"dark\"] #gd-tbl-45f3f1a1 .gt_table_body .gt_row {\n  color: #d0d0d0;\n  border-top-color: #4b4b4b;\n  border-bottom-color: #4b4b4b;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-45f3f1a1 .gd-tbl-rownum,\nhtml.quarto-dark #gd-tbl-45f3f1a1 .gd-tbl-rownum,\n:root[data-bs-theme=\"dark\"] #gd-tbl-45f3f1a1 .gd-tbl-rownum {\n  color: #888;\n  border-right-color: rgba(102, 153, 204, 0.4) !important;\n}\nbody.quarto-dark #gd-tbl-45f3f1a1 .gd-tbl-missing,\nhtml.quarto-dark #gd-tbl-45f3f1a1 .gd-tbl-missing,\n:root[data-bs-theme=\"dark\"] #gd-tbl-45f3f1a1 .gd-tbl-missing {\n  color: #ff6b6b !important;\n  background-color: rgba(60, 17, 24, 0.2);\n}\nbody.quarto-dark #gd-tbl-45f3f1a1 .gd-tbl-dtype,\nhtml.quarto-dark #gd-tbl-45f3f1a1 .gd-tbl-dtype,\n:root[data-bs-theme=\"dark\"] #gd-tbl-45f3f1a1 .gd-tbl-dtype {\n  color: #888;\n}\nbody.quarto-dark #gd-tbl-45f3f1a1 .gt_bottom_border,\nhtml.quarto-dark #gd-tbl-45f3f1a1 .gt_bottom_border,\n:root[data-bs-theme=\"dark\"] #gd-tbl-45f3f1a1 .gt_bottom_border {\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-45f3f1a1 .gd-tbl-badge-rows-label,\nhtml.quarto-dark #gd-tbl-45f3f1a1 .gd-tbl-badge-rows-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-45f3f1a1 .gd-tbl-badge-rows-label {\n  background-color: #3d2a4d;\n  border-color: #3d2a4d;\n  color: #e0c0ff;\n}\nbody.quarto-dark #gd-tbl-45f3f1a1 .gd-tbl-badge-rows-value,\nhtml.quarto-dark #gd-tbl-45f3f1a1 .gd-tbl-badge-rows-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-45f3f1a1 .gd-tbl-badge-rows-value {\n  border-color: #3d2a4d;\n  color: #d0b0e0;\n}\nbody.quarto-dark #gd-tbl-45f3f1a1 .gd-tbl-badge-cols-label,\nhtml.quarto-dark #gd-tbl-45f3f1a1 .gd-tbl-badge-cols-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-45f3f1a1 .gd-tbl-badge-cols-label {\n  background-color: #2a4d2a;\n  border-color: #2a4d2a;\n  color: #b0e0b0;\n}\nbody.quarto-dark #gd-tbl-45f3f1a1 .gd-tbl-badge-cols-value,\nhtml.quarto-dark #gd-tbl-45f3f1a1 .gd-tbl-badge-cols-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-45f3f1a1 .gd-tbl-badge-cols-value {\n  border-color: #2a4d2a;\n  color: #a0d0a0;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"true\" data-quarto-bootstrap=\"false\">\n<colgroup>\n<col style=\"width: 35px\"/>\n<col style=\"width: 87px\"/>\n<col style=\"width: 145px\"/>\n<col style=\"width: 78px\"/>\n<col style=\"width: 152px\"/>\n</colgroup>\n<thead>\n<tr class=\"gt_heading\"><td class=\"gt_heading gt_title gt_font_normal\" colspan=\"5\"><div style=\"padding-top: 0; padding-bottom: 7px;\"><span class=\"gd-tbl-badge\" style=\"background-color: #0075FF; color: #FFFFFF; border: 1px solid #0075FF; margin-right: 8px;\">Polars</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-label\">Rows</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-value\">3</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-label\">Columns</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-value\">4</span></div></td></tr>\n<tr class=\"gt_col_headings\">\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\"></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\"><div><div class=\"gd-tbl-colname\">term</div><div class=\"gd-tbl-dtype\"><em>str</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"chisq\"><div><div class=\"gd-tbl-colname\">chisq</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df\"><div><div class=\"gd-tbl-colname\">df</div><div class=\"gd-tbl-dtype\"><em>i64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p_value\"><div><div class=\"gd-tbl-colname\">p_value</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">0</td>\n<td class=\"gt_row gt_left\" style=\"max-width: 87px;\">age</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 145px;\">0.141747561345</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 78px;\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 152px;\">0.70654984373</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">1</td>\n<td class=\"gt_row gt_left\" style=\"max-width: 87px;\">sex</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 145px;\">2.71840108815</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 78px;\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 152px;\">0.0991973377972</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">2</td>\n<td class=\"gt_row gt_left\" style=\"max-width: 87px;\">GLOBAL</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 145px;\">2.8333913831</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 78px;\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 152px;\">0.242514035592</td>\n</tr>\n</tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThe table has one row per covariate plus a `GLOBAL` row that tests all covariates jointly.\nLarge p-values, as here, are reassuring: they give no evidence against proportional hazards.\nThe test uses a time transform, which defaults to `\"identity\"`; `\"log\"` is also available.\n\n::: {.callout-warning}\n## A non-significant test is not proof\n\nFailing to reject the proportional hazards assumption does not prove it holds, especially in\nsmall samples. Complement the test by plotting scaled Schoenfeld residuals or by fitting\ntime-stratified models when you have reason to suspect a time-varying effect.\n:::\n\n## Residuals\n\nResiduals reveal how individual observations relate to the fitted model. Martingale\nresiduals, one per subject, are the difference between the observed number of events and the\nnumber the model expected; large negative values flag subjects who lived much longer than\npredicted. Schoenfeld residuals, one per event, underlie the proportional hazards test and\nare useful for spotting time trends in a covariate's effect.\n\nThe martingale residuals come back as a NumPy array with one entry per subject. There are 228\nof them, so we look at the first five rather than the whole array.\n\n::: {#aed7d17a .cell execution_count=6}\n``` {.python .cell-code}\n# Load data and build the response\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\ny = gw.Surv.right(lung[\"time\"], event=(lung[\"status\"] == 2))\n\n# Fit a Cox model with age and sex as covariates\ncox = gw.CoxPH().fit(y, lung[[\"age\", \"sex\"]])\n\n# Compute martingale residuals (one per subject); peek at the first five\ncox.residuals(\"martingale\")[:5]\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n```\narray([ 0.00438999, -0.50576203, -3.12981924,  0.53275397, -2.35065745])\n```\n:::\n:::\n\n\nThe Schoenfeld residuals come back as a DataFrame instead, with one row per event and one\ncolumn per covariate.\n\n::: {#0fc2b811 .cell execution_count=7}\n``` {.python .cell-code}\n# Compute Schoenfeld residuals (one row per event, one column per covariate)\ncox.residuals(\"schoenfeld\", format=\"polars\")\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```{=html}\n<div id=\"gd-tbl-454d5f45\" class=\"gd-tbl-preview\" style=\"padding-left: 0px; overflow-x: auto; overflow-y: hidden; width: 100%; max-width: 100%; margin-bottom: 1em;\">\n<style>\n@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,600;1,400&family=IBM+Plex+Sans:wght@400;600&display=swap');\n#gd-tbl-454d5f45 .gt_table {\n  display: table;\n  border-collapse: collapse;\n  table-layout: fixed;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 14px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n}\n#gd-tbl-454d5f45 .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-454d5f45 .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n#gd-tbl-454d5f45 .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n#gd-tbl-454d5f45 .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n#gd-tbl-454d5f45 .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-454d5f45 .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #F2F2F2;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #F2F2F2;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n#gd-tbl-454d5f45 .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n}\n#gd-tbl-454d5f45 .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #E9E9E9;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #E9E9E9;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #E9E9E9;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n#gd-tbl-454d5f45 .gt_left { text-align: left; }\n#gd-tbl-454d5f45 .gt_center { text-align: center; }\n#gd-tbl-454d5f45 .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n#gd-tbl-454d5f45 .gt_font_normal { font-weight: normal; }\n#gd-tbl-454d5f45 .gt_font_bold { font-weight: bold; }\n#gd-tbl-454d5f45 .gt_font_italic { font-style: italic; }\n#gd-tbl-454d5f45 .gt_striped { background-color: rgba(128,128,128,0.05); }\n#gd-tbl-454d5f45 .gt_from_md > :first-child { margin-top: 0; }\n#gd-tbl-454d5f45 .gt_from_md > :last-child { margin-bottom: 0; }\n/* Data cell font */\n#gd-tbl-454d5f45 .gt_table_body .gt_row {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  height: 14px;\n}\n/* Column label font */\n#gd-tbl-454d5f45 .gt_col_heading {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n}\n/* Row number styling */\n#gd-tbl-454d5f45 .gd-tbl-rownum {\n  color: gray;\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 10px;\n  border-right: 2px solid rgba(102, 153, 204, 0.5) !important;\n  text-align: right;\n  padding-right: 6px;\n  white-space: nowrap;\n}\n/* Head/tail divider */\n#gd-tbl-454d5f45 tr.gd-tbl-divider td,\n#gd-tbl-454d5f45 tr.gd-tbl-divider th {\n  border-bottom: 2px solid rgba(102, 153, 204, 0.5);\n}\n/* Missing values */\n#gd-tbl-454d5f45 .gd-tbl-missing {\n  color: #B22222 !important;\n  background-color: rgba(255, 193, 193, 0.35);\n}\n/* Column label sub-elements */\n#gd-tbl-454d5f45 .gd-tbl-colname {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-bottom: 0;\n  margin-bottom: 0;\n}\n#gd-tbl-454d5f45 .gd-tbl-dtype {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-top: 0;\n  margin-top: 0;\n  color: #666666;\n}\n/* Header badge styling */\n#gd-tbl-454d5f45 .gd-tbl-badge {\n  display: inline-block;\n  padding: 2px 10px;\n  font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, sans-serif;\n  font-size: 10px;\n  font-weight: bold;\n  text-transform: uppercase;\n  position: inherit;\n}\n#gd-tbl-454d5f45 .gd-tbl-badge-rows-label {\n  background-color: #eecbff;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: 5px;\n}\n#gd-tbl-454d5f45 .gd-tbl-badge-rows-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: -4px;\n  margin-right: 3px;\n}\n#gd-tbl-454d5f45 .gd-tbl-badge-cols-label {\n  background-color: #BDE7B4;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n}\n#gd-tbl-454d5f45 .gd-tbl-badge-cols-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n  margin-left: -4px;\n}\n/* Dark mode */\nbody.quarto-dark #gd-tbl-454d5f45 .gt_table,\nhtml.quarto-dark #gd-tbl-454d5f45 .gt_table,\n:root[data-bs-theme=\"dark\"] #gd-tbl-454d5f45 .gt_table {\n  background-color: #1a1a2e;\n  color: #e0e0e0;\n  border-top-color: #555;\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-454d5f45 .gt_heading,\nhtml.quarto-dark #gd-tbl-454d5f45 .gt_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-454d5f45 .gt_heading {\n  background-color: #1a1a2e;\n  border-bottom-color: #1a1a2e;\n}\nbody.quarto-dark #gd-tbl-454d5f45 .gt_title,\nhtml.quarto-dark #gd-tbl-454d5f45 .gt_title,\n:root[data-bs-theme=\"dark\"] #gd-tbl-454d5f45 .gt_title {\n  color: #e0e0e0;\n}\nbody.quarto-dark #gd-tbl-454d5f45 .gt_subtitle,\nhtml.quarto-dark #gd-tbl-454d5f45 .gt_subtitle,\n:root[data-bs-theme=\"dark\"] #gd-tbl-454d5f45 .gt_subtitle {\n  color: #b0b0b0;\n}\nbody.quarto-dark #gd-tbl-454d5f45 .gt_col_headings,\nhtml.quarto-dark #gd-tbl-454d5f45 .gt_col_headings,\n:root[data-bs-theme=\"dark\"] #gd-tbl-454d5f45 .gt_col_headings {\n  border-top-color: #444;\n  border-bottom-color: #444;\n}\nbody.quarto-dark #gd-tbl-454d5f45 .gt_col_heading,\nhtml.quarto-dark #gd-tbl-454d5f45 .gt_col_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-454d5f45 .gt_col_heading {\n  color: #b0b0b0;\n  background-color: #1a1a2e;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-454d5f45 .gt_table_body,\nhtml.quarto-dark #gd-tbl-454d5f45 .gt_table_body,\n:root[data-bs-theme=\"dark\"] #gd-tbl-454d5f45 .gt_table_body {\n  border-top-color: #444;\n}\nbody.quarto-dark #gd-tbl-454d5f45 .gt_table_body .gt_row,\nhtml.quarto-dark #gd-tbl-454d5f45 .gt_table_body .gt_row,\n:root[data-bs-theme=\"dark\"] #gd-tbl-454d5f45 .gt_table_body .gt_row {\n  color: #d0d0d0;\n  border-top-color: #4b4b4b;\n  border-bottom-color: #4b4b4b;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-454d5f45 .gd-tbl-rownum,\nhtml.quarto-dark #gd-tbl-454d5f45 .gd-tbl-rownum,\n:root[data-bs-theme=\"dark\"] #gd-tbl-454d5f45 .gd-tbl-rownum {\n  color: #888;\n  border-right-color: rgba(102, 153, 204, 0.4) !important;\n}\nbody.quarto-dark #gd-tbl-454d5f45 .gd-tbl-missing,\nhtml.quarto-dark #gd-tbl-454d5f45 .gd-tbl-missing,\n:root[data-bs-theme=\"dark\"] #gd-tbl-454d5f45 .gd-tbl-missing {\n  color: #ff6b6b !important;\n  background-color: rgba(60, 17, 24, 0.2);\n}\nbody.quarto-dark #gd-tbl-454d5f45 .gd-tbl-dtype,\nhtml.quarto-dark #gd-tbl-454d5f45 .gd-tbl-dtype,\n:root[data-bs-theme=\"dark\"] #gd-tbl-454d5f45 .gd-tbl-dtype {\n  color: #888;\n}\nbody.quarto-dark #gd-tbl-454d5f45 .gt_bottom_border,\nhtml.quarto-dark #gd-tbl-454d5f45 .gt_bottom_border,\n:root[data-bs-theme=\"dark\"] #gd-tbl-454d5f45 .gt_bottom_border {\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-454d5f45 .gd-tbl-badge-rows-label,\nhtml.quarto-dark #gd-tbl-454d5f45 .gd-tbl-badge-rows-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-454d5f45 .gd-tbl-badge-rows-label {\n  background-color: #3d2a4d;\n  border-color: #3d2a4d;\n  color: #e0c0ff;\n}\nbody.quarto-dark #gd-tbl-454d5f45 .gd-tbl-badge-rows-value,\nhtml.quarto-dark #gd-tbl-454d5f45 .gd-tbl-badge-rows-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-454d5f45 .gd-tbl-badge-rows-value {\n  border-color: #3d2a4d;\n  color: #d0b0e0;\n}\nbody.quarto-dark #gd-tbl-454d5f45 .gd-tbl-badge-cols-label,\nhtml.quarto-dark #gd-tbl-454d5f45 .gd-tbl-badge-cols-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-454d5f45 .gd-tbl-badge-cols-label {\n  background-color: #2a4d2a;\n  border-color: #2a4d2a;\n  color: #b0e0b0;\n}\nbody.quarto-dark #gd-tbl-454d5f45 .gd-tbl-badge-cols-value,\nhtml.quarto-dark #gd-tbl-454d5f45 .gd-tbl-badge-cols-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-454d5f45 .gd-tbl-badge-cols-value {\n  border-color: #2a4d2a;\n  color: #a0d0a0;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"true\" data-quarto-bootstrap=\"false\">\n<colgroup>\n<col style=\"width: 35px\"/>\n<col style=\"width: 229px\"/>\n<col style=\"width: 236px\"/>\n</colgroup>\n<thead>\n<tr class=\"gt_heading\"><td class=\"gt_heading gt_title gt_font_normal\" colspan=\"3\"><div style=\"padding-top: 0; padding-bottom: 7px;\"><span class=\"gd-tbl-badge\" style=\"background-color: #0075FF; color: #FFFFFF; border: 1px solid #0075FF; margin-right: 8px;\">Polars</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-label\">Rows</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-value\">165</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-label\">Columns</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-value\">2</span></div></td></tr>\n<tr class=\"gt_col_headings\">\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\"></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"age\"><div><div class=\"gd-tbl-colname\">age</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sex\"><div><div class=\"gd-tbl-colname\">sex</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 229px;\">0.935464711892</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 236px;\">0.727079613965</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 229px;\">10.0052299319</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 236px;\">-0.272302937094</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 229px;\">17.0052299319</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 236px;\">-0.272302937094</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">3</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 229px;\">3.00522993189</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 236px;\">-0.272302937094</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">4</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 229px;\">10.1404536933</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 236px;\">-0.275789612537</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">5</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 229px;\">12.227706252</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 236px;\">-0.278411033642</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">6</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 229px;\">1.22770625199</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 236px;\">-0.278411033642</td>\n</tr>\n<tr class=\"gd-tbl-divider\">\n<td class=\"gt_row gt_right gd-tbl-rownum\">7</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 229px;\">5.29450657479</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 236px;\">-0.280979164464</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">162</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 229px;\">-2.90825326766</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 236px;\">-0.155341657484</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">163</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 229px;\">0.611217430947</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 236px;\">-0.196097246718</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">164</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 229px;\">-4.65909168016</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 236px;\">-0.171473016943</td>\n</tr>\n</tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nTaken together, martingale residuals are most useful for spotting influential subjects or a\nnonlinear covariate relationship, while Schoenfeld residuals are the basis for the proportional\nhazards test and for plotting a covariate's effect against time.\n\n## Baseline hazard and predicted survival\n\nAlthough the Cox model does not assume a shape for the baseline hazard, it can estimate one\nafter fitting. The baseline cumulative hazard, and the survival curve derived from it,\ndescribe a reference subject.\n\n::: {#16c055e5 .cell execution_count=8}\n``` {.python .cell-code}\n# Load data and build the response\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\ny = gw.Surv.right(lung[\"time\"], event=(lung[\"status\"] == 2))\n\n# Fit a Cox model with age and sex as covariates\ncox = gw.CoxPH().fit(y, lung[[\"age\", \"sex\"]])\n\n# Retrieve the Breslow cumulative baseline hazard and implied survival\ncox.baseline_hazard(format=\"polars\")\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```{=html}\n<div id=\"gd-tbl-cfeff3e7\" class=\"gd-tbl-preview\" style=\"padding-left: 0px; overflow-x: auto; overflow-y: hidden; width: 100%; max-width: 100%; margin-bottom: 1em;\">\n<style>\n@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,600;1,400&family=IBM+Plex+Sans:wght@400;600&display=swap');\n#gd-tbl-cfeff3e7 .gt_table {\n  display: table;\n  border-collapse: collapse;\n  table-layout: fixed;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 14px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n}\n#gd-tbl-cfeff3e7 .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-cfeff3e7 .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n#gd-tbl-cfeff3e7 .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n#gd-tbl-cfeff3e7 .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n#gd-tbl-cfeff3e7 .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-cfeff3e7 .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #F2F2F2;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #F2F2F2;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n#gd-tbl-cfeff3e7 .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n}\n#gd-tbl-cfeff3e7 .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #E9E9E9;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #E9E9E9;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #E9E9E9;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n#gd-tbl-cfeff3e7 .gt_left { text-align: left; }\n#gd-tbl-cfeff3e7 .gt_center { text-align: center; }\n#gd-tbl-cfeff3e7 .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n#gd-tbl-cfeff3e7 .gt_font_normal { font-weight: normal; }\n#gd-tbl-cfeff3e7 .gt_font_bold { font-weight: bold; }\n#gd-tbl-cfeff3e7 .gt_font_italic { font-style: italic; }\n#gd-tbl-cfeff3e7 .gt_striped { background-color: rgba(128,128,128,0.05); }\n#gd-tbl-cfeff3e7 .gt_from_md > :first-child { margin-top: 0; }\n#gd-tbl-cfeff3e7 .gt_from_md > :last-child { margin-bottom: 0; }\n/* Data cell font */\n#gd-tbl-cfeff3e7 .gt_table_body .gt_row {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  height: 14px;\n}\n/* Column label font */\n#gd-tbl-cfeff3e7 .gt_col_heading {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n}\n/* Row number styling */\n#gd-tbl-cfeff3e7 .gd-tbl-rownum {\n  color: gray;\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 10px;\n  border-right: 2px solid rgba(102, 153, 204, 0.5) !important;\n  text-align: right;\n  padding-right: 6px;\n  white-space: nowrap;\n}\n/* Head/tail divider */\n#gd-tbl-cfeff3e7 tr.gd-tbl-divider td,\n#gd-tbl-cfeff3e7 tr.gd-tbl-divider th {\n  border-bottom: 2px solid rgba(102, 153, 204, 0.5);\n}\n/* Missing values */\n#gd-tbl-cfeff3e7 .gd-tbl-missing {\n  color: #B22222 !important;\n  background-color: rgba(255, 193, 193, 0.35);\n}\n/* Column label sub-elements */\n#gd-tbl-cfeff3e7 .gd-tbl-colname {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-bottom: 0;\n  margin-bottom: 0;\n}\n#gd-tbl-cfeff3e7 .gd-tbl-dtype {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-top: 0;\n  margin-top: 0;\n  color: #666666;\n}\n/* Header badge styling */\n#gd-tbl-cfeff3e7 .gd-tbl-badge {\n  display: inline-block;\n  padding: 2px 10px;\n  font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, sans-serif;\n  font-size: 10px;\n  font-weight: bold;\n  text-transform: uppercase;\n  position: inherit;\n}\n#gd-tbl-cfeff3e7 .gd-tbl-badge-rows-label {\n  background-color: #eecbff;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: 5px;\n}\n#gd-tbl-cfeff3e7 .gd-tbl-badge-rows-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: -4px;\n  margin-right: 3px;\n}\n#gd-tbl-cfeff3e7 .gd-tbl-badge-cols-label {\n  background-color: #BDE7B4;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n}\n#gd-tbl-cfeff3e7 .gd-tbl-badge-cols-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n  margin-left: -4px;\n}\n/* Dark mode */\nbody.quarto-dark #gd-tbl-cfeff3e7 .gt_table,\nhtml.quarto-dark #gd-tbl-cfeff3e7 .gt_table,\n:root[data-bs-theme=\"dark\"] #gd-tbl-cfeff3e7 .gt_table {\n  background-color: #1a1a2e;\n  color: #e0e0e0;\n  border-top-color: #555;\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-cfeff3e7 .gt_heading,\nhtml.quarto-dark #gd-tbl-cfeff3e7 .gt_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-cfeff3e7 .gt_heading {\n  background-color: #1a1a2e;\n  border-bottom-color: #1a1a2e;\n}\nbody.quarto-dark #gd-tbl-cfeff3e7 .gt_title,\nhtml.quarto-dark #gd-tbl-cfeff3e7 .gt_title,\n:root[data-bs-theme=\"dark\"] #gd-tbl-cfeff3e7 .gt_title {\n  color: #e0e0e0;\n}\nbody.quarto-dark #gd-tbl-cfeff3e7 .gt_subtitle,\nhtml.quarto-dark #gd-tbl-cfeff3e7 .gt_subtitle,\n:root[data-bs-theme=\"dark\"] #gd-tbl-cfeff3e7 .gt_subtitle {\n  color: #b0b0b0;\n}\nbody.quarto-dark #gd-tbl-cfeff3e7 .gt_col_headings,\nhtml.quarto-dark #gd-tbl-cfeff3e7 .gt_col_headings,\n:root[data-bs-theme=\"dark\"] #gd-tbl-cfeff3e7 .gt_col_headings {\n  border-top-color: #444;\n  border-bottom-color: #444;\n}\nbody.quarto-dark #gd-tbl-cfeff3e7 .gt_col_heading,\nhtml.quarto-dark #gd-tbl-cfeff3e7 .gt_col_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-cfeff3e7 .gt_col_heading {\n  color: #b0b0b0;\n  background-color: #1a1a2e;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-cfeff3e7 .gt_table_body,\nhtml.quarto-dark #gd-tbl-cfeff3e7 .gt_table_body,\n:root[data-bs-theme=\"dark\"] #gd-tbl-cfeff3e7 .gt_table_body {\n  border-top-color: #444;\n}\nbody.quarto-dark #gd-tbl-cfeff3e7 .gt_table_body .gt_row,\nhtml.quarto-dark #gd-tbl-cfeff3e7 .gt_table_body .gt_row,\n:root[data-bs-theme=\"dark\"] #gd-tbl-cfeff3e7 .gt_table_body .gt_row {\n  color: #d0d0d0;\n  border-top-color: #4b4b4b;\n  border-bottom-color: #4b4b4b;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-cfeff3e7 .gd-tbl-rownum,\nhtml.quarto-dark #gd-tbl-cfeff3e7 .gd-tbl-rownum,\n:root[data-bs-theme=\"dark\"] #gd-tbl-cfeff3e7 .gd-tbl-rownum {\n  color: #888;\n  border-right-color: rgba(102, 153, 204, 0.4) !important;\n}\nbody.quarto-dark #gd-tbl-cfeff3e7 .gd-tbl-missing,\nhtml.quarto-dark #gd-tbl-cfeff3e7 .gd-tbl-missing,\n:root[data-bs-theme=\"dark\"] #gd-tbl-cfeff3e7 .gd-tbl-missing {\n  color: #ff6b6b !important;\n  background-color: rgba(60, 17, 24, 0.2);\n}\nbody.quarto-dark #gd-tbl-cfeff3e7 .gd-tbl-dtype,\nhtml.quarto-dark #gd-tbl-cfeff3e7 .gd-tbl-dtype,\n:root[data-bs-theme=\"dark\"] #gd-tbl-cfeff3e7 .gd-tbl-dtype {\n  color: #888;\n}\nbody.quarto-dark #gd-tbl-cfeff3e7 .gt_bottom_border,\nhtml.quarto-dark #gd-tbl-cfeff3e7 .gt_bottom_border,\n:root[data-bs-theme=\"dark\"] #gd-tbl-cfeff3e7 .gt_bottom_border {\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-cfeff3e7 .gd-tbl-badge-rows-label,\nhtml.quarto-dark #gd-tbl-cfeff3e7 .gd-tbl-badge-rows-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-cfeff3e7 .gd-tbl-badge-rows-label {\n  background-color: #3d2a4d;\n  border-color: #3d2a4d;\n  color: #e0c0ff;\n}\nbody.quarto-dark #gd-tbl-cfeff3e7 .gd-tbl-badge-rows-value,\nhtml.quarto-dark #gd-tbl-cfeff3e7 .gd-tbl-badge-rows-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-cfeff3e7 .gd-tbl-badge-rows-value {\n  border-color: #3d2a4d;\n  color: #d0b0e0;\n}\nbody.quarto-dark #gd-tbl-cfeff3e7 .gd-tbl-badge-cols-label,\nhtml.quarto-dark #gd-tbl-cfeff3e7 .gd-tbl-badge-cols-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-cfeff3e7 .gd-tbl-badge-cols-label {\n  background-color: #2a4d2a;\n  border-color: #2a4d2a;\n  color: #b0e0b0;\n}\nbody.quarto-dark #gd-tbl-cfeff3e7 .gd-tbl-badge-cols-value,\nhtml.quarto-dark #gd-tbl-cfeff3e7 .gd-tbl-badge-cols-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-cfeff3e7 .gd-tbl-badge-cols-value {\n  border-color: #2a4d2a;\n  color: #a0d0a0;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"true\" data-quarto-bootstrap=\"false\">\n<colgroup>\n<col style=\"width: 35px\"/>\n<col style=\"width: 105px\"/>\n<col style=\"width: 186px\"/>\n<col style=\"width: 172px\"/>\n</colgroup>\n<thead>\n<tr class=\"gt_heading\"><td class=\"gt_heading gt_title gt_font_normal\" colspan=\"4\"><div style=\"padding-top: 0; padding-bottom: 7px;\"><span class=\"gd-tbl-badge\" style=\"background-color: #0075FF; color: #FFFFFF; border: 1px solid #0075FF; margin-right: 8px;\">Polars</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-label\">Rows</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-value\">186</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-label\">Columns</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-value\">3</span></div></td></tr>\n<tr class=\"gt_col_headings\">\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\"></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"time\"><div><div class=\"gd-tbl-colname\">time</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"cumhaz\"><div><div class=\"gd-tbl-colname\">cumhaz</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"survival\"><div><div class=\"gd-tbl-colname\">survival</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 105px;\">5</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 186px;\">0.00295531012895</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 172px;\">0.997049052501</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 105px;\">11</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 186px;\">0.0119063396838</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 172px;\">0.988164260305</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 105px;\">12</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 186px;\">0.0149282203866</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 172px;\">0.985182653095</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">3</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 105px;\">13</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 186px;\">0.0210294286393</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 172px;\">0.979190147912</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">4</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 105px;\">15</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 186px;\">0.0241081722771</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 172px;\">0.976180108421</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">5</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 105px;\">26</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 186px;\">0.0272054191316</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 172px;\">0.973161315038</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">6</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 105px;\">30</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 186px;\">0.0303227228765</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 172px;\">0.970132399105</td>\n</tr>\n<tr class=\"gd-tbl-divider\">\n<td class=\"gt_row gt_right gd-tbl-rownum\">7</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 105px;\">31</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 186px;\">0.0334599993722</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 172px;\">0.967093594809</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">183</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 105px;\">965</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 186px;\">2.01305845682</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 172px;\">0.133579502131</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">184</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 105px;\">1010</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 186px;\">2.01305845682</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 172px;\">0.133579502131</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">185</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 105px;\">1022</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 186px;\">2.01305845682</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 172px;\">0.133579502131</td>\n</tr>\n</tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nMore useful in practice is predicting the survival curve for specific covariate values.\nFirst we build a small frame of the subjects we want predictions for: a 50-year-old with\n`sex` 1 and a 70-year-old with `sex` 2. Showing it confirms the covariate values before we\npredict from them.\n\n::: {#3437ebbd .cell execution_count=9}\n``` {.python .cell-code}\nimport pandas as pd\n\n# Two new subjects: a 50-year-old male and a 70-year-old female\nnewdata = pd.DataFrame({\"age\": [50, 70], \"sex\": [1, 2]})\n\n# Preview the covariate frame before predicting\nnewdata\n```\n\n::: {.cell-output .cell-output-display execution_count=9}\n```{=html}\n<div id=\"gd-tbl-b031089a\" class=\"gd-tbl-preview\" style=\"padding-left: 0px; overflow-x: auto; overflow-y: hidden; width: 100%; max-width: 100%; margin-bottom: 1em;\">\n<style>\n@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,600;1,400&family=IBM+Plex+Sans:wght@400;600&display=swap');\n#gd-tbl-b031089a .gt_table {\n  display: table;\n  border-collapse: collapse;\n  table-layout: fixed;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 14px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n}\n#gd-tbl-b031089a .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-b031089a .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n#gd-tbl-b031089a .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n#gd-tbl-b031089a .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n#gd-tbl-b031089a .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-b031089a .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #F2F2F2;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #F2F2F2;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n#gd-tbl-b031089a .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n}\n#gd-tbl-b031089a .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #E9E9E9;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #E9E9E9;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #E9E9E9;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n#gd-tbl-b031089a .gt_left { text-align: left; }\n#gd-tbl-b031089a .gt_center { text-align: center; }\n#gd-tbl-b031089a .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n#gd-tbl-b031089a .gt_font_normal { font-weight: normal; }\n#gd-tbl-b031089a .gt_font_bold { font-weight: bold; }\n#gd-tbl-b031089a .gt_font_italic { font-style: italic; }\n#gd-tbl-b031089a .gt_striped { background-color: rgba(128,128,128,0.05); }\n#gd-tbl-b031089a .gt_from_md > :first-child { margin-top: 0; }\n#gd-tbl-b031089a .gt_from_md > :last-child { margin-bottom: 0; }\n/* Data cell font */\n#gd-tbl-b031089a .gt_table_body .gt_row {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  height: 14px;\n}\n/* Column label font */\n#gd-tbl-b031089a .gt_col_heading {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n}\n/* Row number styling */\n#gd-tbl-b031089a .gd-tbl-rownum {\n  color: gray;\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 10px;\n  border-right: 2px solid rgba(102, 153, 204, 0.5) !important;\n  text-align: right;\n  padding-right: 6px;\n  white-space: nowrap;\n}\n/* Head/tail divider */\n#gd-tbl-b031089a tr.gd-tbl-divider td,\n#gd-tbl-b031089a tr.gd-tbl-divider th {\n  border-bottom: 2px solid rgba(102, 153, 204, 0.5);\n}\n/* Missing values */\n#gd-tbl-b031089a .gd-tbl-missing {\n  color: #B22222 !important;\n  background-color: rgba(255, 193, 193, 0.35);\n}\n/* Column label sub-elements */\n#gd-tbl-b031089a .gd-tbl-colname {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-bottom: 0;\n  margin-bottom: 0;\n}\n#gd-tbl-b031089a .gd-tbl-dtype {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-top: 0;\n  margin-top: 0;\n  color: #666666;\n}\n/* Header badge styling */\n#gd-tbl-b031089a .gd-tbl-badge {\n  display: inline-block;\n  padding: 2px 10px;\n  font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, sans-serif;\n  font-size: 10px;\n  font-weight: bold;\n  text-transform: uppercase;\n  position: inherit;\n}\n#gd-tbl-b031089a .gd-tbl-badge-rows-label {\n  background-color: #eecbff;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: 5px;\n}\n#gd-tbl-b031089a .gd-tbl-badge-rows-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: -4px;\n  margin-right: 3px;\n}\n#gd-tbl-b031089a .gd-tbl-badge-cols-label {\n  background-color: #BDE7B4;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n}\n#gd-tbl-b031089a .gd-tbl-badge-cols-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n  margin-left: -4px;\n}\n/* Dark mode */\nbody.quarto-dark #gd-tbl-b031089a .gt_table,\nhtml.quarto-dark #gd-tbl-b031089a .gt_table,\n:root[data-bs-theme=\"dark\"] #gd-tbl-b031089a .gt_table {\n  background-color: #1a1a2e;\n  color: #e0e0e0;\n  border-top-color: #555;\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-b031089a .gt_heading,\nhtml.quarto-dark #gd-tbl-b031089a .gt_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-b031089a .gt_heading {\n  background-color: #1a1a2e;\n  border-bottom-color: #1a1a2e;\n}\nbody.quarto-dark #gd-tbl-b031089a .gt_title,\nhtml.quarto-dark #gd-tbl-b031089a .gt_title,\n:root[data-bs-theme=\"dark\"] #gd-tbl-b031089a .gt_title {\n  color: #e0e0e0;\n}\nbody.quarto-dark #gd-tbl-b031089a .gt_subtitle,\nhtml.quarto-dark #gd-tbl-b031089a .gt_subtitle,\n:root[data-bs-theme=\"dark\"] #gd-tbl-b031089a .gt_subtitle {\n  color: #b0b0b0;\n}\nbody.quarto-dark #gd-tbl-b031089a .gt_col_headings,\nhtml.quarto-dark #gd-tbl-b031089a .gt_col_headings,\n:root[data-bs-theme=\"dark\"] #gd-tbl-b031089a .gt_col_headings {\n  border-top-color: #444;\n  border-bottom-color: #444;\n}\nbody.quarto-dark #gd-tbl-b031089a .gt_col_heading,\nhtml.quarto-dark #gd-tbl-b031089a .gt_col_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-b031089a .gt_col_heading {\n  color: #b0b0b0;\n  background-color: #1a1a2e;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-b031089a .gt_table_body,\nhtml.quarto-dark #gd-tbl-b031089a .gt_table_body,\n:root[data-bs-theme=\"dark\"] #gd-tbl-b031089a .gt_table_body {\n  border-top-color: #444;\n}\nbody.quarto-dark #gd-tbl-b031089a .gt_table_body .gt_row,\nhtml.quarto-dark #gd-tbl-b031089a .gt_table_body .gt_row,\n:root[data-bs-theme=\"dark\"] #gd-tbl-b031089a .gt_table_body .gt_row {\n  color: #d0d0d0;\n  border-top-color: #4b4b4b;\n  border-bottom-color: #4b4b4b;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-b031089a .gd-tbl-rownum,\nhtml.quarto-dark #gd-tbl-b031089a .gd-tbl-rownum,\n:root[data-bs-theme=\"dark\"] #gd-tbl-b031089a .gd-tbl-rownum {\n  color: #888;\n  border-right-color: rgba(102, 153, 204, 0.4) !important;\n}\nbody.quarto-dark #gd-tbl-b031089a .gd-tbl-missing,\nhtml.quarto-dark #gd-tbl-b031089a .gd-tbl-missing,\n:root[data-bs-theme=\"dark\"] #gd-tbl-b031089a .gd-tbl-missing {\n  color: #ff6b6b !important;\n  background-color: rgba(60, 17, 24, 0.2);\n}\nbody.quarto-dark #gd-tbl-b031089a .gd-tbl-dtype,\nhtml.quarto-dark #gd-tbl-b031089a .gd-tbl-dtype,\n:root[data-bs-theme=\"dark\"] #gd-tbl-b031089a .gd-tbl-dtype {\n  color: #888;\n}\nbody.quarto-dark #gd-tbl-b031089a .gt_bottom_border,\nhtml.quarto-dark #gd-tbl-b031089a .gt_bottom_border,\n:root[data-bs-theme=\"dark\"] #gd-tbl-b031089a .gt_bottom_border {\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-b031089a .gd-tbl-badge-rows-label,\nhtml.quarto-dark #gd-tbl-b031089a .gd-tbl-badge-rows-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-b031089a .gd-tbl-badge-rows-label {\n  background-color: #3d2a4d;\n  border-color: #3d2a4d;\n  color: #e0c0ff;\n}\nbody.quarto-dark #gd-tbl-b031089a .gd-tbl-badge-rows-value,\nhtml.quarto-dark #gd-tbl-b031089a .gd-tbl-badge-rows-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-b031089a .gd-tbl-badge-rows-value {\n  border-color: #3d2a4d;\n  color: #d0b0e0;\n}\nbody.quarto-dark #gd-tbl-b031089a .gd-tbl-badge-cols-label,\nhtml.quarto-dark #gd-tbl-b031089a .gd-tbl-badge-cols-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-b031089a .gd-tbl-badge-cols-label {\n  background-color: #2a4d2a;\n  border-color: #2a4d2a;\n  color: #b0e0b0;\n}\nbody.quarto-dark #gd-tbl-b031089a .gd-tbl-badge-cols-value,\nhtml.quarto-dark #gd-tbl-b031089a .gd-tbl-badge-cols-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-b031089a .gd-tbl-badge-cols-value {\n  border-color: #2a4d2a;\n  color: #a0d0a0;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"true\" data-quarto-bootstrap=\"false\">\n<colgroup>\n<col style=\"width: 35px\"/>\n<col style=\"width: 232px\"/>\n<col style=\"width: 232px\"/>\n</colgroup>\n<thead>\n<tr class=\"gt_heading\"><td class=\"gt_heading gt_title gt_font_normal\" colspan=\"3\"><div style=\"padding-top: 0; padding-bottom: 7px;\"><span class=\"gd-tbl-badge\" style=\"background-color: #150458; color: #FFFFFF; border: 1px solid #150458; margin-right: 8px;\">Pandas</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-label\">Rows</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-value\">2</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-label\">Columns</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-value\">2</span></div></td></tr>\n<tr class=\"gt_col_headings\">\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\"></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"age\"><div><div class=\"gd-tbl-colname\">age</div><div class=\"gd-tbl-dtype\"><em>i64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sex\"><div><div class=\"gd-tbl-colname\">sex</div><div class=\"gd-tbl-dtype\"><em>i64</em></div></div></th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 232px;\">50</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 232px;\">1</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 232px;\">70</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 232px;\">2</td>\n</tr>\n</tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nGiven that new data and a set of times, `predict` returns the estimated survival probability\nfor each subject.\n\n::: {#27e4b283 .cell execution_count=10}\n``` {.python .cell-code}\n# Predict survival probabilities at specific times for each subject in newdata\ncox.predict(newdata, type=\"survival\", times=[180, 365, 730], format=\"polars\")\n```\n\n::: {.cell-output .cell-output-display execution_count=10}\n```{=html}\n<div id=\"gd-tbl-8d35a9d3\" class=\"gd-tbl-preview\" style=\"padding-left: 0px; overflow-x: auto; overflow-y: hidden; width: 100%; max-width: 100%; margin-bottom: 1em;\">\n<style>\n@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,600;1,400&family=IBM+Plex+Sans:wght@400;600&display=swap');\n#gd-tbl-8d35a9d3 .gt_table {\n  display: table;\n  border-collapse: collapse;\n  table-layout: fixed;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 14px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n}\n#gd-tbl-8d35a9d3 .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-8d35a9d3 .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n#gd-tbl-8d35a9d3 .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n#gd-tbl-8d35a9d3 .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n#gd-tbl-8d35a9d3 .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-8d35a9d3 .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #F2F2F2;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #F2F2F2;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n#gd-tbl-8d35a9d3 .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n}\n#gd-tbl-8d35a9d3 .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #E9E9E9;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #E9E9E9;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #E9E9E9;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n#gd-tbl-8d35a9d3 .gt_left { text-align: left; }\n#gd-tbl-8d35a9d3 .gt_center { text-align: center; }\n#gd-tbl-8d35a9d3 .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n#gd-tbl-8d35a9d3 .gt_font_normal { font-weight: normal; }\n#gd-tbl-8d35a9d3 .gt_font_bold { font-weight: bold; }\n#gd-tbl-8d35a9d3 .gt_font_italic { font-style: italic; }\n#gd-tbl-8d35a9d3 .gt_striped { background-color: rgba(128,128,128,0.05); }\n#gd-tbl-8d35a9d3 .gt_from_md > :first-child { margin-top: 0; }\n#gd-tbl-8d35a9d3 .gt_from_md > :last-child { margin-bottom: 0; }\n/* Data cell font */\n#gd-tbl-8d35a9d3 .gt_table_body .gt_row {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  height: 14px;\n}\n/* Column label font */\n#gd-tbl-8d35a9d3 .gt_col_heading {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n}\n/* Row number styling */\n#gd-tbl-8d35a9d3 .gd-tbl-rownum {\n  color: gray;\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 10px;\n  border-right: 2px solid rgba(102, 153, 204, 0.5) !important;\n  text-align: right;\n  padding-right: 6px;\n  white-space: nowrap;\n}\n/* Head/tail divider */\n#gd-tbl-8d35a9d3 tr.gd-tbl-divider td,\n#gd-tbl-8d35a9d3 tr.gd-tbl-divider th {\n  border-bottom: 2px solid rgba(102, 153, 204, 0.5);\n}\n/* Missing values */\n#gd-tbl-8d35a9d3 .gd-tbl-missing {\n  color: #B22222 !important;\n  background-color: rgba(255, 193, 193, 0.35);\n}\n/* Column label sub-elements */\n#gd-tbl-8d35a9d3 .gd-tbl-colname {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-bottom: 0;\n  margin-bottom: 0;\n}\n#gd-tbl-8d35a9d3 .gd-tbl-dtype {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-top: 0;\n  margin-top: 0;\n  color: #666666;\n}\n/* Header badge styling */\n#gd-tbl-8d35a9d3 .gd-tbl-badge {\n  display: inline-block;\n  padding: 2px 10px;\n  font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, sans-serif;\n  font-size: 10px;\n  font-weight: bold;\n  text-transform: uppercase;\n  position: inherit;\n}\n#gd-tbl-8d35a9d3 .gd-tbl-badge-rows-label {\n  background-color: #eecbff;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: 5px;\n}\n#gd-tbl-8d35a9d3 .gd-tbl-badge-rows-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: -4px;\n  margin-right: 3px;\n}\n#gd-tbl-8d35a9d3 .gd-tbl-badge-cols-label {\n  background-color: #BDE7B4;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n}\n#gd-tbl-8d35a9d3 .gd-tbl-badge-cols-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n  margin-left: -4px;\n}\n/* Dark mode */\nbody.quarto-dark #gd-tbl-8d35a9d3 .gt_table,\nhtml.quarto-dark #gd-tbl-8d35a9d3 .gt_table,\n:root[data-bs-theme=\"dark\"] #gd-tbl-8d35a9d3 .gt_table {\n  background-color: #1a1a2e;\n  color: #e0e0e0;\n  border-top-color: #555;\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-8d35a9d3 .gt_heading,\nhtml.quarto-dark #gd-tbl-8d35a9d3 .gt_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-8d35a9d3 .gt_heading {\n  background-color: #1a1a2e;\n  border-bottom-color: #1a1a2e;\n}\nbody.quarto-dark #gd-tbl-8d35a9d3 .gt_title,\nhtml.quarto-dark #gd-tbl-8d35a9d3 .gt_title,\n:root[data-bs-theme=\"dark\"] #gd-tbl-8d35a9d3 .gt_title {\n  color: #e0e0e0;\n}\nbody.quarto-dark #gd-tbl-8d35a9d3 .gt_subtitle,\nhtml.quarto-dark #gd-tbl-8d35a9d3 .gt_subtitle,\n:root[data-bs-theme=\"dark\"] #gd-tbl-8d35a9d3 .gt_subtitle {\n  color: #b0b0b0;\n}\nbody.quarto-dark #gd-tbl-8d35a9d3 .gt_col_headings,\nhtml.quarto-dark #gd-tbl-8d35a9d3 .gt_col_headings,\n:root[data-bs-theme=\"dark\"] #gd-tbl-8d35a9d3 .gt_col_headings {\n  border-top-color: #444;\n  border-bottom-color: #444;\n}\nbody.quarto-dark #gd-tbl-8d35a9d3 .gt_col_heading,\nhtml.quarto-dark #gd-tbl-8d35a9d3 .gt_col_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-8d35a9d3 .gt_col_heading {\n  color: #b0b0b0;\n  background-color: #1a1a2e;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-8d35a9d3 .gt_table_body,\nhtml.quarto-dark #gd-tbl-8d35a9d3 .gt_table_body,\n:root[data-bs-theme=\"dark\"] #gd-tbl-8d35a9d3 .gt_table_body {\n  border-top-color: #444;\n}\nbody.quarto-dark #gd-tbl-8d35a9d3 .gt_table_body .gt_row,\nhtml.quarto-dark #gd-tbl-8d35a9d3 .gt_table_body .gt_row,\n:root[data-bs-theme=\"dark\"] #gd-tbl-8d35a9d3 .gt_table_body .gt_row {\n  color: #d0d0d0;\n  border-top-color: #4b4b4b;\n  border-bottom-color: #4b4b4b;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-8d35a9d3 .gd-tbl-rownum,\nhtml.quarto-dark #gd-tbl-8d35a9d3 .gd-tbl-rownum,\n:root[data-bs-theme=\"dark\"] #gd-tbl-8d35a9d3 .gd-tbl-rownum {\n  color: #888;\n  border-right-color: rgba(102, 153, 204, 0.4) !important;\n}\nbody.quarto-dark #gd-tbl-8d35a9d3 .gd-tbl-missing,\nhtml.quarto-dark #gd-tbl-8d35a9d3 .gd-tbl-missing,\n:root[data-bs-theme=\"dark\"] #gd-tbl-8d35a9d3 .gd-tbl-missing {\n  color: #ff6b6b !important;\n  background-color: rgba(60, 17, 24, 0.2);\n}\nbody.quarto-dark #gd-tbl-8d35a9d3 .gd-tbl-dtype,\nhtml.quarto-dark #gd-tbl-8d35a9d3 .gd-tbl-dtype,\n:root[data-bs-theme=\"dark\"] #gd-tbl-8d35a9d3 .gd-tbl-dtype {\n  color: #888;\n}\nbody.quarto-dark #gd-tbl-8d35a9d3 .gt_bottom_border,\nhtml.quarto-dark #gd-tbl-8d35a9d3 .gt_bottom_border,\n:root[data-bs-theme=\"dark\"] #gd-tbl-8d35a9d3 .gt_bottom_border {\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-8d35a9d3 .gd-tbl-badge-rows-label,\nhtml.quarto-dark #gd-tbl-8d35a9d3 .gd-tbl-badge-rows-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-8d35a9d3 .gd-tbl-badge-rows-label {\n  background-color: #3d2a4d;\n  border-color: #3d2a4d;\n  color: #e0c0ff;\n}\nbody.quarto-dark #gd-tbl-8d35a9d3 .gd-tbl-badge-rows-value,\nhtml.quarto-dark #gd-tbl-8d35a9d3 .gd-tbl-badge-rows-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-8d35a9d3 .gd-tbl-badge-rows-value {\n  border-color: #3d2a4d;\n  color: #d0b0e0;\n}\nbody.quarto-dark #gd-tbl-8d35a9d3 .gd-tbl-badge-cols-label,\nhtml.quarto-dark #gd-tbl-8d35a9d3 .gd-tbl-badge-cols-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-8d35a9d3 .gd-tbl-badge-cols-label {\n  background-color: #2a4d2a;\n  border-color: #2a4d2a;\n  color: #b0e0b0;\n}\nbody.quarto-dark #gd-tbl-8d35a9d3 .gd-tbl-badge-cols-value,\nhtml.quarto-dark #gd-tbl-8d35a9d3 .gd-tbl-badge-cols-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-8d35a9d3 .gd-tbl-badge-cols-value {\n  border-color: #2a4d2a;\n  color: #a0d0a0;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"true\" data-quarto-bootstrap=\"false\">\n<colgroup>\n<col style=\"width: 35px\"/>\n<col style=\"width: 110px\"/>\n<col style=\"width: 177px\"/>\n<col style=\"width: 177px\"/>\n</colgroup>\n<thead>\n<tr class=\"gt_heading\"><td class=\"gt_heading gt_title gt_font_normal\" colspan=\"4\"><div style=\"padding-top: 0; padding-bottom: 7px;\"><span class=\"gd-tbl-badge\" style=\"background-color: #0075FF; color: #FFFFFF; border: 1px solid #0075FF; margin-right: 8px;\">Polars</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-label\">Rows</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-value\">3</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-label\">Columns</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-value\">3</span></div></td></tr>\n<tr class=\"gt_col_headings\">\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\"></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"time\"><div><div class=\"gd-tbl-colname\">time</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"subject_1\"><div><div class=\"gd-tbl-colname\">subject_1</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"subject_2\"><div><div class=\"gd-tbl-colname\">subject_2</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 110px;\">180</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 177px;\">0.7297626204</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 177px;\">0.767074757103</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 110px;\">365</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 177px;\">0.417781082587</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 177px;\">0.479674113531</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 110px;\">730</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 177px;\">0.119648956441</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 177px;\">0.167440538104</td>\n</tr>\n</tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nEach column is a subject from `newdata`, and each row is a requested time. The `type=\"lp\"`\nand `type=\"risk\"` options instead return the linear predictor and the relative risk.\n\n### Confidence bands and conditional survival\n\nPass `ci=True` to add a pointwise confidence band around each predicted curve. Every subject\nthen gains `_lower` and `_upper` columns, built from the standard error of the cumulative\nhazard and matching R's `survfit` (which combines baseline-hazard and coefficient\nuncertainty).\n\n::: {#859f796c .cell execution_count=11}\n``` {.python .cell-code}\n# Add pointwise 95% confidence bands; each subject gains _lower and _upper columns\ncox.predict(newdata, type=\"survival\", times=[180, 365, 730], ci=True, format=\"polars\")\n```\n\n::: {.cell-output .cell-output-display execution_count=11}\n```{=html}\n<div id=\"gd-tbl-c57d3e50\" class=\"gd-tbl-preview\" style=\"padding-left: 0px; overflow-x: auto; overflow-y: hidden; width: 100%; max-width: 100%; margin-bottom: 1em;\">\n<style>\n@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,600;1,400&family=IBM+Plex+Sans:wght@400;600&display=swap');\n#gd-tbl-c57d3e50 .gt_table {\n  display: table;\n  border-collapse: collapse;\n  table-layout: fixed;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 14px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n}\n#gd-tbl-c57d3e50 .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-c57d3e50 .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n#gd-tbl-c57d3e50 .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n#gd-tbl-c57d3e50 .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n#gd-tbl-c57d3e50 .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-c57d3e50 .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #F2F2F2;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #F2F2F2;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n#gd-tbl-c57d3e50 .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n}\n#gd-tbl-c57d3e50 .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #E9E9E9;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #E9E9E9;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #E9E9E9;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n#gd-tbl-c57d3e50 .gt_left { text-align: left; }\n#gd-tbl-c57d3e50 .gt_center { text-align: center; }\n#gd-tbl-c57d3e50 .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n#gd-tbl-c57d3e50 .gt_font_normal { font-weight: normal; }\n#gd-tbl-c57d3e50 .gt_font_bold { font-weight: bold; }\n#gd-tbl-c57d3e50 .gt_font_italic { font-style: italic; }\n#gd-tbl-c57d3e50 .gt_striped { background-color: rgba(128,128,128,0.05); }\n#gd-tbl-c57d3e50 .gt_from_md > :first-child { margin-top: 0; }\n#gd-tbl-c57d3e50 .gt_from_md > :last-child { margin-bottom: 0; }\n/* Data cell font */\n#gd-tbl-c57d3e50 .gt_table_body .gt_row {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  height: 14px;\n}\n/* Column label font */\n#gd-tbl-c57d3e50 .gt_col_heading {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n}\n/* Row number styling */\n#gd-tbl-c57d3e50 .gd-tbl-rownum {\n  color: gray;\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 10px;\n  border-right: 2px solid rgba(102, 153, 204, 0.5) !important;\n  text-align: right;\n  padding-right: 6px;\n  white-space: nowrap;\n}\n/* Head/tail divider */\n#gd-tbl-c57d3e50 tr.gd-tbl-divider td,\n#gd-tbl-c57d3e50 tr.gd-tbl-divider th {\n  border-bottom: 2px solid rgba(102, 153, 204, 0.5);\n}\n/* Missing values */\n#gd-tbl-c57d3e50 .gd-tbl-missing {\n  color: #B22222 !important;\n  background-color: rgba(255, 193, 193, 0.35);\n}\n/* Column label sub-elements */\n#gd-tbl-c57d3e50 .gd-tbl-colname {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-bottom: 0;\n  margin-bottom: 0;\n}\n#gd-tbl-c57d3e50 .gd-tbl-dtype {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-top: 0;\n  margin-top: 0;\n  color: #666666;\n}\n/* Header badge styling */\n#gd-tbl-c57d3e50 .gd-tbl-badge {\n  display: inline-block;\n  padding: 2px 10px;\n  font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, sans-serif;\n  font-size: 10px;\n  font-weight: bold;\n  text-transform: uppercase;\n  position: inherit;\n}\n#gd-tbl-c57d3e50 .gd-tbl-badge-rows-label {\n  background-color: #eecbff;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: 5px;\n}\n#gd-tbl-c57d3e50 .gd-tbl-badge-rows-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: -4px;\n  margin-right: 3px;\n}\n#gd-tbl-c57d3e50 .gd-tbl-badge-cols-label {\n  background-color: #BDE7B4;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n}\n#gd-tbl-c57d3e50 .gd-tbl-badge-cols-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n  margin-left: -4px;\n}\n/* Dark mode */\nbody.quarto-dark #gd-tbl-c57d3e50 .gt_table,\nhtml.quarto-dark #gd-tbl-c57d3e50 .gt_table,\n:root[data-bs-theme=\"dark\"] #gd-tbl-c57d3e50 .gt_table {\n  background-color: #1a1a2e;\n  color: #e0e0e0;\n  border-top-color: #555;\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-c57d3e50 .gt_heading,\nhtml.quarto-dark #gd-tbl-c57d3e50 .gt_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-c57d3e50 .gt_heading {\n  background-color: #1a1a2e;\n  border-bottom-color: #1a1a2e;\n}\nbody.quarto-dark #gd-tbl-c57d3e50 .gt_title,\nhtml.quarto-dark #gd-tbl-c57d3e50 .gt_title,\n:root[data-bs-theme=\"dark\"] #gd-tbl-c57d3e50 .gt_title {\n  color: #e0e0e0;\n}\nbody.quarto-dark #gd-tbl-c57d3e50 .gt_subtitle,\nhtml.quarto-dark #gd-tbl-c57d3e50 .gt_subtitle,\n:root[data-bs-theme=\"dark\"] #gd-tbl-c57d3e50 .gt_subtitle {\n  color: #b0b0b0;\n}\nbody.quarto-dark #gd-tbl-c57d3e50 .gt_col_headings,\nhtml.quarto-dark #gd-tbl-c57d3e50 .gt_col_headings,\n:root[data-bs-theme=\"dark\"] #gd-tbl-c57d3e50 .gt_col_headings {\n  border-top-color: #444;\n  border-bottom-color: #444;\n}\nbody.quarto-dark #gd-tbl-c57d3e50 .gt_col_heading,\nhtml.quarto-dark #gd-tbl-c57d3e50 .gt_col_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-c57d3e50 .gt_col_heading {\n  color: #b0b0b0;\n  background-color: #1a1a2e;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-c57d3e50 .gt_table_body,\nhtml.quarto-dark #gd-tbl-c57d3e50 .gt_table_body,\n:root[data-bs-theme=\"dark\"] #gd-tbl-c57d3e50 .gt_table_body {\n  border-top-color: #444;\n}\nbody.quarto-dark #gd-tbl-c57d3e50 .gt_table_body .gt_row,\nhtml.quarto-dark #gd-tbl-c57d3e50 .gt_table_body .gt_row,\n:root[data-bs-theme=\"dark\"] #gd-tbl-c57d3e50 .gt_table_body .gt_row {\n  color: #d0d0d0;\n  border-top-color: #4b4b4b;\n  border-bottom-color: #4b4b4b;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-c57d3e50 .gd-tbl-rownum,\nhtml.quarto-dark #gd-tbl-c57d3e50 .gd-tbl-rownum,\n:root[data-bs-theme=\"dark\"] #gd-tbl-c57d3e50 .gd-tbl-rownum {\n  color: #888;\n  border-right-color: rgba(102, 153, 204, 0.4) !important;\n}\nbody.quarto-dark #gd-tbl-c57d3e50 .gd-tbl-missing,\nhtml.quarto-dark #gd-tbl-c57d3e50 .gd-tbl-missing,\n:root[data-bs-theme=\"dark\"] #gd-tbl-c57d3e50 .gd-tbl-missing {\n  color: #ff6b6b !important;\n  background-color: rgba(60, 17, 24, 0.2);\n}\nbody.quarto-dark #gd-tbl-c57d3e50 .gd-tbl-dtype,\nhtml.quarto-dark #gd-tbl-c57d3e50 .gd-tbl-dtype,\n:root[data-bs-theme=\"dark\"] #gd-tbl-c57d3e50 .gd-tbl-dtype {\n  color: #888;\n}\nbody.quarto-dark #gd-tbl-c57d3e50 .gt_bottom_border,\nhtml.quarto-dark #gd-tbl-c57d3e50 .gt_bottom_border,\n:root[data-bs-theme=\"dark\"] #gd-tbl-c57d3e50 .gt_bottom_border {\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-c57d3e50 .gd-tbl-badge-rows-label,\nhtml.quarto-dark #gd-tbl-c57d3e50 .gd-tbl-badge-rows-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-c57d3e50 .gd-tbl-badge-rows-label {\n  background-color: #3d2a4d;\n  border-color: #3d2a4d;\n  color: #e0c0ff;\n}\nbody.quarto-dark #gd-tbl-c57d3e50 .gd-tbl-badge-rows-value,\nhtml.quarto-dark #gd-tbl-c57d3e50 .gd-tbl-badge-rows-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-c57d3e50 .gd-tbl-badge-rows-value {\n  border-color: #3d2a4d;\n  color: #d0b0e0;\n}\nbody.quarto-dark #gd-tbl-c57d3e50 .gd-tbl-badge-cols-label,\nhtml.quarto-dark #gd-tbl-c57d3e50 .gd-tbl-badge-cols-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-c57d3e50 .gd-tbl-badge-cols-label {\n  background-color: #2a4d2a;\n  border-color: #2a4d2a;\n  color: #b0e0b0;\n}\nbody.quarto-dark #gd-tbl-c57d3e50 .gd-tbl-badge-cols-value,\nhtml.quarto-dark #gd-tbl-c57d3e50 .gd-tbl-badge-cols-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-c57d3e50 .gd-tbl-badge-cols-value {\n  border-color: #2a4d2a;\n  color: #a0d0a0;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"true\" data-quarto-bootstrap=\"false\">\n<colgroup>\n<col style=\"width: 35px\"/>\n<col style=\"width: 50px\"/>\n<col style=\"width: 117px\"/>\n<col style=\"width: 133px\"/>\n<col style=\"width: 133px\"/>\n<col style=\"width: 117px\"/>\n<col style=\"width: 133px\"/>\n<col style=\"width: 133px\"/>\n</colgroup>\n<thead>\n<tr class=\"gt_heading\"><td class=\"gt_heading gt_title gt_font_normal\" colspan=\"8\"><div style=\"padding-top: 0; padding-bottom: 7px;\"><span class=\"gd-tbl-badge\" style=\"background-color: #0075FF; color: #FFFFFF; border: 1px solid #0075FF; margin-right: 8px;\">Polars</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-label\">Rows</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-value\">3</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-label\">Columns</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-value\">7</span></div></td></tr>\n<tr class=\"gt_col_headings\">\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\"></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"time\"><div><div class=\"gd-tbl-colname\">time</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"subject_1\"><div><div class=\"gd-tbl-colname\">subject_1</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"subject_1_lower\"><div><div class=\"gd-tbl-colname\">subject_1_lower</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"subject_1_upper\"><div><div class=\"gd-tbl-colname\">subject_1_upper</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"subject_2\"><div><div class=\"gd-tbl-colname\">subject_2</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"subject_2_lower\"><div><div class=\"gd-tbl-colname\">subject_2_lower</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"subject_2_upper\"><div><div class=\"gd-tbl-colname\">subject_2_upper</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 50px;\">180</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.7297626204</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 133px;\">0.65075626184</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 133px;\">0.818360903092</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.767074757103</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 133px;\">0.696725970364</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 133px;\">0.844526697744</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 50px;\">365</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.417781082587</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 133px;\">0.312492619485</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 133px;\">0.558544497004</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.479674113531</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 133px;\">0.379184415457</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 133px;\">0.6067951261</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 50px;\">730</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.119648956441</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 133px;\">0.0574578159532</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 133px;\">0.249154489079</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.167440538104</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 133px;\">0.0910524175713</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 133px;\">0.307914216319</td>\n</tr>\n</tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nYou can also predict conditional on a subject having already survived some time, which is\nuseful for updating a prognosis partway through follow-up. With `conditional_after=180`, the\nreturned probabilities are $P(T > t \\mid T > 180) = S(t) / S(180)$.\n\n::: {#a269e7c5 .cell execution_count=12}\n``` {.python .cell-code}\n# Predict P(T > t | T > 180): survival conditional on being alive at day 180\ncox.predict(newdata, type=\"survival\", times=[365, 730], conditional_after=180, format=\"polars\")\n```\n\n::: {.cell-output .cell-output-display execution_count=12}\n```{=html}\n<div id=\"gd-tbl-e154b40a\" class=\"gd-tbl-preview\" style=\"padding-left: 0px; overflow-x: auto; overflow-y: hidden; width: 100%; max-width: 100%; margin-bottom: 1em;\">\n<style>\n@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,600;1,400&family=IBM+Plex+Sans:wght@400;600&display=swap');\n#gd-tbl-e154b40a .gt_table {\n  display: table;\n  border-collapse: collapse;\n  table-layout: fixed;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 14px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n}\n#gd-tbl-e154b40a .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-e154b40a .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n#gd-tbl-e154b40a .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n#gd-tbl-e154b40a .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n#gd-tbl-e154b40a .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-e154b40a .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #F2F2F2;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #F2F2F2;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n#gd-tbl-e154b40a .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n}\n#gd-tbl-e154b40a .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #E9E9E9;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #E9E9E9;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #E9E9E9;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n#gd-tbl-e154b40a .gt_left { text-align: left; }\n#gd-tbl-e154b40a .gt_center { text-align: center; }\n#gd-tbl-e154b40a .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n#gd-tbl-e154b40a .gt_font_normal { font-weight: normal; }\n#gd-tbl-e154b40a .gt_font_bold { font-weight: bold; }\n#gd-tbl-e154b40a .gt_font_italic { font-style: italic; }\n#gd-tbl-e154b40a .gt_striped { background-color: rgba(128,128,128,0.05); }\n#gd-tbl-e154b40a .gt_from_md > :first-child { margin-top: 0; }\n#gd-tbl-e154b40a .gt_from_md > :last-child { margin-bottom: 0; }\n/* Data cell font */\n#gd-tbl-e154b40a .gt_table_body .gt_row {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  height: 14px;\n}\n/* Column label font */\n#gd-tbl-e154b40a .gt_col_heading {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n}\n/* Row number styling */\n#gd-tbl-e154b40a .gd-tbl-rownum {\n  color: gray;\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 10px;\n  border-right: 2px solid rgba(102, 153, 204, 0.5) !important;\n  text-align: right;\n  padding-right: 6px;\n  white-space: nowrap;\n}\n/* Head/tail divider */\n#gd-tbl-e154b40a tr.gd-tbl-divider td,\n#gd-tbl-e154b40a tr.gd-tbl-divider th {\n  border-bottom: 2px solid rgba(102, 153, 204, 0.5);\n}\n/* Missing values */\n#gd-tbl-e154b40a .gd-tbl-missing {\n  color: #B22222 !important;\n  background-color: rgba(255, 193, 193, 0.35);\n}\n/* Column label sub-elements */\n#gd-tbl-e154b40a .gd-tbl-colname {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-bottom: 0;\n  margin-bottom: 0;\n}\n#gd-tbl-e154b40a .gd-tbl-dtype {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-top: 0;\n  margin-top: 0;\n  color: #666666;\n}\n/* Header badge styling */\n#gd-tbl-e154b40a .gd-tbl-badge {\n  display: inline-block;\n  padding: 2px 10px;\n  font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, sans-serif;\n  font-size: 10px;\n  font-weight: bold;\n  text-transform: uppercase;\n  position: inherit;\n}\n#gd-tbl-e154b40a .gd-tbl-badge-rows-label {\n  background-color: #eecbff;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: 5px;\n}\n#gd-tbl-e154b40a .gd-tbl-badge-rows-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: -4px;\n  margin-right: 3px;\n}\n#gd-tbl-e154b40a .gd-tbl-badge-cols-label {\n  background-color: #BDE7B4;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n}\n#gd-tbl-e154b40a .gd-tbl-badge-cols-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n  margin-left: -4px;\n}\n/* Dark mode */\nbody.quarto-dark #gd-tbl-e154b40a .gt_table,\nhtml.quarto-dark #gd-tbl-e154b40a .gt_table,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e154b40a .gt_table {\n  background-color: #1a1a2e;\n  color: #e0e0e0;\n  border-top-color: #555;\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-e154b40a .gt_heading,\nhtml.quarto-dark #gd-tbl-e154b40a .gt_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e154b40a .gt_heading {\n  background-color: #1a1a2e;\n  border-bottom-color: #1a1a2e;\n}\nbody.quarto-dark #gd-tbl-e154b40a .gt_title,\nhtml.quarto-dark #gd-tbl-e154b40a .gt_title,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e154b40a .gt_title {\n  color: #e0e0e0;\n}\nbody.quarto-dark #gd-tbl-e154b40a .gt_subtitle,\nhtml.quarto-dark #gd-tbl-e154b40a .gt_subtitle,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e154b40a .gt_subtitle {\n  color: #b0b0b0;\n}\nbody.quarto-dark #gd-tbl-e154b40a .gt_col_headings,\nhtml.quarto-dark #gd-tbl-e154b40a .gt_col_headings,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e154b40a .gt_col_headings {\n  border-top-color: #444;\n  border-bottom-color: #444;\n}\nbody.quarto-dark #gd-tbl-e154b40a .gt_col_heading,\nhtml.quarto-dark #gd-tbl-e154b40a .gt_col_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e154b40a .gt_col_heading {\n  color: #b0b0b0;\n  background-color: #1a1a2e;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-e154b40a .gt_table_body,\nhtml.quarto-dark #gd-tbl-e154b40a .gt_table_body,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e154b40a .gt_table_body {\n  border-top-color: #444;\n}\nbody.quarto-dark #gd-tbl-e154b40a .gt_table_body .gt_row,\nhtml.quarto-dark #gd-tbl-e154b40a .gt_table_body .gt_row,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e154b40a .gt_table_body .gt_row {\n  color: #d0d0d0;\n  border-top-color: #4b4b4b;\n  border-bottom-color: #4b4b4b;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-e154b40a .gd-tbl-rownum,\nhtml.quarto-dark #gd-tbl-e154b40a .gd-tbl-rownum,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e154b40a .gd-tbl-rownum {\n  color: #888;\n  border-right-color: rgba(102, 153, 204, 0.4) !important;\n}\nbody.quarto-dark #gd-tbl-e154b40a .gd-tbl-missing,\nhtml.quarto-dark #gd-tbl-e154b40a .gd-tbl-missing,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e154b40a .gd-tbl-missing {\n  color: #ff6b6b !important;\n  background-color: rgba(60, 17, 24, 0.2);\n}\nbody.quarto-dark #gd-tbl-e154b40a .gd-tbl-dtype,\nhtml.quarto-dark #gd-tbl-e154b40a .gd-tbl-dtype,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e154b40a .gd-tbl-dtype {\n  color: #888;\n}\nbody.quarto-dark #gd-tbl-e154b40a .gt_bottom_border,\nhtml.quarto-dark #gd-tbl-e154b40a .gt_bottom_border,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e154b40a .gt_bottom_border {\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-e154b40a .gd-tbl-badge-rows-label,\nhtml.quarto-dark #gd-tbl-e154b40a .gd-tbl-badge-rows-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e154b40a .gd-tbl-badge-rows-label {\n  background-color: #3d2a4d;\n  border-color: #3d2a4d;\n  color: #e0c0ff;\n}\nbody.quarto-dark #gd-tbl-e154b40a .gd-tbl-badge-rows-value,\nhtml.quarto-dark #gd-tbl-e154b40a .gd-tbl-badge-rows-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e154b40a .gd-tbl-badge-rows-value {\n  border-color: #3d2a4d;\n  color: #d0b0e0;\n}\nbody.quarto-dark #gd-tbl-e154b40a .gd-tbl-badge-cols-label,\nhtml.quarto-dark #gd-tbl-e154b40a .gd-tbl-badge-cols-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e154b40a .gd-tbl-badge-cols-label {\n  background-color: #2a4d2a;\n  border-color: #2a4d2a;\n  color: #b0e0b0;\n}\nbody.quarto-dark #gd-tbl-e154b40a .gd-tbl-badge-cols-value,\nhtml.quarto-dark #gd-tbl-e154b40a .gd-tbl-badge-cols-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e154b40a .gd-tbl-badge-cols-value {\n  border-color: #2a4d2a;\n  color: #a0d0a0;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"true\" data-quarto-bootstrap=\"false\">\n<colgroup>\n<col style=\"width: 35px\"/>\n<col style=\"width: 110px\"/>\n<col style=\"width: 177px\"/>\n<col style=\"width: 177px\"/>\n</colgroup>\n<thead>\n<tr class=\"gt_heading\"><td class=\"gt_heading gt_title gt_font_normal\" colspan=\"4\"><div style=\"padding-top: 0; padding-bottom: 7px;\"><span class=\"gd-tbl-badge\" style=\"background-color: #0075FF; color: #FFFFFF; border: 1px solid #0075FF; margin-right: 8px;\">Polars</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-label\">Rows</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-value\">2</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-label\">Columns</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-value\">3</span></div></td></tr>\n<tr class=\"gt_col_headings\">\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\"></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"time\"><div><div class=\"gd-tbl-colname\">time</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"subject_1\"><div><div class=\"gd-tbl-colname\">subject_1</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"subject_2\"><div><div class=\"gd-tbl-colname\">subject_2</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 110px;\">365</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 177px;\">0.572489013425</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 177px;\">0.625329029654</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 110px;\">730</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 177px;\">0.163955994862</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 177px;\">0.218284510803</td>\n</tr>\n</tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nConfidence bands quantify the uncertainty in a predicted survival curve, and conditional\nsurvival gives an updated estimate that is directly meaningful for a patient already some\ntime into follow-up. Both are straightforward extensions of the base `predict()` call.\n\n## Stratification\n\nSometimes a variable violates the proportional hazards assumption but is not of direct\ninterest, such as enrolling hospital. Stratification lets each level of that variable have\nits own baseline hazard while sharing the coefficients of the covariates you do care about.\nYou pass the stratifying variable to `strata`. Here we stratify by `sex` while keeping `age`\nand `ph.ecog` as covariates.\n\n::: {#81451418 .cell execution_count=13}\n``` {.python .cell-code}\n# Load data and build the response\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\ny = gw.Surv.right(lung[\"time\"], event=(lung[\"status\"] == 2))\n\n# Fit a stratified model: separate baselines per sex, shared age and ECOG coefficients\nstratified = gw.CoxPH().fit(y, lung[[\"age\", \"ph.ecog\"]], strata=lung[\"sex\"])\n```\n:::\n\n\nAs with any fitted model, we can print `stratified` for a summary \n\n::: {#06fc26fa .cell execution_count=14}\n``` {.python .cell-code}\nstratified\n```\n\n::: {.cell-output .cell-output-display execution_count=14}\n```\nCoxPH (Cox proportional hazards model, ties='efron')\n\n            coef  exp(coef)  se(coef)      z          p\nage      0.01057      1.011  0.009241  1.143     0.2529\nph.ecog   0.4624      1.588    0.1148  4.029  5.591e-05\n\nn = 227, events = 164\nLikelihood ratio test = 19.48 on 2 df, p = 5.895e-05\n```\n:::\n:::\n\n\nor read its coefficient table as a DataFrame with `to_frame()`.\n\n::: {#b60063b6 .cell execution_count=15}\n``` {.python .cell-code}\n# Export the coefficient table; sex does not appear (absorbed into the baselines)\nstratified.to_frame(format=\"polars\")\n```\n\n::: {.cell-output .cell-output-display execution_count=15}\n```{=html}\n<div id=\"gd-tbl-bac5ffa9\" class=\"gd-tbl-preview\" style=\"padding-left: 0px; overflow-x: auto; overflow-y: hidden; width: 100%; max-width: 100%; margin-bottom: 1em;\">\n<style>\n@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,600;1,400&family=IBM+Plex+Sans:wght@400;600&display=swap');\n#gd-tbl-bac5ffa9 .gt_table {\n  display: table;\n  border-collapse: collapse;\n  table-layout: fixed;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 14px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n}\n#gd-tbl-bac5ffa9 .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-bac5ffa9 .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n#gd-tbl-bac5ffa9 .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n#gd-tbl-bac5ffa9 .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n#gd-tbl-bac5ffa9 .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-bac5ffa9 .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #F2F2F2;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #F2F2F2;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n#gd-tbl-bac5ffa9 .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n}\n#gd-tbl-bac5ffa9 .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #E9E9E9;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #E9E9E9;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #E9E9E9;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n#gd-tbl-bac5ffa9 .gt_left { text-align: left; }\n#gd-tbl-bac5ffa9 .gt_center { text-align: center; }\n#gd-tbl-bac5ffa9 .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n#gd-tbl-bac5ffa9 .gt_font_normal { font-weight: normal; }\n#gd-tbl-bac5ffa9 .gt_font_bold { font-weight: bold; }\n#gd-tbl-bac5ffa9 .gt_font_italic { font-style: italic; }\n#gd-tbl-bac5ffa9 .gt_striped { background-color: rgba(128,128,128,0.05); }\n#gd-tbl-bac5ffa9 .gt_from_md > :first-child { margin-top: 0; }\n#gd-tbl-bac5ffa9 .gt_from_md > :last-child { margin-bottom: 0; }\n/* Data cell font */\n#gd-tbl-bac5ffa9 .gt_table_body .gt_row {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  height: 14px;\n}\n/* Column label font */\n#gd-tbl-bac5ffa9 .gt_col_heading {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n}\n/* Row number styling */\n#gd-tbl-bac5ffa9 .gd-tbl-rownum {\n  color: gray;\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 10px;\n  border-right: 2px solid rgba(102, 153, 204, 0.5) !important;\n  text-align: right;\n  padding-right: 6px;\n  white-space: nowrap;\n}\n/* Head/tail divider */\n#gd-tbl-bac5ffa9 tr.gd-tbl-divider td,\n#gd-tbl-bac5ffa9 tr.gd-tbl-divider th {\n  border-bottom: 2px solid rgba(102, 153, 204, 0.5);\n}\n/* Missing values */\n#gd-tbl-bac5ffa9 .gd-tbl-missing {\n  color: #B22222 !important;\n  background-color: rgba(255, 193, 193, 0.35);\n}\n/* Column label sub-elements */\n#gd-tbl-bac5ffa9 .gd-tbl-colname {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-bottom: 0;\n  margin-bottom: 0;\n}\n#gd-tbl-bac5ffa9 .gd-tbl-dtype {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-top: 0;\n  margin-top: 0;\n  color: #666666;\n}\n/* Header badge styling */\n#gd-tbl-bac5ffa9 .gd-tbl-badge {\n  display: inline-block;\n  padding: 2px 10px;\n  font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, sans-serif;\n  font-size: 10px;\n  font-weight: bold;\n  text-transform: uppercase;\n  position: inherit;\n}\n#gd-tbl-bac5ffa9 .gd-tbl-badge-rows-label {\n  background-color: #eecbff;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: 5px;\n}\n#gd-tbl-bac5ffa9 .gd-tbl-badge-rows-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: -4px;\n  margin-right: 3px;\n}\n#gd-tbl-bac5ffa9 .gd-tbl-badge-cols-label {\n  background-color: #BDE7B4;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n}\n#gd-tbl-bac5ffa9 .gd-tbl-badge-cols-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n  margin-left: -4px;\n}\n/* Dark mode */\nbody.quarto-dark #gd-tbl-bac5ffa9 .gt_table,\nhtml.quarto-dark #gd-tbl-bac5ffa9 .gt_table,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bac5ffa9 .gt_table {\n  background-color: #1a1a2e;\n  color: #e0e0e0;\n  border-top-color: #555;\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-bac5ffa9 .gt_heading,\nhtml.quarto-dark #gd-tbl-bac5ffa9 .gt_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bac5ffa9 .gt_heading {\n  background-color: #1a1a2e;\n  border-bottom-color: #1a1a2e;\n}\nbody.quarto-dark #gd-tbl-bac5ffa9 .gt_title,\nhtml.quarto-dark #gd-tbl-bac5ffa9 .gt_title,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bac5ffa9 .gt_title {\n  color: #e0e0e0;\n}\nbody.quarto-dark #gd-tbl-bac5ffa9 .gt_subtitle,\nhtml.quarto-dark #gd-tbl-bac5ffa9 .gt_subtitle,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bac5ffa9 .gt_subtitle {\n  color: #b0b0b0;\n}\nbody.quarto-dark #gd-tbl-bac5ffa9 .gt_col_headings,\nhtml.quarto-dark #gd-tbl-bac5ffa9 .gt_col_headings,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bac5ffa9 .gt_col_headings {\n  border-top-color: #444;\n  border-bottom-color: #444;\n}\nbody.quarto-dark #gd-tbl-bac5ffa9 .gt_col_heading,\nhtml.quarto-dark #gd-tbl-bac5ffa9 .gt_col_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bac5ffa9 .gt_col_heading {\n  color: #b0b0b0;\n  background-color: #1a1a2e;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-bac5ffa9 .gt_table_body,\nhtml.quarto-dark #gd-tbl-bac5ffa9 .gt_table_body,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bac5ffa9 .gt_table_body {\n  border-top-color: #444;\n}\nbody.quarto-dark #gd-tbl-bac5ffa9 .gt_table_body .gt_row,\nhtml.quarto-dark #gd-tbl-bac5ffa9 .gt_table_body .gt_row,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bac5ffa9 .gt_table_body .gt_row {\n  color: #d0d0d0;\n  border-top-color: #4b4b4b;\n  border-bottom-color: #4b4b4b;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-bac5ffa9 .gd-tbl-rownum,\nhtml.quarto-dark #gd-tbl-bac5ffa9 .gd-tbl-rownum,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bac5ffa9 .gd-tbl-rownum {\n  color: #888;\n  border-right-color: rgba(102, 153, 204, 0.4) !important;\n}\nbody.quarto-dark #gd-tbl-bac5ffa9 .gd-tbl-missing,\nhtml.quarto-dark #gd-tbl-bac5ffa9 .gd-tbl-missing,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bac5ffa9 .gd-tbl-missing {\n  color: #ff6b6b !important;\n  background-color: rgba(60, 17, 24, 0.2);\n}\nbody.quarto-dark #gd-tbl-bac5ffa9 .gd-tbl-dtype,\nhtml.quarto-dark #gd-tbl-bac5ffa9 .gd-tbl-dtype,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bac5ffa9 .gd-tbl-dtype {\n  color: #888;\n}\nbody.quarto-dark #gd-tbl-bac5ffa9 .gt_bottom_border,\nhtml.quarto-dark #gd-tbl-bac5ffa9 .gt_bottom_border,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bac5ffa9 .gt_bottom_border {\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-bac5ffa9 .gd-tbl-badge-rows-label,\nhtml.quarto-dark #gd-tbl-bac5ffa9 .gd-tbl-badge-rows-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bac5ffa9 .gd-tbl-badge-rows-label {\n  background-color: #3d2a4d;\n  border-color: #3d2a4d;\n  color: #e0c0ff;\n}\nbody.quarto-dark #gd-tbl-bac5ffa9 .gd-tbl-badge-rows-value,\nhtml.quarto-dark #gd-tbl-bac5ffa9 .gd-tbl-badge-rows-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bac5ffa9 .gd-tbl-badge-rows-value {\n  border-color: #3d2a4d;\n  color: #d0b0e0;\n}\nbody.quarto-dark #gd-tbl-bac5ffa9 .gd-tbl-badge-cols-label,\nhtml.quarto-dark #gd-tbl-bac5ffa9 .gd-tbl-badge-cols-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bac5ffa9 .gd-tbl-badge-cols-label {\n  background-color: #2a4d2a;\n  border-color: #2a4d2a;\n  color: #b0e0b0;\n}\nbody.quarto-dark #gd-tbl-bac5ffa9 .gd-tbl-badge-cols-value,\nhtml.quarto-dark #gd-tbl-bac5ffa9 .gd-tbl-badge-cols-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bac5ffa9 .gd-tbl-badge-cols-value {\n  border-color: #2a4d2a;\n  color: #a0d0a0;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"true\" data-quarto-bootstrap=\"false\">\n<colgroup>\n<col style=\"width: 35px\"/>\n<col style=\"width: 66px\"/>\n<col style=\"width: 124px\"/>\n<col style=\"width: 131px\"/>\n<col style=\"width: 110px\"/>\n<col style=\"width: 138px\"/>\n<col style=\"width: 138px\"/>\n<col style=\"width: 124px\"/>\n</colgroup>\n<thead>\n<tr class=\"gt_heading\"><td class=\"gt_heading gt_title gt_font_normal\" colspan=\"8\"><div style=\"padding-top: 0; padding-bottom: 7px;\"><span class=\"gd-tbl-badge\" style=\"background-color: #0075FF; color: #FFFFFF; border: 1px solid #0075FF; margin-right: 8px;\">Polars</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-label\">Rows</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-value\">2</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-label\">Columns</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-value\">7</span></div></td></tr>\n<tr class=\"gt_col_headings\">\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\"></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\"><div><div class=\"gd-tbl-colname\">term</div><div class=\"gd-tbl-dtype\"><em>str</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><div><div class=\"gd-tbl-colname\">estimate</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std_error\"><div><div class=\"gd-tbl-colname\">std_error</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\"><div><div class=\"gd-tbl-colname\">statistic</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p_value\"><div><div class=\"gd-tbl-colname\">p_value</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf_low\"><div><div class=\"gd-tbl-colname\">conf_low</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf_high\"><div><div class=\"gd-tbl-colname\">conf_high</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">0</td>\n<td class=\"gt_row gt_left\" style=\"max-width: 66px;\">age</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 124px;\">0.0105662546009</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 131px;\">0.00924137389309</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 110px;\">1.14336404123</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 138px;\">0.252887475744</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 138px;\">-0.00754650539718</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 124px;\">0.0286790145991</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">1</td>\n<td class=\"gt_row gt_left\" style=\"max-width: 66px;\">ph.ecog</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 124px;\">0.462424434358</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 131px;\">0.114761097855</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 110px;\">4.0294528634</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 138px;\">5.59068243623e-05</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 138px;\">0.237496815737</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 124px;\">0.68735205298</td>\n</tr>\n</tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nNotice that the stratifying variable, `sex`, does not appear as a coefficient. Its effect is\nabsorbed into the separate baselines, which is exactly the point of stratification.\n\n## Robust and clustered standard errors\n\nWhen observations are not independent, for example when the same subject contributes several\nrows or when subjects are grouped into clusters, the model-based standard errors are too\nsmall. The robust, or sandwich, variance corrects for this. Set `robust=True` for the\nLin-Wei sandwich estimator, and pass `cluster` to group correlated observations.\n\n::: {#352a4c4e .cell execution_count=16}\n``` {.python .cell-code}\n# Load data and build the response\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\ny = gw.Surv.right(lung[\"time\"], event=(lung[\"status\"] == 2))\n\n# Fit with the Lin-Wei sandwich variance; coefficients are unchanged, SEs are adjusted\nrobust = gw.CoxPH().fit(y, lung[[\"age\", \"sex\"]], robust=True)\n\n# Show only the standard errors to compare against the model-based values\nrobust.to_frame(format=\"polars\")[[\"term\", \"std_error\"]]\n```\n\n::: {.cell-output .cell-output-display execution_count=16}\n```{=html}\n<div id=\"gd-tbl-65a9d1a4\" class=\"gd-tbl-preview\" style=\"padding-left: 0px; overflow-x: auto; overflow-y: hidden; width: 100%; max-width: 100%; margin-bottom: 1em;\">\n<style>\n@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,600;1,400&family=IBM+Plex+Sans:wght@400;600&display=swap');\n#gd-tbl-65a9d1a4 .gt_table {\n  display: table;\n  border-collapse: collapse;\n  table-layout: fixed;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 14px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n}\n#gd-tbl-65a9d1a4 .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-65a9d1a4 .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n#gd-tbl-65a9d1a4 .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n#gd-tbl-65a9d1a4 .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n#gd-tbl-65a9d1a4 .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-65a9d1a4 .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #F2F2F2;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #F2F2F2;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n#gd-tbl-65a9d1a4 .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n}\n#gd-tbl-65a9d1a4 .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #E9E9E9;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #E9E9E9;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #E9E9E9;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n#gd-tbl-65a9d1a4 .gt_left { text-align: left; }\n#gd-tbl-65a9d1a4 .gt_center { text-align: center; }\n#gd-tbl-65a9d1a4 .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n#gd-tbl-65a9d1a4 .gt_font_normal { font-weight: normal; }\n#gd-tbl-65a9d1a4 .gt_font_bold { font-weight: bold; }\n#gd-tbl-65a9d1a4 .gt_font_italic { font-style: italic; }\n#gd-tbl-65a9d1a4 .gt_striped { background-color: rgba(128,128,128,0.05); }\n#gd-tbl-65a9d1a4 .gt_from_md > :first-child { margin-top: 0; }\n#gd-tbl-65a9d1a4 .gt_from_md > :last-child { margin-bottom: 0; }\n/* Data cell font */\n#gd-tbl-65a9d1a4 .gt_table_body .gt_row {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  height: 14px;\n}\n/* Column label font */\n#gd-tbl-65a9d1a4 .gt_col_heading {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n}\n/* Row number styling */\n#gd-tbl-65a9d1a4 .gd-tbl-rownum {\n  color: gray;\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 10px;\n  border-right: 2px solid rgba(102, 153, 204, 0.5) !important;\n  text-align: right;\n  padding-right: 6px;\n  white-space: nowrap;\n}\n/* Head/tail divider */\n#gd-tbl-65a9d1a4 tr.gd-tbl-divider td,\n#gd-tbl-65a9d1a4 tr.gd-tbl-divider th {\n  border-bottom: 2px solid rgba(102, 153, 204, 0.5);\n}\n/* Missing values */\n#gd-tbl-65a9d1a4 .gd-tbl-missing {\n  color: #B22222 !important;\n  background-color: rgba(255, 193, 193, 0.35);\n}\n/* Column label sub-elements */\n#gd-tbl-65a9d1a4 .gd-tbl-colname {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-bottom: 0;\n  margin-bottom: 0;\n}\n#gd-tbl-65a9d1a4 .gd-tbl-dtype {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-top: 0;\n  margin-top: 0;\n  color: #666666;\n}\n/* Header badge styling */\n#gd-tbl-65a9d1a4 .gd-tbl-badge {\n  display: inline-block;\n  padding: 2px 10px;\n  font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, sans-serif;\n  font-size: 10px;\n  font-weight: bold;\n  text-transform: uppercase;\n  position: inherit;\n}\n#gd-tbl-65a9d1a4 .gd-tbl-badge-rows-label {\n  background-color: #eecbff;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: 5px;\n}\n#gd-tbl-65a9d1a4 .gd-tbl-badge-rows-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: -4px;\n  margin-right: 3px;\n}\n#gd-tbl-65a9d1a4 .gd-tbl-badge-cols-label {\n  background-color: #BDE7B4;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n}\n#gd-tbl-65a9d1a4 .gd-tbl-badge-cols-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n  margin-left: -4px;\n}\n/* Dark mode */\nbody.quarto-dark #gd-tbl-65a9d1a4 .gt_table,\nhtml.quarto-dark #gd-tbl-65a9d1a4 .gt_table,\n:root[data-bs-theme=\"dark\"] #gd-tbl-65a9d1a4 .gt_table {\n  background-color: #1a1a2e;\n  color: #e0e0e0;\n  border-top-color: #555;\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-65a9d1a4 .gt_heading,\nhtml.quarto-dark #gd-tbl-65a9d1a4 .gt_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-65a9d1a4 .gt_heading {\n  background-color: #1a1a2e;\n  border-bottom-color: #1a1a2e;\n}\nbody.quarto-dark #gd-tbl-65a9d1a4 .gt_title,\nhtml.quarto-dark #gd-tbl-65a9d1a4 .gt_title,\n:root[data-bs-theme=\"dark\"] #gd-tbl-65a9d1a4 .gt_title {\n  color: #e0e0e0;\n}\nbody.quarto-dark #gd-tbl-65a9d1a4 .gt_subtitle,\nhtml.quarto-dark #gd-tbl-65a9d1a4 .gt_subtitle,\n:root[data-bs-theme=\"dark\"] #gd-tbl-65a9d1a4 .gt_subtitle {\n  color: #b0b0b0;\n}\nbody.quarto-dark #gd-tbl-65a9d1a4 .gt_col_headings,\nhtml.quarto-dark #gd-tbl-65a9d1a4 .gt_col_headings,\n:root[data-bs-theme=\"dark\"] #gd-tbl-65a9d1a4 .gt_col_headings {\n  border-top-color: #444;\n  border-bottom-color: #444;\n}\nbody.quarto-dark #gd-tbl-65a9d1a4 .gt_col_heading,\nhtml.quarto-dark #gd-tbl-65a9d1a4 .gt_col_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-65a9d1a4 .gt_col_heading {\n  color: #b0b0b0;\n  background-color: #1a1a2e;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-65a9d1a4 .gt_table_body,\nhtml.quarto-dark #gd-tbl-65a9d1a4 .gt_table_body,\n:root[data-bs-theme=\"dark\"] #gd-tbl-65a9d1a4 .gt_table_body {\n  border-top-color: #444;\n}\nbody.quarto-dark #gd-tbl-65a9d1a4 .gt_table_body .gt_row,\nhtml.quarto-dark #gd-tbl-65a9d1a4 .gt_table_body .gt_row,\n:root[data-bs-theme=\"dark\"] #gd-tbl-65a9d1a4 .gt_table_body .gt_row {\n  color: #d0d0d0;\n  border-top-color: #4b4b4b;\n  border-bottom-color: #4b4b4b;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-65a9d1a4 .gd-tbl-rownum,\nhtml.quarto-dark #gd-tbl-65a9d1a4 .gd-tbl-rownum,\n:root[data-bs-theme=\"dark\"] #gd-tbl-65a9d1a4 .gd-tbl-rownum {\n  color: #888;\n  border-right-color: rgba(102, 153, 204, 0.4) !important;\n}\nbody.quarto-dark #gd-tbl-65a9d1a4 .gd-tbl-missing,\nhtml.quarto-dark #gd-tbl-65a9d1a4 .gd-tbl-missing,\n:root[data-bs-theme=\"dark\"] #gd-tbl-65a9d1a4 .gd-tbl-missing {\n  color: #ff6b6b !important;\n  background-color: rgba(60, 17, 24, 0.2);\n}\nbody.quarto-dark #gd-tbl-65a9d1a4 .gd-tbl-dtype,\nhtml.quarto-dark #gd-tbl-65a9d1a4 .gd-tbl-dtype,\n:root[data-bs-theme=\"dark\"] #gd-tbl-65a9d1a4 .gd-tbl-dtype {\n  color: #888;\n}\nbody.quarto-dark #gd-tbl-65a9d1a4 .gt_bottom_border,\nhtml.quarto-dark #gd-tbl-65a9d1a4 .gt_bottom_border,\n:root[data-bs-theme=\"dark\"] #gd-tbl-65a9d1a4 .gt_bottom_border {\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-65a9d1a4 .gd-tbl-badge-rows-label,\nhtml.quarto-dark #gd-tbl-65a9d1a4 .gd-tbl-badge-rows-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-65a9d1a4 .gd-tbl-badge-rows-label {\n  background-color: #3d2a4d;\n  border-color: #3d2a4d;\n  color: #e0c0ff;\n}\nbody.quarto-dark #gd-tbl-65a9d1a4 .gd-tbl-badge-rows-value,\nhtml.quarto-dark #gd-tbl-65a9d1a4 .gd-tbl-badge-rows-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-65a9d1a4 .gd-tbl-badge-rows-value {\n  border-color: #3d2a4d;\n  color: #d0b0e0;\n}\nbody.quarto-dark #gd-tbl-65a9d1a4 .gd-tbl-badge-cols-label,\nhtml.quarto-dark #gd-tbl-65a9d1a4 .gd-tbl-badge-cols-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-65a9d1a4 .gd-tbl-badge-cols-label {\n  background-color: #2a4d2a;\n  border-color: #2a4d2a;\n  color: #b0e0b0;\n}\nbody.quarto-dark #gd-tbl-65a9d1a4 .gd-tbl-badge-cols-value,\nhtml.quarto-dark #gd-tbl-65a9d1a4 .gd-tbl-badge-cols-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-65a9d1a4 .gd-tbl-badge-cols-value {\n  border-color: #2a4d2a;\n  color: #a0d0a0;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"true\" data-quarto-bootstrap=\"false\">\n<colgroup>\n<col style=\"width: 35px\"/>\n<col style=\"width: 192px\"/>\n<col style=\"width: 273px\"/>\n</colgroup>\n<thead>\n<tr class=\"gt_heading\"><td class=\"gt_heading gt_title gt_font_normal\" colspan=\"3\"><div style=\"padding-top: 0; padding-bottom: 7px;\"><span class=\"gd-tbl-badge\" style=\"background-color: #0075FF; color: #FFFFFF; border: 1px solid #0075FF; margin-right: 8px;\">Polars</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-label\">Rows</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-value\">2</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-label\">Columns</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-value\">2</span></div></td></tr>\n<tr class=\"gt_col_headings\">\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\"></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\"><div><div class=\"gd-tbl-colname\">term</div><div class=\"gd-tbl-dtype\"><em>str</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std_error\"><div><div class=\"gd-tbl-colname\">std_error</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">0</td>\n<td class=\"gt_row gt_left\" style=\"max-width: 192px;\">age</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 273px;\">0.00948922108421</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">1</td>\n<td class=\"gt_row gt_left\" style=\"max-width: 192px;\">sex</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 273px;\">0.159919372277</td>\n</tr>\n</tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThe coefficients are unchanged; only the standard errors, and therefore the p-values and\nintervals, are adjusted. The model-based standard errors remain available as\n`naive_std_error_` for comparison.\n\n## The concordance index\n\nThe concordance index, or C-statistic, measures how well the model's risk ordering agrees\nwith the observed order of events. It is the probability that, for a random comparable pair\nof subjects, the one who failed first had the higher predicted risk. A value of 0.5 is no\nbetter than chance and 1.0 is perfect discrimination.\n\n::: {#8a5ae633 .cell execution_count=17}\n``` {.python .cell-code}\n# Load data and build the response\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\ny = gw.Surv.right(lung[\"time\"], event=(lung[\"status\"] == 2))\n\n# Fit a Cox model with age and sex as covariates\ncox = gw.CoxPH().fit(y, lung[[\"age\", \"sex\"]])\n\n# Compute Harrell's C-statistic: probability of correct pairwise risk ordering\ncox.concordance()\n```\n\n::: {.cell-output .cell-output-display execution_count=17}\n```\n0.6028530028979714\n```\n:::\n:::\n\n\nThe C-statistic summarizes discrimination across all observed pairs, but it does not say\nwhether predicted probabilities are well calibrated. For a more complete picture of model\nperformance, including calibration and the Brier score, see\n[Prediction performance](prediction-performance.qmd).\n\n## Next steps\n\nYou can now validate a Cox model and use it to predict.\n\n- [Prediction performance](prediction-performance.qmd) extends discrimination and adds\nthe Brier score for calibration, including for external risk scores.\n- [Parametric survival models](parametric-models.qmd) provide an alternative when the\nproportional hazards assumption is untenable.\n- Revisit [Cox regression](cox-regression.qmd) for the modeling basics if any of this is\nunfamiliar.\n\n",
    "supporting": [
      "cox-diagnostics_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}