"""Conformance of `Surv()` against R's `survival::Surv()`.

The cases under `spec/conformance/surv/` are generated by `scripts/generate_surv_conformance.R`.
Each records the arguments of a call and what R returned (columns, type, and states), or the
error it raised, along with any warnings. `Surv()` must match all of it, including the exact
error and warning messages. See `spec/surv.md`.
"""

from __future__ import annotations

import warnings
from typing import Any

import pytest

import greenwood as gw

from ._conformance import decode_input, floats_equal, load_conformance, r_floats

pytestmark = pytest.mark.rparity

# Warnings that come from R itself rather than from Surv()'s rules. `max()` of an empty vector
# warns in R, which has no Python counterpart.
R_ONLY_WARNINGS = ("no non-missing arguments to max",)

CASES: list[dict[str, Any]] = load_conformance("surv", "surv")


def _call(case: dict[str, Any]) -> gw.Surv:
    args: dict[str, Any] = {}
    for name, value in case["args"].items():
        args[name] = value if name in ("type", "origin") else decode_input(value)
    return gw.Surv(**args)


def _expected_warnings(result: dict[str, Any]) -> list[str]:
    return [w for w in result["warnings"] if not w.startswith(R_ONLY_WARNINGS)]


def test_case_ids_are_unique() -> None:
    ids = [case["id"] for case in CASES]
    assert len(ids) == len(set(ids))


@pytest.mark.parametrize("case", CASES, ids=[case["id"] for case in CASES])
def test_surv_matches_r(case: dict[str, Any]) -> None:
    result = case["result"]
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter("always")
        if not result["ok"]:
            with pytest.raises((TypeError, ValueError)) as excinfo:
                _call(case)
            assert str(excinfo.value) == result["message"]
            return
        surv = _call(case)

    assert [str(w.message) for w in caught] == _expected_warnings(result)
    assert surv.type == result["type"]
    assert surv.states == (None if result["states"] is None else tuple(result["states"]))
    columns = surv.to_frame(format="polars").to_dict(as_series=False)
    assert list(columns) == list(result["columns"])
    for name, values in result["columns"].items():
        assert floats_equal(columns[name], r_floats(values)), name
