{
  "hash": "11cea36230fcb04b3981d1a5a28aa8a1",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: Parametric survival models\nguide-section: \"Regression\"\nbread-crumbs: false\n---\n\n\n\nThe Cox model deliberately avoids specifying the shape of the baseline hazard. Parametric models\ntake the opposite approach: they assume the survival times follow a particular distribution, such as\nWeibull or log-normal. In exchange for that assumption you gain a fully specified model that can\nextrapolate beyond the observed follow-up, produce smooth survival and hazard curves, and sometimes\nfit more efficiently. Greenwood provides these as accelerated failure time models, which describe\nhow covariates stretch or compress the time scale. This page shows how to fit them and how to read\ntheir coefficients.\n\nWe work from the `lung` outcomes. The response `y` is a `Surv` object that pairs each follow-up time\nwith an event indicator, and it is what every model on this page is fit against.\n\n::: {#f1469258 .cell execution_count=2}\n``` {.python .cell-code}\n# Import the Greenwood library\nimport greenwood as gw\n\n# Load the bundled lung dataset as a Polars DataFrame\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\n\n# Build a right-censored response (status 2 = dead in this R-originating dataset)\ny = gw.Surv.right(lung[\"time\"], event=(lung[\"status\"] == 2))\n\n# Display the response summary\ny\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```\nSurv(type=right, n=228, events=165)\n```\n:::\n:::\n\n\nThe printed response shows a right-censored response with 165 events among 228 subjects.\n\n## Fitting a distribution to survival data\n\nBefore adding covariates, it is often useful to ask: what parametric distribution fits this data\nbest? The `Parametric` class fits a standalone survival distribution by maximum likelihood, giving\nyou parameter estimates, standard errors, and model-selection statistics.\n\n::: {#55c5203f .cell execution_count=3}\n``` {.python .cell-code}\n# Fit a Weibull distribution by maximum likelihood (no covariates)\nfit = gw.Parametric(\"weibull\").fit(y)\n\n# Display parameter estimates, standard errors, and model-selection statistics\nfit\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```\nParametric (weibull distribution)\n\n       estimate  std_error\nshape     1.317    0.08221\nscale     417.8       24.7\n\nn = 228, events = 165\nLog-likelihood = -1154\nAIC = 2312, BIC = 2319\n```\n:::\n:::\n\n\nThe summary reports the natural parameters of the chosen family (here, Weibull shape and scale), the\nlog-likelihood, and AIC/BIC. The estimated shape parameter tells you about the hazard trend:\nshape > 1 means the hazard increases over time, shape < 1 means it decreases, and shape = 1 is a\nconstant hazard (exponential).\n\n### Comparing distributions\n\nRather than fitting each family one at a time, `compare_distributions` fits all four and returns a\nmodel-selection table sorted by AIC (where lower is better):\n\n::: {#ba712621 .cell execution_count=4}\n``` {.python .cell-code}\n# Fit all four families at once and rank by AIC (lower is better)\ngw.compare_distributions(y, format=\"polars\")\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```{=html}\n<div id=\"gd-tbl-35c5ac8a\" class=\"gd-tbl-preview\" style=\"padding-left: 0px; overflow-x: auto; overflow-y: hidden; width: 100%; max-width: 100%; margin-bottom: 1em;\">\n<style>\n@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,600;1,400&family=IBM+Plex+Sans:wght@400;600&display=swap');\n#gd-tbl-35c5ac8a .gt_table {\n  display: table;\n  border-collapse: collapse;\n  table-layout: fixed;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 14px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n}\n#gd-tbl-35c5ac8a .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-35c5ac8a .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n#gd-tbl-35c5ac8a .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n#gd-tbl-35c5ac8a .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n#gd-tbl-35c5ac8a .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-35c5ac8a .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #F2F2F2;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #F2F2F2;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n#gd-tbl-35c5ac8a .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n}\n#gd-tbl-35c5ac8a .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #E9E9E9;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #E9E9E9;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #E9E9E9;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n#gd-tbl-35c5ac8a .gt_left { text-align: left; }\n#gd-tbl-35c5ac8a .gt_center { text-align: center; }\n#gd-tbl-35c5ac8a .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n#gd-tbl-35c5ac8a .gt_font_normal { font-weight: normal; }\n#gd-tbl-35c5ac8a .gt_font_bold { font-weight: bold; }\n#gd-tbl-35c5ac8a .gt_font_italic { font-style: italic; }\n#gd-tbl-35c5ac8a .gt_striped { background-color: rgba(128,128,128,0.05); }\n#gd-tbl-35c5ac8a .gt_from_md > :first-child { margin-top: 0; }\n#gd-tbl-35c5ac8a .gt_from_md > :last-child { margin-bottom: 0; }\n/* Data cell font */\n#gd-tbl-35c5ac8a .gt_table_body .gt_row {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  height: 14px;\n}\n/* Column label font */\n#gd-tbl-35c5ac8a .gt_col_heading {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n}\n/* Row number styling */\n#gd-tbl-35c5ac8a .gd-tbl-rownum {\n  color: gray;\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 10px;\n  border-right: 2px solid rgba(102, 153, 204, 0.5) !important;\n  text-align: right;\n  padding-right: 6px;\n  white-space: nowrap;\n}\n/* Head/tail divider */\n#gd-tbl-35c5ac8a tr.gd-tbl-divider td,\n#gd-tbl-35c5ac8a tr.gd-tbl-divider th {\n  border-bottom: 2px solid rgba(102, 153, 204, 0.5);\n}\n/* Missing values */\n#gd-tbl-35c5ac8a .gd-tbl-missing {\n  color: #B22222 !important;\n  background-color: rgba(255, 193, 193, 0.35);\n}\n/* Column label sub-elements */\n#gd-tbl-35c5ac8a .gd-tbl-colname {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-bottom: 0;\n  margin-bottom: 0;\n}\n#gd-tbl-35c5ac8a .gd-tbl-dtype {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-top: 0;\n  margin-top: 0;\n  color: #666666;\n}\n/* Header badge styling */\n#gd-tbl-35c5ac8a .gd-tbl-badge {\n  display: inline-block;\n  padding: 2px 10px;\n  font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, sans-serif;\n  font-size: 10px;\n  font-weight: bold;\n  text-transform: uppercase;\n  position: inherit;\n}\n#gd-tbl-35c5ac8a .gd-tbl-badge-rows-label {\n  background-color: #eecbff;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: 5px;\n}\n#gd-tbl-35c5ac8a .gd-tbl-badge-rows-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: -4px;\n  margin-right: 3px;\n}\n#gd-tbl-35c5ac8a .gd-tbl-badge-cols-label {\n  background-color: #BDE7B4;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n}\n#gd-tbl-35c5ac8a .gd-tbl-badge-cols-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n  margin-left: -4px;\n}\n/* Dark mode */\nbody.quarto-dark #gd-tbl-35c5ac8a .gt_table,\nhtml.quarto-dark #gd-tbl-35c5ac8a .gt_table,\n:root[data-bs-theme=\"dark\"] #gd-tbl-35c5ac8a .gt_table {\n  background-color: #1a1a2e;\n  color: #e0e0e0;\n  border-top-color: #555;\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-35c5ac8a .gt_heading,\nhtml.quarto-dark #gd-tbl-35c5ac8a .gt_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-35c5ac8a .gt_heading {\n  background-color: #1a1a2e;\n  border-bottom-color: #1a1a2e;\n}\nbody.quarto-dark #gd-tbl-35c5ac8a .gt_title,\nhtml.quarto-dark #gd-tbl-35c5ac8a .gt_title,\n:root[data-bs-theme=\"dark\"] #gd-tbl-35c5ac8a .gt_title {\n  color: #e0e0e0;\n}\nbody.quarto-dark #gd-tbl-35c5ac8a .gt_subtitle,\nhtml.quarto-dark #gd-tbl-35c5ac8a .gt_subtitle,\n:root[data-bs-theme=\"dark\"] #gd-tbl-35c5ac8a .gt_subtitle {\n  color: #b0b0b0;\n}\nbody.quarto-dark #gd-tbl-35c5ac8a .gt_col_headings,\nhtml.quarto-dark #gd-tbl-35c5ac8a .gt_col_headings,\n:root[data-bs-theme=\"dark\"] #gd-tbl-35c5ac8a .gt_col_headings {\n  border-top-color: #444;\n  border-bottom-color: #444;\n}\nbody.quarto-dark #gd-tbl-35c5ac8a .gt_col_heading,\nhtml.quarto-dark #gd-tbl-35c5ac8a .gt_col_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-35c5ac8a .gt_col_heading {\n  color: #b0b0b0;\n  background-color: #1a1a2e;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-35c5ac8a .gt_table_body,\nhtml.quarto-dark #gd-tbl-35c5ac8a .gt_table_body,\n:root[data-bs-theme=\"dark\"] #gd-tbl-35c5ac8a .gt_table_body {\n  border-top-color: #444;\n}\nbody.quarto-dark #gd-tbl-35c5ac8a .gt_table_body .gt_row,\nhtml.quarto-dark #gd-tbl-35c5ac8a .gt_table_body .gt_row,\n:root[data-bs-theme=\"dark\"] #gd-tbl-35c5ac8a .gt_table_body .gt_row {\n  color: #d0d0d0;\n  border-top-color: #4b4b4b;\n  border-bottom-color: #4b4b4b;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-35c5ac8a .gd-tbl-rownum,\nhtml.quarto-dark #gd-tbl-35c5ac8a .gd-tbl-rownum,\n:root[data-bs-theme=\"dark\"] #gd-tbl-35c5ac8a .gd-tbl-rownum {\n  color: #888;\n  border-right-color: rgba(102, 153, 204, 0.4) !important;\n}\nbody.quarto-dark #gd-tbl-35c5ac8a .gd-tbl-missing,\nhtml.quarto-dark #gd-tbl-35c5ac8a .gd-tbl-missing,\n:root[data-bs-theme=\"dark\"] #gd-tbl-35c5ac8a .gd-tbl-missing {\n  color: #ff6b6b !important;\n  background-color: rgba(60, 17, 24, 0.2);\n}\nbody.quarto-dark #gd-tbl-35c5ac8a .gd-tbl-dtype,\nhtml.quarto-dark #gd-tbl-35c5ac8a .gd-tbl-dtype,\n:root[data-bs-theme=\"dark\"] #gd-tbl-35c5ac8a .gd-tbl-dtype {\n  color: #888;\n}\nbody.quarto-dark #gd-tbl-35c5ac8a .gt_bottom_border,\nhtml.quarto-dark #gd-tbl-35c5ac8a .gt_bottom_border,\n:root[data-bs-theme=\"dark\"] #gd-tbl-35c5ac8a .gt_bottom_border {\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-35c5ac8a .gd-tbl-badge-rows-label,\nhtml.quarto-dark #gd-tbl-35c5ac8a .gd-tbl-badge-rows-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-35c5ac8a .gd-tbl-badge-rows-label {\n  background-color: #3d2a4d;\n  border-color: #3d2a4d;\n  color: #e0c0ff;\n}\nbody.quarto-dark #gd-tbl-35c5ac8a .gd-tbl-badge-rows-value,\nhtml.quarto-dark #gd-tbl-35c5ac8a .gd-tbl-badge-rows-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-35c5ac8a .gd-tbl-badge-rows-value {\n  border-color: #3d2a4d;\n  color: #d0b0e0;\n}\nbody.quarto-dark #gd-tbl-35c5ac8a .gd-tbl-badge-cols-label,\nhtml.quarto-dark #gd-tbl-35c5ac8a .gd-tbl-badge-cols-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-35c5ac8a .gd-tbl-badge-cols-label {\n  background-color: #2a4d2a;\n  border-color: #2a4d2a;\n  color: #b0e0b0;\n}\nbody.quarto-dark #gd-tbl-35c5ac8a .gd-tbl-badge-cols-value,\nhtml.quarto-dark #gd-tbl-35c5ac8a .gd-tbl-badge-cols-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-35c5ac8a .gd-tbl-badge-cols-value {\n  border-color: #2a4d2a;\n  color: #a0d0a0;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"true\" data-quarto-bootstrap=\"false\">\n<colgroup>\n<col style=\"width: 35px\"/>\n<col style=\"width: 95px\"/>\n<col style=\"width: 78px\"/>\n<col style=\"width: 117px\"/>\n<col style=\"width: 110px\"/>\n<col style=\"width: 110px\"/>\n</colgroup>\n<thead>\n<tr class=\"gt_heading\"><td class=\"gt_heading gt_title gt_font_normal\" colspan=\"6\"><div style=\"padding-top: 0; padding-bottom: 7px;\"><span class=\"gd-tbl-badge\" style=\"background-color: #0075FF; color: #FFFFFF; border: 1px solid #0075FF; margin-right: 8px;\">Polars</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-label\">Rows</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-value\">4</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-label\">Columns</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-value\">5</span></div></td></tr>\n<tr class=\"gt_col_headings\">\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\"></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"dist\"><div><div class=\"gd-tbl-colname\">dist</div><div class=\"gd-tbl-dtype\"><em>str</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n_params\"><div><div class=\"gd-tbl-colname\">n_params</div><div class=\"gd-tbl-dtype\"><em>i64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"loglik\"><div><div class=\"gd-tbl-colname\">loglik</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"aic\"><div><div class=\"gd-tbl-colname\">aic</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"bic\"><div><div class=\"gd-tbl-colname\">bic</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">0</td>\n<td class=\"gt_row gt_left\" style=\"max-width: 95px;\">weibull</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 78px;\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">-1153.85118809</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 110px;\">2311.70237618</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 110px;\">2318.56106744</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">1</td>\n<td class=\"gt_row gt_left\" style=\"max-width: 95px;\">loglogistic</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 78px;\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">-1160.93062351</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 110px;\">2325.86124702</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 110px;\">2332.71993828</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">2</td>\n<td class=\"gt_row gt_left\" style=\"max-width: 95px;\">exponential</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 78px;\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">-1162.33817579</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 110px;\">2326.67635157</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 110px;\">2330.1056972</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">3</td>\n<td class=\"gt_row gt_left\" style=\"max-width: 95px;\">lognormal</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 78px;\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">-1169.26905531</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 110px;\">2342.53811061</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 110px;\">2349.39680187</td>\n</tr>\n</tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThis immediately tells you which distributional assumption is most supported by the data. A\ndifference of 2 or less in AIC is negligible whereas differences above 10 are decisive.\n\n### Predictions from a fitted distribution\n\nA fitted `Parametric` object gives you the full distributional toolkit without needing to specify\ncovariates:\n\n::: {#8756043d .cell execution_count=5}\n``` {.python .cell-code}\n# Refit the Weibull for prediction\nfit = gw.Parametric(\"weibull\").fit(y)\n\n# Query the survival function at 6 months, 1 year, and 2 years\nfit.survival([180, 365, 730])\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```\narray([0.71893491, 0.43295354, 0.12425187])\n```\n:::\n:::\n\n\n::: {#e0212380 .cell execution_count=6}\n``` {.python .cell-code}\n# Instantaneous hazard rate at the same time points (risk of event per unit time)\nfit.hazard([180, 365, 730])\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n```\narray([0.00241409, 0.00302016, 0.00376191])\n```\n:::\n:::\n\n\n::: {#fee29985 .cell execution_count=7}\n``` {.python .cell-code}\n# Time by which 25%, 50%, and 75% of subjects have experienced the event\nfit.quantile([0.25, 0.5, 0.75])\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```\narray([162.19120953, 316.26369238, 535.36451702])\n```\n:::\n:::\n\n\n::: {#c29e06f7 .cell execution_count=8}\n``` {.python .cell-code}\n# Single-number summaries of the fitted distribution\nprint(f\"Mean:   {fit.mean():.1f} days\")\nprint(f\"Median: {fit.median():.1f} days\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMean:   384.9 days\nMedian: 316.3 days\n```\n:::\n:::\n\n\nThese predictions describe the population-level survival distribution. Once you are satisfied with a\ndistributional family, you can move to an AFT model to understand how covariates shift that\ndistribution.\n\n::: {.callout-tip}\n## From exploration to regression\n\nThe `Parametric` class is for exploration: which distribution shape fits my data? Once you've\nchosen, use `AFT` with the same distribution to model covariate effects. For example, if\n`compare_distributions()` picks Weibull, follow up with `gw.AFT(\"weibull\").fit(y, covariates)`.\n:::\n\n## The accelerated failure time model\n\nAn accelerated failure time model, or AFT model, works on the logarithm of survival time. It says\nthat covariates act by multiplying the time scale: a covariate might make time pass twice as fast,\nhalving survival, or twice as slowly, doubling it. This is a different and often more intuitive\nframing than the Cox model's multiplication of hazards. The model is fit by maximum likelihood, and\nit includes an intercept because it estimates the actual location of the survival distribution, not\njust relative effects.\n\nYou fit one by naming a distribution. The Weibull is the default and the most common choice.\n\n::: {#7be5991f .cell execution_count=9}\n``` {.python .cell-code}\n# Fit a Weibull AFT model with age and sex as covariates\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\ny = gw.Surv.right(lung[\"time\"], event=(lung[\"status\"] == 2))\n\n# The model estimates how each covariate stretches or compresses survival time\naft = gw.AFT(\"weibull\").fit(y, lung[[\"age\", \"sex\"]])\n\n# Display the coefficient table, scale, and log-likelihood\naft\n```\n\n::: {.cell-output .cell-output-display execution_count=9}\n```\nAFT (accelerated failure time model, dist='weibull')\n\n                 coef  se(coef)       z          p\n(Intercept)     6.275    0.4814  13.036  7.671e-39\nage          -0.01226  0.006957  -1.762    0.07811\nsex            0.3821    0.1275   2.997   0.002723\n\nScale = 0.7541\nn = 228, events = 165\nLog-likelihood = -1147\n```\n:::\n:::\n\n\nPrinting the fitted model gives a summary in the style of R's `survreg`: the coefficient table, the\nscale parameter, the sample size, and the log-likelihood. For the coefficients as data, pass the\nmodel to `gw.tidy()`, which returns a tidy DataFrame.\n\n::: {#e65aa960 .cell execution_count=10}\n``` {.python .cell-code}\n# Extract the coefficient table as a tidy DataFrame (one row per term)\ngw.tidy(aft, format=\"polars\")\n```\n\n::: {.cell-output .cell-output-display execution_count=10}\n```{=html}\n<div id=\"gd-tbl-377dcc1f\" class=\"gd-tbl-preview\" style=\"padding-left: 0px; overflow-x: auto; overflow-y: hidden; width: 100%; max-width: 100%; margin-bottom: 1em;\">\n<style>\n@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,600;1,400&family=IBM+Plex+Sans:wght@400;600&display=swap');\n#gd-tbl-377dcc1f .gt_table {\n  display: table;\n  border-collapse: collapse;\n  table-layout: fixed;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 14px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n}\n#gd-tbl-377dcc1f .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-377dcc1f .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n#gd-tbl-377dcc1f .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n#gd-tbl-377dcc1f .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n#gd-tbl-377dcc1f .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-377dcc1f .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #F2F2F2;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #F2F2F2;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n#gd-tbl-377dcc1f .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n}\n#gd-tbl-377dcc1f .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #E9E9E9;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #E9E9E9;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #E9E9E9;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n#gd-tbl-377dcc1f .gt_left { text-align: left; }\n#gd-tbl-377dcc1f .gt_center { text-align: center; }\n#gd-tbl-377dcc1f .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n#gd-tbl-377dcc1f .gt_font_normal { font-weight: normal; }\n#gd-tbl-377dcc1f .gt_font_bold { font-weight: bold; }\n#gd-tbl-377dcc1f .gt_font_italic { font-style: italic; }\n#gd-tbl-377dcc1f .gt_striped { background-color: rgba(128,128,128,0.05); }\n#gd-tbl-377dcc1f .gt_from_md > :first-child { margin-top: 0; }\n#gd-tbl-377dcc1f .gt_from_md > :last-child { margin-bottom: 0; }\n/* Data cell font */\n#gd-tbl-377dcc1f .gt_table_body .gt_row {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  height: 14px;\n}\n/* Column label font */\n#gd-tbl-377dcc1f .gt_col_heading {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n}\n/* Row number styling */\n#gd-tbl-377dcc1f .gd-tbl-rownum {\n  color: gray;\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 10px;\n  border-right: 2px solid rgba(102, 153, 204, 0.5) !important;\n  text-align: right;\n  padding-right: 6px;\n  white-space: nowrap;\n}\n/* Head/tail divider */\n#gd-tbl-377dcc1f tr.gd-tbl-divider td,\n#gd-tbl-377dcc1f tr.gd-tbl-divider th {\n  border-bottom: 2px solid rgba(102, 153, 204, 0.5);\n}\n/* Missing values */\n#gd-tbl-377dcc1f .gd-tbl-missing {\n  color: #B22222 !important;\n  background-color: rgba(255, 193, 193, 0.35);\n}\n/* Column label sub-elements */\n#gd-tbl-377dcc1f .gd-tbl-colname {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-bottom: 0;\n  margin-bottom: 0;\n}\n#gd-tbl-377dcc1f .gd-tbl-dtype {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-top: 0;\n  margin-top: 0;\n  color: #666666;\n}\n/* Header badge styling */\n#gd-tbl-377dcc1f .gd-tbl-badge {\n  display: inline-block;\n  padding: 2px 10px;\n  font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, sans-serif;\n  font-size: 10px;\n  font-weight: bold;\n  text-transform: uppercase;\n  position: inherit;\n}\n#gd-tbl-377dcc1f .gd-tbl-badge-rows-label {\n  background-color: #eecbff;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: 5px;\n}\n#gd-tbl-377dcc1f .gd-tbl-badge-rows-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: -4px;\n  margin-right: 3px;\n}\n#gd-tbl-377dcc1f .gd-tbl-badge-cols-label {\n  background-color: #BDE7B4;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n}\n#gd-tbl-377dcc1f .gd-tbl-badge-cols-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n  margin-left: -4px;\n}\n/* Dark mode */\nbody.quarto-dark #gd-tbl-377dcc1f .gt_table,\nhtml.quarto-dark #gd-tbl-377dcc1f .gt_table,\n:root[data-bs-theme=\"dark\"] #gd-tbl-377dcc1f .gt_table {\n  background-color: #1a1a2e;\n  color: #e0e0e0;\n  border-top-color: #555;\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-377dcc1f .gt_heading,\nhtml.quarto-dark #gd-tbl-377dcc1f .gt_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-377dcc1f .gt_heading {\n  background-color: #1a1a2e;\n  border-bottom-color: #1a1a2e;\n}\nbody.quarto-dark #gd-tbl-377dcc1f .gt_title,\nhtml.quarto-dark #gd-tbl-377dcc1f .gt_title,\n:root[data-bs-theme=\"dark\"] #gd-tbl-377dcc1f .gt_title {\n  color: #e0e0e0;\n}\nbody.quarto-dark #gd-tbl-377dcc1f .gt_subtitle,\nhtml.quarto-dark #gd-tbl-377dcc1f .gt_subtitle,\n:root[data-bs-theme=\"dark\"] #gd-tbl-377dcc1f .gt_subtitle {\n  color: #b0b0b0;\n}\nbody.quarto-dark #gd-tbl-377dcc1f .gt_col_headings,\nhtml.quarto-dark #gd-tbl-377dcc1f .gt_col_headings,\n:root[data-bs-theme=\"dark\"] #gd-tbl-377dcc1f .gt_col_headings {\n  border-top-color: #444;\n  border-bottom-color: #444;\n}\nbody.quarto-dark #gd-tbl-377dcc1f .gt_col_heading,\nhtml.quarto-dark #gd-tbl-377dcc1f .gt_col_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-377dcc1f .gt_col_heading {\n  color: #b0b0b0;\n  background-color: #1a1a2e;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-377dcc1f .gt_table_body,\nhtml.quarto-dark #gd-tbl-377dcc1f .gt_table_body,\n:root[data-bs-theme=\"dark\"] #gd-tbl-377dcc1f .gt_table_body {\n  border-top-color: #444;\n}\nbody.quarto-dark #gd-tbl-377dcc1f .gt_table_body .gt_row,\nhtml.quarto-dark #gd-tbl-377dcc1f .gt_table_body .gt_row,\n:root[data-bs-theme=\"dark\"] #gd-tbl-377dcc1f .gt_table_body .gt_row {\n  color: #d0d0d0;\n  border-top-color: #4b4b4b;\n  border-bottom-color: #4b4b4b;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-377dcc1f .gd-tbl-rownum,\nhtml.quarto-dark #gd-tbl-377dcc1f .gd-tbl-rownum,\n:root[data-bs-theme=\"dark\"] #gd-tbl-377dcc1f .gd-tbl-rownum {\n  color: #888;\n  border-right-color: rgba(102, 153, 204, 0.4) !important;\n}\nbody.quarto-dark #gd-tbl-377dcc1f .gd-tbl-missing,\nhtml.quarto-dark #gd-tbl-377dcc1f .gd-tbl-missing,\n:root[data-bs-theme=\"dark\"] #gd-tbl-377dcc1f .gd-tbl-missing {\n  color: #ff6b6b !important;\n  background-color: rgba(60, 17, 24, 0.2);\n}\nbody.quarto-dark #gd-tbl-377dcc1f .gd-tbl-dtype,\nhtml.quarto-dark #gd-tbl-377dcc1f .gd-tbl-dtype,\n:root[data-bs-theme=\"dark\"] #gd-tbl-377dcc1f .gd-tbl-dtype {\n  color: #888;\n}\nbody.quarto-dark #gd-tbl-377dcc1f .gt_bottom_border,\nhtml.quarto-dark #gd-tbl-377dcc1f .gt_bottom_border,\n:root[data-bs-theme=\"dark\"] #gd-tbl-377dcc1f .gt_bottom_border {\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-377dcc1f .gd-tbl-badge-rows-label,\nhtml.quarto-dark #gd-tbl-377dcc1f .gd-tbl-badge-rows-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-377dcc1f .gd-tbl-badge-rows-label {\n  background-color: #3d2a4d;\n  border-color: #3d2a4d;\n  color: #e0c0ff;\n}\nbody.quarto-dark #gd-tbl-377dcc1f .gd-tbl-badge-rows-value,\nhtml.quarto-dark #gd-tbl-377dcc1f .gd-tbl-badge-rows-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-377dcc1f .gd-tbl-badge-rows-value {\n  border-color: #3d2a4d;\n  color: #d0b0e0;\n}\nbody.quarto-dark #gd-tbl-377dcc1f .gd-tbl-badge-cols-label,\nhtml.quarto-dark #gd-tbl-377dcc1f .gd-tbl-badge-cols-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-377dcc1f .gd-tbl-badge-cols-label {\n  background-color: #2a4d2a;\n  border-color: #2a4d2a;\n  color: #b0e0b0;\n}\nbody.quarto-dark #gd-tbl-377dcc1f .gd-tbl-badge-cols-value,\nhtml.quarto-dark #gd-tbl-377dcc1f .gd-tbl-badge-cols-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-377dcc1f .gd-tbl-badge-cols-value {\n  border-color: #2a4d2a;\n  color: #a0d0a0;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"true\" data-quarto-bootstrap=\"false\">\n<colgroup>\n<col style=\"width: 35px\"/>\n<col style=\"width: 95px\"/>\n<col style=\"width: 131px\"/>\n<col style=\"width: 131px\"/>\n<col style=\"width: 117px\"/>\n<col style=\"width: 138px\"/>\n<col style=\"width: 131px\"/>\n<col style=\"width: 131px\"/>\n</colgroup>\n<thead>\n<tr class=\"gt_heading\"><td class=\"gt_heading gt_title gt_font_normal\" colspan=\"8\"><div style=\"padding-top: 0; padding-bottom: 7px;\"><span class=\"gd-tbl-badge\" style=\"background-color: #0075FF; color: #FFFFFF; border: 1px solid #0075FF; margin-right: 8px;\">Polars</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-label\">Rows</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-value\">3</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-label\">Columns</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-value\">7</span></div></td></tr>\n<tr class=\"gt_col_headings\">\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\"></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\"><div><div class=\"gd-tbl-colname\">term</div><div class=\"gd-tbl-dtype\"><em>str</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><div><div class=\"gd-tbl-colname\">estimate</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std_error\"><div><div class=\"gd-tbl-colname\">std_error</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\"><div><div class=\"gd-tbl-colname\">statistic</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p_value\"><div><div class=\"gd-tbl-colname\">p_value</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf_low\"><div><div class=\"gd-tbl-colname\">conf_low</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf_high\"><div><div class=\"gd-tbl-colname\">conf_high</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">0</td>\n<td class=\"gt_row gt_left\" style=\"max-width: 95px;\">(Intercept)</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 131px;\">6.27487656662</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 131px;\">0.481362779739</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">13.035649682</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 138px;\">7.67107986691e-39</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 131px;\">5.33142285484</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 131px;\">7.21833027841</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">1</td>\n<td class=\"gt_row gt_left\" style=\"max-width: 95px;\">age</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 131px;\">-0.0122574075016</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 131px;\">0.00695741143991</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">-1.76177700679</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 138px;\">0.0781069810601</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 131px;\">-0.0258936833495</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 131px;\">0.00137886834625</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">2</td>\n<td class=\"gt_row gt_left\" style=\"max-width: 95px;\">sex</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 131px;\">0.382085592498</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 131px;\">0.127473120177</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">2.99738165949</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 138px;\">0.00272309560252</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 131px;\">0.132242867954</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 131px;\">0.631928317043</td>\n</tr>\n</tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThe coefficients are on the log-time scale. A positive coefficient lengthens survival time, and a\nnegative coefficient shortens it. This is the opposite direction from a Cox hazard ratio, where a\npositive coefficient means higher risk and shorter survival, so take care when comparing the two.\n\n## Choosing a distribution\n\nGreenwood supports four parametric distributions, each giving a different hazard shape.\n\n- exponential: Constant hazard (h(t) = λ). Simplest and often too restrictive.\n- Weibull: monotonic hazard (increasing or decreasing). The default and most flexible while\nremaining parsimonious.\n- log-normal: hazard rises then falls (many peak early). Good for disease incidence.\n- log-logistic: similar to log-normal but with heavier tails.\n\n::: {#6ed1e726 .cell execution_count=11}\n``` {.python .cell-code}\n# Fit each distribution to the same data and print the log-likelihood and scale\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\ny = gw.Surv.right(lung[\"time\"], event=(lung[\"status\"] == 2))\n\nfor dist in (\"exponential\", \"weibull\", \"lognormal\", \"loglogistic\"):\n    model = gw.AFT(dist).fit(y, lung[[\"age\", \"sex\"]])\n    print(f\"{dist:20s} loglik={model.loglik_:10.3f} scale={model.scale_:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nexponential          loglik= -1156.099 scale=1.0000\nweibull              loglik= -1147.054 scale=0.7541\nlognormal            loglik= -1158.750 scale=1.0527\nloglogistic          loglik= -1152.897 scale=0.5656\n```\n:::\n:::\n\n\nTo compare and choose among distributions, use the AIC (available from `glance()`), where a\nlower value indicates a better fit:\n\n::: {#7b528016 .cell execution_count=12}\n``` {.python .cell-code}\nimport pandas as pd\n\n# Collect glance summaries from each distribution into one table\nresults = []\nfor dist in (\"exponential\", \"weibull\", \"lognormal\", \"loglogistic\"):\n    model = gw.AFT(dist).fit(y, lung[[\"age\", \"sex\"]])\n    glance_result = gw.glance(model, format=\"pandas\")\n    glance_result[\"distribution\"] = dist\n    results.append(glance_result)\n\n# Combine and sort by AIC (lower is better)\ncomparison = pd.concat(results)[[\"distribution\", \"loglik\", \"aic\"]]\nprint(comparison.sort_values(\"aic\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  distribution       loglik          aic\n0      weibull -1147.054431  2302.108863\n0  loglogistic -1152.897225  2313.794451\n0  exponential -1156.099037  2318.198074\n0    lognormal -1158.750143  2325.500285\n```\n:::\n:::\n\n\nThe `scale=` parameter describes the spread of the distribution. For the exponential, it is fixed at\n`1` (constant hazard). For Weibull, values > 1 indicate increasing hazard, < 1 indicate decreasing.\nOther distributions use scale differently so see the model's help page for details.\n\n## Model comparison and selection\n\nEach call to `gw.glance()` returns a one-row DataFrame of model-level summaries for a single fit. We\ncan compare all four distributions systematically:\n\n::: {#3826495a .cell execution_count=13}\n``` {.python .cell-code}\n# Fit each distribution and collect glance results for ranking\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\ny = gw.Surv.right(lung[\"time\"], event=(lung[\"status\"] == 2))\n\ncomparisons = []\nfor dist in (\"exponential\", \"weibull\", \"lognormal\", \"loglogistic\"):\n    model = gw.AFT(dist).fit(y, lung[[\"age\", \"sex\"]])\n    result = gw.glance(model, format=\"pandas\")\n    result[\"distribution\"] = dist\n    comparisons.append(result)\n\n# Rank distributions by AIC: the lowest value wins\ncomparison = pd.concat(comparisons)[[\"distribution\", \"loglik\", \"aic\"]]\nprint(comparison.sort_values(\"aic\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  distribution       loglik          aic\n0      weibull -1147.054431  2302.108863\n0  loglogistic -1152.897225  2313.794451\n0  exponential -1156.099037  2318.198074\n0    lognormal -1158.750143  2325.500285\n```\n:::\n:::\n\n\nCompare the models by reading the AIC column and preferring the lowest value. A difference of 10 in\nAIC is substantial. Differences of 2-3 are subtle and don't warrant changing models.\n\n**When to use each distribution:**\n\n- exponential: only if you're confident hazard is constant (rare).\n- Weibull: safe default that fits many data types well.\n- log-normal/log-logistic: When you expect a hazard peak early in follow-up.\n- Gompertz: for aging-related or mortality data where hazard accelerates exponentially.\n\n::: {.callout-note}\n## Parametric or Cox?\n\nChoose a parametric model when you need to extrapolate, want smooth hazard or quantile predictions,\nor have a distributional form suggested by theory. Choose the Cox model when you want to avoid\ndistributional assumptions and care mainly about relative effects. Both are valid and they answer\nslightly different questions.\n:::\n\n::: {.callout-tip}\n## Interpreting the acceleration factor\n\nExponentiating an AFT coefficient gives a time-acceleration factor. A factor of 1.5 for a covariate\nmeans subjects with a one-unit-higher value survive 1.5 times as long on average, holding other\ncovariates fixed.\n:::\n\n## Predicting survival and quantiles\n\nBecause a parametric model specifies the whole distribution, it can predict smoothly at any time and\nextrapolate beyond the observed follow-up. We predict for two new subjects, a 50-year-old and a\n70-year-old, both with `sex` coded as `1`.\n\n::: {#f868094a .cell execution_count=14}\n``` {.python .cell-code}\n# Fit a Weibull AFT and define two new subjects for prediction\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\ny = gw.Surv.right(lung[\"time\"], event=(lung[\"status\"] == 2))\naft = gw.AFT(\"weibull\").fit(y, lung[[\"age\", \"sex\"]])\n\n# Two new subjects: a 50-year-old and a 70-year-old, both sex = 1\nnewdata = pd.DataFrame({\"age\": [50, 70], \"sex\": [1, 1]})\n\n# Predict survival-time quantiles at 25%, 50%, and 75% failure probabilities\naft.predict(newdata, type=\"quantile\", p=[0.25, 0.5, 0.75], format=\"polars\")\n```\n\n::: {.cell-output .cell-output-display execution_count=14}\n```{=html}\n<div id=\"gd-tbl-e90a6fbd\" class=\"gd-tbl-preview\" style=\"padding-left: 0px; overflow-x: auto; overflow-y: hidden; width: 100%; max-width: 100%; margin-bottom: 1em;\">\n<style>\n@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,600;1,400&family=IBM+Plex+Sans:wght@400;600&display=swap');\n#gd-tbl-e90a6fbd .gt_table {\n  display: table;\n  border-collapse: collapse;\n  table-layout: fixed;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 14px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n}\n#gd-tbl-e90a6fbd .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-e90a6fbd .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n#gd-tbl-e90a6fbd .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n#gd-tbl-e90a6fbd .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n#gd-tbl-e90a6fbd .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-e90a6fbd .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #F2F2F2;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #F2F2F2;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n#gd-tbl-e90a6fbd .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n}\n#gd-tbl-e90a6fbd .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #E9E9E9;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #E9E9E9;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #E9E9E9;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n#gd-tbl-e90a6fbd .gt_left { text-align: left; }\n#gd-tbl-e90a6fbd .gt_center { text-align: center; }\n#gd-tbl-e90a6fbd .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n#gd-tbl-e90a6fbd .gt_font_normal { font-weight: normal; }\n#gd-tbl-e90a6fbd .gt_font_bold { font-weight: bold; }\n#gd-tbl-e90a6fbd .gt_font_italic { font-style: italic; }\n#gd-tbl-e90a6fbd .gt_striped { background-color: rgba(128,128,128,0.05); }\n#gd-tbl-e90a6fbd .gt_from_md > :first-child { margin-top: 0; }\n#gd-tbl-e90a6fbd .gt_from_md > :last-child { margin-bottom: 0; }\n/* Data cell font */\n#gd-tbl-e90a6fbd .gt_table_body .gt_row {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  height: 14px;\n}\n/* Column label font */\n#gd-tbl-e90a6fbd .gt_col_heading {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n}\n/* Row number styling */\n#gd-tbl-e90a6fbd .gd-tbl-rownum {\n  color: gray;\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 10px;\n  border-right: 2px solid rgba(102, 153, 204, 0.5) !important;\n  text-align: right;\n  padding-right: 6px;\n  white-space: nowrap;\n}\n/* Head/tail divider */\n#gd-tbl-e90a6fbd tr.gd-tbl-divider td,\n#gd-tbl-e90a6fbd tr.gd-tbl-divider th {\n  border-bottom: 2px solid rgba(102, 153, 204, 0.5);\n}\n/* Missing values */\n#gd-tbl-e90a6fbd .gd-tbl-missing {\n  color: #B22222 !important;\n  background-color: rgba(255, 193, 193, 0.35);\n}\n/* Column label sub-elements */\n#gd-tbl-e90a6fbd .gd-tbl-colname {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-bottom: 0;\n  margin-bottom: 0;\n}\n#gd-tbl-e90a6fbd .gd-tbl-dtype {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-top: 0;\n  margin-top: 0;\n  color: #666666;\n}\n/* Header badge styling */\n#gd-tbl-e90a6fbd .gd-tbl-badge {\n  display: inline-block;\n  padding: 2px 10px;\n  font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, sans-serif;\n  font-size: 10px;\n  font-weight: bold;\n  text-transform: uppercase;\n  position: inherit;\n}\n#gd-tbl-e90a6fbd .gd-tbl-badge-rows-label {\n  background-color: #eecbff;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: 5px;\n}\n#gd-tbl-e90a6fbd .gd-tbl-badge-rows-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: -4px;\n  margin-right: 3px;\n}\n#gd-tbl-e90a6fbd .gd-tbl-badge-cols-label {\n  background-color: #BDE7B4;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n}\n#gd-tbl-e90a6fbd .gd-tbl-badge-cols-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n  margin-left: -4px;\n}\n/* Dark mode */\nbody.quarto-dark #gd-tbl-e90a6fbd .gt_table,\nhtml.quarto-dark #gd-tbl-e90a6fbd .gt_table,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e90a6fbd .gt_table {\n  background-color: #1a1a2e;\n  color: #e0e0e0;\n  border-top-color: #555;\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-e90a6fbd .gt_heading,\nhtml.quarto-dark #gd-tbl-e90a6fbd .gt_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e90a6fbd .gt_heading {\n  background-color: #1a1a2e;\n  border-bottom-color: #1a1a2e;\n}\nbody.quarto-dark #gd-tbl-e90a6fbd .gt_title,\nhtml.quarto-dark #gd-tbl-e90a6fbd .gt_title,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e90a6fbd .gt_title {\n  color: #e0e0e0;\n}\nbody.quarto-dark #gd-tbl-e90a6fbd .gt_subtitle,\nhtml.quarto-dark #gd-tbl-e90a6fbd .gt_subtitle,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e90a6fbd .gt_subtitle {\n  color: #b0b0b0;\n}\nbody.quarto-dark #gd-tbl-e90a6fbd .gt_col_headings,\nhtml.quarto-dark #gd-tbl-e90a6fbd .gt_col_headings,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e90a6fbd .gt_col_headings {\n  border-top-color: #444;\n  border-bottom-color: #444;\n}\nbody.quarto-dark #gd-tbl-e90a6fbd .gt_col_heading,\nhtml.quarto-dark #gd-tbl-e90a6fbd .gt_col_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e90a6fbd .gt_col_heading {\n  color: #b0b0b0;\n  background-color: #1a1a2e;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-e90a6fbd .gt_table_body,\nhtml.quarto-dark #gd-tbl-e90a6fbd .gt_table_body,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e90a6fbd .gt_table_body {\n  border-top-color: #444;\n}\nbody.quarto-dark #gd-tbl-e90a6fbd .gt_table_body .gt_row,\nhtml.quarto-dark #gd-tbl-e90a6fbd .gt_table_body .gt_row,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e90a6fbd .gt_table_body .gt_row {\n  color: #d0d0d0;\n  border-top-color: #4b4b4b;\n  border-bottom-color: #4b4b4b;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-e90a6fbd .gd-tbl-rownum,\nhtml.quarto-dark #gd-tbl-e90a6fbd .gd-tbl-rownum,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e90a6fbd .gd-tbl-rownum {\n  color: #888;\n  border-right-color: rgba(102, 153, 204, 0.4) !important;\n}\nbody.quarto-dark #gd-tbl-e90a6fbd .gd-tbl-missing,\nhtml.quarto-dark #gd-tbl-e90a6fbd .gd-tbl-missing,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e90a6fbd .gd-tbl-missing {\n  color: #ff6b6b !important;\n  background-color: rgba(60, 17, 24, 0.2);\n}\nbody.quarto-dark #gd-tbl-e90a6fbd .gd-tbl-dtype,\nhtml.quarto-dark #gd-tbl-e90a6fbd .gd-tbl-dtype,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e90a6fbd .gd-tbl-dtype {\n  color: #888;\n}\nbody.quarto-dark #gd-tbl-e90a6fbd .gt_bottom_border,\nhtml.quarto-dark #gd-tbl-e90a6fbd .gt_bottom_border,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e90a6fbd .gt_bottom_border {\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-e90a6fbd .gd-tbl-badge-rows-label,\nhtml.quarto-dark #gd-tbl-e90a6fbd .gd-tbl-badge-rows-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e90a6fbd .gd-tbl-badge-rows-label {\n  background-color: #3d2a4d;\n  border-color: #3d2a4d;\n  color: #e0c0ff;\n}\nbody.quarto-dark #gd-tbl-e90a6fbd .gd-tbl-badge-rows-value,\nhtml.quarto-dark #gd-tbl-e90a6fbd .gd-tbl-badge-rows-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e90a6fbd .gd-tbl-badge-rows-value {\n  border-color: #3d2a4d;\n  color: #d0b0e0;\n}\nbody.quarto-dark #gd-tbl-e90a6fbd .gd-tbl-badge-cols-label,\nhtml.quarto-dark #gd-tbl-e90a6fbd .gd-tbl-badge-cols-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e90a6fbd .gd-tbl-badge-cols-label {\n  background-color: #2a4d2a;\n  border-color: #2a4d2a;\n  color: #b0e0b0;\n}\nbody.quarto-dark #gd-tbl-e90a6fbd .gd-tbl-badge-cols-value,\nhtml.quarto-dark #gd-tbl-e90a6fbd .gd-tbl-badge-cols-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-e90a6fbd .gd-tbl-badge-cols-value {\n  border-color: #2a4d2a;\n  color: #a0d0a0;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"true\" data-quarto-bootstrap=\"false\">\n<colgroup>\n<col style=\"width: 35px\"/>\n<col style=\"width: 115px\"/>\n<col style=\"width: 175px\"/>\n<col style=\"width: 175px\"/>\n</colgroup>\n<thead>\n<tr class=\"gt_heading\"><td class=\"gt_heading gt_title gt_font_normal\" colspan=\"4\"><div style=\"padding-top: 0; padding-bottom: 7px;\"><span class=\"gd-tbl-badge\" style=\"background-color: #0075FF; color: #FFFFFF; border: 1px solid #0075FF; margin-right: 8px;\">Polars</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-label\">Rows</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-value\">3</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-label\">Columns</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-value\">3</span></div></td></tr>\n<tr class=\"gt_col_headings\">\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\"></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p\"><div><div class=\"gd-tbl-colname\">p</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"subject_1\"><div><div class=\"gd-tbl-colname\">subject_1</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"subject_2\"><div><div class=\"gd-tbl-colname\">subject_2</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 115px;\">0.25</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 175px;\">164.781414313</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 175px;\">128.956054541</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 115px;\">0.5</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 175px;\">319.808460567</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 175px;\">250.278451947</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 115px;\">0.75</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 175px;\">539.364048781</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 175px;\">422.100149962</td>\n</tr>\n</tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nWith `type=\"quantile\"` the model returns survival-time quantiles: each column is a subject and each\nrow a failure probability. The middle row (`p = 0.5`) is the predicted median survival time, and the\nolder subject's is shorter, as expected. These quantiles match R's `survreg`.\n\nFor the survival curve itself, use `type=\"survival\"` with the times you want.\n\n::: {#381ad7b4 .cell execution_count=15}\n``` {.python .cell-code}\n# Survival curve at specific times: probability of being alive past each time point\naft.predict(newdata, type=\"survival\", times=[180, 365, 730], format=\"polars\")\n```\n\n::: {.cell-output .cell-output-display execution_count=15}\n```{=html}\n<div id=\"gd-tbl-bfc0fb2d\" class=\"gd-tbl-preview\" style=\"padding-left: 0px; overflow-x: auto; overflow-y: hidden; width: 100%; max-width: 100%; margin-bottom: 1em;\">\n<style>\n@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,600;1,400&family=IBM+Plex+Sans:wght@400;600&display=swap');\n#gd-tbl-bfc0fb2d .gt_table {\n  display: table;\n  border-collapse: collapse;\n  table-layout: fixed;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 14px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n}\n#gd-tbl-bfc0fb2d .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-bfc0fb2d .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n#gd-tbl-bfc0fb2d .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n#gd-tbl-bfc0fb2d .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n#gd-tbl-bfc0fb2d .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-bfc0fb2d .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #F2F2F2;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #F2F2F2;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n#gd-tbl-bfc0fb2d .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n}\n#gd-tbl-bfc0fb2d .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #E9E9E9;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #E9E9E9;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #E9E9E9;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n#gd-tbl-bfc0fb2d .gt_left { text-align: left; }\n#gd-tbl-bfc0fb2d .gt_center { text-align: center; }\n#gd-tbl-bfc0fb2d .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n#gd-tbl-bfc0fb2d .gt_font_normal { font-weight: normal; }\n#gd-tbl-bfc0fb2d .gt_font_bold { font-weight: bold; }\n#gd-tbl-bfc0fb2d .gt_font_italic { font-style: italic; }\n#gd-tbl-bfc0fb2d .gt_striped { background-color: rgba(128,128,128,0.05); }\n#gd-tbl-bfc0fb2d .gt_from_md > :first-child { margin-top: 0; }\n#gd-tbl-bfc0fb2d .gt_from_md > :last-child { margin-bottom: 0; }\n/* Data cell font */\n#gd-tbl-bfc0fb2d .gt_table_body .gt_row {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  height: 14px;\n}\n/* Column label font */\n#gd-tbl-bfc0fb2d .gt_col_heading {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n}\n/* Row number styling */\n#gd-tbl-bfc0fb2d .gd-tbl-rownum {\n  color: gray;\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 10px;\n  border-right: 2px solid rgba(102, 153, 204, 0.5) !important;\n  text-align: right;\n  padding-right: 6px;\n  white-space: nowrap;\n}\n/* Head/tail divider */\n#gd-tbl-bfc0fb2d tr.gd-tbl-divider td,\n#gd-tbl-bfc0fb2d tr.gd-tbl-divider th {\n  border-bottom: 2px solid rgba(102, 153, 204, 0.5);\n}\n/* Missing values */\n#gd-tbl-bfc0fb2d .gd-tbl-missing {\n  color: #B22222 !important;\n  background-color: rgba(255, 193, 193, 0.35);\n}\n/* Column label sub-elements */\n#gd-tbl-bfc0fb2d .gd-tbl-colname {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-bottom: 0;\n  margin-bottom: 0;\n}\n#gd-tbl-bfc0fb2d .gd-tbl-dtype {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-top: 0;\n  margin-top: 0;\n  color: #666666;\n}\n/* Header badge styling */\n#gd-tbl-bfc0fb2d .gd-tbl-badge {\n  display: inline-block;\n  padding: 2px 10px;\n  font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, sans-serif;\n  font-size: 10px;\n  font-weight: bold;\n  text-transform: uppercase;\n  position: inherit;\n}\n#gd-tbl-bfc0fb2d .gd-tbl-badge-rows-label {\n  background-color: #eecbff;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: 5px;\n}\n#gd-tbl-bfc0fb2d .gd-tbl-badge-rows-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: -4px;\n  margin-right: 3px;\n}\n#gd-tbl-bfc0fb2d .gd-tbl-badge-cols-label {\n  background-color: #BDE7B4;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n}\n#gd-tbl-bfc0fb2d .gd-tbl-badge-cols-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n  margin-left: -4px;\n}\n/* Dark mode */\nbody.quarto-dark #gd-tbl-bfc0fb2d .gt_table,\nhtml.quarto-dark #gd-tbl-bfc0fb2d .gt_table,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bfc0fb2d .gt_table {\n  background-color: #1a1a2e;\n  color: #e0e0e0;\n  border-top-color: #555;\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-bfc0fb2d .gt_heading,\nhtml.quarto-dark #gd-tbl-bfc0fb2d .gt_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bfc0fb2d .gt_heading {\n  background-color: #1a1a2e;\n  border-bottom-color: #1a1a2e;\n}\nbody.quarto-dark #gd-tbl-bfc0fb2d .gt_title,\nhtml.quarto-dark #gd-tbl-bfc0fb2d .gt_title,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bfc0fb2d .gt_title {\n  color: #e0e0e0;\n}\nbody.quarto-dark #gd-tbl-bfc0fb2d .gt_subtitle,\nhtml.quarto-dark #gd-tbl-bfc0fb2d .gt_subtitle,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bfc0fb2d .gt_subtitle {\n  color: #b0b0b0;\n}\nbody.quarto-dark #gd-tbl-bfc0fb2d .gt_col_headings,\nhtml.quarto-dark #gd-tbl-bfc0fb2d .gt_col_headings,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bfc0fb2d .gt_col_headings {\n  border-top-color: #444;\n  border-bottom-color: #444;\n}\nbody.quarto-dark #gd-tbl-bfc0fb2d .gt_col_heading,\nhtml.quarto-dark #gd-tbl-bfc0fb2d .gt_col_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bfc0fb2d .gt_col_heading {\n  color: #b0b0b0;\n  background-color: #1a1a2e;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-bfc0fb2d .gt_table_body,\nhtml.quarto-dark #gd-tbl-bfc0fb2d .gt_table_body,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bfc0fb2d .gt_table_body {\n  border-top-color: #444;\n}\nbody.quarto-dark #gd-tbl-bfc0fb2d .gt_table_body .gt_row,\nhtml.quarto-dark #gd-tbl-bfc0fb2d .gt_table_body .gt_row,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bfc0fb2d .gt_table_body .gt_row {\n  color: #d0d0d0;\n  border-top-color: #4b4b4b;\n  border-bottom-color: #4b4b4b;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-bfc0fb2d .gd-tbl-rownum,\nhtml.quarto-dark #gd-tbl-bfc0fb2d .gd-tbl-rownum,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bfc0fb2d .gd-tbl-rownum {\n  color: #888;\n  border-right-color: rgba(102, 153, 204, 0.4) !important;\n}\nbody.quarto-dark #gd-tbl-bfc0fb2d .gd-tbl-missing,\nhtml.quarto-dark #gd-tbl-bfc0fb2d .gd-tbl-missing,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bfc0fb2d .gd-tbl-missing {\n  color: #ff6b6b !important;\n  background-color: rgba(60, 17, 24, 0.2);\n}\nbody.quarto-dark #gd-tbl-bfc0fb2d .gd-tbl-dtype,\nhtml.quarto-dark #gd-tbl-bfc0fb2d .gd-tbl-dtype,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bfc0fb2d .gd-tbl-dtype {\n  color: #888;\n}\nbody.quarto-dark #gd-tbl-bfc0fb2d .gt_bottom_border,\nhtml.quarto-dark #gd-tbl-bfc0fb2d .gt_bottom_border,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bfc0fb2d .gt_bottom_border {\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-bfc0fb2d .gd-tbl-badge-rows-label,\nhtml.quarto-dark #gd-tbl-bfc0fb2d .gd-tbl-badge-rows-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bfc0fb2d .gd-tbl-badge-rows-label {\n  background-color: #3d2a4d;\n  border-color: #3d2a4d;\n  color: #e0c0ff;\n}\nbody.quarto-dark #gd-tbl-bfc0fb2d .gd-tbl-badge-rows-value,\nhtml.quarto-dark #gd-tbl-bfc0fb2d .gd-tbl-badge-rows-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bfc0fb2d .gd-tbl-badge-rows-value {\n  border-color: #3d2a4d;\n  color: #d0b0e0;\n}\nbody.quarto-dark #gd-tbl-bfc0fb2d .gd-tbl-badge-cols-label,\nhtml.quarto-dark #gd-tbl-bfc0fb2d .gd-tbl-badge-cols-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bfc0fb2d .gd-tbl-badge-cols-label {\n  background-color: #2a4d2a;\n  border-color: #2a4d2a;\n  color: #b0e0b0;\n}\nbody.quarto-dark #gd-tbl-bfc0fb2d .gd-tbl-badge-cols-value,\nhtml.quarto-dark #gd-tbl-bfc0fb2d .gd-tbl-badge-cols-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-bfc0fb2d .gd-tbl-badge-cols-value {\n  border-color: #2a4d2a;\n  color: #a0d0a0;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"true\" data-quarto-bootstrap=\"false\">\n<colgroup>\n<col style=\"width: 35px\"/>\n<col style=\"width: 108px\"/>\n<col style=\"width: 175px\"/>\n<col style=\"width: 182px\"/>\n</colgroup>\n<thead>\n<tr class=\"gt_heading\"><td class=\"gt_heading gt_title gt_font_normal\" colspan=\"4\"><div style=\"padding-top: 0; padding-bottom: 7px;\"><span class=\"gd-tbl-badge\" style=\"background-color: #0075FF; color: #FFFFFF; border: 1px solid #0075FF; margin-right: 8px;\">Polars</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-label\">Rows</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-value\">3</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-label\">Columns</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-value\">3</span></div></td></tr>\n<tr class=\"gt_col_headings\">\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\"></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"time\"><div><div class=\"gd-tbl-colname\">time</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"subject_1\"><div><div class=\"gd-tbl-colname\">subject_1</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"subject_2\"><div><div class=\"gd-tbl-colname\">subject_2</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 108px;\">180</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 175px;\">0.723657198394</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 182px;\">0.639099089283</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 108px;\">365</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 175px;\">0.437820768409</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 182px;\">0.318778859044</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 108px;\">730</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 175px;\">0.126066714828</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 182px;\">0.0568943192275</td>\n</tr>\n</tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nEach column is a subject and each row a requested time, giving the estimated probability of\nsurviving past that time.\n\n## Flexible parametric (Royston-Parmar) models\n\nThe AFT distributions impose a fixed hazard shape. When none of them fits well but you still want\nthe smooth, extrapolatable curves of a parametric model, a Royston-Parmar model is a good middle\nground. It models the log cumulative hazard as a restricted cubic spline in log time, so the\nbaseline shape is estimated from the data rather than assumed. The flexibility is set by `df=`, the\nnumber of spline degrees of freedom.\n\n::: {#28fc05cd .cell execution_count=16}\n``` {.python .cell-code}\n# Fit a Royston-Parmar flexible-parametric model (3 spline degrees of freedom)\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\ny = gw.Surv.right(lung[\"time\"], event=(lung[\"status\"] == 2))\n\nrp = gw.RoystonParmar(df=3).fit(y, lung[[\"age\", \"sex\"]])\n\n# Display the spline and covariate coefficients\nrp.to_frame(format=\"polars\")\n```\n\n::: {.cell-output .cell-output-display execution_count=16}\n```{=html}\n<div id=\"gd-tbl-1be694cb\" class=\"gd-tbl-preview\" style=\"padding-left: 0px; overflow-x: auto; overflow-y: hidden; width: 100%; max-width: 100%; margin-bottom: 1em;\">\n<style>\n@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,600;1,400&family=IBM+Plex+Sans:wght@400;600&display=swap');\n#gd-tbl-1be694cb .gt_table {\n  display: table;\n  border-collapse: collapse;\n  table-layout: fixed;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 14px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n}\n#gd-tbl-1be694cb .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-1be694cb .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n#gd-tbl-1be694cb .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n#gd-tbl-1be694cb .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n#gd-tbl-1be694cb .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-1be694cb .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #F2F2F2;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #F2F2F2;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n#gd-tbl-1be694cb .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n}\n#gd-tbl-1be694cb .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #E9E9E9;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #E9E9E9;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #E9E9E9;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n#gd-tbl-1be694cb .gt_left { text-align: left; }\n#gd-tbl-1be694cb .gt_center { text-align: center; }\n#gd-tbl-1be694cb .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n#gd-tbl-1be694cb .gt_font_normal { font-weight: normal; }\n#gd-tbl-1be694cb .gt_font_bold { font-weight: bold; }\n#gd-tbl-1be694cb .gt_font_italic { font-style: italic; }\n#gd-tbl-1be694cb .gt_striped { background-color: rgba(128,128,128,0.05); }\n#gd-tbl-1be694cb .gt_from_md > :first-child { margin-top: 0; }\n#gd-tbl-1be694cb .gt_from_md > :last-child { margin-bottom: 0; }\n/* Data cell font */\n#gd-tbl-1be694cb .gt_table_body .gt_row {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  height: 14px;\n}\n/* Column label font */\n#gd-tbl-1be694cb .gt_col_heading {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n}\n/* Row number styling */\n#gd-tbl-1be694cb .gd-tbl-rownum {\n  color: gray;\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 10px;\n  border-right: 2px solid rgba(102, 153, 204, 0.5) !important;\n  text-align: right;\n  padding-right: 6px;\n  white-space: nowrap;\n}\n/* Head/tail divider */\n#gd-tbl-1be694cb tr.gd-tbl-divider td,\n#gd-tbl-1be694cb tr.gd-tbl-divider th {\n  border-bottom: 2px solid rgba(102, 153, 204, 0.5);\n}\n/* Missing values */\n#gd-tbl-1be694cb .gd-tbl-missing {\n  color: #B22222 !important;\n  background-color: rgba(255, 193, 193, 0.35);\n}\n/* Column label sub-elements */\n#gd-tbl-1be694cb .gd-tbl-colname {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-bottom: 0;\n  margin-bottom: 0;\n}\n#gd-tbl-1be694cb .gd-tbl-dtype {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-top: 0;\n  margin-top: 0;\n  color: #666666;\n}\n/* Header badge styling */\n#gd-tbl-1be694cb .gd-tbl-badge {\n  display: inline-block;\n  padding: 2px 10px;\n  font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, sans-serif;\n  font-size: 10px;\n  font-weight: bold;\n  text-transform: uppercase;\n  position: inherit;\n}\n#gd-tbl-1be694cb .gd-tbl-badge-rows-label {\n  background-color: #eecbff;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: 5px;\n}\n#gd-tbl-1be694cb .gd-tbl-badge-rows-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: -4px;\n  margin-right: 3px;\n}\n#gd-tbl-1be694cb .gd-tbl-badge-cols-label {\n  background-color: #BDE7B4;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n}\n#gd-tbl-1be694cb .gd-tbl-badge-cols-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n  margin-left: -4px;\n}\n/* Dark mode */\nbody.quarto-dark #gd-tbl-1be694cb .gt_table,\nhtml.quarto-dark #gd-tbl-1be694cb .gt_table,\n:root[data-bs-theme=\"dark\"] #gd-tbl-1be694cb .gt_table {\n  background-color: #1a1a2e;\n  color: #e0e0e0;\n  border-top-color: #555;\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-1be694cb .gt_heading,\nhtml.quarto-dark #gd-tbl-1be694cb .gt_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-1be694cb .gt_heading {\n  background-color: #1a1a2e;\n  border-bottom-color: #1a1a2e;\n}\nbody.quarto-dark #gd-tbl-1be694cb .gt_title,\nhtml.quarto-dark #gd-tbl-1be694cb .gt_title,\n:root[data-bs-theme=\"dark\"] #gd-tbl-1be694cb .gt_title {\n  color: #e0e0e0;\n}\nbody.quarto-dark #gd-tbl-1be694cb .gt_subtitle,\nhtml.quarto-dark #gd-tbl-1be694cb .gt_subtitle,\n:root[data-bs-theme=\"dark\"] #gd-tbl-1be694cb .gt_subtitle {\n  color: #b0b0b0;\n}\nbody.quarto-dark #gd-tbl-1be694cb .gt_col_headings,\nhtml.quarto-dark #gd-tbl-1be694cb .gt_col_headings,\n:root[data-bs-theme=\"dark\"] #gd-tbl-1be694cb .gt_col_headings {\n  border-top-color: #444;\n  border-bottom-color: #444;\n}\nbody.quarto-dark #gd-tbl-1be694cb .gt_col_heading,\nhtml.quarto-dark #gd-tbl-1be694cb .gt_col_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-1be694cb .gt_col_heading {\n  color: #b0b0b0;\n  background-color: #1a1a2e;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-1be694cb .gt_table_body,\nhtml.quarto-dark #gd-tbl-1be694cb .gt_table_body,\n:root[data-bs-theme=\"dark\"] #gd-tbl-1be694cb .gt_table_body {\n  border-top-color: #444;\n}\nbody.quarto-dark #gd-tbl-1be694cb .gt_table_body .gt_row,\nhtml.quarto-dark #gd-tbl-1be694cb .gt_table_body .gt_row,\n:root[data-bs-theme=\"dark\"] #gd-tbl-1be694cb .gt_table_body .gt_row {\n  color: #d0d0d0;\n  border-top-color: #4b4b4b;\n  border-bottom-color: #4b4b4b;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-1be694cb .gd-tbl-rownum,\nhtml.quarto-dark #gd-tbl-1be694cb .gd-tbl-rownum,\n:root[data-bs-theme=\"dark\"] #gd-tbl-1be694cb .gd-tbl-rownum {\n  color: #888;\n  border-right-color: rgba(102, 153, 204, 0.4) !important;\n}\nbody.quarto-dark #gd-tbl-1be694cb .gd-tbl-missing,\nhtml.quarto-dark #gd-tbl-1be694cb .gd-tbl-missing,\n:root[data-bs-theme=\"dark\"] #gd-tbl-1be694cb .gd-tbl-missing {\n  color: #ff6b6b !important;\n  background-color: rgba(60, 17, 24, 0.2);\n}\nbody.quarto-dark #gd-tbl-1be694cb .gd-tbl-dtype,\nhtml.quarto-dark #gd-tbl-1be694cb .gd-tbl-dtype,\n:root[data-bs-theme=\"dark\"] #gd-tbl-1be694cb .gd-tbl-dtype {\n  color: #888;\n}\nbody.quarto-dark #gd-tbl-1be694cb .gt_bottom_border,\nhtml.quarto-dark #gd-tbl-1be694cb .gt_bottom_border,\n:root[data-bs-theme=\"dark\"] #gd-tbl-1be694cb .gt_bottom_border {\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-1be694cb .gd-tbl-badge-rows-label,\nhtml.quarto-dark #gd-tbl-1be694cb .gd-tbl-badge-rows-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-1be694cb .gd-tbl-badge-rows-label {\n  background-color: #3d2a4d;\n  border-color: #3d2a4d;\n  color: #e0c0ff;\n}\nbody.quarto-dark #gd-tbl-1be694cb .gd-tbl-badge-rows-value,\nhtml.quarto-dark #gd-tbl-1be694cb .gd-tbl-badge-rows-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-1be694cb .gd-tbl-badge-rows-value {\n  border-color: #3d2a4d;\n  color: #d0b0e0;\n}\nbody.quarto-dark #gd-tbl-1be694cb .gd-tbl-badge-cols-label,\nhtml.quarto-dark #gd-tbl-1be694cb .gd-tbl-badge-cols-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-1be694cb .gd-tbl-badge-cols-label {\n  background-color: #2a4d2a;\n  border-color: #2a4d2a;\n  color: #b0e0b0;\n}\nbody.quarto-dark #gd-tbl-1be694cb .gd-tbl-badge-cols-value,\nhtml.quarto-dark #gd-tbl-1be694cb .gd-tbl-badge-cols-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-1be694cb .gd-tbl-badge-cols-value {\n  border-color: #2a4d2a;\n  color: #a0d0a0;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"true\" data-quarto-bootstrap=\"false\">\n<colgroup>\n<col style=\"width: 35px\"/>\n<col style=\"width: 59px\"/>\n<col style=\"width: 131px\"/>\n<col style=\"width: 124px\"/>\n<col style=\"width: 124px\"/>\n<col style=\"width: 138px\"/>\n<col style=\"width: 138px\"/>\n<col style=\"width: 124px\"/>\n</colgroup>\n<thead>\n<tr class=\"gt_heading\"><td class=\"gt_heading gt_title gt_font_normal\" colspan=\"8\"><div style=\"padding-top: 0; padding-bottom: 7px;\"><span class=\"gd-tbl-badge\" style=\"background-color: #0075FF; color: #FFFFFF; border: 1px solid #0075FF; margin-right: 8px;\">Polars</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-label\">Rows</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-value\">6</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-label\">Columns</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-value\">7</span></div></td></tr>\n<tr class=\"gt_col_headings\">\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\"></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\"><div><div class=\"gd-tbl-colname\">term</div><div class=\"gd-tbl-dtype\"><em>str</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><div><div class=\"gd-tbl-colname\">estimate</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std_error\"><div><div class=\"gd-tbl-colname\">std_error</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\"><div><div class=\"gd-tbl-colname\">statistic</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p_value\"><div><div class=\"gd-tbl-colname\">p_value</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf_low\"><div><div class=\"gd-tbl-colname\">conf_low</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf_high\"><div><div class=\"gd-tbl-colname\">conf_high</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">0</td>\n<td class=\"gt_row gt_left\" style=\"max-width: 59px;\">gamma0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 131px;\">-7.22846438615</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 124px;\">1.32609527414</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 124px;\">-5.45093895371</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 138px;\">5.0104568809e-08</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 138px;\">-9.82756336353</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 124px;\">-4.62936540876</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">1</td>\n<td class=\"gt_row gt_left\" style=\"max-width: 59px;\">gamma1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 131px;\">1.02751318673</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 124px;\">0.296797465595</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 124px;\">3.46200121578</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 138px;\">0.000536174733159</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 138px;\">0.445800843461</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 124px;\">1.60922553</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">2</td>\n<td class=\"gt_row gt_left\" style=\"max-width: 59px;\">gamma2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 131px;\">-0.0964198530341</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 124px;\">0.129713726754</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 124px;\">-0.743328061314</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 138px;\">0.457283086384</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 138px;\">-0.350654085773</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 124px;\">0.157814379705</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">3</td>\n<td class=\"gt_row gt_left\" style=\"max-width: 59px;\">gamma3</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 131px;\">0.117232173258</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 124px;\">0.18493276195</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 124px;\">0.633917819763</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 138px;\">0.526134455489</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 138px;\">-0.245229379726</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 124px;\">0.479693726242</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">4</td>\n<td class=\"gt_row gt_left\" style=\"max-width: 59px;\">age</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 131px;\">0.0161469261877</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 124px;\">0.0091925791922</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 124px;\">1.75651749635</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 138px;\">0.0790000866033</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 138px;\">-0.00187019795402</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 124px;\">0.0341640503295</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">5</td>\n<td class=\"gt_row gt_left\" style=\"max-width: 59px;\">sex</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 131px;\">-0.510126834073</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 124px;\">0.167162261846</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 124px;\">-3.05168659744</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 138px;\">0.00227559559524</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 138px;\">-0.837758846865</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 124px;\">-0.182494821281</td>\n</tr>\n</tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThe `gamma` terms are the spline coefficients for the baseline log cumulative hazard, and the named\nterms are the covariate effects on that scale.\n\n### Choosing the degrees of freedom\n\nThe `df=` parameter controls spline flexibility. `df=1` is exactly a Weibull model (no spline);\nhigher values let the hazard adapt to the data shape. More flexibility fits the observed data better\nbut risks overfitting and unstable extrapolation.\n\n::: {#ba0d1bff .cell execution_count=17}\n``` {.python .cell-code}\n# Sweep across spline degrees of freedom to find the best-fitting complexity\nresults = []\nfor df in (1, 2, 3, 4, 5):\n    rp_df = gw.RoystonParmar(df=df).fit(y, lung[[\"age\", \"sex\"]])\n    results.append({\"df\": df, \"loglik\": rp_df.loglik_})\n\n# Display the improvement (or lack thereof) as df increases\ncomparison = pd.DataFrame(results)\nprint(comparison)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   df       loglik\n0   1 -1147.054431\n1   2 -1146.810064\n2   3 -1146.570537\n3   4 -1146.438891\n4   5 -1146.513762\n```\n:::\n:::\n\n\nNotice that loglik generally improves up to `df=3`, after which gains diminish, suggesting that\nadditional flexibility is not justified by the data. Two or three degrees of freedom are typical\ndefaults. Choose based on the trade-off between fit and complexity:\n\n- **df=1**: equivalent to Weibull (simplest).\n- **df=2-3**: common choices (balances parsimony and fit).\n- **df=4+**: use only if AIC clearly favors it and validation shows good extrapolation.\n\nPrediction works as for the AFT model, with survival, hazard, or cumulative hazard curves.\n\n::: {#e83c3ebf .cell execution_count=18}\n``` {.python .cell-code}\n# Two new subjects for prediction from the Royston-Parmar model\nnewdata = pd.DataFrame({\"age\": [50, 70], \"sex\": [1, 1]})\n\n# Predicted survival at 6 months, 1 year, and 2 years\nrp.predict(newdata, type=\"survival\", times=[180, 365, 730], format=\"polars\")\n```\n\n::: {.cell-output .cell-output-display execution_count=18}\n```{=html}\n<div id=\"gd-tbl-184f8247\" class=\"gd-tbl-preview\" style=\"padding-left: 0px; overflow-x: auto; overflow-y: hidden; width: 100%; max-width: 100%; margin-bottom: 1em;\">\n<style>\n@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,600;1,400&family=IBM+Plex+Sans:wght@400;600&display=swap');\n#gd-tbl-184f8247 .gt_table {\n  display: table;\n  border-collapse: collapse;\n  table-layout: fixed;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 14px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n}\n#gd-tbl-184f8247 .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-184f8247 .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n#gd-tbl-184f8247 .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n#gd-tbl-184f8247 .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n#gd-tbl-184f8247 .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-184f8247 .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #F2F2F2;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #F2F2F2;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n#gd-tbl-184f8247 .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n}\n#gd-tbl-184f8247 .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #E9E9E9;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #E9E9E9;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #E9E9E9;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n#gd-tbl-184f8247 .gt_left { text-align: left; }\n#gd-tbl-184f8247 .gt_center { text-align: center; }\n#gd-tbl-184f8247 .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n#gd-tbl-184f8247 .gt_font_normal { font-weight: normal; }\n#gd-tbl-184f8247 .gt_font_bold { font-weight: bold; }\n#gd-tbl-184f8247 .gt_font_italic { font-style: italic; }\n#gd-tbl-184f8247 .gt_striped { background-color: rgba(128,128,128,0.05); }\n#gd-tbl-184f8247 .gt_from_md > :first-child { margin-top: 0; }\n#gd-tbl-184f8247 .gt_from_md > :last-child { margin-bottom: 0; }\n/* Data cell font */\n#gd-tbl-184f8247 .gt_table_body .gt_row {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  height: 14px;\n}\n/* Column label font */\n#gd-tbl-184f8247 .gt_col_heading {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n}\n/* Row number styling */\n#gd-tbl-184f8247 .gd-tbl-rownum {\n  color: gray;\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 10px;\n  border-right: 2px solid rgba(102, 153, 204, 0.5) !important;\n  text-align: right;\n  padding-right: 6px;\n  white-space: nowrap;\n}\n/* Head/tail divider */\n#gd-tbl-184f8247 tr.gd-tbl-divider td,\n#gd-tbl-184f8247 tr.gd-tbl-divider th {\n  border-bottom: 2px solid rgba(102, 153, 204, 0.5);\n}\n/* Missing values */\n#gd-tbl-184f8247 .gd-tbl-missing {\n  color: #B22222 !important;\n  background-color: rgba(255, 193, 193, 0.35);\n}\n/* Column label sub-elements */\n#gd-tbl-184f8247 .gd-tbl-colname {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-bottom: 0;\n  margin-bottom: 0;\n}\n#gd-tbl-184f8247 .gd-tbl-dtype {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-top: 0;\n  margin-top: 0;\n  color: #666666;\n}\n/* Header badge styling */\n#gd-tbl-184f8247 .gd-tbl-badge {\n  display: inline-block;\n  padding: 2px 10px;\n  font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, sans-serif;\n  font-size: 10px;\n  font-weight: bold;\n  text-transform: uppercase;\n  position: inherit;\n}\n#gd-tbl-184f8247 .gd-tbl-badge-rows-label {\n  background-color: #eecbff;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: 5px;\n}\n#gd-tbl-184f8247 .gd-tbl-badge-rows-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: -4px;\n  margin-right: 3px;\n}\n#gd-tbl-184f8247 .gd-tbl-badge-cols-label {\n  background-color: #BDE7B4;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n}\n#gd-tbl-184f8247 .gd-tbl-badge-cols-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n  margin-left: -4px;\n}\n/* Dark mode */\nbody.quarto-dark #gd-tbl-184f8247 .gt_table,\nhtml.quarto-dark #gd-tbl-184f8247 .gt_table,\n:root[data-bs-theme=\"dark\"] #gd-tbl-184f8247 .gt_table {\n  background-color: #1a1a2e;\n  color: #e0e0e0;\n  border-top-color: #555;\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-184f8247 .gt_heading,\nhtml.quarto-dark #gd-tbl-184f8247 .gt_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-184f8247 .gt_heading {\n  background-color: #1a1a2e;\n  border-bottom-color: #1a1a2e;\n}\nbody.quarto-dark #gd-tbl-184f8247 .gt_title,\nhtml.quarto-dark #gd-tbl-184f8247 .gt_title,\n:root[data-bs-theme=\"dark\"] #gd-tbl-184f8247 .gt_title {\n  color: #e0e0e0;\n}\nbody.quarto-dark #gd-tbl-184f8247 .gt_subtitle,\nhtml.quarto-dark #gd-tbl-184f8247 .gt_subtitle,\n:root[data-bs-theme=\"dark\"] #gd-tbl-184f8247 .gt_subtitle {\n  color: #b0b0b0;\n}\nbody.quarto-dark #gd-tbl-184f8247 .gt_col_headings,\nhtml.quarto-dark #gd-tbl-184f8247 .gt_col_headings,\n:root[data-bs-theme=\"dark\"] #gd-tbl-184f8247 .gt_col_headings {\n  border-top-color: #444;\n  border-bottom-color: #444;\n}\nbody.quarto-dark #gd-tbl-184f8247 .gt_col_heading,\nhtml.quarto-dark #gd-tbl-184f8247 .gt_col_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-184f8247 .gt_col_heading {\n  color: #b0b0b0;\n  background-color: #1a1a2e;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-184f8247 .gt_table_body,\nhtml.quarto-dark #gd-tbl-184f8247 .gt_table_body,\n:root[data-bs-theme=\"dark\"] #gd-tbl-184f8247 .gt_table_body {\n  border-top-color: #444;\n}\nbody.quarto-dark #gd-tbl-184f8247 .gt_table_body .gt_row,\nhtml.quarto-dark #gd-tbl-184f8247 .gt_table_body .gt_row,\n:root[data-bs-theme=\"dark\"] #gd-tbl-184f8247 .gt_table_body .gt_row {\n  color: #d0d0d0;\n  border-top-color: #4b4b4b;\n  border-bottom-color: #4b4b4b;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-184f8247 .gd-tbl-rownum,\nhtml.quarto-dark #gd-tbl-184f8247 .gd-tbl-rownum,\n:root[data-bs-theme=\"dark\"] #gd-tbl-184f8247 .gd-tbl-rownum {\n  color: #888;\n  border-right-color: rgba(102, 153, 204, 0.4) !important;\n}\nbody.quarto-dark #gd-tbl-184f8247 .gd-tbl-missing,\nhtml.quarto-dark #gd-tbl-184f8247 .gd-tbl-missing,\n:root[data-bs-theme=\"dark\"] #gd-tbl-184f8247 .gd-tbl-missing {\n  color: #ff6b6b !important;\n  background-color: rgba(60, 17, 24, 0.2);\n}\nbody.quarto-dark #gd-tbl-184f8247 .gd-tbl-dtype,\nhtml.quarto-dark #gd-tbl-184f8247 .gd-tbl-dtype,\n:root[data-bs-theme=\"dark\"] #gd-tbl-184f8247 .gd-tbl-dtype {\n  color: #888;\n}\nbody.quarto-dark #gd-tbl-184f8247 .gt_bottom_border,\nhtml.quarto-dark #gd-tbl-184f8247 .gt_bottom_border,\n:root[data-bs-theme=\"dark\"] #gd-tbl-184f8247 .gt_bottom_border {\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-184f8247 .gd-tbl-badge-rows-label,\nhtml.quarto-dark #gd-tbl-184f8247 .gd-tbl-badge-rows-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-184f8247 .gd-tbl-badge-rows-label {\n  background-color: #3d2a4d;\n  border-color: #3d2a4d;\n  color: #e0c0ff;\n}\nbody.quarto-dark #gd-tbl-184f8247 .gd-tbl-badge-rows-value,\nhtml.quarto-dark #gd-tbl-184f8247 .gd-tbl-badge-rows-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-184f8247 .gd-tbl-badge-rows-value {\n  border-color: #3d2a4d;\n  color: #d0b0e0;\n}\nbody.quarto-dark #gd-tbl-184f8247 .gd-tbl-badge-cols-label,\nhtml.quarto-dark #gd-tbl-184f8247 .gd-tbl-badge-cols-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-184f8247 .gd-tbl-badge-cols-label {\n  background-color: #2a4d2a;\n  border-color: #2a4d2a;\n  color: #b0e0b0;\n}\nbody.quarto-dark #gd-tbl-184f8247 .gd-tbl-badge-cols-value,\nhtml.quarto-dark #gd-tbl-184f8247 .gd-tbl-badge-cols-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-184f8247 .gd-tbl-badge-cols-value {\n  border-color: #2a4d2a;\n  color: #a0d0a0;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"true\" data-quarto-bootstrap=\"false\">\n<colgroup>\n<col style=\"width: 35px\"/>\n<col style=\"width: 108px\"/>\n<col style=\"width: 175px\"/>\n<col style=\"width: 182px\"/>\n</colgroup>\n<thead>\n<tr class=\"gt_heading\"><td class=\"gt_heading gt_title gt_font_normal\" colspan=\"4\"><div style=\"padding-top: 0; padding-bottom: 7px;\"><span class=\"gd-tbl-badge\" style=\"background-color: #0075FF; color: #FFFFFF; border: 1px solid #0075FF; margin-right: 8px;\">Polars</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-label\">Rows</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-value\">3</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-label\">Columns</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-value\">3</span></div></td></tr>\n<tr class=\"gt_col_headings\">\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\"></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"time\"><div><div class=\"gd-tbl-colname\">time</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"subject_1\"><div><div class=\"gd-tbl-colname\">subject_1</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"subject_2\"><div><div class=\"gd-tbl-colname\">subject_2</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 108px;\">180</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 175px;\">0.732463442055</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 182px;\">0.650496559624</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 108px;\">365</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 175px;\">0.433699254697</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 182px;\">0.315422083546</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 108px;\">730</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 175px;\">0.123266928691</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 182px;\">0.0555002672218</td>\n</tr>\n</tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## Survival predictions with confidence intervals\n\nWhen predicting survival probabilities from an AFT model, you can also compute confidence intervals\nthat quantify uncertainty in the predictions. This is especially valuable when making personalized\nsurvival predictions for clinical use.\n\nConfidence intervals are computed via the delta-method, which propagates coefficient uncertainty\nthrough the survival function. Wider intervals indicate greater model uncertainty, often due to\ncovariate values that are far from the training data mean.\n\nPass `ci=True` to get confidence bounds alongside the survival probability:\n\n::: {#21cfda04 .cell execution_count=19}\n``` {.python .cell-code}\n# Refit the Weibull AFT for confidence interval demonstration\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\ny = gw.Surv.right(lung[\"time\"], event=(lung[\"status\"] == 2))\naft = gw.AFT(\"weibull\").fit(y, lung[[\"age\", \"sex\"]])\n\n# Two subjects with different covariate profiles\nnewdata = pd.DataFrame({\"age\": [50, 70], \"sex\": [1, 2]})\n\n# Predict survival with delta-method confidence intervals (log-log transform)\npredictions = aft.predict(\n    newdata, type=\"survival\", times=[180, 365, 730],\n    ci=True, conf_type=\"log-log\", format=\"polars\"\n)\n\n# Display the point estimates and their confidence bounds\npredictions\n```\n\n::: {.cell-output .cell-output-display execution_count=19}\n```{=html}\n<div id=\"gd-tbl-70572e43\" class=\"gd-tbl-preview\" style=\"padding-left: 0px; overflow-x: auto; overflow-y: hidden; width: 100%; max-width: 100%; margin-bottom: 1em;\">\n<style>\n@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,600;1,400&family=IBM+Plex+Sans:wght@400;600&display=swap');\n#gd-tbl-70572e43 .gt_table {\n  display: table;\n  border-collapse: collapse;\n  table-layout: fixed;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 14px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n}\n#gd-tbl-70572e43 .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-70572e43 .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n#gd-tbl-70572e43 .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n#gd-tbl-70572e43 .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n#gd-tbl-70572e43 .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-70572e43 .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #F2F2F2;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #F2F2F2;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n#gd-tbl-70572e43 .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n}\n#gd-tbl-70572e43 .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #E9E9E9;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #E9E9E9;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #E9E9E9;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n#gd-tbl-70572e43 .gt_left { text-align: left; }\n#gd-tbl-70572e43 .gt_center { text-align: center; }\n#gd-tbl-70572e43 .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n#gd-tbl-70572e43 .gt_font_normal { font-weight: normal; }\n#gd-tbl-70572e43 .gt_font_bold { font-weight: bold; }\n#gd-tbl-70572e43 .gt_font_italic { font-style: italic; }\n#gd-tbl-70572e43 .gt_striped { background-color: rgba(128,128,128,0.05); }\n#gd-tbl-70572e43 .gt_from_md > :first-child { margin-top: 0; }\n#gd-tbl-70572e43 .gt_from_md > :last-child { margin-bottom: 0; }\n/* Data cell font */\n#gd-tbl-70572e43 .gt_table_body .gt_row {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  height: 14px;\n}\n/* Column label font */\n#gd-tbl-70572e43 .gt_col_heading {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n}\n/* Row number styling */\n#gd-tbl-70572e43 .gd-tbl-rownum {\n  color: gray;\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 10px;\n  border-right: 2px solid rgba(102, 153, 204, 0.5) !important;\n  text-align: right;\n  padding-right: 6px;\n  white-space: nowrap;\n}\n/* Head/tail divider */\n#gd-tbl-70572e43 tr.gd-tbl-divider td,\n#gd-tbl-70572e43 tr.gd-tbl-divider th {\n  border-bottom: 2px solid rgba(102, 153, 204, 0.5);\n}\n/* Missing values */\n#gd-tbl-70572e43 .gd-tbl-missing {\n  color: #B22222 !important;\n  background-color: rgba(255, 193, 193, 0.35);\n}\n/* Column label sub-elements */\n#gd-tbl-70572e43 .gd-tbl-colname {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-bottom: 0;\n  margin-bottom: 0;\n}\n#gd-tbl-70572e43 .gd-tbl-dtype {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-top: 0;\n  margin-top: 0;\n  color: #666666;\n}\n/* Header badge styling */\n#gd-tbl-70572e43 .gd-tbl-badge {\n  display: inline-block;\n  padding: 2px 10px;\n  font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, sans-serif;\n  font-size: 10px;\n  font-weight: bold;\n  text-transform: uppercase;\n  position: inherit;\n}\n#gd-tbl-70572e43 .gd-tbl-badge-rows-label {\n  background-color: #eecbff;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: 5px;\n}\n#gd-tbl-70572e43 .gd-tbl-badge-rows-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: -4px;\n  margin-right: 3px;\n}\n#gd-tbl-70572e43 .gd-tbl-badge-cols-label {\n  background-color: #BDE7B4;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n}\n#gd-tbl-70572e43 .gd-tbl-badge-cols-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n  margin-left: -4px;\n}\n/* Dark mode */\nbody.quarto-dark #gd-tbl-70572e43 .gt_table,\nhtml.quarto-dark #gd-tbl-70572e43 .gt_table,\n:root[data-bs-theme=\"dark\"] #gd-tbl-70572e43 .gt_table {\n  background-color: #1a1a2e;\n  color: #e0e0e0;\n  border-top-color: #555;\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-70572e43 .gt_heading,\nhtml.quarto-dark #gd-tbl-70572e43 .gt_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-70572e43 .gt_heading {\n  background-color: #1a1a2e;\n  border-bottom-color: #1a1a2e;\n}\nbody.quarto-dark #gd-tbl-70572e43 .gt_title,\nhtml.quarto-dark #gd-tbl-70572e43 .gt_title,\n:root[data-bs-theme=\"dark\"] #gd-tbl-70572e43 .gt_title {\n  color: #e0e0e0;\n}\nbody.quarto-dark #gd-tbl-70572e43 .gt_subtitle,\nhtml.quarto-dark #gd-tbl-70572e43 .gt_subtitle,\n:root[data-bs-theme=\"dark\"] #gd-tbl-70572e43 .gt_subtitle {\n  color: #b0b0b0;\n}\nbody.quarto-dark #gd-tbl-70572e43 .gt_col_headings,\nhtml.quarto-dark #gd-tbl-70572e43 .gt_col_headings,\n:root[data-bs-theme=\"dark\"] #gd-tbl-70572e43 .gt_col_headings {\n  border-top-color: #444;\n  border-bottom-color: #444;\n}\nbody.quarto-dark #gd-tbl-70572e43 .gt_col_heading,\nhtml.quarto-dark #gd-tbl-70572e43 .gt_col_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-70572e43 .gt_col_heading {\n  color: #b0b0b0;\n  background-color: #1a1a2e;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-70572e43 .gt_table_body,\nhtml.quarto-dark #gd-tbl-70572e43 .gt_table_body,\n:root[data-bs-theme=\"dark\"] #gd-tbl-70572e43 .gt_table_body {\n  border-top-color: #444;\n}\nbody.quarto-dark #gd-tbl-70572e43 .gt_table_body .gt_row,\nhtml.quarto-dark #gd-tbl-70572e43 .gt_table_body .gt_row,\n:root[data-bs-theme=\"dark\"] #gd-tbl-70572e43 .gt_table_body .gt_row {\n  color: #d0d0d0;\n  border-top-color: #4b4b4b;\n  border-bottom-color: #4b4b4b;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-70572e43 .gd-tbl-rownum,\nhtml.quarto-dark #gd-tbl-70572e43 .gd-tbl-rownum,\n:root[data-bs-theme=\"dark\"] #gd-tbl-70572e43 .gd-tbl-rownum {\n  color: #888;\n  border-right-color: rgba(102, 153, 204, 0.4) !important;\n}\nbody.quarto-dark #gd-tbl-70572e43 .gd-tbl-missing,\nhtml.quarto-dark #gd-tbl-70572e43 .gd-tbl-missing,\n:root[data-bs-theme=\"dark\"] #gd-tbl-70572e43 .gd-tbl-missing {\n  color: #ff6b6b !important;\n  background-color: rgba(60, 17, 24, 0.2);\n}\nbody.quarto-dark #gd-tbl-70572e43 .gd-tbl-dtype,\nhtml.quarto-dark #gd-tbl-70572e43 .gd-tbl-dtype,\n:root[data-bs-theme=\"dark\"] #gd-tbl-70572e43 .gd-tbl-dtype {\n  color: #888;\n}\nbody.quarto-dark #gd-tbl-70572e43 .gt_bottom_border,\nhtml.quarto-dark #gd-tbl-70572e43 .gt_bottom_border,\n:root[data-bs-theme=\"dark\"] #gd-tbl-70572e43 .gt_bottom_border {\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-70572e43 .gd-tbl-badge-rows-label,\nhtml.quarto-dark #gd-tbl-70572e43 .gd-tbl-badge-rows-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-70572e43 .gd-tbl-badge-rows-label {\n  background-color: #3d2a4d;\n  border-color: #3d2a4d;\n  color: #e0c0ff;\n}\nbody.quarto-dark #gd-tbl-70572e43 .gd-tbl-badge-rows-value,\nhtml.quarto-dark #gd-tbl-70572e43 .gd-tbl-badge-rows-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-70572e43 .gd-tbl-badge-rows-value {\n  border-color: #3d2a4d;\n  color: #d0b0e0;\n}\nbody.quarto-dark #gd-tbl-70572e43 .gd-tbl-badge-cols-label,\nhtml.quarto-dark #gd-tbl-70572e43 .gd-tbl-badge-cols-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-70572e43 .gd-tbl-badge-cols-label {\n  background-color: #2a4d2a;\n  border-color: #2a4d2a;\n  color: #b0e0b0;\n}\nbody.quarto-dark #gd-tbl-70572e43 .gd-tbl-badge-cols-value,\nhtml.quarto-dark #gd-tbl-70572e43 .gd-tbl-badge-cols-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-70572e43 .gd-tbl-badge-cols-value {\n  border-color: #2a4d2a;\n  color: #a0d0a0;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"true\" data-quarto-bootstrap=\"false\">\n<colgroup>\n<col style=\"width: 35px\"/>\n<col style=\"width: 50px\"/>\n<col style=\"width: 117px\"/>\n<col style=\"width: 133px\"/>\n<col style=\"width: 133px\"/>\n<col style=\"width: 117px\"/>\n<col style=\"width: 133px\"/>\n<col style=\"width: 133px\"/>\n</colgroup>\n<thead>\n<tr class=\"gt_heading\"><td class=\"gt_heading gt_title gt_font_normal\" colspan=\"8\"><div style=\"padding-top: 0; padding-bottom: 7px;\"><span class=\"gd-tbl-badge\" style=\"background-color: #0075FF; color: #FFFFFF; border: 1px solid #0075FF; margin-right: 8px;\">Polars</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-label\">Rows</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-value\">3</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-label\">Columns</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-value\">7</span></div></td></tr>\n<tr class=\"gt_col_headings\">\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\"></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"time\"><div><div class=\"gd-tbl-colname\">time</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"subject_1\"><div><div class=\"gd-tbl-colname\">subject_1</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"subject_1_lower\"><div><div class=\"gd-tbl-colname\">subject_1_lower</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"subject_1_upper\"><div><div class=\"gd-tbl-colname\">subject_1_upper</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"subject_2\"><div><div class=\"gd-tbl-colname\">subject_2</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"subject_2_lower\"><div><div class=\"gd-tbl-colname\">subject_2_lower</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"subject_2_upper\"><div><div class=\"gd-tbl-colname\">subject_2_upper</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 50px;\">180</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.723657198394</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 133px;\">0.644182108512</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 133px;\">0.788300132548</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.763589325374</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 133px;\">0.694594995229</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 133px;\">0.81903096516</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 50px;\">365</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.437820768409</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 133px;\">0.325293389151</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 133px;\">0.544736721602</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.502186717452</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 133px;\">0.394310422343</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 133px;\">0.600619587507</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 50px;\">730</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.126066714828</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 133px;\">0.0598546494462</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 133px;\">0.21803422453</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 117px;\">0.177812008035</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 133px;\">0.0969662403084</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 133px;\">0.278528071515</td>\n</tr>\n</tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThe returned frame includes one column per subject with point estimates and confidence bounds:\n\n- `subject_1`: survival probability for subject 1\n- `subject_1_lower`, `subject_1_upper`: lower and upper confidence interval bounds for subject 1\n- (same pattern for subject 2, etc.)\n\nThe `conf_type=` parameter controls the confidence interval transform, just as with baseline\nhazard confidence intervals:\n\n- `\"log-log\"` (default): Uses a log-log transformation that ensures bounds respect the\nsurvival probability constraint (between 0 and 1). Recommended.\n- `\"plain\"`: Wald confidence intervals without transformation. Simpler but may produce\ninvalid bounds (survival < 0 or > 1).\n\nConfidence intervals are valuable for:\n\n- clinical decision-making: quantifying uncertainty in individual prognoses\n- study planning: assessing how precisely your model can predict for new subjects\n- model diagnostics: detecting when predictions are made far from the training data\n(wider intervals indicate extrapolation)\n\nThe width of the confidence interval grows as covariate values move further from the training\nmean, reflecting increased model uncertainty in extrapolated regions.\n\n## Mean survival and expected remaining lifetime\n\nSurvival curves and quantiles describe what happens at specific time points, but sometimes\nyou want a single summary number for each subject: how long are they expected to survive\noverall? How much longer should a censored subject expect to live given they have already\nreached their last follow-up time? These questions are answered by mean survival predictions\nand conditional expectations.\n\n### Unconditional mean survival\n\nUsing `type=\"mean\"` returns the expected survival time $E[T]$ for each subject under the fitted\ndistribution. Each distribution has a closed-form formula, so the calculation is exact and\nfast:\n\n- **Weibull/Exponential**: $E[T] = e^{\\mu}\\,\\Gamma(1+\\sigma)$\n- **Log-normal**: $E[T] = e^{\\mu + \\sigma^2/2}$\n- **Log-logistic** ($\\sigma < 1$): $E[T] = e^{\\mu}\\,\\pi\\sigma / \\sin(\\pi\\sigma)$\n\nwhere $\\mu = X\\beta$ is the log-time location for each subject and $\\sigma$ is the scale\nparameter.\n\n::: {#f001f174 .cell execution_count=20}\n``` {.python .cell-code}\n# Fit a log-normal AFT model (different distributional choice for illustration)\nlung = gw.load_dataset(\"lung\", backend=\"polars\")\ny = gw.Surv.right(lung[\"time\"], event=(lung[\"status\"] == 2))\naft = gw.AFT(\"lognormal\").fit(y, lung[[\"age\", \"sex\"]])\n\n# Two subjects for prediction\nnewdata = pd.DataFrame({\"age\": [50, 70], \"sex\": [1, 1]})\n\n# Unconditional expected survival time E[T] for each subject\naft.predict(newdata, type=\"mean\")\n```\n\n::: {.cell-output .cell-output-display execution_count=20}\n```\narray([551.96643754, 345.96965546])\n```\n:::\n:::\n\n\nThe returned array has one value per subject. The younger subject has a substantially higher\nexpected survival time, as expected.\n\n::: {.callout-note}\n## Log-logistic mean only exists when $\\sigma < 1$\n\nFor log-logistic, the mean is only finite when $\\sigma < 1$. When $\\sigma \\ge 1$ the\ndistribution has a heavy enough right tail that the mean diverges. In that case\n`type=\"mean\"` returns `np.inf`. Use `type=\"rmst\"` with a finite restriction time as an\nalternative summary.\n:::\n\n### Conditional mean survival given landmark time\n\nIn follow-up studies, subjects are often censored at different times. For a censored subject\nwho has already survived to time $t_0$, the relevant question is not \"how long will they\nsurvive in total?\" but \"how much longer can they expect to live?\" This is the conditional\nmean $E[T \\mid T > t_0]$, computed by passing `conditional_after`:\n\n::: {#3a29a0a9 .cell execution_count=21}\n``` {.python .cell-code}\n# Conditional mean given that each subject has already survived one year\naft.predict(newdata, type=\"mean\", conditional_after=365)\n```\n\n::: {.cell-output .cell-output-display execution_count=21}\n```\narray([1013.98560697,  837.9523237 ])\n```\n:::\n:::\n\n\nCompare with the unconditional mean to see how much being alive at one year updates the\nprognosis. The conditioning time can also be a per-subject array. This is useful when each\nsubject has a different follow-up time:\n\n::: {#bef89c72 .cell execution_count=22}\n``` {.python .cell-code}\nimport numpy as np\n\n# Each subject has a different last-known follow-up time (their landmark)\nlandmark_times = np.array([200.0, 400.0])\n\n# Conditional mean given each subject's own landmark\naft.predict(newdata, type=\"mean\", conditional_after=landmark_times)\n```\n\n::: {.cell-output .cell-output-display execution_count=22}\n```\narray([768.57588911, 889.45750323])\n```\n:::\n:::\n\n\n### Expected remaining lifetime\n\n`type=\"mean_remaining\"` computes the expected remaining lifetime $E[T - t_0 \\mid T > t_0]$\ndirectly. This is how much longer a subject is expected to survive past their landmark time:\n\n::: {#c804942d .cell execution_count=23}\n``` {.python .cell-code}\n# Expected additional lifetime beyond the landmark: E[T - t0 | T > t0]\nremaining = aft.predict(newdata, type=\"mean_remaining\", conditional_after=landmark_times)\nremaining\n```\n\n::: {.cell-output .cell-output-display execution_count=23}\n```\narray([568.57588911, 489.45750323])\n```\n:::\n:::\n\n\nThe relationship between the two quantities is exact:\n\n$$E[T \\mid T > t_0] = t_0 + E[T - t_0 \\mid T > t_0]$$\n\nso you can recover either from the other. The remaining-lifetime form is often more\ninterpretable in a clinical setting: \"given that you are alive today, you can expect\napproximately X more months.\"\n\n::: {.callout-tip}\n## The memoryless exponential\n\nUnder an exponential (constant-hazard) model, $E[T - t_0 \\mid T > t_0] = E[T]$ for\nall $t_0$. The expected remaining life never changes, regardless of how long the\nsubject has already survived (the defining property of the exponential distribution).\n:::\n\n## Restricted mean survival time\n\nThe restricted mean survival time (RMST) at horizon $\\tau$ is the area under the survival\ncurve from 0 to $\\tau$:\n\n$$\\text{RMST}(\\tau) = E[\\min(T, \\tau)] = \\int_0^\\tau S(t)\\,dt$$\n\nIt answers the question \"on average, how many days of event-free follow-up does a subject\naccumulate within the first $\\tau$ days?\" Unlike the mean, it is always finite regardless of\nthe distribution's tail behaviour, and it avoids the need to extrapolate beyond the\nobservation window.\n\nUse `type=\"rmst\"` with the `tau` argument:\n\n::: {#c39b3b4a .cell execution_count=24}\n``` {.python .cell-code}\n# RMST within one year: expected event-free days accumulated in [0, 365]\naft.predict(newdata, type=\"rmst\", tau=365)\n```\n\n::: {.cell-output .cell-output-display execution_count=24}\n```\narray([261.92109853, 212.64413244])\n```\n:::\n:::\n\n\nThe result is one RMST value per subject, reflecting how covariate differences shift the\nentire survival curve within the follow-up window.\n\nBecause RMST is bounded by $\\tau$, it is straightforward to compare predictions across\nsubjects or models on an absolute scale (days, or whatever the time unit is). Comparing\nRMST values at several horizons also reveals how quickly a covariate effect unfolds:\n\n::: {#c0f1abac .cell execution_count=25}\n``` {.python .cell-code}\n# RMST at several horizons: shows how the covariate gap widens over time\nhorizons = [180, 365, 730]\n\nfor tau in horizons:\n    rmst = aft.predict(newdata, type=\"rmst\", tau=tau)\n    print(f\"tau={tau:4d}: subject_1={rmst[0]:.1f}  subject_2={rmst[1]:.1f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntau= 180: subject_1=157.7  subject_2=140.2\ntau= 365: subject_1=261.9  subject_2=212.6\ntau= 730: subject_1=375.6  subject_2=277.2\n```\n:::\n:::\n\n\n::: {.callout-note}\n## Subject-specific vs. group RMST\n\nThe `type=\"rmst\"` prediction from `AFT.predict()` gives a subject-specific RMST for\ncovariate-adjusted predictions from a parametric model. Greenwood also provides\n`gw.rmst_test()` and `gw.rmst_diff()` for nonparametric group comparisons of RMST from\nKaplan-Meier curves. The two approaches are complementary: parametric RMST leverages\ndistributional assumptions for individual-level predictions; nonparametric RMST makes no\nassumptions and tests group-level differences.\n:::\n\n## Next steps\n\nYou can now fit, compare, and predict from parametric survival models.\n\n- [Cox regression](cox-regression.qmd) is the semiparametric alternative, useful when you\nprefer not to assume a distribution.\n- [Prediction performance](prediction-performance.qmd) evaluates any fitted model,\nparametric or not.\n- [Competing risks](competing-risks.qmd) handles the case of more than one type of event.\n\n",
    "supporting": [
      "parametric-models_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}